### ISSUE TITLE
This method can cause UI unresponsiveness if invoked on the main thread. Instead, consider waiting for the `-locationManagerDidChangeAuthorization:` callback and checking `authorizationStatus` first.

### ISSUE THREAD

**Issue by BadihBaz** [Baseflow/flutter-permission-handler#1002]
when I call Permision location always the below xcode message
This method can cause UI unresponsiveness if invoked on the main thread. Instead, consider waiting for the `-locationManagerDidChangeAuthorization:` callback and checking `authorizationStatus` first.

**Comment by MmtDrn** [comment]
DispatchQueue.global().async { 
       //if you do what you want to do in here you can safe to any app crash
}

**Comment by BadihBaz** [comment]
Thank you for your reply.
how to do it on Flutter?

**Comment by christinachimi** [comment]
I see this error in my Xcode logs as well. I believe it comes from this plugin. Is there specific information that would be useful in tracking it down and resolving?

**Comment by JeroenWeener** [comment]
There was a similar issue for `flutter-geolocator` (https://github.com/Baseflow/flutter-geolocator/issues/1293) that was fixed in https://github.com/Baseflow/flutter-geolocator/pull/1265.

If someone wants to contribute, this would be a nice issue to pick up, as one can copy the changes from the geolocator PR.

**Comment by justinschier** [comment]
Hello, I am getting this warning as well. Hoping someone will fix it soon.

<img src="https://github.com/Baseflow/flutter-permission-handler/assets/126453/cb25e185-67fe-4a06-84c4-7a0fe1efc30b" width="800" />

**Comment by SouMyth** [comment]
same issue persists in iOS 16, need a fix in flutter...

**Comment by yasargil** [comment]
Upvoting

**Comment by mohansai1993** [comment]
Anybody fixed this issue?
a few days back [location](location: ^5.0.3) plugin was working fine

/Users/kapilsharma/.pub-cache/hosted/pub.dev/location-5.0.3/ios/Classes/LocationPlugin.m:115 This method can cause UI unresponsiveness if invoked on the main thread. Instead, consider waiting for the `-locationManagerDidChangeAuthorization:` callback and checking `authorizationStatus` first.


<img width="899" alt="Screenshot at Jan 03 14-00-20" src="https://github.com/Baseflow/flutter-permission-handler/assets/130203440/5c33064e-dae1-406d-89b8-2eb2036fe728">

**Comment by JaveedIshaq** [comment]
` This method can cause UI unresponsiveness if invoked on the main thread. Instead, consider waiting for the `-locationManagerDidChangeAuthorization:` callback and checking `authorizationStatus` first.`

same issue please some one help

**Comment by Lazizbek97** [comment]
same issue here.. any solution?

**Comment by Spramani** [comment]
This method can cause UI unresponsiveness if invoked on the main thread. Instead, consider waiting for the `-locationManagerDidChangeAuthorization:` callback and checking `authorizationStatus` first.



<img width="1066" alt="Screenshot 2024-04-26 at 7 48 03 AM" src="https://github.com/Baseflow/flutter-permission-handler/assets/52794564/34491b9b-cb31-469e-a363-964808d8c8ff">
