### ISSUE TITLE
can't read text file in android 13

### ISSUE THREAD

**Issue by cateyelow** [Baseflow/flutter-permission-handler#1004]
## 🐛 Bug Report

even though storage permission is granted, however this app can't read text file but image file.
PATH : /storage/emulated/0/Documents/KakaoTalk/Chats
![image](https://user-images.githubusercontent.com/73046218/222973040-9b54f1e9-ceaa-4c44-aecb-dd6eb269240c.png)
this directory include kakaoTalks.txt file but cannot read (Permission denied OS Error : 13)
### Reproduction steps
(flutter clean and flutter pub get)
my permission
    <uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />
    <uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
### Configuration

**Version:** 1.x
Android 13, API 33
**Platform:** 
- [ X] :iphone: iOS
- [O ] :robot: Android

**Comment by cateyelow** [comment]
I solved this problem using Storage Access Framework (SAF) API

**Comment by ayasoftware** [comment]
I have the same issue, Could you please share your solution?

**Comment by cateyelow** [comment]
@ayasoftware yes, i solved it.

from android 11, we have to request scoped storage permission. it is very inconvinient and ciritical for User Experience.

**Comment by cateyelow** [comment]
@ayasoftware 
Here is sample code. but it maybe not correct. i wrote this code 6months ago.

```
import 'package:saf/saf.dart';

  void checkPerMission() async{
    await Permission.storage.request();
    var storage = await Permission.storage.status.isGranted;
    if (Platform.isAndroid) {
      readKakaoChatsPreview();
    } else{
      readKakaoChatsPreview();
    }
  }

 Future<void> readSelectedKakaoChats(int index, String path) async{
    // Path /storage/self/primary/Documents/KakaoTalk/Chats
    var safPath = path.replaceAll('/storage/emulated/0/', '/');
    Saf saf = Saf(safPath);
    showToast('please allow using this directory');
    bool? isGranted = await saf.getDirectoryPermission(grantWritePermission: false, isDynamic: true);
    List<String>? isCached = await saf.cache();
    List<String>? cachedFilesPath = await saf.getCachedFilesPath();
    // Iterate through the list of files and print the file name
    for (final cachedFile in cachedFilesPath!) {
      File file = File(cachedFile);
      if(isTextFile(file.path)){
        // Get the file stat
        FileStat stat = File(file.path).statSync();
        List textData= await readTextFile(file.path);
        //printList(textData);
        chattingList[index]['title']=textData[0].toString().replaceAll('\r\n저장한 날짜 : ', '');
        chattingList[index]['date']=stat.changed;
        chattingList[index]['size']=stat.size;
        chattingText[index]=textData;
      }
    }
    setState(() {});
  }


```

**Comment by ayasoftware** [comment]
Thanks for sharing your code. I'll give it a try and let you know.
