### ISSUE TITLE
some pictures in assets are mising

### ISSUE THREAD

**Issue by zzzh** [Baseflow/flutter-permission-handler#1008]
Tried to run example in permission_handler, got this:
Error detected in pubspec.yaml:
No file or variants found for asset: packages/baseflow_plugin_template/logo.png.

**Comment by JeroenWeener** [comment]
Hi @zzzh, thank you for filing this issue!

This should be resolved on the latest version of the `permission_handler`. If you are still encountering this issue, please let us know by opening a new issue.
