### ISSUE TITLE
CTTelephonyNetworkInfo

### ISSUE THREAD

**Issue by SurMesure237** [Baseflow/flutter-permission-handler#1009]
## 🐛 Bug Report

Every time I run the simulation on VS Code, I get this error :

Could not build the precompiled application for the device.
ARC Semantic Issue (Xcode): No visible @interface for 'CTTelephonyNetworkInfo' declares the selector 'serviceSubscriberCellularProvidersserviceSubscriberCellularProviders'

But when I try on Xcode, there are some problems, but the simulation starts and works properly.

**Version:** flutter-permission-handler ^10.2.0

**Platform:** 
- [X] :iphone: iOS
- [ ] :robot: Android

**Comment by TimHoogstrate** [comment]
Dear @SurMesure237,

Thanks for filing this issue. Can you try to `flutter clean` `flutter pub get`? Maybe run `pod install` in the iOS folder? It is an interface from native iOS but I cannot find the interface for: `serviceSubscriberCellularProvidersserviceSubscriberCellularProviders` neither on the project nor on google. only `serviceSubscriberCellularProviders`

Kind regards,

Tim
