### ISSUE TITLE
bluetooth.status, bluetoothScan.status, bluetoothConnect.status, location.status (all return false on iOS)

### ISSUE THREAD

**Issue by kbessemer** [Baseflow/flutter-permission-handler#1014]
I am trying to detect if the user has turned off bluetooth on the device, or denied the app bluetooth permissions. This is what I have tried, and what I am receiving in response. Please note that bluetooth scans and connects are working, yet all of these return false.

```
print(await Permission.bluetoothScan.status);
print(await Permission.bluetooth.status);
print(await Permission.location.status);
```

```
flutter: PermissionStatus.denied
flutter: PermissionStatus.denied
flutter: PermissionStatus.denied
```

**Comment by vlad-ed-git** [comment]
Same issue. I understand the other permissions are android only, but Permission.bluetooth also returns false.

**Comment by blueeyestw** [comment]
Same, Permission.bluetooth always returns PermissionStatus.denied on iOS.

**Comment by mvanbeusekom** [comment]
As mentioned by @blueeyestw, please make sure to add the required configuration in the `ios/Podfile`. Detailed instructions can be found in the "iOS" section of the [README](https://pub.dev/packages/permission_handler).
