### ISSUE TITLE
crashed after proguard from gson

### ISSUE THREAD

**Issue by zouzhenglu** [Baseflow/flutter-permission-handler#102]
## 🔙 Regression

I found you import the gson lib into your lib. And then it crashed after I proguard. I think it will much better to tell us to notice that.
**Platform:** 
- [ ] :robot: Android

**Comment by jp1017** [comment]
@mleonhard Same Issue

**Comment by jp1017** [comment]
@zouzhenglu Add this to the file `proguard-rules.pro`

>-keep public class com.google.gson.**
-keep public class com.google.gson.** {public private protected *;}
-keepattributes Signature
-keepattributes *Annotation*
-keep public class com.baseflow.permissionhandler.**{*;}
