### ISSUE TITLE
不兼容 windows server 2012 R2 和 windows server 2008 R2 

### ISSUE THREAD

**Issue by zhuyuzhuyu132** [Baseflow/flutter-permission-handler#1023]
windows server 2012 R2 和 windows server 2008 R2  中运行失败，没有错误提示，下面是Windows日志中的错误信息。（win10和win11可以正常运行）

错误应用程序名称: app.exe，版本: 1.0.2.2，时间戳: 0x642e82d1
错误模块名称: ucrtbase.DLL，版本: 10.0.14393.2990，时间戳: 0x5caeb96f
异常代码: 0xc0000409
错误偏移量: 0x000000000006e00e
错误进程 ID: 0x11b8
错误应用程序启动时间: 0x01d96861e9717cda
错误应用程序路径: C:\Users\Administrator\Desktop\A\app.exe
错误模块路径: C:\Windows\SYSTEM32\ucrtbase.DLL
报告 ID: 2734ad3a-d455-11ed-80d0-861b657ef320
错误程序包全名: 
错误程序包相对应用程序 ID:

**Comment by mvanbeusekom** [comment]
Please post your issues in English.
