### ISSUE TITLE
Callback when the Permission is Granted

### ISSUE THREAD

**Issue by ashkan84f** [Baseflow/flutter-permission-handler#1029]
Hi
I have just started to use permission_handler package a few days ago.
I need to know how we can have a call back method to get notified when a user granted/denied the permission?
My scenario is:
1- Request to get contact permission granted
2- When it's granted, get contacts
3- Everytime the app launches, if the contact permission is permanently_denied, show a warning pop up to user and navigate him to setting screen

The problem is I don't know where to perform step 2? Because immediately after I show the permission request (in step 1), the next line (which is checking status and navigating to setting screen) will be executed.

You can find my code below.

```dart
  Future<void> _checkPermissions() async {
    final status = Permission.contacts.request();
    if (status == PermissionStatus.granted) {
      // load contacts
    } else {
      // navigate to setting screen
    }
  }
```

I know I can use other methods like ChangeNotifiers, but I would like to know if permission_handler has already implemented this.

Thanks in advance.

**Comment by markfili** [comment]
ah, I think you're missing an `await` on `Permission.contacts.request()` that should wait for user interaction and return a new permission status

**Comment by mvanbeusekom** [comment]
As mentioned by @markfili, the `request` method is asynchronous and should be awaited. The following updated snippet should work:

```dart
  Future<void> _checkPermissions() async {
    final status = await Permission.contacts.request();
    if (status == PermissionStatus.granted) {
      // load contacts
    } else {
      // navigate to setting screen
    }
  }
```
