### ISSUE TITLE
Apple reports that app requires permissions, that are disabled in plist

### ISSUE THREAD

**Issue by nosovk** [Baseflow/flutter-permission-handler#1031]
## 🐛 Bug Report

We make some cleanup in a project, and removed explanation for unused permissions. For example, we use camera and notifications, but dont use geolocation.

For example removed from info.plist
```diff file=info.plist
- <key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
```
That shouldn't cause any problems, because we don't use location data and do not make request for location permission in our code. But then we suddenly got a notification from apple:

<img width="344" alt="image" src="https://user-images.githubusercontent.com/1398808/233791377-72791632-4828-4b06-9cb8-f66a8185aef5.png">

It means that they somehow detect usage of location permission in our code....

### Expected behavior

It was expected that requested permissions are not used in resulting iOS code

### Configuration

**Version:** 10.2.0

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

<details><summary>podfile</summary>

```ruby

# Uncomment this line to define a global platform for your project
platform :ios, '13'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'
use_frameworks!
use_modular_headers!
pod 'GoogleUtilities', :modular_headers => true


project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  # use_frameworks!
  # use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "i386 arm64 x86"
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        'PERMISSION_CAMERA=1',
        'PERMISSION_MICROPHONE=1',
        'PERMISSION_NOTIFICATIONS=1',
        'PERMISSION_PHOTOS=1',
        'PERMISSION_APP_TRACKING_TRANSPARENCY=1',
        'PERMISSION_LOCATION=0',
      ]
    end
  end
end

target 'OneSignalNotificationServiceExtension' do
  use_frameworks!
  pod 'OneSignalXCFramework', '>= 3.4.3', '< 4.0'
end
```
</details>

I've digged into ios project, and find out that in `ios/Pods/Pods.xcodeproj/project.pbxproj`  there are still references to location headers
```diff
3BF2C0F119734309E01E3749BCE0033C /* LocationPermissionStrategy.h */ = {isa = PBXFileReference; includeInIndex = 1; lastKnownFileType = sourcecode.c.h; name = LocationPermissionStrategy.h; path = "../../../../../../../../../../../.pub-cache/hosted/pub.dartlang.org/permission_handler_apple-9.0.7/ios/Classes/strategies/LocationPermissionStrategy.h"; sourceTree = "<group>"; };
80330C3D40648D86DB6F36681E27CEBB /* LocationPermissionStrategy.m */ = {isa = PBXFileReference; includeInIndex = 1; lastKnownFileType = sourcecode.c.objc; name = LocationPermissionStrategy.m; path = "../../../../../../../../../../../.pub-cache/hosted/pub.dartlang.org/permission_handler_apple-9.0.7/ios/Classes/strategies/LocationPermissionStrategy.m"; sourceTree = "<group>"; };
3BF2C0F119734309E01E3749BCE0033C /* LocationPermissionStrategy.h */,
80330C3D40648D86DB6F36681E27CEBB /* LocationPermissionStrategy.m */,
94B38A01AB672E7983E9985C5493AE7A /* LocationPermissionStrategy.h in Headers */,
EBEDC0CFF96948F125C1E7068FB83A9F /* LocationPermissionStrategy.m in Sources */,
```
It seems nevertheless of 'PERMISSION_LOCATION=0' setting is present in plist, location permission code is still linked to final build.

**Comment by TimHoogstrate** [comment]
Dear @nosovk,

Could it be cached somewhere? Try to remove the podfile.lock and then run `pod install` again.

Kind regards,

**Comment by nosovk** [comment]
Yep, I've tried to do `pod install`, but it does not help

**Comment by nosovk** [comment]
I was able to find that there are conditional directive inside those files, and even when they are included, they are empty

**Comment by mvanbeusekom** [comment]
Hi @nosovk, 

Could it be that the `camera` (or other) plugin accesses the location API to acquire location information and attaches it as meta data to the image?

The `permission_handler` relies on macros to swap the contents of the `LocationPermissionStrategy.h` and `LocationPermissionStrategy.m` files with an empty implementation when the macros are not set (or explicitly set to 0). So they will always show up in the `ios/Pods/Pods.xcodeproj/project.pbxproj` file, however depending on the macro their contents will differ.
