### ISSUE TITLE
Ask location.request() but paramgram does't continue to excute

### ISSUE THREAD

**Issue by mrginpadd** [Baseflow/flutter-permission-handler#1037]
## 🐛 Bug Report

  
      await Permission.location.request();
      _hasAuthority?.call()

     // i wanna to get location permission then excute a callback  but when excute   Permission.location.request()
   // paragran does't go down to excute callback

**Platform:** 
- [x] :iphone: iOS15.5 simulator
- [ ] :robot:

**Comment by mrginpadd** [comment]
Location permission and speech permission have the same issue while other permission work fine.

**Comment by sezer** [comment]
Notification permission doesn't work for me either.
