### ISSUE TITLE
Contact management permission not working for iOS 

### ISSUE THREAD

**Issue by monik-techuz** [Baseflow/flutter-permission-handler#1038]
## 🐛 Bug Report

Hello Community , I have been working on flutter app which is highly dependent on user's contact data . App is in under development for a while, and team has used this plugin for handling contact management permission . as per our recent test in iOS we found that permission handler is not able to request in iOS . it always returns `permission denied` as output of permission request even though user has not been promoted for permission popup at all . 

### Expected behavior
It should prompt user for asking whether user wants to give permission for contact or not as it usually does with other permission like location . 

### Reproduction steps
Add latest version of permission handler plugin in the project and ask for the location permission , it will give you permission denied as a output . 

### Configuration
Flutter : 3.7.2 • channel stable 
Dart : 2.19.2 
DevTools : 2.20.1
MacOs : 13.3.1 
Simulator iOS : 16.2

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by monik-techuz** [comment]
@mvanbeusekom thanks for the reply but i have already added required pre-processor in Podfile

**Comment by grknstudios** [comment]
Did you resolve this issue? I have an app project that is based on contacts, but the app doesn’t request any permissions for contacts and couldn’t import contacts from the iPhone.
