### ISSUE TITLE
Android 13 Permission.notification.status returns denied when app installed first time

### ISSUE THREAD

**Issue by Avinash01111992** [Baseflow/flutter-permission-handler#1040]
## 🐛 Bug Report

 I am having issue with respect to getting the status of the notification permission.

When the app installed first time, When i check for
final notificationStatus = await Permission.notification.status;

I need the status as unknown in app first lunch to show some explanations before i show the OS permission pop-up.

### Expected behavior
Status should be UNKNOWN or not determined

### Actual behavior
Status coming as Denied.

### Configuration

**Version:** 1.x

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by tshuvo** [comment]
Same issue here... is there any update?

**Comment by markfili** [comment]
As per [documentation](https://developer.android.com/develop/ui/views/notifications/notification-permission#new-apps), notifications on Android 13 are off by default on new installs so I'm not sure if this really is an issue related to this package.

**Comment by JeroenWeener** [comment]
Thank you @Avinash01111992 for taking the time to file this issue!

As @markfili mentioned, starting with Android 13, notification permissions are off by default. I am therefore going to close this issue. If you feel like this should be documented somewhere in the plugin, feel free to open an issue for it.
