### ISSUE TITLE
Execution failed for task ':permission_handler_android:extractReleaseAnnotations' on Windows

### ISSUE THREAD

**Issue by jseminck** [Baseflow/flutter-permission-handler#1041]
## 🐛 Bug Report

Since `permission_handler` was added to our project, I cannot run it on Windows anymore. I am getting the following error. If I remove the `permission_handler` dependency, then everything works.

We are using the latest version, and `compileSdkVersion` is set to `33` and `ext.kotlin_version` to `1.6.10`

```
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':permission_handler_android:extractReleaseAnnotations'.
> A failure occurred while executing com.android.build.gradle.internal.lint.AndroidLintWorkAction
   > com/intellij/openapi/project/Project

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Failed to notify build listener.
> com/intellij/mock/MockProject

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org
```

### Expected behavior

Build works

### Reproduction steps

`flutter build apk`

### Configuration

**Version:** latest

**Platform:** 
- [x] :robot: Android

**Comment by JaviGaiax** [comment]
Same problem here since like 2 days ago when I updated my flutter version. Non release works fine but this is keeping me stuck. Did you ever find out what was the problem? My sdk and kotlin versions are the same as yours.

**Comment by TimHoogstrate** [comment]
Dear @jseminck or @JaviGaiax,

Can you paste an output of ``flutter doctor -v` and can you confirm if this is also happening on the example app? It helps a lot when reproducing this issue. Can you also try to build with --stacktrace option. Maybe this gives a bit more context.

**Comment by JimmyGoGoGo** [comment]
@TimHoogstrate 
Hi,I am getting the same error.
Here is the log i run with --stacktrace option:

AAPT2 process unexpectedly exit. Error output:
aapt2 W 07-03 17:21:56  5826  5826 LoadedArsc.cpp:682] Unknown chunk type '200'.
May it help?

**Comment by TimHoogstrate** [comment]
@JimmyGoGoGo, do you run into this issue in the example app too?

Kind regards,

**Comment by abkoradiya** [comment]
Same issue I am facing. What is the solution?
