### ISSUE TITLE
Build fail with AGP 8.0

### ISSUE THREAD

**Issue by ttb-inc** [Baseflow/flutter-permission-handler#1043]
## 🐛 Bug Report

Hi,
Please resolve issues with AGP 8.0 on Android.(’namespace’)
Thank you.

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
Solved with release 10.2.1 of the [permission_handler_android](https://pub.dev/packages/permission_handler_android) plugin. 

if you reference `permission_handler` directly simply run the `flutter pub upgrade` command which will automatically update to the latest version of the `permission_handler_android` plugin.

**Comment by MrCsabaToth** [comment]
How is this solved exactly? The example's build.gradle references 7.1.2 (https://github.com/Baseflow/flutter-permission-handler/blob/194ea7fda454232e9172dd13ecf234ecaac18153/permission_handler_android/example/android/build.gradle#L8) however the plugin itself references some ancient 4.1.0: https://github.com/Baseflow/flutter-permission-handler/blob/194ea7fda454232e9172dd13ecf234ecaac18153/permission_handler_android/android/build.gradle#L12
