### ISSUE TITLE
permission popup will disappear while click outside the application in android 

### ISSUE THREAD

**Issue by DrashtiJoshi29** [Baseflow/flutter-permission-handler#1046]
### Expected behavior
permission popup should not disappear while click outside the popup 

### Reproduction steps
click outside the popup any where it should not disappear the popup 

### Configuration

**Version:** 1.x
10.2.0

**Platform:** 
- [ ] :robot: Android

**Comment by JeroenWeener** [comment]
Hi @DrashtiJoshi29, thank you for filing this issue.

Whether permission dialogs are cancellable by tapping outside of the dialog is up to the OS and beyond our control. Whether the dialog is dismissible is different between iOS and Android, between Android versions, and between phone brands that add their own flavor of an Android version.

Is there a specific need you have for having the dialogs non-dismissible? There might be a solution to your use case that does not involve making the dialogs non-dismissible.
