### ISSUE TITLE
Add support for VPN permission

### ISSUE THREAD

**Issue by problematicconsumer** [Baseflow/flutter-permission-handler#1051]
## 🚀 Feature Requests
would be nice to have VPN permission handling as well. I get that its not very common for flutter projects to manage VPNs but it definitely has its use cases

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by JeroenWeener** [comment]
Hi @problematicconsumer, thank you for filing this feature request!

I am not too familiar with VPN for Android and iOS myself.

Does it behave in the same way as the other permissions? I.e. could you sketch out a common use case?

Do you perhaps know of starting points for developers that want to look into this issue? More concretely, could you point them to Android and/or iOS APIs that allow such behavior, or similar plugins/applications that already implemented your feature?

Hope to hear from you!

**Comment by shafiquecbl** [comment]
Hi @0xConsumer @JeroenWeener you can use [vpn_permission](https://pub.dev/packages/vpn_permission) package to handle VPN Permission.
