### ISSUE TITLE
Bluetooth permission missing in manifest

### ISSUE THREAD

**Issue by enricocaliolo** [Baseflow/flutter-permission-handler#1052]
## 🐛 Bug Report

I am trying to scan devices using Flutter Blue Plus, and handling the permissions with permission_handler. What is strange is that earlier today I tested and it worked, but now it doesn't. Even though I put the required permissions on AndroidManifest, I got stuck and receive this message in the console:

```
Bluetooth permission missing in manifest
```

I am even using the same permissions as the flutter blue plus example, but it is not working. I did flutter clean, but it was the same.

Checked on different branches than the one I was using and same thing. On both android 10 and android 13. Could it be something with my macbook? I am using a Macbook Pro 14 with a M1 Pro.

### Expected behavior

It should work as it was yester

### Configuration

AndroidManifest.xml

```
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <!-- Allow Bluetooth -->
    <uses-feature
        android:name="android.hardware.bluetooth_le"
        android:required="true" />
    <!-- Request legacy Bluetooth permissions on older devices. -->
    <uses-permission android:name="android.permission.BLUETOOTH"
        android:maxSdkVersion="30" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN"
        android:maxSdkVersion="30" />
    <!-- Needed only if your app looks for Bluetooth devices.
        If your app doesn't use Bluetooth scan results to derive physical
        location information, you can strongly assert that your app
        doesn't derive physical location. -->
    <uses-permission android:name="android.permission.BLUETOOTH_SCAN" android:usesPermissionFlags="neverForLocation"/>
    <!-- Needed only if your app makes the device discoverable to Bluetooth
         devices. -->
    <uses-permission android:name="android.permission.BLUETOOTH_ADVERTISE" />
    <!-- Needed only if your app communicates with already-paired Bluetooth
      devices. -->
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
    <!-- If your application supports a service and can run on Android 10 (API level 29) or Android 11, you must also declare 
    the ACCESS_BACKGROUND_LOCATION permission to discover Bluetooth devices. -->
    <!-- <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" /> -->
```

**Version:** 10.2.0

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android 13 (Samsung S21+)

**Comment by enricocaliolo** [comment]
The issue is related to this library, but it wasn't what was causing the bug, so I'll be closing it for now.

**Comment by Roee-Tsur** [comment]
@enricocaliolo can you share more details about the issue?
I'm also facing it.

**Comment by Snofkin** [comment]
i am having same issue in s23

**Comment by jonashoelzel** [comment]
Same here

**Comment by NoriThorleifs** [comment]
I'm having this issue as well, running in S22

**Comment by mfeizi** [comment]
I'm having this issue as well, running in Poco f3

**Comment by bbkransomzx** [comment]
I'm also having this same issue on  🤖 Android 13 (Samsung S21+) please can someone help.

**Comment by bbkransomzx** [comment]
I've resolved this now. 

I was using an older version of flutter_blue_plus. I updated it to the latest version within my pubspec.yaml file to the latest version and this worked.  

dependencies:
    cupertino_icons: ^1.0.2
    flutter:
        sdk: flutter
    permission_handler: ^11.3.0
    flutter_blue_plus: ^1.31.15
    get: ^4.6.5

https://pub.dev/packages/flutter_blue_plus

Hope this helps anyone else who gets stuck 😊

**Comment by nvbien2000** [comment]
sam here

**Comment by zhiye1995** [comment]
It seems like an issue has occurred again when using `flutter_blue_plus` together with `bluetooth_low_energy`.

**Comment by JosueLopezRamirez** [comment]
Seems occurred to me at the last version of the library

**Comment by ydori** [comment]
> It seems like an issue has occurred again when using `flutter_blue_plus` together with `bluetooth_low_energy`.

Did you find a solution @zhiye1995 ? I am also using both plugins.

**Comment by zhiye1995** [comment]
> > It seems like an issue has occurred again when using `flutter_blue_plus` together with `bluetooth_low_energy`.似乎在使用 `flutter_blue_plus` 与 `bluetooth_low_energy` 一起时又出现了问题。
> 
> Did you find a solution [@zhiye1995](https://github.com/zhiye1995) ? I am also using both plugins.您找到解决方案了吗？我也在使用这两个插件。

No, only one can be used.

**Comment by zhiye1995** [comment]
> > It seems like an issue has occurred again when using `flutter_blue_plus` together with `bluetooth_low_energy`.似乎在使用 `flutter_blue_plus` 与 `bluetooth_low_energy` 一起时又出现了问题。
> 
> Did you find a solution [@zhiye1995](https://github.com/zhiye1995) ? I am also using both plugins.您找到解决方案了吗？我也在使用这两个插件。

@ydori Couldn't find a good method, so I can only use one.

**Comment by jos-technion** [comment]
have you found a solution? looks like bluetooth_low_energy is causing permission issue
