### ISSUE TITLE
App is crashing when use manageExternalStorage()

### ISSUE THREAD

**Issue by b4ra0** [Baseflow/flutter-permission-handler#1054]
## 🐛 Bug Report

When I use the method manageExternalStorage.request(), the device opens the app's settings. But when the user turn back to the app, it crash!

### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android

**Comment by JeroenWeener** [comment]
Hi @b4ra0, thank you for taking the time to file this issue.

Could you confirm that this also happens with the example app?

**Comment by AwaisQazii** [comment]
I'm also facing same issue
