### ISSUE TITLE
Missing case clause for 'provisional'

### ISSUE THREAD

**Issue by mugbug** [Baseflow/flutter-permission-handler#1062]
## 🐛 Bug Report

A breaking change was added without being marked as such on this PR: https://github.com/Baseflow/flutter-permission-handler/pull/990

Basically, since a new enum case was added to `PermissionStatus`, the analyzer started throwing a warning on switch case statements that used this enum.

### Expected behavior

When deploying a new version with this change, I understand that the major number should have been bumped instead of the minor one so it makes it clear that a new breaking change was added to that version and that the caret syntax on pubspec "^3.0.0" works as expected

### Reproduction steps

Create some switch case for the `PermissionStatus` and don't add a case check for `PermissionStatus.provisional` case.

### Configuration

**Version:** Breaks for `10.3.0`. Works for `10.2.1`. 

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi @mugbug,

Thank you for pointing this out. Unfortunately it slipped through the review process and got published as a minor. I am very sorry for the inconvenience caused, however rolling back is difficult and I am afraid it will result in even bigger issues.

Please update the switch statement and add the `provisional` case, it is not necessary to catch if you don't want to handle it's use case (e.g. make the application work as it always has).
