### ISSUE TITLE
Android - onRequestPermissionsResult not being called in add-to-app

### ISSUE THREAD

**Issue by kodypeterson** [Baseflow/flutter-permission-handler#1063]
## 🐛 Bug Report

We use Flutter in the "add-to-app" context and when attempting to use this plugin we have found that when making a call to `request()` a permission for the app, the Future never returns.

In debugging we found that the `onRequestPermissionsResult` is never being called. I have been unable to identify any further on why that might be.

### Configuration

**Version:** 10.3.0

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android

**Comment by TimHoogstrate** [comment]
Dear @kodypeterson,

Can you explain a bit more regarding your setup and steps to reproduce? Because I cannot reproduce this. An output of `flutter doctor -v` could also help a lot in investigating this issue. 

Kind regards,

**Comment by ahmetakil** [comment]
I'm facing the same error with Android, add-to-app application

I do see the native prompts and when I allow the app receives the permission but the operation   
`    await [Permission.camera, Permission.microphone].request(); `

Never returns a value, if I close the app and retry subsequent calls works as expected with the value of granted 

Do not see any logs from Logcat and Manifest does have the permissions added
