### ISSUE TITLE
Error: MissingPluginException(No implementation found for method checkPermissionStatus on channel flutter.baseflow.com/permissions/methods)

### ISSUE THREAD

**Issue by JosonJiang** [Baseflow/flutter-permission-handler#1064]
## 🐛 Bug Report

Uncaught (in promise) Error: MissingPluginException(No implementation found for method checkPermissionStatus on channel flutter.baseflow.com/permissions/methods)

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by TimHoogstrate** [comment]
Dear @JosonJiang,

Thanks for your contribution. It would be helpful if you could provide the output of 'flutter doctor -v' and clear, step-by-step instructions to reproduce the issue in the comment section. This will assist us in better understanding and addressing the problem.
