### ISSUE TITLE
Android 13: Notification Permission is not requested

### ISSUE THREAD

**Issue by m4rcelknu** [Baseflow/flutter-permission-handler#1067]
## 🐛 Bug Report

On Android 13 the notification permission is not requested, on iOS it does request correctly. Permission is in the manifest and the permission is requested in our Flutter code. I followed all the steps that can be found here under setup: https://pub.dev/packages/permission_handler

### Expected behavior

Notification permission request is triggered on Android.

### Reproduction steps

Fresh install of an app that requests multiple permissions including the notification permission. Notification permission should be the first permission that is requested.

### Configuration

**Version:** 10.2.0

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by TykanN** [comment]
@m4rcelknu
I had same issue. But not now.
**You should set Android targetSdkVersion to 33 in build.gradle.**

**Comment by Avi067** [comment]
I had same issue , but I resolved it by increasing the targetSdkVersion to 33.
