### ISSUE TITLE
https://stackoverflow.com/questions/76506501/flutter-app-storage-permission-issue-on-android-13-devices

### ISSUE THREAD

**Issue by DhruvalPrime** [Baseflow/flutter-permission-handler#1069]
please check this and help me

https://stackoverflow.com/questions/76506501/flutter-app-storage-permission-issue-on-android-13-devices

**Comment by harshitwe360** [comment]
I m also facing this issue

**Comment by A7MeDG0L0L** [comment]
Same...

**Comment by JeroenWeener** [comment]
Thank you for filing this issue!

This is a duplicate of #955. I am therefore going to close it. Until the issue is resolved, the comments on that issue may provide you with valuable solutions in the meantime.
