### ISSUE TITLE
Check if the permission dialog is already open

### ISSUE THREAD

**Issue by hugocbpassos** [Baseflow/flutter-permission-handler#107]
I have this situation in which there's a button that calls `requestPermissions` on press. If the user is fast enough, he/she can tap the button while the permission dialog stills visible, resulting in a `PlatformException`.  We should be able to check whether the dialog is already open. A simple `bool` like `PermissionHandler().isRequestingPermission` would be perfect.

**Comment by ened** [comment]
Fixed in #109.

**Comment by hugocbpassos** [comment]
I still have the issue even with this change.

**Comment by danielroek** [comment]
Unable to reproduce the issue on iOS or Android. Closing this issue
