### ISSUE TITLE
[Bug]: Storage permission request returns `permanentlyDenied` when back button is clicked

### ISSUE THREAD

**Issue by marius-bareisa-telia** [Baseflow/flutter-permission-handler#1072]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Windows

### Steps to reproduce

This only happens on Android 12.0 devices.

1. Launch Android 12.0 device.
2. Request storage permissions with: `await Permission.storage.request()`.
3. Storage Permission request dialog is on the screen.
4. Click hardware back button.

### Expected results

Dialog is dismissed.

### Actual results

`Permission.storage.request()` returns `PermissionStatus.permanentlyDenied`.

### Code sample

<details><summary>Code sample</summary>

```dart
  Future<PermissionStatus> getStoragePermission() async {
    final permissionStatus = await Permission.storage.request();
    return permissionStatus;
  }
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

10.3.0

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.4, on macOS 13.4 22F66 darwin-arm64, locale en-LT)
    • Flutter version 3.10.4 on channel stable at /Users/lpt223/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 682aa387cf (3 weeks ago), 2023-06-05 18:04:56 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/lpt223/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.78.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[!] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1
    • NO_PROXY contains localhost
    • NO_PROXY contains 127.0.0.1
    ! NO_PROXY does not contain ::1

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 31) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 114.0.5735.133

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.

```

</details>

**Comment by Chalwe19** [comment]
+1

**Comment by lednewcrk** [comment]
+1

**Comment by gabrieLnasc11** [comment]
+1

**Comment by Chalwe19** [comment]
i was able to find a work around using [device_info_plus](https://pub.dev/packages/device_info_plus) to check the sdk version.
`bool permissionStatus;
final deviceInfo = await DeviceInfoPlugin().androidInfo;
    
if (deviceInfo.version.sdkInt >= 33) {
permissionStatus = true;
} else {
    permissionStatus = await Permission.storage.request().isGranted;
}`

**Comment by Chalwe19** [comment]
https://github.com/Baseflow/flutter-permission-handler/issues/1066#issuecomment-1609441896 this worked for me

**Comment by marius-bareisa-telia** [comment]
> [#1066 (comment)](https://github.com/Baseflow/flutter-permission-handler/issues/1066#issuecomment-1609441896) this worked for me

This solution doesn't handle different statuses like `PermissionStatus.permanentlyDenied` because it returns just a bool - `Permission.storage.request().isGranted`.

**Comment by Kamran73** [comment]
Facing same issue. Either by pressing back button or clicking outside the permission dialog. it always returns PermissionStatus.permanentlyDenied
