### ISSUE TITLE
[Bug]:  on iOS I can see the microphone permission on in Device settings but permission handler returns denied.

### ISSUE THREAD

**Issue by MauScheff** [Baseflow/flutter-permission-handler#1076]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [ ] Android
- [X] iOS
- [ ] Windows

### Steps to reproduce

[Bug]:  on iOS I can see the microphone permission on in Device settings but permission handler returns denied.

### Expected results

[Bug]:  on iOS I can see the microphone permission on in Device settings but permission handler returns denied.

### Actual results

[Bug]:  on iOS I can see the microphone permission on in Device settings but permission handler returns denied.

### Code sample

<details><summary>Code sample</summary>

```dart
[Bug]:  on iOS I can see the microphone permission on in Device settings but permission handler returns denied.
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

10.2.0

### Flutter Doctor output

<details><summary>Doctor output</summary>
s
```console
[Paste your output here]s
```
s
</details>

**Comment by whitesoil** [comment]
flutter: 3.10.5
permission_handler: 10.4.0
os: Android 13

I faced similar issue on Android.

I called below code and accepted permission. But it returns PermissionStatus.denied
```
final permission = await Permission.microphone.request();
```

**Comment by mvanbeusekom** [comment]
Hi @whitesoil,

Thank you for reaching out. The issue you are facing seems to be unrelated. To help resolving this particular issue it would be great if you can create a new issue and supply the requested details.

**Comment by MauScheff** [comment]
@mvanbeusekom I can confirm that NSMicrophonePhoneUsage description is present with a string value in my Info.plist.
