### ISSUE TITLE
Improve documentation on when to use Permission.storage vs Permission.photos on Android

### ISSUE THREAD

**Issue by mvanbeusekom** [Baseflow/flutter-permission-handler#1085]
Explain when the use of `Permission.storage` is allowed and when users should switch to using the Media Store API. See also comment: https://github.com/Baseflow/flutter-permission-handler/issues/1084#issuecomment-1619621941

**Comment by JeroenWeener** [comment]
Ideally, we explain this at both the `Permission` documentation and in the README. The `Permission` documentation will pop up in most IDEs when typing and gives developers quick info about the permission. The README is the place where people (should) first go when they encounter problems or when they are setting things up.

The README documentation could use some polish, creating a clear FAQ section which includes this specific situation as well.

While we are at it, it would be nice to add a checkmark 'I have read the FAQ' to the bug report, to encourage users to check that before submitting a bug report. This could save us some time during triaging.

Just my two cents 🎤 

We can, of course, create separate tickets for the points I have mentioned, if that is desirable.
