### ISSUE TITLE
[Bug]: `Permission.storage.request().isGranted` returns true before access allowed on iOS

### ISSUE THREAD

**Issue by brand17** [Baseflow/flutter-permission-handler#1091]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [ ] Android
- [X] iOS
- [ ] Windows

### Steps to reproduce

1. run the following code (which is based on the example) on iOS 15.6 with iPhone 6s . The example could be used instead with the same result.

### Expected results

I would expect `request()` to wait until the notification closed.

So I would expect to see `permitted` after I press the button in the notification.

### Actual results

`Permission.storage.request().isGranted` returns `true` before I allow access in notification.

As a result the code prints `permitted` before I allow access.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'dart:async';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:photo_gallery/photo_gallery.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  void initState() {
    super.initState();
    initAsync();
  }

  Future<void> initAsync() async {
    if (await _promptPermissionSetting()) {
      final albums =
          await PhotoGallery.listAlbums().then((value) => value[0].listMedia());
      final albumCount = albums.items.length;
      print(albumCount); // <= prints 0 on the first call despite I have photos on the phone
    }
    setState(() {});
  }

  Future<bool> _promptPermissionSetting() async {
    if (Platform.isIOS) {
      if (await Permission.storage.request().isGranted) {
        // final permissionStatus = await Permission.phone.request();
        print('permitted'); // <= prints before I allow access
        return true;
      }
    }
    return false;
  }

  @override
  Widget build(BuildContext context) {
    return const MaterialApp();
  }
}
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

10.4.2

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.10.5, on macOS 12.6.7 21G651
    darwin-x64, locale en-RU)
    ! Warning: `flutter` on your path resolves to
      /Users/admin/Downloads/flutter/bin/flutter, which is not
      inside your current Flutter SDK checkout at
      /Users/admin/downloads/flutter. Consider adding
      /Users/admin/downloads/flutter/bin to the front of your
      path.
    ! Warning: `dart` on your path resolves to
      /Users/admin/Downloads/flutter/bin/dart, which is not
      inside your current Flutter SDK checkout at
      /Users/admin/downloads/flutter. Consider adding
      /Users/admin/downloads/flutter/bin to the front of your
      path.
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the
      Android SDK components.
      (or visit
      https://flutter.dev/docs/get-started/install/macos#android-
      setup for detailed instructions).
      If the Android SDK has been installed to a custom location,
      please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✗] Chrome - develop for the web (Cannot find Chrome executable
    at /Applications/Google Chrome.app/Contents/MacOS/Google
    Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a
      Chrome executable.
[!] Android Studio (not installed)
[✓] VS Code (version 1.79.2)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 4 categories.
```

</details>

**Comment by gugadev** [comment]
Can confirm using the last version and iOS 16.4+.

**Comment by JeroenWeener** [comment]
Hi @brand17, thanks for filing a bug report!

On iOS, `Permission.storage` is always granted.

From the source code documentation:
```dart
  /// iOS: Access to folders like `Documents` or `Downloads`. Implicitly
  /// granted.
  static const storage = Permission._(15);
```

For the implementation, see https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler_apple/ios/Classes/strategies/StoragePermissionStrategy.m and https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler_platform_interface/lib/src/permissions.dart.

It is expected behavior that `Permission.storage.request()` returns immediately with `PermissionStatus.granted`. Also, no permission dialog should show up.

Please let me know if my described behavior differs from what you experience, or if you feel like the behavior should be different.
