### ISSUE TITLE
 [Question]: i try to  access gallery  its done but not take user permisson .

### ISSUE THREAD

**Issue by eansharma** [Baseflow/flutter-permission-handler#1096]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-permission-handler/blob/main/permission_handler/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [ ] iOS
- [ ] Windows

### Your question

this is my code i try to acces galler and take user permision  but working my code on Sumsung Glaxay A14 5g

```dart
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:permission_handler/permission_handler.dart';



class ImageScreen extends StatefulWidget {
  const ImageScreen({Key? key}) : super(key: key);

  @override
  State<ImageScreen> createState() => _ImageScreenState();
}

class _ImageScreenState extends State<ImageScreen> with WidgetsBindingObserver {

   @override
  Widget build(BuildContext context) {
    return Scaffold(
      
      body: Center(
        child: ElevatedButton(
          onPressed: () => _getFromGallery(context),
          child: Text('Pick Image'),
        ),
      ),
    );
  }

/// Get from gallery
_getFromGallery(context) async {
  PermissionStatus status = await Permission.photos.request();
  if (status.isGranted) {
    try {
      XFile? pickedFile = await ImagePicker().pickImage(
        source: ImageSource.gallery,
        maxWidth: 1800,
        maxHeight: 1800,
      );
      if (pickedFile != null) {
        File imageFile = File(pickedFile.path);
        // Process the selected image file
      }
    } catch (e) {
      print(e.toString());
    }
  } else if (status.isDenied) {
    // The user denied the permission
    showDialog(
      context: context,
      builder: (context) {
        return AlertDialog(
          title: Text('Permission denied'),
          content: Text('Please grant permission to access the gallery'),
          actions: [
            TextButton(
              onPressed: () {
                Navigator.pop(context);
              },
              child: Text('Cancel'),
            ),
            TextButton(
              onPressed: () {
                Permission.photos.request();
              },
              child: Text('Request permission'),
            ),
          ],
        );
      },
    );
  } else if (status.isPermanentlyDenied) {
    // The user permanently denied the permission
    // You can open the Settings app to manually grant the permission
  }
```

### Version

Latest version

**Comment by eansharma** [comment]
Please Solve my error and send me the code where I mistake

**Comment by AlexOrthopy** [comment]
Hello, I encounter a similar problem: Permission.photos.request() returns denied on Android emulator and physical device.
But even it is denied if I still can open the gallery.

**Comment by eansharma** [comment]
If you don't request the necessary permission from the user and upload your app to the Play Store, it is likely to be rejected due to the app's permission issues. Google Play Store has strict guidelines regarding app permissions and user data access to ensure user privacy and security.

how I can solve this problem

thanks in advance.

**Comment by AlexOrthopy** [comment]
@eansharma Did you adjusted your Android Manifest file? 
Try to add `<uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/>`
to your `main/AndroidManifest.xml` file.
For access the media file those permission is needed. After I added it I was able to use`Permission.photos.request()` as expected

**Comment by eansharma** [comment]
Thanks, brother 😘

**Comment by eansharma** [comment]
can you share with us Ids like @insta fb and others?
for connecting if you are comfortable.

**Comment by mvanbeusekom** [comment]
Thanks @AlexOrthopy for clarifying this question.

I will close this issue as @AlexOrthopy is correct, to make sure the `Permission.photos.request()` permission works correctly it is necessary to add the `READ_MEDIA_IMAGES` permission to the `android/app/src/main/AndroidManifest.xml` file (just like any of the other permissions).
