### ISSUE TITLE
[Bug]: Permission.activityRecognition returns PermissionStatus.denied when requested for 2nd time after denying 1st time.

### ISSUE THREAD

**Issue by bharat8** [Baseflow/flutter-permission-handler#1098]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Windows

### Steps to reproduce

1. Request the ActivityRecoginition permission for the first time.
2. Get the status of the ActivityRecoginition permission.
3. If user denies, got the status of PermissionStatus.denied and again request the permission.
4. Again got the status of PermissionStatus.denied.

### Expected results

What i expected is that if the user denies the permission for the second time, I should get the status of PermissionStatus.permanentlyDenied which is not happening. It always get the status of PermissionStatus.denied.

### Actual results

User is shown the permission dialog to allow or deny the permission. Now, if the user denied this permission, I get the status of PermissionStatus.denied and I have the logic to again show the permission dialog and if user denies the permission again, I still get the status of PermissionStatus.denied.

### Code sample

<details><summary>Code sample</summary>

```dart
var status = await Permission.activityRecognition.status;

if(!status.isGranted) {
   status = await Permission.activityRecognition.status;
}

print(status);
```

</details>

### Version

10.4.2

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.7.12, on macOS 13.3.1 22E772610a darwin-arm64 (Rosetta), locale en-IN)
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.0.5/libexec/bin/dart, which
      is not inside your current Flutter SDK checkout at
      /Users/bharatsundal/Documents/development/flutter. Consider adding
      /Users/bharatsundal/Documents/development/flutter/bin to the front of your path.
Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.80.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```

</details>

**Comment by Benjamin-Leroux** [comment]
I have the same issue with the Camera permission.

**Comment by TimHoogstrate** [comment]
Dear @bharat8 or @Benjamin-Leroux,

I am unable to reproduce this issue. It works as expected on my Nexus 7.... On what Android version are you testing this?

Kind regards,

**Comment by Benjamin-Leroux** [comment]
Thank you for your answer @TimHoogstrate.
I faced this issue on Android 12, on a Xiaomi phone (POCO x3).

**Comment by Benjamin-Leroux** [comment]
I tried the example app and it works well. The problem was in my code. I didn't understand that I could not have the status "PermanentlyDenied" with out calling request first.

> WARNING: This can only be determined AFTER requesting this permission. Therefore make a request call first.

In my case, I want to show a pop-up before asking for permission, only if the permission is not permanently denied (or granted ofc). The pop-up goal is to not call permission request if the user does not want to grant the permission. But I guess it is not possible to not show the pop-up since I can't get the status "PermanentlyDenied" before calling request. And calling request before showing my popup makes no sense.

**Comment by TimHoogstrate** [comment]
Seems like you solved your issue. I'll keep the issue open for now to see If new information pops-up.
