### ISSUE TITLE
[Question]: when add permission handler to yml file ,pub get not work?

### ISSUE THREAD

**Issue by Alvirwalid** [Baseflow/flutter-permission-handler#1104]
### Please check the following before submitting a new issue.

- [ ] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-permission-handler/blob/main/permission_handler/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [ ] iOS
- [ ] Windows

### Your question

when add permission handler to new project ,pub get not working 

### Version

permission_handler: ^10.4.2

**Comment by Alvirwalid** [comment]
![Screenshot 2023-07-12 100247](https://github.com/Baseflow/flutter-permission-handler/assets/44261018/7b6765c9-5775-4722-8490-ffe5e0907607)

**Comment by JeroenWeener** [comment]
Hi @Alvirwalid, thanks for reaching out!

It seems like this might be a problem with either your network or environment settings, and less so with the plugin.
A search for `Get socket error trying to find package` led me to these pages:

- https://stackoverflow.com/questions/52158282/got-socket-error-trying-to-find-package-cupertino-icons-at-https-pub-dartlang
- https://github.com/dart-lang/pub-dev/issues/4610

Please see if any of the proposed solutions offer you any help.
