### ISSUE TITLE
[Question]: Flutter : how to save captured image in local storage Android 13 ?

### ISSUE THREAD

**Issue by essyty** [Baseflow/flutter-permission-handler#1113]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-permission-handler/blob/main/permission_handler/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [ ] iOS
- [ ] Windows

### Your question

You find below the code used to save the captured image in the local storage, the permessions is ok, and in mode debug i can fin the saved images, but when i build the apk and installed it, nothing happens.

var image = await boundary.toImage();
    var byteData = await image.toByteData(format: ui.ImageByteFormat.png);
    var ref = FFAppState().FrameRef;
    final directory = await getExternalStorageDirectory();
    final imagePath = '${directory?.path}/cl1box2_' + ref + '.png';
  

    final file = File(imagePath);
    await file.writeAsBytes(byteData!.buffer.asUint8List());

    print('Image saved to: $imagePath');

### Version

1

**Comment by KSnamAce** [comment]
`class SaveImageService {
  Future<bool> _getStoragePermission() async {
    DeviceInfoPlugin deviceInfo = DeviceInfoPlugin();
    AndroidDeviceInfo androidInfo = await deviceInfo.androidInfo;
    if (androidInfo.version.sdkInt < 33) {
      if (await Permission.storage.request().isGranted) {
        return true;
      } else if (await Permission.storage.request().isPermanentlyDenied) {
        await openAppSettings();
      }
    } else {
      if (await Permission.photos.request().isGranted) {
        return true;
      } else if (await Permission.photos.request().isPermanentlyDenied) {
        await openAppSettings();
      }
    }
    return false;
  }

  Future<void> saveImage(String imagePath,
      GlobalKey<ScaffoldMessengerState> scaffoldMessengerKey) async {
    bool permissionGranted = await _getStoragePermission();
    if (permissionGranted) {
      ByteData bytes = await rootBundle.load(imagePath);
      final result = await ImageGallerySaver.saveImage(
          bytes.buffer.asUint8List(),
          quality: 100);
      debugPrint('Image saved to gallery: $result');
      scaffoldMessengerKey.currentState?.showSnackBar(
        const SnackBar(
          content: Text('Image saved to gallery!'),
        ),
      );
    } else {
      debugPrint('Permission not granted. Unable to save image.');
      scaffoldMessengerKey.currentState?.showSnackBar(
        const SnackBar(
          content: Text('Permission not granted. Unable to save image.'),
        ),
      );
    }
  }
}`

**Comment by KSnamAce** [comment]
`class SaveImageService {`
 ` Future<bool> _getStoragePermission() async {`
    `DeviceInfoPlugin deviceInfo = DeviceInfoPlugin();`
    `AndroidDeviceInfo androidInfo = await deviceInfo.androidInfo;`
   ` if (androidInfo.version.sdkInt < 33) {`
      `if (await Permission.storage.request().isGranted) {`
        `return true;`
      `} else if (await Permission.storage.request().isPermanentlyDenied) {`
        `await openAppSettings();`
      `}`
    `} else {`
      `if (await Permission.photos.request().isGranted) {`
        `return true;`
      `} else if (await Permission.photos.request().isPermanentlyDenied) {`
        `await openAppSettings();`
      `}`
    `}`
    `return false;`
  `}`

my first time to answer why  not look like code >.<
and add this to AndroidManifest.xml
  `<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>`
   `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>`
   `<uses-permission android:name="android.permission.INTERNET"/>`
   `<uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/>`

**Comment by TimHoogstrate** [comment]
Dear @essyty,

Can you elaborate a bit on the issue? We don't understand the relation to the permission handler.

Kind regards,
