### ISSUE TITLE
[Question]:  Android 12 requests location and locationWhenInUse to report an error, with the error message: No permissions found in manifest for: [] 3

### ISSUE THREAD

**Issue by weifucheng1102** [Baseflow/flutter-permission-handler#1115]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-permission-handler/blob/main/permission_handler/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [ ] iOS
- [ ] Windows

### Your question

I have added all permissions related to location in the androidManifest.xml file as follows:

<img width="686" alt="image" src="https://github.com/Baseflow/flutter-permission-handler/assets/39686870/7c03233c-1d42-4a0c-ae4b-72fa1f1da007">

### Version

10.2.0

**Comment by mvanbeusekom** [comment]
Hi @weifucheng1102, 

Thank you for taking the time in posting this issue. To be able to help I would like to ask a few questions:

1. Does this only happend on Android 12, did you test on other Android devices?
2. Could you provide the output of the `flutter doctor -v` command?
3. Are the permissions added to the `android/app/src/main/AndroidManifest.xml` file? They should not be added to the `android/app/src/debug/AndroidManifest.xml` or `android/app/src/profile/AndroidManifest.xml` files.

A good way to analyse which permissions end up in the final `AndroidManifest.xml` file (being used by the application binary) is to check the contents of the `build/app/outputs/logs/manifest-merger-release-report.txt` file. This file is generated after running the `flutter run`, `flutter build appbundle` or `flutter build apk` commands and contains information on how the final `AndroidManifest.xml` (bundled with the application binary) is constructed. Specifically look for entries mentioning the `ACCESS_FINE_LOCATION` or `ACCESS_COARSE_LOCATION` permissions. Make sure the log doesn't mention anything about the location permissions being removed. If you feel this file doesn't contain any sensitive information, it would be very helpful to also share it with us.

**Comment by weifucheng1102** [comment]
[✓] Flutter (Channel stable, 3.7.0, on macOS 13.3.1 22E772610a darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[!] Android Studio (version 2022.2)
    ✗ Unable to find bundled Java version.
[✓] VS Code (version 1.80.1)
[!] Proxy Configuration
    ! NO_PROXY is not set
[✓] Connected device (2 available)
[✓] HTTP Host Availability

**Comment by mvanbeusekom** [comment]
@weifucheng1102, please use the `-v` switch when running `flutter doctor -v` command. Also please provide the other information requested.

**Comment by weifucheng1102** [comment]
I have tried Android 11 and there is no problem. I have also checked the manifest merge release report. text file and have permissions related to the location

**Comment by weifucheng1102** [comment]
[!] Flutter (Channel stable, 3.7.0, on macOS 13.3.1 22E772610a darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.7.0 on channel stable at /Users/apple/fvm/versions/3.7.0
    ! Warning: `flutter` on your path resolves to /Users/apple/fvm/versions/3.0.0/bin/flutter, which is not inside your current Flutter SDK checkout at /Users/apple/fvm/versions/3.7.0. Consider adding /Users/apple/fvm/versions/3.7.0/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/apple/fvm/versions/3.0.0/bin/dart, which is not inside your current Flutter SDK checkout at /Users/apple/fvm/versions/3.7.0. Consider adding /Users/apple/fvm/versions/3.7.0/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b06b8b2710 (6 months ago), 2023-01-23 16:55:55 -0800
    • Engine revision b24591ed32
    • Dart version 2.19.0
    • DevTools version 2.20.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[!] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 13.3.1 22E772610a darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 115.0.5790.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.

**Comment by mvanbeusekom** [comment]
@weifucheng1102, 

With the information provided I am unable to locate the problem. I have constructed a quick test application using the steps below. 

I have tested the application on the following devices:
- Redmi Note 9 (Android 12 API 31) 
- Emulator running Android 12 API 32 

During my tests the application runs fine and was able to request `locationWhenInUse` permissions without any problems. Could you please run the same application on your test devices (instructions and code provided below) and let me know if it works:

1. Create a new Flutter application: `flutter create permission_demo`.
2. Change into the `permission_demo` folder: `cd permission_demo`.
3. Add a dependency on the permission_handler: `flutter pub add permission_handler`.
4. Add logic to call the permission_handler in `main.dart` (see `main.dart` section below).
5. Enable location permissions in the `android/app/src/main/AndroidManifest.xml` file (see `AndroidManifest.xml` section below).
6. Run the application:
  * Initial status will be `denied`.
  * Hit the `+` floating action button to request permission. 
  * The dialog should show and select "Allow".
  * The permission will be updated to `allowed`.

<details>
<summary> android/app/src/main/AndroidManifest.xml </summary>

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android">

    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />

    <application
        android:label="permission_demo"
        android:name="${applicationName}"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>
```

</details>

<details>
<summary> main.dart </summary>

```dart
import 'package:flutter/material.dart';
import 'package:permission_handler/permission_handler.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Permission test'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String _notificationStatus = 'Not determined';

  @override
  void initState() {
    Permission.locationWhenInUse.status.then((PermissionStatus status) {
      setState(() {
        updateNotificationStatus(status);
      });
    });
    super.initState();
  }

  void updateNotificationStatus(PermissionStatus status) {
    _notificationStatus =
        status == PermissionStatus.granted ? 'allowed' : 'denied';
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'Permission status:',
            ),
            Text(
              _notificationStatus,
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () async {
          final PermissionStatus status =
              await Permission.locationWhenInUse.request();

          setState(() {
            updateNotificationStatus(status);
          });
        },
        tooltip: 'Request permission',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

</details>

The output of `flutter doctor -v` on my machine:

```
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4.1 22F770820d darwin-arm64, locale en-NL)
    • Flutter version 3.10.5 on channel stable at /Users/maurits/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (6 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/maurits/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (4 available)
    • M2003J15SC (mobile)         • 106fdad20410  • android-arm64  • Android 12 (API 31)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 32) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 13.4.1 22F770820d darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 115.0.5790.114

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by weifucheng1102** [comment]
Sorry, I tried a new demo and it's okay. Let me take a look at my code again. Sorry to bother you

**Comment by mvanbeusekom** [comment]
@weifucheng1102, thanks for confirming that the demo version works. I will go ahead and close the issue. If you run into another problem feel free to create a new issue.
