### ISSUE TITLE
[Bug]: Getting approximate location status after having paused the app, returns always denied

### ISSUE THREAD

**Issue by benoit-rolandeau-act** [Baseflow/flutter-permission-handler#1116]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Windows

### Steps to reproduce

The problem appears at least on Android 12

1. Call `Permission.locationWhenInUse.request()`
2. The user chooses `Allow only while using the app` and click on *`approximate` location* 
3. The request returns `granted`
4. Call right after the method: `Permission.locationWhenInUse.status`, it returns `granted`
5. If the user pauses the application (by opening another app for instance) and then go back to the app, if you call `Permission.locationWhenInUse.status`, it will always return `denied`, even after waiting 3 seconds (but I can get the position without exception).

*The problem only occurs when choosing `approximate location`*

### Expected results

It shouldn't have behaviour differences between precise and approximate in that case.

### Actual results

The method: `Permission.locationWhenInUse.status` returns `denied` if we pause the app

### Code sample

<details><summary>Code sample</summary>

```dart
final result = Permission.locationWhenInUse.request(); // Returns granted, even if user chooses approximate location
final secondResult = Permission.locationWhenInUse.status; // Returns granted
```

To call when the app is resumed after having be paused
```dart
final secondResult = Permission.locationWhenInUse.status; // Returns denied
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

10.3.3

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.6, on Microsoft Windows [version 10.0.22621.1992], locale fr-FR)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.3)
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.80.1)
[√] Connected device (4 available)
[√] Network resources

• No issues found!
```

</details>

**Comment by TimHoogstrate** [comment]
It works as expected on Android 13. But if someone can confirm this on Android 12 it would be great.

Kind regards,

**Comment by JeroenWeener** [comment]
Hi @benoit-rolandeau-act, thank you for taking the time to report this issue and providing helpful information!

I have tried to replicate the behavior you described. My findings are different from yours, but conceivably wrong nonetheless. It would be cool if we can determine why our findings differ and what the desired behavior should be. To that end I will describe my findings and link you the contents of the `main.dart` I used to verify the behavior.

Initially, `await Permission.locationWhenInUse.status` returns `PermissionStatus.denied`. When calling `Permission.locationWhenInUse.request()` and selecting `While using the app` with `approximate`, the function call future resolves in `PermissionStatus.granted`. Calling `await Permission.locationWhenInUse.status` now returns `PermissionStatus.denied` **regardless** of whether it is called immediately or after app pause. From here on, calling `Permission.locationWhenInUse.request()` will ask the user to upgrade the location to `precise location`. Regardless of the user's action (`keep approximate location`, `dismiss`), the future will resolve in `PermissionStatus.granted`.

From these findings, it seems that `request()` returns the correct status, as it returns `PermissionStatus.granted`, regardless of the location accuracy. `status`'s behavior seems incorrect, however, as it only returns `PermissionStatus.granted` if the precise location accuracy has been selected, and not when the approximate location accuracy has been selected.

I have tested on an emulated Pixel 5 running Android 13 (API 33). As my findings are different from yours, I want to invite you to run my code and see what happens for you. I have included a gist with the contents of my `main.dart`, which you should be able to plug into the `main.dart` of the example app of `permission_handler`. If you see the same behavior, the next step would be finding out why your code behaves differently. If you could provide us with a minimal reproducible code sample in the form of a gist containing a `main.dart`, we might be able to pinpoint the cause of this issue.

From these findings I think we should at least consider updating the logic for `Permission.locationWhenInUse.status`, so it returns `PermissionStatus.granted` for the approximate location setting.

Gist: https://gist.github.com/JeroenWeener/b4f522a8c75271ea4d33bc89f78bdd9b
Screenrecording of the behavior:

https://github.com/Baseflow/flutter-permission-handler/assets/9049645/afa7240d-5923-4e56-aec5-d06ff278b55d

**Comment by kostov** [comment]
@JeroenWeener
> From these findings I think we should at least consider updating the logic for Permission.locationWhenInUse.status, so it returns PermissionStatus.granted for the approximate location setting.

The behavior you dream of, and which looks logical, is already happening on iOS. However, if the authors of the plugin do as you say, and when choosing an _approximate_ geolocation, we will get the PermissionStatus.granted, then we will have a problem with another plugin (**network_info_plus**) -- also on Android :) (please, see https://github.com/Baseflow/flutter-permission-handler/issues/984#issuecomment-1681615614)

Here: https://pub.dev/packages/network_info_plus they say:
_"To access protected WiFi methods related to location, you must request additional permissions on Android and iOS. Users of this plugin should use the [permission_handler](https://pub.dev/packages/permission_handler) Flutter plugin to handle these cases."_
And:
_"If your app is targeting Android 10 (API level 29) SDK or higher, your app needs to have the ACCESS_FINE_LOCATION permission."_ (It's always been like this on iPhones)
 
I think, maybe we need to separate location permission on two: Permission.exactLocation and Permission.approxLocation?
