### ISSUE TITLE
[Question]: Permission Handler in Android 13

### ISSUE THREAD

**Issue by adeliaputrii** [Baseflow/flutter-permission-handler#1119]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-permission-handler/blob/main/permission_handler/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [ ] iOS
- [ ] Windows

### Your question

How to use permission handler in Android 13? 
I've already used this code in AndroidManifest.xml and manually enable it in the system settings  but it doesn't work :

<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"
                     android:maxSdkVersion="32" />
<uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>
 <uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/>
 <uses-permission android:name="android.permission.READ_MEDIA_VIDEO"/>
<uses-permission android:name="android.permission.READ_MEDIA_AUDIO"/>

### Version

10.4.3

**Comment by shashankantino** [comment]
Solution :
IN MENIFEST FILE : <uses-feature android:name="android.hardware.camera" />
IN APP LEVEL BUILD GRADLE : 
TargetSdkVersion to 32
compileSdkVersion to 33

**Comment by AmenyaZ** [comment]
After Adding permissions in the Manifest Use the following during implementation to check the Platform and Abdroid Verson. There after call the permission to be used based on the Android version.

 ```
Future<bool> _requestWritePermission() async {
    if (Platform.isAndroid) {
      AndroidDeviceInfo androidInfo = await DeviceInfoPlugin().androidInfo;
      int androidVersion = androidInfo.version.sdkInt;
      if (androidVersion < 12) {
        // For Android versions earlier than 12
        await Permission.storage.request();
        return await Permission.storage.isGranted;
      } else {
        // For Android 12 and later
        await Permission.manageExternalStorage.request();
        return await Permission.manageExternalStorage.isGranted;
      }
    }
    return false; // If the platform is not Android
  }
```

**Comment by JeroenWeener** [comment]
Hi @adeliaputrii, thank you for reaching out.

Could you provide me with more information on what you are trying to achieve? Are you having troubles requesting a specific permission, such as storage? You could help us help you by supplying a code sample of what you are trying.
