### ISSUE TITLE
[Bug]: Notification status is not correct .

### ISSUE THREAD

**Issue by harryandroiddev** [Baseflow/flutter-permission-handler#1123]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [ ] Android
- [X] iOS
- [ ] Windows

### Steps to reproduce

1.Start flutter  app  on ios .
2. run this code to check if there is notification enabled .

### Expected results

Get notification status correctly.

### Actual results

Always getting this  PermissionStatus.permanentlyDenied.

### Code sample

<details><summary>Code sample</summary>

```dart
 void checkNotificationPermissionStatus() async {
    final statusNotification = await Permission.notification.request();
    print(statusNotification);
    bool isGranted = statusNotification == PermissionStatus.granted;
    print('notification permission $isGranted');
    if (!isGranted) {
      print('permission is not granted');
      // AppSettings.openAppSettings(type: AppSettingsType.notification);
    }
  }
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

10.4.3

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.0 22A8380 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.81.0)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by mvanbeusekom** [comment]
Hi @harryandroiddev,

Have you enabled the notification permissions in the `ios/Podfile` file and added the required entries in the `ios/Runner/Info.plist` file? More information can be found in the "iOS" section of the [README](https://pub.dev/packages/permission_handler) page.
