### ISSUE TITLE
[Question]: MANAGE_EXTERNAL_STORAGE  

### ISSUE THREAD

**Issue by tmi111** [Baseflow/flutter-permission-handler#1132]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-permission-handler/blob/main/permission_handler/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [ ] iOS
- [ ] Windows

### Your question

How do I remove this permission from the manifest file if I don't need it

### Version

10.3.0

**Comment by JeroenWeener** [comment]
Hi @tmi111, thank you for reaching out!

You can remove the permission from the `AndroidManifest.xml` file. It should look like this:
```xml
<uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" />
```

**Comment by tmi111** [comment]
I deleted the permission_handler AndroidManifest from flutter plugins MANAGE_EXTERNAL_STORAGE permission Why does my app not close MANAGE_EXTERNAL_STORAGE
