### ISSUE TITLE
[Bug]: Permission popup not showing when requesting scheduleExactAlarm

### ISSUE THREAD

**Issue by AndyDavidJoyce** [Baseflow/flutter-permission-handler#1137]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Windows

### Steps to reproduce

1. Install the app 
2. Request setExactAlarm permission 

### Expected results

A permission popup asking the user to grant / deny access for the app to use exact alarm 

### Actual results

A permission popup does not display 

### Code sample

<details>

<summary>

Request both notification and scheduleExactAlarm permissions. The notification permission popup does display but the scheduleExactAlarm popup does not. I have tried just requesting the scheduleExactAlarm permission by itself but that still does not work

</summary>

```dart
  Future<void> requestNotificationPermission() async {
    await [Permission.notification, Permission.scheduleExactAlarm].request();
  }
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

10.4.3

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.3, on macOS 13.2.1 22D68 darwin-arm64, locale en-GB)
    • Flutter version 3.10.3 on channel stable at /Users/andyadmin/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f92f44110e (3 months ago), 2023-06-01 18:17:33 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/andyadmin/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 14 (API 34) (emulator)
    • iPhone 14 Pro Max (mobile)  • 0C286A20-B407-4F6E-803F-8163798B6425 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 116.0.5845.96

[✓] Network resources
    • All expected network resources are available.

```

</details>

**Comment by JeroenWeener** [comment]
Hi @AndyDavidJoyce, thank you for filing this bug report!

I created a PR to fix the issue: #1138. Should be resolved soon!

**Comment by AndyDavidJoyce** [comment]
@JeroenWeener I appreciate you getting back to me so quickly on this issue! 

Thanks for raising the PR. To confirm, does the PR include a fix for showing the initial permission popup? Reading through your description the PR just seems to talk about opening the settings page?

**Comment by JeroenWeener** [comment]
@AndyDavidJoyce it seems that Android does not show a permission dialog for this permission. The only way to change it is by opening the settings page: https://developer.android.com/training/scheduling/alarms#using-schedule-exact-permission. Android does this for select permissions. Another example is the `request_install_packages` permission.

**Comment by AndyDavidJoyce** [comment]
@JeroenWeener ahh got it! Sorry for not looking into it in more detail before raising the issue!

**Comment by JeroenWeener** [comment]
No problem @AndyDavidJoyce. I am happy you raised the issue so we could resolve it!
