### ISSUE TITLE
Getting "Unable to detect current Activity." when triggered "Permission.notification.request();" in my application.

### ISSUE THREAD

**Issue by Ruby6851** [Baseflow/flutter-permission-handler#1141]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-permission-handler/blob/main/permission_handler/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [ ] iOS
- [ ] Windows

### Your question

I am using Flutter as a module within my native application. When I trigger Permission.notification.request(), I encounter the 'Unable to detect current Activity' error. 
However, when I run my Flutter project as a standalone application (not embedded within a native app), it works fine.

### Version

10.4.3

**Comment by JeroenWeener** [comment]
Hi @Ruby6851, thank you for reaching out!

This is an interesting issue. We do not yet actively support this use case, but are open to do so. For that, we need to do some investigation to see if it is possible in the first place.

We are not too familiar with running Flutter inside native apps. You would help us out a ton by providing an example project showcasing the add-to-app architecture. If you can find the time, could you provide us with a GitHub repo that houses the use case?

Happy to hear from you!

**Comment by ChristianEdwardPadilla** [comment]
A potentially related issue:
https://github.com/Baseflow/flutter-permission-handler/issues/552

I'm not aware of anything that a plugin like this should need to do to support the add2app use case (a growing use case for Flutter, IMO): https://docs.flutter.dev/add-to-app
