### ISSUE TITLE
Is this "permission_handler" package is compatible with your embedded Flutter setup.

### ISSUE THREAD

**Issue by Ruby6851** [Baseflow/flutter-permission-handler#1142]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-permission-handler/blob/main/permission_handler/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [ ] iOS
- [ ] Windows

### Your question

I want to know "permission_handler" package is compatible with your embedded Flutter setup or not?

### Version

10.4.3

**Comment by ChristianEdwardPadilla** [comment]
There isn't enough information here for this issue to be useful. By embedded do you mean add-to-app (https://docs.flutter.dev/add-to-app)?

For simple questions like this you might be better served by the Flutter discord server, see https://flutter.dev/community.
