### ISSUE TITLE
[Bug]: My microphone permission is enabled, but Permission.microphone.status returns status.isDenied

### ISSUE THREAD

**Issue by lingstart** [Baseflow/flutter-permission-handler#1146]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [ ] Android
- [X] iOS
- [ ] Windows

### Steps to reproduce

When asked for microphone permission, select Allow. Obtaining the microphone status through Permission.microphone.status is status.isDenied

### Expected results

It should be status.isGranted

### Actual results

status.isDenied

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or video

Future<void> checkMicrophonePermission() async {
    PermissionStatus status = await Permission.microphone.status;
    if (status.isGranted) {
      print('麦克风权限已被授予');
    } else if (status.isDenied) {
      print('麦克风权限已被拒绝');
    } else if (status.isPermanentlyDenied) {
      print('麦克风权限已被永久拒绝');
    }
  }

### Version

10.4.3

### Flutter Doctor output

麦克风权限已被拒绝

**Comment by JeroenWeener** [comment]
Hi @lingstart, thank you for filing your issue!

I have investigated your issue but was unable to reproduce your outcome.

I tested the latest version of the permission handler (10.4.5) on an emulated iPhone 14 Pro.
You can find the code I used here: https://gist.github.com/JeroenWeener/a95574940ed609cf45c1f66787ae4acd

Could you test the code I provided to see if you get the same result? Additionally, please share the contents of your `Podfile` and `Info.plist`.

https://github.com/Baseflow/flutter-permission-handler/assets/9049645/dcd55b70-d070-40f4-9cd0-99c017d43b72
