### ISSUE TITLE
[Feature request]: Add support for Android 14+ partial media permissions

### ISSUE THREAD

**Issue by ChristianEdwardPadilla** [Baseflow/flutter-permission-handler#1156]
### Is there already an issue requesting this feature?

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Windows

### Use case

Android 14 adds a new permission ([`READ_MEDIA_VISUAL_USER_SELECTED `](https://developer.android.com/reference/android/Manifest.permission#READ_MEDIA_VISUAL_USER_SELECTED)) for granting partial access to photos/videos: https://developer.android.com/about/versions/14/changes/partial-photo-video-access

There is currently no way to request or check this permission in permission_handler.

### Proposal

This new permission should be added as a Dart-level permission API.

**Comment by IceTears1** [comment]
common request

**Comment by b-fab-michael** [comment]
same

**Comment by StigUK** [comment]
Any updates?

**Comment by GuyMangkorn** [comment]
+1

**Comment by Howard2595** [comment]
same

**Comment by TalRa1** [comment]
Same request :)

**Comment by RRrongrui** [comment]
same +1

**Comment by n3rdkid** [comment]
+1
Any update on this?

**Comment by guilhermefbc** [comment]
Same request :)

**Comment by minhkhang0107** [comment]
i have same problem. i try [photo manager](https://pub.dev/packages/photo_manager) to avoid that bug.

**Comment by LulleBulle** [comment]
I have submitted a PR #1347 that adds this permission.

**Comment by WHChaw** [comment]
+1
