### ISSUE TITLE
[Bug]: PermissionUtils.updatePermissionShouldShowStatus seems incomplete and not to do anything

### ISSUE THREAD

**Issue by wujek-srujek** [Baseflow/flutter-permission-handler#1162]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Windows

### Steps to reproduce

The implementation of `PermissionUtils.updatePermissionShouldShowStatus` looks very suspicious, see here: https://github.com/Baseflow/flutter-permission-handler/blob/8da4fc84a98a272653603fea81ed63bf89cf271e/permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java#L525-L538. It seems to be doing nothing (I expect `getManifestNames` to have no side effects), and if you go to that method in Android Studio, it even marks the last `return` as unnecessary.

Possible solutions:

1. Remove this method, as it does nothing, and assuming the code works as expected without this method doing anything sensible, there is no point in having it in the codebase, as it only serves to confuse readers.
2. Think of what it is supposed to do and implement it, because right now it definitely isn't doing it. This must be a source of bugs or advertised but missing functionality.

### Version

checked 11.0.0 and main

**Comment by mvanbeusekom** [comment]
Hi @wujek-srujek,

Thank you for reporting this issue, the `updatePermissionShouldShowStatus` was indeed obsolete. I have removed the method (and applied some additional static code analysis warnings) in PR #1167.
