### ISSUE TITLE
How to make the request message appear in Spanish?

### ISSUE THREAD

**Issue by kvzon1984** [Baseflow/flutter-permission-handler#1163]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-permission-handler/blob/main/permission_handler/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [X] iOS
- [ ] Windows

### Your question

How to make the request message appear in Spanish?

![Screenshot from 2023-09-22 22-54-31](https://github.com/Baseflow/flutter-permission-handler/assets/20741631/bcb2c922-fc78-41ba-9440-776a26ee81c6)

### Version

11.0.0

**Comment by JeroenWeener** [comment]
Hi @kvzon1984!

These dialogs are managed by the OS and are therefore subject to the device language. I don't think is possible to influence this from an application.

**Comment by ziqq** [comment]
You should make the Spanish language in platform side. And how say author above, it depends the device language.

In iOS this make like this.

<img width="151" alt="image" src="https://github.com/Baseflow/flutter-permission-handler/assets/20646071/dc54ea2a-3161-44db-8221-324e1d877cbf">
