### ISSUE TITLE
[Regression]: `requestInstallPackages.isGranted` returns `false` even when the permission is allowed

### ISSUE THREAD

**Issue by ImranR98** [Baseflow/flutter-permission-handler#1165]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Windows

### Old behavior

If the appropriate permission had been granted to the app in settings, `requestInstallPackages.isGranted` would return `true` as expected.

### Current behavior

Even if the appropriate permission has been granted to the app in settings, `requestInstallPackages.isGranted` returns `false`.

### Steps to reproduce

1. Create an Android Flutter app with `<uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />` in the Android manifest file.
2. Show the value of `requestInstallPackages.isGranted` in the app.
3. See if the value changes if the app is granted permission to install apps (it doesn't).

### Code sample

<details><summary>Code sample</summary>

```dart
  Future<void> getInstallPermission() async {
    if (!(await Permission.requestInstallPackages.isGranted)) {
      // Bug: This always runs even when the permission is already granted
      await Permission.requestInstallPackages.request();
    }
  }
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Current version

11.0.3

### Last version without regression

11.0.1

**Comment by drbx** [comment]
It looks like this is an issue with the latest version. After rolling back to version 10.4.5, everything is working fine.

**Comment by JeroenWeener** [comment]
Thanks for reporting @ImranR98!

We have patched the problem. You can pull it in by using `flutter-permission-handler` version 11+.
