### ISSUE TITLE
[Feature request]: iOS backgroundRefreshStatus

### ISSUE THREAD

**Issue by absar** [Baseflow/flutter-permission-handler#1174]
### Is there already an issue requesting this feature?

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).

### Please select affected platform(s)

- [ ] Android
- [X] iOS
- [ ] Windows

### Use case

On iOS users can disable Background App Refresh permission `backgroundRefreshStatus`, due to which background tasks cannot run if user has disabled the permission.
Background tasks are all types of tasks like `Background Fetch`, `BGAppRefreshTask`, `BGProcessingTask`, if the permission is disabled Apps cannot run tasks like daily maintenance, backups, background data processing, or periodic refreshes from server etc

Background App Refresh permission:
![image](https://github.com/Baseflow/flutter-permission-handler/assets/1186833/f7f511b8-a608-4664-80b2-fa07faa84187)

### Proposal

A new permission handler should be created to get `backgroundRefreshStatus` so that Apps would be able to check and prompt the user to enabled Background App Refresh in App settings

**Comment by tony-ditchlabs** [comment]
Looks like the [`background_refresh_status` package](background_refresh_status) can be used as a stopgap, but yes, would much prefer using this package exclusively.

**Comment by ened** [comment]
@mvanbeusekom this ticket should be closed
