### ISSUE TITLE
Having issue on IOS saying 'Flutter/Flutter.h' file not found

### ISSUE THREAD

**Issue by kotran88** [Baseflow/flutter-permission-handler#1177]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-permission-handler/blob/main/permission_handler/README.md).

### Please select for which platform(s) you need help

- [ ] Android
- [X] iOS
- [ ] Windows

### Your question

<img width="311" alt="스크린샷 2023-10-02 오후 10 12 51" src="https://github.com/Baseflow/flutter-permission-handler/assets/20656932/a76bfaf6-6ba1-4f59-bdfb-3c89c1e57af6">

i'm mac sonoma and ios17 . 

flutter doctor

[!] Flutter (Channel stable, 3.13.6, on macOS 14.0 23A344 darwin-arm64 (Rosetta), locale ko-KR)
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.18.6/libexec/bin/dart, which is not inside your current Flutter SDK checkout at
      /Users/pedrojung/Downloads/flutter. Consider adding /Users/pedrojung/Downloads/flutter/bin to the front of your path.
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.70.2)
[✓] VS Code (version 1.66.2)
[✓] Connected device (2 available)
    ! Error: Browsing on the local area network for pedro의 iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area
      network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

### Version

2.7.1

**Comment by mvanbeusekom** [comment]
Hi @kotran88,

Did you run `flutter build ios --no-codesign` before opening the project in Xcode? 

If you did and you are still experiencing the error, please provide the following information:

1. The contents of the `ios/Podfile`.
2. The output of the `flutter build ios --no-codesign --verbose` command.
3. The output of the `flutter doctor -v` command (so including the `-v` switch).

**Comment by mvanbeusekom** [comment]
From the `flutter doctor` information you provided, I noticed you are running an outdated version of the Dart SDK while using a new version of the Flutter SDK. This could also result into problems. 

Try updating the Dart SDK (which it seems you installed through Homebrew) to the latest version if possible.
