### ISSUE TITLE
don't show dialog and always return unknow

### ISSUE THREAD

**Issue by kuyu132** [Baseflow/flutter-permission-handler#118]
I requested the permission but the dialog didn't show up, the PermissionStatus's value is 'unknown'. I checked the settings, it showed 'no permissoins requested' in Permissions group. 

NOTICE:<uses-permission android:name="android.permission.CAMERA" />

I only requested this one permission.

Sad

**Comment by kuyu132** [comment]
android.permission.CAMERA

**Comment by shanzhenghan** [comment]
me too

**Comment by mvanbeusekom** [comment]
@kuyu132 can you provide more information regarding this issue? Questions I have are:

- Does this affect iOS, Android or both platforms?
- Which version of the plugin are you using?
- Can you supply an example we can use to reproduce this issue (or at least a code-snippet of the code you are using now)?

**Comment by juliengit2** [comment]
same issue for us, it works on android but on ios we get :

 _flutter: {PermissionGroup.storage: PermissionStatus.unknown}_

**Comment by harshshredding** [comment]
Same here ;(

**Comment by DenisShakinov** [comment]
It affects only Android and I'm pretty sure this is not a plugin issue. I had the same issue unless I changed my package name to delete all underscores from package names (e.g. change com.example.permission_test to just com.example.permission)

**Comment by EArminjon** [comment]
I had the same problem, you need to add permissions on AndroidManifest.xml to be able to request them.

**Comment by jallynme** [comment]
I had the same issue too it's happened on Android return status unknown and no pop shown

**Comment by EArminjon** [comment]
> I had the same issue too it's happened on Android return status unknown and no pop shown

Did you see my answer ?

**Comment by mvanbeusekom** [comment]
@kuyu132, @jallynme, @harshshredding, @juliengit2, as mentioned by @EArminjon please make sure you include the necessary permissions in you `AndroidManifest.xml` (for Android) and `Info.plist` (for iOS) files. On Android the permission popup is indeed not shown when the permissions are not listed in the `AndroidManifest.xml` file. 

On iOS you should get a `PlatformException` when you are missing the required permissions in your `Info.plist` file. This is also mentioned in the `README.md` in the root of the repo.
