### ISSUE TITLE
[Bug]: Permission.photos.request() didn't work at Android 13 above in Flutter 2.10.5

### ISSUE THREAD

**Issue by michaelsof47** [Baseflow/flutter-permission-handler#1185]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Windows

### Steps to reproduce

1. Install apps
2. Access Page
3. Camera Permission was show. but, Read Media Permission didn't show

### Expected results

Read Media Permission didn't show in Apps

### Actual results

Read Media Permission had shown in Apps

### Code sample

<details><summary>Code sample</summary>

```dart
if (await Permission.camera.request().isGranted) {
      DeviceInfoPlugin infoPlugin = DeviceInfoPlugin();
      AndroidDeviceInfo? info = await infoPlugin.androidInfo;
      if (await Permission.photos.request().isGranted &&
          info.version.sdkInt! >= 33) {
        //access file storage
      } 
      else
       //show alert based on permission storage
    } else
      await showAlertError(
          //show alert based on permission camers
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

9.0.5 (Permission Handler) and 2.10.5 (Flutter Version)

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.7 21G816 darwin-x64, locale en-ID)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[!] Android Studio (version 2022.3)
    ✗ Unable to find bundled Java version.
[✓] VS Code (version 1.83.0)
[✓] Connected device (1 available)
[✓] HTTP Host Availability
```

</details>

**Comment by JeroenWeener** [comment]
Hi @michaelsof47, thank you for filing a bug report.

Have you tried upgrading the `permission_handler` to the newest version (11.0.1)? I don't think version 9.0.5 exists, are you sure that's the version you are using? Version 9 of the plugin is about as old as Android 13, so it might well be that the permissions do not work correctly yet.
