### ISSUE TITLE
[Question]: My app required exact alarm permission (canScheduleExactAlarms()) from user to show schedule notification (I am using flutter_local_notification to show notification) my question is how can i achieved this permission using permission handler?

### ISSUE THREAD

**Issue by pranavo72bex** [Baseflow/flutter-permission-handler#1186]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-permission-handler/blob/main/permission_handler/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [ ] iOS
- [ ] Windows

### Your question

https://stackoverflow.com/questions/71031091/android-12-using-schedule-exact-alarm-permission-to-get-show-data-at-specific-t

![Screenshot 2023-10-12 at 12 21 58](https://github.com/Baseflow/flutter-permission-handler/assets/71395812/a333ee07-ea39-4133-a888-f3790dfa372b)

### Version

10.2.0

**Comment by JeroenWeener** [comment]
Hi @pranavo72bex,

Have you tried calling `Permission.scheduleExactAlarm.request()`?

**Comment by pranavo72bex** [comment]
> Hi @pranavo72bex,
> 
> Have you tried calling `Permission.scheduleExactAlarm.request()`?

It is providing the status but not opening app settings 🤔

**Comment by JeroenWeener** [comment]
I ran the example application on an emulator running Android 12 and Android 14 and the behavior seems as expected.
Can you tell me about your setup and how it differs from the example application? Perhaps the `AndroidManifest.xml` is different?


https://github.com/Baseflow/flutter-permission-handler/assets/9049645/d1730d5e-72a5-4041-a5d5-2b5dd8118d64
