### ISSUE TITLE
[Question]: ImergeDebugResources-17:/values/values.xml:3874: error: style attribute 'android:attr/customOperation1' not found. error: failed linking references.

### ISSUE THREAD

**Issue by e-Mood** [Baseflow/flutter-permission-handler#1187]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-permission-handler/blob/main/permission_handler/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [ ] iOS
- [ ] Windows

### Your question

mergeDebugResources-17:/values/values.xml:3874: error: style attribute 'android:attr/customOperation1' not found.
error: failed linking references.

I met above compile error while compile my demo apk when I want to use the attrs added by myself in /frameworks/base/core/res/res/values/attrs.xml and public.xml . 
In framework I add atts customOperation1 and framework compile OK, and then I configured dependence of classes.jar in Android Studio gradle file . But when I uses the attrs customOperation1 in my demo apk's theme , there's above error.

Something more : I added some interfaces in framework and configured classes.jar in my demo apk project ,and it can compile well. And also no problem at runtime when I called the interfaces added in framework.

So why the added attrs can not work ?  Anyone any suggestions ?

### Version

1

**Comment by e-Mood** [comment]
Below is the code in my demo app theme try to use added attrs:
<item name="android:customOperation1">@drawable/decor_maximize_button_light</item>

**Comment by JeroenWeener** [comment]
Hi @e-Mood,

Is this a question specific to the permission handler? From the information you provided it seems to me that you require help directed at Android and its build process.

**Comment by e-Mood** [comment]
> Hi @e-Mood,
> 
> Is this a question specific to the permission handler? From the information you provided it seems to me that you require help directed at Android and its build process.

Hi @JeroenWeener,
Sorry for require help from wrong place. Yes I want help at Android and its build process

**Comment by JeroenWeener** [comment]
No worries. You can find help at several places online. For example the Android Stack Exchange: https://android.stackexchange.com/ and StackOverflow: https://stackoverflow.com/.

Having a quick glance at your question, the problem might be coming from the way you access your custom `attr`. If my memory serves me well, `android:attr` retrieves attributes bundled with the Android SDK. To access your `attr` you should leave out `android`. Your line of code would then become `attr/customOperation1`. I don't think you should be editing `/frameworks/base/core/res/res/values/attrs.xml` as this is part of the Android SDK. Instead, create your own `attrs.xml` file in the `values` directory in your project.
