### ISSUE TITLE
[Question]: Request "ignoreBatteryOptimizations" and allow, but return denied.

### ISSUE THREAD

**Issue by StarAndSun** [Baseflow/flutter-permission-handler#1191]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-permission-handler/blob/main/permission_handler/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [ ] iOS
- [ ] Windows

### Your question

I use android 13 on my oppo phone. In the Manifest by adding < USES - permission android: name = "android. Permission. REQUEST_IGNORE_BATTERY_OPTIMIZATIONS" / >. And use PermissionStatus state = await Permission. IgnoreBatteryOptimizations. Request (); . In the popup, Allow is selected, but denied is returned. Hoping to get some advice.

### Version

11.0.1

**Comment by mvanbeusekom** [comment]
Hi @StarAndSun,

Thank you for reporting this issue. I was able to reproduce the issue on my Google Pixel 7a using the permission_handler example app. 

This is something we will look into.

**Comment by Coimbra1984** [comment]
I have the same problem on a Samsung A53. My workaround is calling Permission.ignoreBatteryOptimizations.request().isGranted twice.

**Comment by MSOB7YY** [comment]
just for additional info, it prints `D/permissions_handler( 7414): No permissions found in manifest for: []16` in the terminal

**Comment by mvanbeusekom** [comment]
@StarAndSun, @Coimbra1984, this issue is resolved in version 12.0.1 of the permission_handler_android plugin.

**Comment by anandrex5** [comment]
For me it works -

Add this dependency to the pubspec.yaml - disable_battery_optimization: ^1.1.1

and when you press any Button that request battery saver settings -

ElevatedButton(
  onPressed: () async {
    await Utils(context).requestBatteryOptimization();
  },
  child: Text('Request Battery Optimization'),
)


and this is the Util method, which opens the battery-saver settings where you can select No restrictions  -

import 'package:disable_battery_optimization/disable_battery_optimization.dart';


// Request battery optimization settings
  Future<void> requestBatteryOptimization() async {
    try {
      bool isBatteryOptimizationDisabled =
          await DisableBatteryOptimization.isBatteryOptimizationDisabled ?? false;

      if (!isBatteryOptimizationDisabled) {
        // Open settings to disable battery optimization
        DisableBatteryOptimization.showDisableBatteryOptimizationSettings();
      } else {
        Fluttertoast.showToast(msg: 'Battery optimization is already disabled for this app.');
      }
    } catch (e) {
      Fluttertoast.showToast(msg: 'Failed to check battery optimization settings: $e');
    }
  }

**Comment by AliGanjehei** [comment]
i have same problem on Xiaomi 11T pro android version 13 with the permission_handler 11.4.0 @mvanbeusekom
