### ISSUE TITLE
[Question]: add flutter 3.13.8 support with latest sdk of dart

### ISSUE THREAD

**Issue by fisforfaheem** [Baseflow/flutter-permission-handler#1197]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-permission-handler/blob/main/permission_handler/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [ ] iOS
- [ ] Windows

### Your question

kindly fully support flutter 3.13.8

### Version

latest

**Comment by mvanbeusekom** [comment]
Hi @fisforfaheem,

Are you having any specific issues? The current constraints in the permission_handler package are:

```yaml
environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=2.8.0"
```

Meaning every Dart SDK between version 2.15.0 and 4.0.0 is supported and every Flutter SDK bigger or equal to 2.8.0 is supported. 

Testing the permission_handler locally (and in the CI environment) works fine.

**Comment by fisforfaheem** [comment]
If i lower the dart version other packages cause issue on latest flutter sdk
