### ISSUE TITLE
[Regression]: PlatformException(-1, Failed to start recording, Error Domain=NSOSStatusErrorDomain Code=1718449215 "(null)", null)

### ISSUE THREAD

**Issue by mostafiz9900** [Baseflow/flutter-permission-handler#1199]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).

### Please select affected platform(s)

- [ ] Android
- [X] iOS
- [ ] Windows

### Old behavior

```
  Future<void> startRecord() async {
    try {
    var status = await Permission.microphone.request();
      if (status.isGranted) {
        Directory directory = await getApplicationDocumentsDirectory();
        String epochTime = DateTime.now().microsecondsSinceEpoch.toString();
        String pathToAudio = '${directory.path}/audio_$epochTime/*.mp3';
        await audioRecord.start(path: pathToAudio,encoder:GetPlatform.isIOS? record.AudioEncoder.wav: record.AudioEncoder.aacLc, numChannels: 2, bitRate: GetPlatform.isIOS? 320000: 128000);
        isRecording = true;
        if (!isTimerPaused) {startCountdownTimer();}
        update();
      } else {
        Helpers.snackBarForError(titleText: "Permission Denied", bodyText: "You need to grant microphone permission to record audio.",);
      }
    }on Exception catch (error) {
      logError(">>>>>>>>>> <Start Record> >>>>>>>>>>>>>$error");
      Helpers.snackBarForError(titleText: "Start Record", bodyText: error.toString());
    }
  }
```

### Current behavior

not working audio record

### Steps to reproduce

record audio

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>
ss

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Current version

permission_handler: ^11.0.1

### Last version without regression

permission_handler: ^11.0.1

**Comment by JeroenWeener** [comment]
Hi @mostafiz9900, thank you for reaching out!

Judging by the code and error you submitted, I think this might be an issue with the audio recording package you are using, rather than with the permission plugin.
