### ISSUE TITLE
After the user refuses network permission when entering the app in iOS

### ISSUE THREAD

**Issue by giantss** [Baseflow/flutter-permission-handler#1205]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-permission-handler/blob/main/permission_handler/README.md).

### Please select for which platform(s) you need help

- [ ] Android
- [X] iOS
- [ ] Windows

### Your question

After the user refuses network permission when entering the app in iOS, does the plug-in provide an API to request network permission again? I haven't found any yet.

### Version

10.3.0

**Comment by mvanbeusekom** [comment]
Hi @giantss,

On iOS it is not allowed to re-request permissions once the user has actively denied access. The only solution here is to redirect the user to the application settings in the general iOS settings page and ask him to allow permission.
