### ISSUE TITLE
[Bug]: Permission.locationAlways.request() does not show a dialog on iOS but just returns PermissionStatus.denied 

### ISSUE THREAD

**Issue by LeonP2ER** [Baseflow/flutter-permission-handler#1211]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [ ] Android
- [X] iOS
- [ ] Windows

### Steps to reproduce

1. Create new app to rule out anything project specific
2. Setup the plugin as stated in the readme.
3. add `await Permission.locationWhenInUse.request()` and `await Permission.locationAlways.request()` to the `onPressed` method of the button in the Flutter default app
4. Press the button on a real iOS device

### Expected results

I expect the app to first show the dialog for the `locationWhenInUse` request. Then when I authorize to use my location when the app is used, I expect a second dialog to show up to authorize the permanent use of the location.

### Actual results

Only the first dialog shows. 
`await Permission.locationAlways.request()` always returns `PermissionStatus.denied`.

I even tried to add a delay as seen in the code sample. But that did not work either.

### Code sample

<details><summary>Code sample</summary>

```dart
  void _incrementCounter() async {
    final p1 = await Permission.locationWhenInUse.request();
    print(p1);
    
    await Future.delayed(Duration(seconds: 3));

    final p2 = await Permission.locationAlways.request();
    print(p2);
  }
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

11.0.1

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.9, on macOS 14.1 23B74 darwin-arm64, locale de-DE)
    • Flutter version 3.13.9 on channel stable at /Applications/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (12 days ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/leon/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/leon/Library/Android/sdk
    • Java binary at: /Users/leon/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.10121639/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/leon/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.10121639/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio (version 2021.2)
    • Android Studio at /Users/leon/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/212.5712.43.2112.8512546/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.76.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    - 

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by tiyberius** [comment]
I am also experiencing trouble with `Permission.locationAlways.request()`, as it is always returning denied and I have no idea why. I'm using the following code:

```
if (await Permission.locationWhenInUse.request().isGranted) {
  if (await Permission.locationAlways.request().isGranted) {
    log.fine('Always location granted!!! Yay! 🎉🎊🥳');
  } else {
    log.fine('Always location permission denied. Oh no 😕');
  }
} else {
  log.fine('Location "whenInUse" permission denied. Ruh roh 😕');
}
```

When I await `Permission.locationWhenInUse.request().isGranted`, it works great but when I try to await `Permission.locationAlways.request().isGranted` the code seems to zip right by and return denied. When I execute the code in a debugger, and I step _slowly_ through the code, line by line, it works but whenever I run it in real-time, it does not work.

I tested this in an iOS Simulator on iOS 16.4 and also on a physical device, an iPhone 7 running iOS 15.8

**Comment by tiyberius** [comment]
Ah, looks like this is absolutely related to https://github.com/Baseflow/flutter-permission-handler/issues/1152. I've already implemented a LifeCycleManager so I will rely on that instead.

**Comment by TimHoogstrate** [comment]
Dear @tiyberius, 

Good to see that you found a solution for your issue. 

Kind regards,
