### ISSUE TITLE
[Bug]: Android: "onRequestPermissionsResult is called without results." and subsequent exception is thrown: "PermissionHandler.PermissionManager, A request for permissions is already running, please wait for it to finish before doing another request"

### ISSUE THREAD

**Issue by tom-vanlieshout** [Baseflow/flutter-permission-handler#1222]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Windows

### Steps to reproduce

Hi Baseflow-team 👋,
_**For reproduction steps, please read the list below.**_

We're trying to request permission for notifications using the permission_handler package. My colleagues and I are facing the below issue only on android - on iOS it all works as expected. We've done extensive debugging and concluded that we do not call `notification.request()` more than once (and definitely not in quick succession).

### Research

We've also done some digging into the Java-classes of the plugin. We've found that, within `permission_handler_android-11.0.1/PermissionManager.java`, within `onRequestPermissionsResult`, both arrays (`permissions` and `grantedResults`) have a length of `0`. This is where the warning gets logged. Every subsequent call will throw the Exception. Our hunch is that the listener of the first call is never disposed and that this may cause the Exceptions.

### Steps to reproduce

1. Create a Flutter app using `flutter create`, make the `_incrementCounter`-method async and call the following code within `_incrementCounter`: `await Permission.notification.request();`
2. The first time you tap the button - **so after deleting the app and doing a fresh build**, this will log the warning in the console: 
 > onRequestPermissionsResult is called without results. This is probably caused by interfering request codes. If you see this error, please file an issue in flutter-permission-handler, including a list of plugins used by this application: https://github.com/Baseflow/flutter-permission-handler/issues
3. Every subsequent button press will throw the Exception:
>PlatformException (PlatformException(PermissionHandler.PermissionManager, A request for permissions is already running, please wait for it to finish before doing another request (note that you can request multiple permissions at the same time)., null, null))

### Expected results

I'd expect no warning to be logged - and for every subsequent call no exception is thrown. I'd expect that `notification.request()` opens an Android popup-window requesting for permission to show notifications to the user.

### Actual results

As described, the first call will log a warning, then every call after the first will throw an exception

### Code sample

To reduce the scope as much as we could, we tried the below sample app. However, in our actual app we are requesting the permission through a Cubit. We've done the debugging there to rule out that the call is done more than once.

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:permission_handler/permission_handler.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  void _incrementCounter() async => await Permission.notification.request();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: const Text("Body"),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```

</details>

<details><summary>pubspec.yaml</summary>

```yaml
name: sandbox
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
```

</details>

</details>

<details><summary>AndroidManifest.xml</summary>

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.sandbox">
       <!-- Permissions options for the `notification` group -->
   <uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>
    <!-- Permissions options for the `access notification policy` group -->
    <uses-permission android:name="android.permission.ACCESS_NOTIFICATION_POLICY"/>
   <application
        android:label="sandbox"
        android:name="${applicationName}"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>
```

</details>

<details><summary>app/build.gradle</summary>

```gradle
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 33
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.sandbox"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-build-configuration.
        minSdkVersion flutter.minSdkVersion
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}
```

</details>

### Version

11.0.1

### Flutter Doctor output

Our Flutter version is 3.3.10 as we are still in the process of upgrading. As mentioned before, it works on iOS, with the same Flutter doctor output.

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.10, on macOS 14.0 23A344 darwin-arm, locale en-NL)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[!] Android Studio (version 2022.3)
    ✗ Unable to find bundled Java version.
[✓] VS Code (version 1.83.1)
[✓] VS Code (version 1.80.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

! Doctor found issues in 2 categories.
```

**Comment by YoungBloodn** [comment]
I also encountered the same problem！  Android 13

**Comment by TimHoogstrate** [comment]
Dear @tom-vanlieshout,

Thanks for filing this issue and adding the additional information. 

Personally I am unable to reproduce this issue with your code samples. However, I am building this on an Android 13 Emulator and a different flutter version (it should probably not make a big difference). 

Did the issue happen every time you tried the provided example? I mean, was it reproducible 100%? And in that case, could you provide a complete little example project? Then I can check if it is also reproducible on our environment. It helps a lot solving this issue.

The team had seen similar issues before, however, we have not been able to fully reproduce the issue. There is a little indication how we could prevent this issue from happening in the future.

Dear @YounBloodn,

can you elaborate a bit more on your comment, e.g. add some example code or steps to reproduce?

Looking forward for your reply,

**Comment by tom-vanlieshout** [comment]
Hi @TimHoogstrate,

Thank you for looking into this.

> Did the issue happen every time you tried the provided example?

Yes, this is 100% reproducable. While debugging with my colleague we uninstalled & built fresh instances many times over - the issue would always occur in the exact same manner as described in this issue.

> And in that case, could you provide a complete little example project?

I'll compress the sandbox-project I used for debugging. You should be able to unzip this on your local machine, run `flutter pub get && flutter run`. The only differences that then remain (from what I can tell), would be the Flutter version and possibly Java versions. Perhaps you can try the sample project with Flutter version 3.3.10 (using [fvm](https://fvm.app/) is an easy way of switching between SDKs).

[sandbox.zip](https://github.com/Baseflow/flutter-permission-handler/files/13365207/sandbox.zip)

**Comment by TimHoogstrate** [comment]
Dear @tom-vanlieshout,

Thanks for your example app. I was indeed able to reproduce this with flutter 3.3.10. With a newer flutter version this is not happening. I'll discuss with the team how to proceed. If you think about upgrading your project this issue will probably be resolved. 

Kind regards,

**Comment by tom-vanlieshout** [comment]
Hi @TimHoogstrate 

Thanks for the quick response. That is good news. We are planning to upgrade soon. It still surprises me a little bit: the plugin is compatible with the Flutter version we are using, so I'd expect it to work :)

Interested to see what the root cause / solution turns out to be!

Kind regards,

**Comment by eeesnghyun** [comment]
I aslo encountered this issue. 
In my case, it was caused by the difference between completeSdkVersion and targetSdkVersion.

Here's my [post](https://shxrecord.tistory.com/301))

**Comment by TimHoogstrate** [comment]
Dear @eeesnghyun,

Thanks for your post. By reading your post I found out that this might be the reason why @tom-vanlieshout has this issue. 

When we checked the sandbox of Tom we noticed that: `targetSdkVersion flutter.targetSdkVersion` seems to be flutter dependant. Resulting in the issue with flutter (in this case) 3.3.10

I'll add this to the FAQ of the plugin. Therefore I'll label this issue as a documentation enhancement. 

Kind regards,

**Comment by TimHoogstrate** [comment]
Resolved by PR [1229](https://github.com/Baseflow/flutter-permission-handler/pull/1229)

**Comment by filipedfs** [comment]
I changed the flutter version to the newest one and changed the compileSdkVersion and targetSdkVersion to 33. None of that worked.

**Comment by tom-vanlieshout** [comment]
Hi @TimHoogstrate ,

Checking in to let you know that upgrading to Flutter version 3.13.8 indeed resolved the issue for Android. The plugin now requests permission through a popup or takes me to the settings. 👍

However, I noticed the app crashes (and hangs on the Splash screen) when you do the following:
1. Request push permission in the app
2. Put the app in background, go to system settings and turn push permission off for the app - the app crashes
3. Return to the app - it now shows a splash screen

The app crashes right after turning the toggle for push permission off in the system settings. I'm not sure whether this is related to the plugin. I am certain that this is not an issue on iOS.

**Comment by tom-vanlieshout** [comment]
> I changed the flutter version to the newest one and changed the compileSdkVersion and targetSdkVersion to 33. None of that worked.

Perhaps it's good to try the usual: run `flutter clean` and `flutter pub get` and try to create a new emulator (to ensure nothing is cached of your previous build).

**Comment by TimHoogstrate** [comment]
@tom-vanlieshout,

This looks like a known Android issue I saw before. It happens on Android when you run your app in debug mode. It is because the Activity will be recreated. It will not happen if you run in release mode. If this does not resolve your issue, please create a new issue. I'll close this issue for now. Feel free to reopen the issue if new information pops-up, or create a new issue if needed. Success with your project. 

Kind regards,

**Comment by Mageshcoder** [comment]
Please check this url to fix your issue 

https://shxrecord.tistory.com/301

Solution - Increase your TargetSdkversion to 33, that's all

**Comment by letisoft** [comment]
Hello,

I am still getting the error:
permission_handler: ^12.0.3
compileSdk = 36
targetSdk = 36

but still getting:
onRequestPermissionsResult is called without results. This is probably caused by interfering request codes. If you see this error, please file an issue in flutter-permission-handler
if the user clicks the Adnroid system back button.

please note I only got this on Sasmsung A56 Android 16.

Please find sample app attached.

Best regards:
V

[flutter_location_app.zip](https://github.com/user-attachments/files/29196890/flutter_location_app.zip)

**Comment by letisoft** [comment]
Hello,

to make it worse I can confirm that native side is ok. Following code works:
    private final ActivityResultLauncher<String[]> locationPermissionLauncher =
            registerForActivityResult(
                    new ActivityResultContracts.RequestMultiplePermissions(),
                    result -> {
                        Boolean fine = result.get(Manifest.permission.ACCESS_FINE_LOCATION);
                        Boolean coarse = result.get(Manifest.permission.ACCESS_COARSE_LOCATION);
                        boolean granted = Boolean.TRUE.equals(fine) || Boolean.TRUE.equals(coarse);
                        //updateStatus(granted);
                    });
so the Samsung behaves as expected

Best regards:
V

**Comment by letisoft** [comment]
Hello,

I am not sure, haven't check the full flow but the problem is here:
PermissionManager.java, onRequestPermissionsResult:

        if (permissions.length == 0 && grantResults.length == 0) {
            pendingRequestCount = 0;
            Log.w(PermissionConstants.LOG_TAG, "onRequestPermissionsResult is called without results. This is probably caused by interfering request codes. If you see this error, please file an issue in flutter-permission-handler, including a list of plugins used by this application: https://github.com/Baseflow/flutter-permission-handler/issues");
            //return false;
        }

fixes it.

Best regards:
V
