### ISSUE TITLE
[Feature request]: "Add to scheduled summary" tracking

### ISSUE THREAD

**Issue by subzero911** [Baseflow/flutter-permission-handler#1224]
### Is there already an issue requesting this feature?

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).

### Please select affected platform(s)

- [ ] Android
- [X] iOS
- [ ] Windows

### Use case

Since iOS 15+, the user can select "Add to scheduled summary" for notifications permission.
![image](https://github.com/Baseflow/flutter-permission-handler/assets/12999702/59e11bc5-f6e5-4203-9851-f9b3100efb30)

https://support.apple.com/en-us/HT201925

Currently there's no way to check if a user had chosen this option via `permission_handler` API.

### Proposal

Add a new state to the PermissionStatus enum.

`PermissionStatus.scheduledSummary` (iOS-specific && notification-specific)

[documentation](https://developer.apple.com/documentation/usernotifications/unnotificationsettings/3747263-scheduleddeliverysetting)

**Comment by TimHoogstrate** [comment]
Dear @subzero911,

Thanks for filing this feature request. After a brief discussion with the team we decided that this is not the responsibility of the permission-handler. 

The permission returns the same status for both "granting" options. The `scheduledDeliverySetting` is a device setting that is not directly related to the permission status.

I'll close this issue for now. Feel free to reopen this ticket or open a new one if new information pops-up.

Kind regards,
