### ISSUE TITLE
[Bug]: OnePlus 9 Pro mobile phone, Android version 13, cannot pop up to apply for storage permission, and the storage permission status recognition error

### ISSUE THREAD

**Issue by FairyWorld** [Baseflow/flutter-permission-handler#1247]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Windows

### Steps to reproduce

Permission.storage.request()

### Expected results

A dialog box for applying for storage permissions can pop up and the permission status can be correctly identified.

### Actual results

No storage permission pop-up box appears, and the return status is denied. I tried to grant storage permission directly to the app, and found that after granting storage permission and restarting the app, the status of Permission.storage was still denied, but i can actually turn off storage permission verification and open the photo album directly.

### Code sample

<details><summary>Code sample</summary>

```dart
static void getStorage(Function()? onGranted) async {
    // Unable to pop up the authorization box, result always denied, Even if I manually grant storage permissions and restart the app
    if (await Permission.storage.request().isGranted) {
      onGranted?.call();
    }
    //  result always denied, Even if I manually grant storage permissions and restart the app
    if (await Permission.storage.isDenied) {
    }
  }

void pick(){
    getStorage((){
        // The code here will never execute unless I manually grant storage permissions and comment out the check for storage permission status
        static final ImagePicker _picker = ImagePicker();
        final XFile? image = await _picker.pickImage(source: ImageSource.gallery);
    });
}
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

10.4.5

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by mvanbeusekom** [comment]
Hi @FairyWorld,

As documented with the `Permission.storage` enum, this permission has been deprecated by Google since Android 13+. Instead you should make use of the `Permission.photos`, `Permission.media` or `Permission.audio` permissions.

The documentation reads as follows:

```
Permission for accessing external storage.

Depending on the platform and version, the requirements are slightly
different:

**Android:**
- On Android 13 (API 33) and above, this permission is deprecated and
always returns `PermissionStatus.denied`. Instead use `Permission.photos`,
`Permission.video`, `Permission.audio` or
`Permission.manageExternalStorage`. For more information see our
[FAQ](https://pub.dev/packages/permission_handler#faq).
- Below Android 13 (API 33), the `READ_EXTERNAL_STORAGE` and
`WRITE_EXTERNAL_STORAGE` permissions are requested (depending on the
definitions in the AndroidManifest.xml) file.

**iOS:**
- Access to folders like `Documents` or `Downloads`. Implicitly granted.
```

An example on how you could do this could look like this:

```dart
if (Platform.isAndroid) {
  final androidInfo = await DeviceInfoPlugin().androidInfo;
  if (androidInfo.version.sdkInt <= 32) {
    use [Permissions.storage.status]
  }  else {
    use [Permissions.photos.status]
  }
}
```
