### ISSUE TITLE
[Bug]: Failing to request permissions on android

### ISSUE THREAD

**Issue by NWADEM** [Baseflow/flutter-permission-handler#1253]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Windows

### Steps to reproduce

1. Go to the link to the project https://app.flutterflow.io/project/ble-trial5-95e6qh
2. Download apk and install app

### Expected results

As I have requested permissions correctly in the bleRequest method and have called it in the SplashPage action flow, a permission request should pop up. 

### Actual results

The application was running fine until this week, and even after restoring a previous version of it, no pop-up was displayed. The device settings confirm that no permissions were requested from my application. 

### Code sample

Future<bool> bleRequest() async {
bool status = false;
if (await Permission.bluetoothAdvertise.status.isGranted &&
      await Permission.bluetooth.status.isGranted &&
      await Permission.bluetoothConnect.status.isGranted &&
      await Permission.bluetoothScan.status.isGranted &&
      await Permission.locationWhenInUse.status.isGranted) 
{
    status = true;
}
 if (!status) {
    await Permission.bluetooth.request();
    await Permission.bluetoothConnect.request();
    await Permission.bluetoothScan.request();
    await Permission.bluetoothAdvertise.request();
    await Permission.locationWhenInUse.request();
  }
}

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

10.0.0 (I have also tried it in 11.0.0)

### Flutter Doctor output

N/A

**Comment by leandronn** [comment]
Same here testing in an Android 11 physical device. Samsung SM-A305G
