### ISSUE TITLE
[Question]: when I ask permission.camera.request(), it pop up photos permission ask

### ISSUE THREAD

**Issue by estherzhangyue** [Baseflow/flutter-permission-handler#1258]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-permission-handler/blob/main/permission_handler/README.md).

### Please select for which platform(s) you need help

- [ ] Android
- [X] iOS
- [ ] Windows

### Your question

```
static Future<bool> checkCameraPermission() async {
    late PermissionStatus status;
    // show system permission dialog
      status = await Permission.camera.request();

    // if permission not granted before, show dialog
    if (status == PermissionStatus.denied ||
        status == PermissionStatus.permanentlyDenied) {
      DialogUtils.showCameraAllowDialog(Get.context!, () {
        UrlLauncher.openSettings();
      });
    } else {
      return true;
    }
    return false;
  }

```

my code is above, ‘#’ before`'PERMISSION_CAMERA=1'`,  in Podfile is already moved. when run in real phone it popup photo permission popup instead of camera permission popup, could anyone help me?

### Version

^11.0.1

**Comment by TimHoogstrate** [comment]
Dear @estherzhangyue,

In order to investigate this issue, could you please add the output of `flutter doctor -v` to this issue?

Kind regards,
