### ISSUE TITLE
[Bug]:  Can't launch app

### ISSUE THREAD

**Issue by Caviaros123** [Baseflow/flutter-permission-handler#1259]
### Please check the following before submitting a new issue.

- [ ] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [ ] Android
- [X] iOS
- [ ] Windows

### Steps to reproduce

On build ios

### Expected results

ARC Semantic Issue (Xcode): No visible @interface for 'EKEventStore' declares the selector 'requestFullAccessToEventsWithCompletion:'
/Users/prince/.pub-cache/hosted/pub.dev/permission_handler_apple-9.2.0/ios/Classes/strategies/EventPermissionStrategy.m:55:24

ARC Semantic Issue (Xcode): No visible @interface for 'EKEventStore' declares the selector 'requestWriteOnlyAccessToEventsWithCompletion:'
/Users/prince/.pub-cache/hosted/pub.dev/permission_handler_apple-9.2.0/ios/Classes/strategies/EventPermissionStrategy.m:63:24

ARC Semantic Issue (Xcode): No visible @interface for 'EKEventStore' declares the selector 'requestFullAccessToRemindersWithCompletion:'
/Users/prince/.pub-cache/hosted/pub.dev/permission_handler_apple-9.2.0/ios/Classes/strategies/EventPermissionStrategy.m:71:24

Semantic Issue (Xcode): Use of undeclared identifier 'EKAuthorizationStatusFullAccess'
/Users/prince/.pub-cache/hosted/pub.dev/permission_handler_apple-9.2.0/ios/Classes/strategies/EventPermissionStrategy.m:105:17

Semantic Issue (Xcode): Use of undeclared identifier 'EKAuthorizationStatusWriteOnly'; did you mean 'EKAuthorizationStatusDenied'?
/Users/prince/.pub-cache/hosted/pub.dev/permission_handler_apple-9.2.0/ios/Classes/strategies/EventPermissionStrategy.m:107:17

Semantic Issue (Xcode): Duplicate case value 'EKAuthorizationStatusDenied'
/Users/prince/.pub-cache/hosted/pub.dev/permission_handler_apple-9.2.0/ios/Classes/strategies/EventPermissionStrategy.m:107:17

Semantic Issue (Xcode): Use of undeclared identifier 'EKAuthorizationStatusWriteOnly'; did you mean 'EKAuthorizationStatusDenied'?
/Users/prince/.pub-cache/hosted/pub.dev/permission_handler_apple-9.2.0/ios/Classes/strategies/EventPermissionStrategy.m:123:17

Semantic Issue (Xcode): Duplicate case value 'EKAuthorizationStatusDenied'
/Users/prince/.pub-cache/hosted/pub.dev/permission_handler_apple-9.2.0/ios/Classes/strategies/EventPermissionStrategy.m:123:17

Could not build the application for the simulator.
Error launching application on iPhone 14 Pro Max.

### Actual results

ARC Semantic Issue (Xcode): No visible @interface for 'EKEventStore' declares the selector 'requestFullAccessToEventsWithCompletion:'
/Users/prince/.pub-cache/hosted/pub.dev/permission_handler_apple-9.2.0/ios/Classes/strategies/EventPermissionStrategy.m:55:24

ARC Semantic Issue (Xcode): No visible @interface for 'EKEventStore' declares the selector 'requestWriteOnlyAccessToEventsWithCompletion:'
/Users/prince/.pub-cache/hosted/pub.dev/permission_handler_apple-9.2.0/ios/Classes/strategies/EventPermissionStrategy.m:63:24

ARC Semantic Issue (Xcode): No visible @interface for 'EKEventStore' declares the selector 'requestFullAccessToRemindersWithCompletion:'
/Users/prince/.pub-cache/hosted/pub.dev/permission_handler_apple-9.2.0/ios/Classes/strategies/EventPermissionStrategy.m:71:24

Semantic Issue (Xcode): Use of undeclared identifier 'EKAuthorizationStatusFullAccess'
/Users/prince/.pub-cache/hosted/pub.dev/permission_handler_apple-9.2.0/ios/Classes/strategies/EventPermissionStrategy.m:105:17

Semantic Issue (Xcode): Use of undeclared identifier 'EKAuthorizationStatusWriteOnly'; did you mean 'EKAuthorizationStatusDenied'?
/Users/prince/.pub-cache/hosted/pub.dev/permission_handler_apple-9.2.0/ios/Classes/strategies/EventPermissionStrategy.m:107:17

Semantic Issue (Xcode): Duplicate case value 'EKAuthorizationStatusDenied'
/Users/prince/.pub-cache/hosted/pub.dev/permission_handler_apple-9.2.0/ios/Classes/strategies/EventPermissionStrategy.m:107:17

Semantic Issue (Xcode): Use of undeclared identifier 'EKAuthorizationStatusWriteOnly'; did you mean 'EKAuthorizationStatusDenied'?
/Users/prince/.pub-cache/hosted/pub.dev/permission_handler_apple-9.2.0/ios/Classes/strategies/EventPermissionStrategy.m:123:17

Semantic Issue (Xcode): Duplicate case value 'EKAuthorizationStatusDenied'
/Users/prince/.pub-cache/hosted/pub.dev/permission_handler_apple-9.2.0/ios/Classes/strategies/EventPermissionStrategy.m:123:17

Could not build the application for the simulator.
Error launching application on iPhone 14 Pro Max.

### Code sample

<details><summary>Code sample</summary>

```dart
Flutter latest version
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

9.2.0

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Launching lib/main.dart on iPhone 14 Pro Max in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                           72,3s
Failed to build iOS app
ARC Semantic Issue (Xcode): No visible @interface for 'EKEventStore' declares the selector 'requestFullAccessToEventsWithCompletion:'
/Users/prince/.pub-cache/hosted/pub.dev/permission_handler_apple-9.2.0/ios/Classes/strategies/EventPermissionStrategy.m:55:24

ARC Semantic Issue (Xcode): No visible @interface for 'EKEventStore' declares the selector 'requestWriteOnlyAccessToEventsWithCompletion:'
/Users/prince/.pub-cache/hosted/pub.dev/permission_handler_apple-9.2.0/ios/Classes/strategies/EventPermissionStrategy.m:63:24

ARC Semantic Issue (Xcode): No visible @interface for 'EKEventStore' declares the selector 'requestFullAccessToRemindersWithCompletion:'
/Users/prince/.pub-cache/hosted/pub.dev/permission_handler_apple-9.2.0/ios/Classes/strategies/EventPermissionStrategy.m:71:24

Semantic Issue (Xcode): Use of undeclared identifier 'EKAuthorizationStatusFullAccess'
/Users/prince/.pub-cache/hosted/pub.dev/permission_handler_apple-9.2.0/ios/Classes/strategies/EventPermissionStrategy.m:105:17

Semantic Issue (Xcode): Use of undeclared identifier 'EKAuthorizationStatusWriteOnly'; did you mean 'EKAuthorizationStatusDenied'?
/Users/prince/.pub-cache/hosted/pub.dev/permission_handler_apple-9.2.0/ios/Classes/strategies/EventPermissionStrategy.m:107:17

Semantic Issue (Xcode): Duplicate case value 'EKAuthorizationStatusDenied'
/Users/prince/.pub-cache/hosted/pub.dev/permission_handler_apple-9.2.0/ios/Classes/strategies/EventPermissionStrategy.m:107:17

Semantic Issue (Xcode): Use of undeclared identifier 'EKAuthorizationStatusWriteOnly'; did you mean 'EKAuthorizationStatusDenied'?
/Users/prince/.pub-cache/hosted/pub.dev/permission_handler_apple-9.2.0/ios/Classes/strategies/EventPermissionStrategy.m:123:17

Semantic Issue (Xcode): Duplicate case value 'EKAuthorizationStatusDenied'
/Users/prince/.pub-cache/hosted/pub.dev/permission_handler_apple-9.2.0/ios/Classes/strategies/EventPermissionStrategy.m:123:17

Could not build the application for the simulator.
Error launching application on iPhone 14 Pro Max.

```

</details>

**Comment by mvanbeusekom** [comment]
Hi @Caviaros123, 

This is not a bug but a result of outdated version of Xcode.

Please make sure you update Xcode to the latest version en have the latest iOS SDK installed. 

The latest version of the permission_handler supports the latest changes in iOS 16 and require symbols only available with the latest SDKs and Xcode versions.
