### ISSUE TITLE
[Bug]: AppState looping in Android14 Pixel 7

### ISSUE THREAD

**Issue by CloudIQTechnologies** [Baseflow/flutter-permission-handler#1270]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Windows

### Steps to reproduce

After getting permission grant status the Application state streams between resume state and inactive. then the application goes to a hidden state.

D/SessionLifecycleClient(12654): Sending lifecycle 1 to service
D/SessionLifecycleService(12654): Activity foregrounding at 284172967.
D/SessionLifecycleClient(12654): Sending lifecycle 2 to service
D/SessionLifecycleService(12654): Activity backgrounding at 284172969
D/SessionLifecycleClient(12654): Sending lifecycle 1 to service
D/SessionLifecycleService(12654): Activity foregrounding at 284173009.
D/SessionLifecycleClient(12654): Sending lifecycle 2 to service
D/SessionLifecycleService(12654): Activity backgrounding at 284173011
D/SessionLifecycleClient(12654): Sending lifecycle 1 to service
D/SessionLifecycleService(12654): Activity foregrounding at 284173070.
D/SessionLifecycleClient(12654): Sending lifecycle 2 to service
D/SessionLifecycleService(12654): Activity backgrounding at 284173071
D/SessionLifecycleClient(12654): Sending lifecycle 1 to service
D/SessionLifecycleService(12654): Activity foregrounding at 284173132.

**Custom logs** 
[log] Application state changes to AppLifecycleState.resumed
[log] Application state changes to AppLifecycleState.inactive
[log] Application state changes to AppLifecycleState.resumed
[log] Application state changes to AppLifecycleState.inactive
[log] Application state changes to AppLifecycleState.resumed
[log] Application state changes to AppLifecycleState.inactive
[log] Application state changes to AppLifecycleState.resumed
[log] Application state changes to AppLifecycleState.inactive
[log] Application state changes to AppLifecycleState.resumed
[log] Application state changes to AppLifecycleState.inactive
[log] Application state changes to AppLifecycleState.resumed
[log] Application state changes to AppLifecycleState.inactive
[log] Application state changes to AppLifecycleState.resumed

### Expected results

The app should not go to a hidden state

### Actual results

The application goes to a hidden state.

### Code sample

<details><summary>Code sample</summary>

```dart
void _updateStatus(PermissionStatus status) {
    if (status != _status) {
      // check status has changed
      setState(() {
        _status = status; // update
      });
    } else {
      if (status != PermissionStatus.granted) {
        Permission.microphone.request().then(_onStatusRequested);
      }
    }
  }

  void _askMicrophonePermission() async {
    await Permission.microphone.request();
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }
  
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.resumed) {
      Permission.microphone.status.then(_updateStatus);
    }
    super.didChangeAppLifecycleState(state);
  }

  void _onStatusRequested(PermissionStatus status) {
    if (status != PermissionStatus.granted) {
      // On iOS if "deny" is pressed, open App Settings
      // Permission.openAppSettings();
    } else {
      _updateStatus(status);
    }
  }
```
</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

11.2.0

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by GuyMangkorn** [comment]
+1 face the same issue when upgrade project Flutter from 3.13.6 to 3.16.9

**Comment by mvanbeusekom** [comment]
Hi @CloudIQTechnologies, @GuyMangkorn,

This is expected behaviour, because when requesting permissions on Android the requesting application is send to the background (becomes inactive) and Android takes over control and displays the permission dialog. When a response is provided by the user, Android gives back control to the application by moving it back into the foreground (resuming the application).

So the danger of requesting permissions in the `didChangeAppLifecycleState` is to get into a infinite loop. If you really need to check (and request) permission in the `didChangeAppLifecycleState` callback it is best practise to keep track of a boolean indicating the permissions have already been checked and requested and break out of the loop. A similar solution can be found here: https://github.com/Baseflow/flutter-geolocator/issues/1056#issuecomment-1122167349

I hope this helps.
