### ISSUE TITLE
Support HarmonyOS

### ISSUE THREAD

**Issue by zmtzawqlp** [Baseflow/flutter-permission-handler#1271]
### Is there already an issue requesting this feature?

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).

### Please select affected platform(s)

- [ ] Android
- [ ] iOS
- [ ] Windows

### Use case

OpenHarmony will support flutter base on Flutter 3.7.12. it comes from https://gitee.com/openharmony-sig/flutter_flutter.

### Proposal

I am working on this, but Permission has no public ctor, Permissions on HarmonyOS have much different from other platforms. I need a class OhosPermission which extends Permission to make them look different.

**Comment by zmtzawqlp** [comment]
for example：

The Permission for calendar on HarmonyOS， has four types。 It's hard to use the existing Permission type。

**Comment by TimHoogstrate** [comment]
Dear @zmtzawqlp,

Thank you for bringing up your feature request. Our current support aligns with Flutter's designated platforms, and unfortunately, HarmonyOS is not currently supported. We currently lack the necessary knowledge and resources to maintain and test compatibility with this platform. As a result, we are unable to provide the required assistance at this time. Nevertheless, until Flutter supports HarmonyOS we encourage you to explore and support your own fork on this matter.

Kind regards,
