### ISSUE TITLE
[Bug]: Permission.scheduleExactAlarm.isGranted returns false for devices with android SDK 29

### ISSUE THREAD

**Issue by tomas-dorda** [Baseflow/flutter-permission-handler#1274]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Windows

### Steps to reproduce

Ask for `Permission.scheduleExactAlarm.isGranted`  on device with SDK 29. 

### Expected results

It should return `true`

### Actual results

It returns `false`

### Code sample

<details><summary>Code sample</summary>

```dart
      final isExactAlarmAllowed = await Permission.scheduleExactAlarm.isGranted;
      print('ScheduleExactAlarm notifications are allowed: $isExactAlarmAllowed');
```

</details>

### Version

11.1.0

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.2, on Microsoft Windows [Version 10.0.19045.3930], locale cs-CZ)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.1)
[√] Android Studio (version 2023.1)
[√] VS Code (version 1.86.0)
[√] Connected device (4 available)
[√] Network resources

• No issues found!
```

</details>

**Comment by TimHoogstrate** [comment]
Dear @tomas-dorda,

This permission is introduced in SDK 31. From 34 it is [denied by default] (https://developer.android.com/about/versions/14/changes/schedule-exact-alarms). On devices lower than SDK 31 you don't have to request the permission, you can just schedule the exact alarm. 

I can reproduce this and therefore, I agree that the isGranted should probably return "True". I'll label this as a bug. 

Kind regards,

**Comment by TimHoogstrate** [comment]
Fixed by (https://github.com/Baseflow/flutter-permission-handler/pull/1277)
