### ISSUE TITLE
shouldShowRequestPermissionRationale always false on Android

### ISSUE THREAD

**Issue by altherat** [Baseflow/flutter-permission-handler#128]
## 🐛 Bug Report

`shouldShowRequestPermissionRationale` is always returning `false` on Android. I am trying to check for storage permissions and I've put READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE permissions in my AndroidManifest. Nothing is logged in the debug console and it happens on both debug and release versions.

### Expected behavior

`shouldShowRequestPermissionRationale` to return `true` if permissions have not been accepted on Android. Or am I misunderstanding something?

### Reproduction steps

Sample app:
```
import 'package:flutter/material.dart';
import 'package:permission_handler/permission_handler.dart';

void main() => runApp(App());

class App extends StatelessWidget {
  
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        floatingActionButton: FloatingActionButton(
          onPressed: () async {
            final PermissionHandler permissionHandler = PermissionHandler();
            final bool show = await permissionHandler.shouldShowRequestPermissionRationale(PermissionGroup.storage);
            print(show);
            final PermissionStatus permissionStatus = await permissionHandler.checkPermissionStatus(PermissionGroup.storage);
            print(permissionStatus);
          }
        ),
      )
    );
  }

}
```
output:
```
false
PermissionStatus.denied
```

### Configuration

**Version:** 3.1.0
**Flutter:** 1.5.4-hotfix.2
**Dart:** 2.3.0
**Device:** OnePlus 6t, Android Pie

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Edit:** It appears to return `true` after I've used `requestPermissions` and pressed the deny button on the dialog. But it returns `false` again after I clear the app's storage. For now I can workaround by just using `checkPermissionStatus` to see if it is `PermissionStatus.denied`, but I'm not sure how it's handled on iOS.

**Comment by mvanbeusekom** [comment]
In the next version (4.2.0) we will introduce a fix for this. When using `checkPermissionStatus` or `requestPermissions` you will (only on Android) receive an extra result item "neverAskAgain" in those cases were the user denied permissions and checked the "Don't ask again" checkbox.
