### ISSUE TITLE
[Feature request]: Impl WRITE_SETTINGS

### ISSUE THREAD

**Issue by demid** [Baseflow/flutter-permission-handler#1288]
### Is there already an issue requesting this feature?

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Windows

### Use case

Impl WRITE_SETTINGS permission

### Proposal

android:name="android.permission.WRITE_SETTINGS"

**Comment by TimHoogstrate** [comment]
Dear @demid, 

We are currently working on a refactor that would implement such a feature. I'll label this as an enhancement to keep track of it.

kind regards,

**Comment by TimHoogstrate** [comment]
Dear @demid,

It looks like WRITE_SETTINGS is a manifest permission. You can add it to your manifest. It should work. (https://developer.android.com/reference/android/Manifest.permission#WRITE_SETTINGS). I'll close this issue for now. Feel free to reopen or open a new issue with new information.

Kind regards,

**Comment by demid** [comment]
Read bellow

Note: If the app targets API level 23 or higher, the app user must explicitly grant this permission to the app through a permission management screen. The app requests the user's approval by sending an intent with action [Settings.ACTION_MANAGE_WRITE_SETTINGS](https://developer.android.com/reference/android/provider/Settings#ACTION_MANAGE_WRITE_SETTINGS). The app can check whether it has this authorization by calling [Settings.System.canWrite()](https://developer.android.com/reference/android/provider/Settings.System#canWrite(android.content.Context)).
