### ISSUE TITLE
[Bug]: Critical. Always use Location in Windows

### ISSUE THREAD

**Issue by hiddify-com** [Baseflow/flutter-permission-handler#1289]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [ ] Android
- [ ] iOS
- [X] Windows

### Steps to reproduce

Just Add permission handler into pubspec.yaml and run the program. You can see that it shows the program is using your location permanently.

### Expected results

It should not use permission for location

### Actual results

![image](https://github.com/Baseflow/flutter-permission-handler/assets/114227601/09ff0a85-8d5f-463f-9649-52f18425c6ab)

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

11.3.0

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by flutter-painter** [comment]
Why is this closed?
Not planned is legit but please keep it open
