### ISSUE TITLE
[Bug]: `permission_handler_apple` has an incorrect privacy manifest

### ISSUE THREAD

**Issue by stuartmorgan** [Baseflow/flutter-permission-handler#1292]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [ ] Android
- [X] iOS
- [ ] Windows

### Steps to reproduce

1. Look at https://github.com/Baseflow/flutter-permission-handler/blob/3be556e67d52f73b1c072ad2334cd9b64196737f/permission_handler_apple/ios/Classes/strategies/LocationPermissionStrategy.m#L45 and see the use of `NSUserDefaults`
2. Look at https://github.com/Baseflow/flutter-permission-handler/blob/3be556e67d52f73b1c072ad2334cd9b64196737f/permission_handler_apple/ios/Resources/PrivacyInfo.xcprivacy and see the lack of corresponding [required reason entry](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api).

Any plugin that uses a required reason API needs to declare it.

(I have not done a comprehensive audit; there may be other missing required reason API declarations as well. I'm filing this as I find it.)

### Expected results

Privacy manifest that includes explanations of all Required Reason APIs

### Actual results

Missing declaration

### Code sample

N/A

### Version

current master

### Flutter Doctor output

N/A

**Comment by jmagman** [comment]
cc @mvanbeusekom

**Comment by mvanbeusekom** [comment]
Hi @stuartmorgan,

Thanks for pointing this out, I missed the use of NSUserDefaults completely. We have just released an update containing the required privacy declaration.
