### ISSUE TITLE
[Question]: AppStore refuses app submission.

### ISSUE THREAD

**Issue by MichalPalko2** [Baseflow/flutter-permission-handler#1296]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-permission-handler/blob/main/permission_handler/README.md).

### Please select for which platform(s) you need help

- [ ] Android
- [X] iOS
- [ ] Windows

### Your question

Hello we are trying to submit the application to app store. It was rejected due to this statement 

Issue Description
One or more purpose strings in the app do not sufficiently explain the use of protected resources. Purpose strings must clearly and completely describe the app's use of data and, in most cases, provide an example of how the data will be used.
Examples of unclear purpose strings:
- "App would like to access your Contacts"
- "App needs microphone access"

We use application for storage permissions. 
There was opened opened issues already. So I'd like to ask if this is still the thing in plugin version 11.1.0. We don't use neither Contacts access nor microphone access in our application. Could you please have a look ? 

### Version

11.1.0

**Comment by mvanbeusekom** [comment]
Hi @MichalPalko2,

Have you enabled/ disabled the permissions that the application doesn't require in the `ios/Podfile` configuration? Detailed explanation can be found in "iOS" section (expand the section by clicking the rectangle) of the [README.md](https://pub.dev/packages/permission_handler) file.

Also if the app does require Contacts and Microphone permissions, they need to be declared in the `ios/Runner/Info.plist` file. This is also described in the "iOS" section of the [README.md](https://pub.dev/packages/permission_handler) file. 

Let me know if this helps, if the issue remains please provide a copy of your `ios/Podfile` and list the permissions that the application requires.

**Comment by MichalPalko2** [comment]
Hello,

Yes I didn't notice that those sections are expandable. We tried to disable those we don't need. So let's see what reviewers tell us. Thank you. I'll get back here with the response.

**Comment by mvanbeusekom** [comment]
Hi @MichalPalko2,

Considering you haven't come back with additional problems I will go ahead and consider this issue resolved. I will close the issue, if you have any other questions feel free to submit a new issue.
