### ISSUE TITLE
[Question]: Add iOS privacy manifests

### ISSUE THREAD

**Issue by a-yarimizu-dc** [Baseflow/flutter-permission-handler#1300]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-permission-handler/blob/main/permission_handler/README.md).

### Please select for which platform(s) you need help

- [ ] Android
- [X] iOS
- [ ] Windows

### Your question

Hello,

In my project, we are working on supporting PrivacyManifest to meet the latest privacy requirements on iOS. Could you please confirm if there are plans to implement this support in the project?

I would appreciate any details regarding the plans and progress for implementing PrivacyManifest. 

Thank you for your consideration.

### Version

11.3.1

**Comment by MewanWA** [comment]
https://github.com/Baseflow/flutter-permission-handler/pull/1293

Its already added.

https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler_apple/CHANGELOG.md#942

**Comment by a-yarimizu-dc** [comment]
I apologize for not confirming earlier.
Thank you very much for responding.

**Comment by jsch-adt** [comment]
@a-yarimizu-dc did upgrading work for you? For some reason we still get the issue even with permission_handler_apple 9.4.4. If we fully remove permission handler, we don't get the email from apple.

**Comment by a-yarimizu-dc** [comment]
@jsch-adt 
We recently had a project reviewed by Apple that included permission_handler_apple 9.4.4, and there were no issues mentioned in the email from Apple. The review process went smoothly.
