### ISSUE TITLE
[Question]: Why AppLifeCycleListener method called repeatedly 

### ISSUE THREAD

**Issue by nadas00** [Baseflow/flutter-permission-handler#1301]
- [x] Android
- [ ] iOS
- [ ] Windows

My code:

```dart
  AppLifecycleListener? listener;

  @override
  void initState() {
    super.initState();
    context.ref = ref;
    listener = AppLifecycleListener(
      onStateChange: _onStateChange,
    );
  }
  
    void _onStateChange(AppLifecycleState value) {
    log("AppLifecycleState: $value");
  }
```
  
then

```dart
 await Permission.notification.request();
```
it prints :

[log] AppLifecycleState: AppLifecycleState.resumed
[log] AppLifecycleState: AppLifecycleState.inactive
[log] AppLifecycleState: AppLifecycleState.resumed
[log] AppLifecycleState: AppLifecycleState.inactive

.... 

and never stops.

### Version

permission_handler: ^11.3.1

**Comment by mvanbeusekom** [comment]
That is how the Android operating system works. When permissions are requested, Android moves the application into the background and instead shows the permission dialog. When the user provides an answer, Android moves the requesting application back to the foreground and informs the application with the response of the user.

This means that when you request permissions inside the callback of the `AppLifecycleListener` or the `didChangeAppLifecycleState` method (see [documentation](https://api.flutter.dev/flutter/widgets/WidgetsBindingObserver/didChangeAppLifecycleState.html)) you'll need to implement some logic to prevent an endless loop.

See also these issues:
- #1270 
- baseflow/flutter-geolocator#1056
