### ISSUE TITLE
[Enhancement proposal]: Add wasm support

### ISSUE THREAD

**Issue by MominRaza** [Baseflow/flutter-permission-handler#1302]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [ ] Android
- [ ] iOS
- [ ] Windows
- [x] Web

### Proposal

web plugin is using `dart:html` which is not compatible with WASM, migrate to [package:web](https://pub.dev/packages/web).

Context: The unavailable library 'dart:html' is imported through these packages:
    web_plugin_registrant.dart => package:permission_handler_html => dart:html

### Pitch

Flutter doc: https://docs.flutter.dev/platform-integration/web/wasm

**Comment by rokk4** [comment]
Would be great! Also since wasm compilation as now landed in stable.

```
Target dart2wasm failed: ProcessException: Process exited abnormally with exit code 64:
Context: The unavailable library 'dart:html' is imported through these packages:

    web_plugin_registrant.dart => package:permission_handler_html => dart:html
```

**Comment by MominRaza** [comment]
@mvanbeusekom What's the status, there is also a PR linked please review it.
