### ISSUE TITLE
[Bug]: Gets Permission Granted Status for Limited Permission

### ISSUE THREAD

**Issue by Mozammal-hossain** [Baseflow/flutter-permission-handler#1309]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Windows

### Steps to reproduce

- Use PhotoManager package
- Call PhotoManger.requestPermissionExtend()
- At android 14 (API 34) select _limited photos and videos_ 
- Permission.image.status , Permission.videos.status, Permission, Permission.accessMediaLocation.status, Permission.mediaLibrary.status ----- shows granted 

### Expected results

- Permission.status.isLimited == true

### Actual results

- Permission.status.isLimited == false

### Code sample

<details><summary>Code sample</summary>

```dart
 Future<void> _requestAssets() async {
    // Request permissions.
    final PermissionState ps = Platform.isAndroid
        ? await PhotoManager.requestPermissionExtend(
            requestOption: const PermissionRequestOption(
              androidPermission: AndroidPermission(
                type: RequestType.common,
                mediaLocation: true,
              ),
            ),
          )
        : await PhotoManager.requestPermissionExtend();
testing()
}

Future<void> testing() async {
    final _testing1 = await Permission.mediaLibrary.status;
    Log.debug("$_testing1");

    final _testing2 = await Permission.accessMediaLocation.status;

    Log.debug("$_testing2");

    final _testing3 = await Permission.photos.status;

    Log.debug("$_testing3");

    final _testing4 = await Permission.manageExternalStorage.status;

    Log.debug("$_testing4");

    final _testing5 = await Permission.storage.status;

    Log.debug("$_testing5");

    final _testing6 = await Permission.videos.status;

    Log.debug("$_testing6");
  }
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

11.0.0

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[!] Flutter (Channel stable, 3.16.9, on macOS 14.4.1 23E224 darwin-arm64, locale en-BD)
    • Flutter version 3.16.9 on channel stable at /Users/bs1101/Downloads/flutter
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.2.6/libexec/bin/dart, which is not inside your current Flutter SDK checkout
      at /Users/bs1101/Downloads/flutter. Consider adding /Users/bs1101/Downloads/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (3 months ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and
      upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/bs1101/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.87.2)
    • VS Code at /Users/bs1101/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (5 available)            
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 13 (API 33) (emulator)
    • sdk gphone64 arm64 (mobile) • emulator-5556                        • android-arm64  • Android 14 (API 34) (emulator)
    • iPhone 15 Pro Max (mobile)  • CFDF7B3C-C24C-4A3B-A810-2E9C916C063B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-4 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 123.0.6312.124

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

**Comment by mvanbeusekom** [comment]
Hi @Mozammal-hossain,

Unfortunately Android only returns a "granted" or "denied" status when requesting permissions (see [Android documentation](https://developer.android.com/training/permissions/requesting#already-granted) for requesting runtime permissions). 

This even goes for permissions (like `READ_MEDIA_AUDIO`, `READ_MEDIA_IMAGES` or `READ_MEDIA_VIDEO`) which show a permission dialog with a "Limited" option.

The `PermissionStatus.limited` status defined by the permission_handler plugin is only used on iOS 14 and higher as mentioned in the API documentation: https://pub.dev/documentation/permission_handler/latest/permission_handler/PermissionStatus.html#limited

**Comment by zhenhao-ola** [comment]
`PhotoManager` is entirely different package right? How is it related to `flutter-permission-handler`?

**Comment by mvanbeusekom** [comment]
@zhenhao-ola `PhotoManager` is a different package and has no relationship with the permission_handler nor with Baseflow (the company maintaining the permission_handler).

**Comment by zhenhao-ola** [comment]
@mvanbeusekom Can I ask if `permission_handler` has plans to support ` android.permission.READ_MEDIA_VISUAL_USER_SELECTED` ? It's one of the required migrations for Android 14 (targetSdk = 34) 

https://developer.android.com/reference/android/Manifest.permission#READ_MEDIA_VISUAL_USER_SELECTED

https://developer.android.com/about/versions/14/behavior-changes-14#partial-photo-library-access
