### ISSUE TITLE
[Bug]: Permission.camera.request() throwing permission denied even if I have granted.

### ISSUE THREAD

**Issue by EliseiNicolae** [Baseflow/flutter-permission-handler#1311]
### Please check the following before submitting a new issue.

- [ ] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [ ] Android
- [X] iOS
- [ ] Windows

### Steps to reproduce

1. Install permission_handler: ^11.3.1 lib.
2. Install   image_picker: ^1.0.7
3. Call the following function when clicking to a button:

``` dart
  Future<void> _goToCamera(ImageSource source) async {
    await Permission.camera.onDeniedCallback(() {
      print('Camera permission denied');
    }).onGrantedCallback(() {
      print('Camera permission granted');
    }).onPermanentlyDeniedCallback(() {
      print('Camera permission permanently denied');
    }).onRestrictedCallback(() {
      print('Camera permission restricted');
    }).onLimitedCallback(() {
      print('Camera permission limited');
    }).onProvisionalCallback(() {
      print('Camera permission provisional');
    }).request();

    final pickedFile = await ImagePicker().pickImage(source: source);

    Navigator.push(
      context,
      MaterialPageRoute(
          builder: (context) => NextView(pickedFile: pickedFile)),
    );
  }
```

### Expected results

If the permission has granted, it should go in the following callback.
```dart
.onGrantedCallback(() {
  print('Camera permission granted');
})
```

### Actual results

Each time it goes just in 
```dart
.onDeniedCallback(() {
  print('Camera permission denied');
})
```

even if I granted.

### Code sample

<details><summary>Code sample</summary>

```dart
  Future<void> _goToCamera(ImageSource source) async {
    await Permission.camera.onDeniedCallback(() {
      print('Camera permission denied');
    }).onGrantedCallback(() {
      print('Camera permission granted');
    }).onPermanentlyDeniedCallback(() {
      print('Camera permission permanently denied');
    }).onRestrictedCallback(() {
      print('Camera permission restricted');
    }).onLimitedCallback(() {
      print('Camera permission limited');
    }).onProvisionalCallback(() {
      print('Camera permission provisional');
    }).request();

    final pickedFile = await ImagePicker().pickImage(source: source);

    Navigator.push(
      context,
      MaterialPageRoute(
          builder: (context) => NextView(pickedFile: pickedFile)),
    );
  }
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

https://github.com/Baseflow/flutter-permission-handler/assets/43387542/0dff53af-de30-4565-9b97-37e66a73fda1

</details>

### Version

^11.3.1

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
eliseinicolae@Eliseis-MacBook-Pro verifica_alimente_flutter % flutter doctor -v 

[✓] Flutter (Channel stable, 3.19.5, on macOS 14.4.1 23E224 darwin-arm64, locale en-RO)
    • Flutter version 3.19.5 on channel stable at /opt/homebrew/Caskroom/flutter/3.13.1/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (3 weeks ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/eliseinicolae/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Users/eliseinicolae/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/222.4459.24.2221.9971841/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/eliseinicolae/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/223.8836.35.2231.10811636/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.84.2)
    • VS Code at /Users/eliseinicolae/Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)            
    • Elisei’s iPhone (mobile) • 00008110-000E244C3601401E • ios            • iOS 17.4.1 21E236
    • macOS (desktop)          • macos                     • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)             • chrome                    • web-javascript • Google Chrome 123.0.6312.124

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

```

</details>

**Comment by mvanbeusekom** [comment]
Hi @EliseiNicolae,

Did you enable the `camera` permissions in the `ios/Podfile` as mentioned in the "iOS" section in the [README.md](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) file?

If so, could you provide the contents of the `ios/Podfile` and `ios/Runner/Info.plist` files?

**Comment by EliseiNicolae** [comment]
Hi @mvanbeusekom , yes I've added in ios/Podfile & ios/Runner/Info.plist, but still getting denied...

Here's the files:
Podfile:
```
# Uncomment this line to define a global platform for your project
# platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      xcconfig_path = config.base_configuration_reference.real_path
      xcconfig = File.read(xcconfig_path)
      xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
      File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }

      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
          '$(inherited)',
          ## dart: PermissionGroup.camera
          'PERMISSION_CAMERA=1',
        ]
    end
  end
end
```

In Info.plist:
```
...
	<key>NSCameraUsageDescription</key>
	<string>We use the camera to scan the product details.</string>
...
```

**Comment by mvanbeusekom** [comment]
Hi @EliseiNicolae,

Thank you for getting back with the additional information. I've created a simple test application to try reproduce the problem using the following steps:

1. Create a new flutter application: `flutter create --platforms=ios geo_issue_1311`
2. Change into the new application directory: `cd geo_issue_1311`
3. Add dependency to the `permission_handler` plugin: `flutter pub add permission_handler`
4. Enable Camera permission in the `ios/Podfile` (see contents below, I copied the settings you mentioned in previous comment)
5. Add permission to the `ios/Runner/Info.plist` file (see contents below)
6. Replace implementation of `lib/main.dart` with implementation below.

When running this test application on my iPhone 12 mini (iOS 17.4.1) permissions are updated as expected. In other words, it fails to reproduce the behavior you are experiencing. Can you confirm the reproduction example works for you as well?

<details>
<summary>ios/Podfile</summary>

```ruby

```

</details>

**Comment by EliseiNicolae** [comment]
@mvanbeusekom, is this the same output as yours?

https://github.com/Baseflow/flutter-permission-handler/assets/43387542/1fa73984-c702-4822-ab98-1b88f3ef40ce

**Comment by EliseiNicolae** [comment]
Not sure why, but now it's working fine 😆 .

**Comment by mvanbeusekom** [comment]
Strange, but happy to hear. I was just about to record a video on how the app behaves on my side.

Thanks for letting us know.

**Comment by Ngochiendev** [comment]
same issue

**Comment by Ngochiendev** [comment]
> Not sure why, but now it's working fine 😆 .
how to fix issue ?

**Comment by EliseiNicolae** [comment]
Hi @Ngochiendev, what I did was to create a fresh project as mvanbeusekom said and run it.

<img width="957" alt="image" src="https://github.com/Baseflow/flutter-permission-handler/assets/43387542/fe70e44b-3095-42ff-92be-fe527f9ed5d6">


After running it, I've run also my project, and it worked well.

**Comment by Ngochiendev** [comment]
> Hi @Ngochiendev, what I did was to create a fresh project as mvanbeusekom said, add the configurations and run it. P.S: Before running the project, remove the build of your app from your device.
> 
> <img alt="image" width="957" src="https://private-user-images.githubusercontent.com/43387542/326160970-fe70e44b-3095-42ff-92be-fe527f9ed5d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMDM0NzUsIm5iZiI6MTcxNDIwMzE3NSwicGF0aCI6Ii80MzM4NzU0Mi8zMjYxNjA5NzAtZmU3MGU0NGItMzA5NS00MmZmLTkyYmUtZmU1MjdmOWVkNWQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDA3MzI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzZTA5MmRmNjVlZjQ2MTAzNGZjZDJhZGZlMjVhNjBmOWEyYzdiZTU1ZWYwOTRiMzU5NzI3NDhhY2RiNTQyYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zwFh4f0iKBu0tjvLttzwuhS5gTIqg6YlCL4QngOaoys">
> After running it, I've run also my project, and it worked well.

I will try again and post the results
