### ISSUE TITLE
[Question]: ITMS-91053: Missing API declaration

### ISSUE THREAD

**Issue by YouLiLiao** [Baseflow/flutter-permission-handler#1313]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-permission-handler/blob/main/permission_handler/README.md).

### Please select for which platform(s) you need help

- [ ] Android
- [X] iOS
- [ ] Windows

### Your question

When I submit an iOS application, it prompts "ITMS-91053: Missing API Declaration". Could you please update the privacy policy of the iOS `NSPrivacyAccessiedAPICategoryUserDefault API`

### Version

11.3.1

**Comment by mvanbeusekom** [comment]
Hi @YouLiLiao,

Which version of the permission_handler_apple package are you using (you can find this in the pubspec.lock file)?

Version 9.4.4 of the permission_handler_apple package contains the required [Privacy manifest file](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler_apple/ios/Resources/PrivacyInfo.xcprivacy), if this is not the version used in your application make sure to run `flutter pub upgrade` to update transient dependencies.
