### ISSUE TITLE
[Bug]: Camera status is always denied in iOS 17

### ISSUE THREAD

**Issue by Ngochiendev** [Baseflow/flutter-permission-handler#1314]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [ ] Android
- [X] iOS
- [ ] Windows

### Steps to reproduce

1. Use await Permission.camera.request(); to get camera permission
2. Check await Permission.camera.status;

### Expected results

await Permission.camera.status; should return granted when permission is granted by user.

### Actual results

I tested 2 cases: 
1. await Permission.camera.request(); return Permission is permanently denied

2. await Permission.camera.status; returned Permission is denied

### Code sample

<details><summary>Code sample</summary>

```dart

1. case 1: return Permission is permanently denied

  var status = await Permission.camera.request();

                      if (status.isGranted) {
                        print("Permission is granted");
                      } else if (status.isDenied) {
                        // await Permission.camera.request();
                        // Permission is denied
                        print("Permission is denied");
                        openAppSettings();
                      } else if (status.isPermanentlyDenied) {
                        // Permission is permanently denied
                        print("Permission is permanently denied");
                        openAppSettings();
                      }

2. case 2: returned Permission is denied

 var status = await Permission.camera.status;

                      if (status.isGranted) {
                        print("Permission is granted");
                      } else if (status.isDenied) {
                        // await Permission.camera.request();
                        // Permission is denied
                        print("Permission is denied");
                        openAppSettings();
                      } else if (status.isPermanentlyDenied) {
                        // Permission is permanently denied
                        print("Permission is permanently denied");
                        openAppSettings();
                      }

```

</details>

### Screenshots or video

<details>
<summary>Because the video file is larger than 10MB, I uploaded it to dropbox and shared the link so I can watch it</summary>

[https://www.dropbox.com/scl/fi/fe4skfa1ek0o6ltgptvwl/Ghi-M-n-h-nh-2024-04-25-l-c-14.22.10.mov?rlkey=0tigbxnxkzbosdozo6e13uh7r&st=cth7f3bx&dl=0]()
</details>

### Version

11.3.1

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[[✓] Flutter (Channel stable, 3.19.6, on macOS 14.2.1 23C71 darwin-arm64, locale vi-VN)
    • Flutter version 3.19.6 on channel stable at /Users/macos/fvm/versions/3.19.6
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (7 days ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/macos/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.88.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.86.0

[✓] Connected device (3 available)
    • iPhone (mobile) • 00008110-001218EC3A0B801E • ios            • iOS 17.3.1 21D61
    • macOS (desktop) • macos                     • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)    • chrome                    • web-javascript • Google Chrome 124.0.6367.78

[✓] Network resources
    • All expected network resources are available.

• No issues found!]
```

</details>

**Comment by Ngochiendev** [comment]
Here is the info.plist and Podfile I have configured

          
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
          '$(inherited)',
          ## dart: PermissionGroup.camera
          'PERMISSION_CAMERA=1',]
        end
    # End of the permission_handler configuration


#     
    <key>NSCameraUsageDescription</key>
	<string>Ứng dụng này yêu cầu quyền truy cập vào máy ảnh.</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>Ứng dụng này yêu cầu quyền truy cập vào thư viện ảnh.</string>#

**Comment by mvanbeusekom** [comment]
Hi @Ngochiendev, 

Have you tried reproducing the problem with the application I have provided in this [comment](https://github.com/Baseflow/flutter-permission-handler/issues/1311#issuecomment-2060736780)?

As mentioned there, using these steps I am unable to reproduce the issue which makes it really hard to help. Please have a really careful look at the settings in your `ios/Podfile` and compare it with the setup I have provided in the mentioned comment.

You can also try:
1. Run `flutter clean`
2. Delete the `ios/Pods` folder
3. Delete the `ios/Podfile.lock` file
4. In the `ios` folder run `pod install`.
5. In the root of your project run `flutter pub get`.

**Comment by Ngochiendev** [comment]
> Hi @Ngochiendev,
> 
> Have you tried reproducing the problem with the application I have provided in this [comment](https://github.com/Baseflow/flutter-permission-handler/issues/1311#issuecomment-2060736780)?
> 
> As mentioned there, using these steps I am unable to reproduce the issue which makes it really hard to help. Please have a really careful look at the settings in your `ios/Podfile` and compare it with the setup I have provided in the mentioned comment.
> 
> You can also try:
> 
> 1. Run `flutter clean`
> 2. Delete the `ios/Pods` folder
> 3. Delete the `ios/Podfile.lock` file
> 4. In the `ios` folder run `pod install`.
> 5. In the root of your project run `flutter pub get`.

I tried the same, but still got the same error

**Comment by luomo-pro** [comment]
I have the same problem, and in my case, besides camera, photos always return Denied

**Comment by mvanbeusekom** [comment]
@luomo-pro can you confirm you can reproduce the issue with the example application provided in this [comment](https://github.com/Baseflow/flutter-permission-handler/issues/1311#issuecomment-2060736780)?

**Comment by luomo-pro** [comment]
@mvanbeusekom
I followed your example and added it inside ios/Podfile:
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
          '$(inherited)',
          'PERMISSION_CAMERA=1',
        ]
The problem was successfully resolved and everything is now working fine.
Thank you!

**Comment by mvanbeusekom** [comment]
@Ngochiendev, 

Did you manage to resolve this issue? In this [comment](https://github.com/Baseflow/flutter-permission-handler/issues/1311#issuecomment-2080400782) you mentioned you would try again, I was curious if you managed to resolve the issue.

**Comment by Ngochiendev** [comment]
> @Ngochiendev,
> 
> Did you manage to resolve this issue? In this [comment](https://github.com/Baseflow/flutter-permission-handler/issues/1311#issuecomment-2080400782) you mentioned you would try again, I was curious if you managed to resolve the issue.

I tried this again today, but....it's still false

**Comment by Ngochiendev** [comment]
> @Ngochiendev,
> 
> Did you manage to resolve this issue? In this [comment](https://github.com/Baseflow/flutter-permission-handler/issues/1311#issuecomment-2080400782) you mentioned you would try again, I was curious if you managed to resolve the issue.
after I deleted and reinitialized the pod file, then added this code it worked

config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
'$(inherited)',
'PERMISSION_CAMERA=1',
]
The problem was successfully resolved and everything is now working fine.
Thank!

**Comment by abdulrahmank** [comment]
This just saved my day. In iOS 17, even after following so many bug fixes, camera permissions wasn't opening. With this code in podfile, I was able to solve it.

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
          xcconfig_path = config.base_configuration_reference.real_path
          xcconfig = File.read(xcconfig_path)
          xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
          File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }

          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
              '$(inherited)',
              ## dart: PermissionGroup.camera
              'PERMISSION_CAMERA=1',
            ]
      end
  end
end
```
