### ISSUE TITLE
 /usr/include/c++/11/cmath:45:15: fatal error: math.h: No such file or directory    ***      45 | #include_next <math.h>    ***         |               ^~~~~~~~    ***   compilation terminated.

### ISSUE THREAD

**Issue by Harshu2032000** [Baseflow/flutter-permission-handler#1317]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-permission-handler/blob/main/permission_handler/README.md).

### Please select for which platform(s) you need help

- [ ] Android
- [ ] iOS
- [X] Windows

### Your question

when trying to install dlib on my system I'm getting above error

![Screenshot from 2024-05-01 11-24-39](https://github.com/Baseflow/flutter-permission-handler/assets/71015350/fc091a05-a865-47d8-81d3-0c3054592384)

### Version

I have ubuntu version 22.04 cuda version 12.4 cudnn - 9 and was trying to install Dlib 19.24

**Comment by mvanbeusekom** [comment]
Hi @Harshu2032000,

How is this related to the Flutter `permission_handler` plugin? Could it be you created the issue in the wrong repository?

Also you have selected the "Windows" option in the issue, but are having an issue related to Linux.

**Comment by Harshu2032000** [comment]
it was created by mistake
