### ISSUE TITLE
[Bug]: Permission handler doesn't work on Android 14

### ISSUE THREAD

**Issue by KalaliEhsan** [Baseflow/flutter-permission-handler#1319]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Windows

### Steps to reproduce

I wanna save a file. For this use case I should get the store permission from the user like following code. But doesn't work on Android 14.

### Expected results

Storage permission granted!

### Actual results

```console
result ====== > PermissionStatus.denied
```

### Code sample

<details><summary>Code sample</summary>

```dart
  static Future<bool> _permissionRequest() async {
    PermissionStatus result;
    result = await Permission.storage.request();
    print("result ====== > $result");
    if (result.isGranted) {
      return true;
    } else {
      return false;
    }
  }
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

11.3.1

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.4, on macOS 14.2 23C64 darwin-arm64, locale en-IR)
    • Flutter version 3.19.4 on channel stable at /Users/frontdeveloper/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 68bfaea224 (8 weeks ago), 2024-03-20 15:36:31 -0700
    • Engine revision a5c24f538d
    • Dart version 3.3.2
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/frontdeveloper/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/frontdeveloper/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.85.1)
    • VS Code at /Users/frontdeveloper/development/apps/Visual Studio Code.app/Contents
    • Flutter extension version 3.88.0

[✓] Connected device (5 available)
    • SM A042F (mobile)                    • adb-R83WA0F1QCN-d5ytXS._adb-tls-connect._tcp. • android-arm64  • Android 14 (API 34)
    • Android SDK built for arm64 (mobile) • emulator-5554                                 • android-arm64  • Android 9 (API 28) (emulator)
    • sdk gphone64 arm64 (mobile)          • emulator-5556                                 • android-arm64  • Android 14 (API 34) (emulator)
    • macOS (desktop)                      • macos                                         • darwin-arm64   • macOS 14.2 23C64 darwin-arm64
    • Chrome (web)                         • chrome                                        • web-javascript • Google Chrome 124.0.6367.202
```

</details>

**Comment by mvanbeusekom** [comment]
Hi @KalaliEhsan,

Google has deprecated the `storage` permission since Android 13+. This is documented in our FAQ section of the README: https://pub.dev/packages/permission_handler#requesting-storage-permissions-always-returns-denied-on-android-13-what-can-i-do

So this is not a "permission_handler" issue, but an explicit decision from the Google Android team. You can save files as part of your application sandbox without the need for any specific permission. This means however that when the application is removed the files will also be removed. 

Alternatively if your application is meant to be used as a file manager you can request the `manage_external_storage` permission. This however requires filling in an additional consent form and approval from Google when publishing the application to the Google Play Store.
