### ISSUE TITLE
Provide a fucntion to open the location settings

### ISSUE THREAD

**Issue by pedromassango** [Baseflow/flutter-permission-handler#132]
## 🚀 Feature Requests

We need a function to open the location settings page, so that we can send the user there enable the permission.

### Contextualize the feature
The current function (**openAppSettings()**) just open the app settings and not the Location Settings activity (tested on **Android 21**). Maybe just check the OS version and act accordly.

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by gkrawiec** [comment]
I came here to write this same thing. Please add a function for "settings" in addition to "openAppSettings". As is, in Android the appsettings page opens and has no way to go back to the location service enable button.
Ideally there would be a function for opening settings at the Enable Location page and another page that opens it at the app settings page to give permissions to the app.

**Comment by ksankumar** [comment]
Any update on this?

**Comment by ekuleshov** [comment]
Current permission_handler 5.0.0 version on Android returns true for location permission for location, locationWhenInUse and locationAlways even when location services are disabled on device.

It should offer to open system UI to enable location services

**Comment by JDDV** [comment]
Thank you for the request, but this feature will not be implemented since this will make the API less clear/complicated if those function will be provided. There is a reliable package who can do such things, opening iOS and Android phone settings from your app which you can find [here](https://pub.dev/packages/app_settings).
