### ISSUE TITLE
[Bug]: iOS GCC_PREPROCESSOR_DEFINITIONS 设置问题

### ISSUE THREAD

**Issue by China-jxsg-YanYuanJie** [Baseflow/flutter-permission-handler#1321]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [ ] Android
- [X] iOS
- [ ] Windows

### Steps to reproduce

1. 创建一个现有的iOS工程.,
2. 通过打包xcframework方式导入flutter module
3. pod install  导入  flutter 模块

### Expected results

能够通过
target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
          '$(inherited)',
            'PERMISSION_MICROPHONE=1',
        ]
      end
      设置获取到麦克风权限

### Actual results

不行, 因为
![image](https://github.com/Baseflow/flutter-permission-handler/assets/112070751/f68dbc1c-99b0-4625-853c-89f7fd91252c)
只有这个,没有
![image](https://github.com/Baseflow/flutter-permission-handler/assets/112070751/74382044-79ef-4152-8f24-84f6499d2b1f)

### Code sample

![image](https://github.com/Baseflow/flutter-permission-handler/assets/112070751/7e62f076-ecfc-4999-8852-b582dd9a8924)

### Version

3.0.6

### Flutter Doctor output

?

**Comment by mvanbeusekom** [comment]
Hi @China-jxsg-YanYuanJie,

Unfortunately we don't understand Chinese and therefore it is impossible for us to understand the exact details of the issue. 

From the screenshots provided I have the following suggestions:

1. Please make sure the correct permissions are added to the `ios/Runner/Info.plist`.
2. Although commented out in the screenshot, I noticed the `if target.name == "permission_handler"` statement. On iOS the target should be `permission_handler_apple` as that is the package that is actually used in the iOS and macOS build.

I am closing this issue. Feel free to file a new issue in English.
