### ISSUE TITLE
[Bug]: The existing windows implementation does not work in Windows 7

### ISSUE THREAD

**Issue by YancyHsu** [Baseflow/flutter-permission-handler#1322]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [ ] Android
- [ ] iOS
- [X] Windows

### Steps to reproduce

The existing windows implementation does not work in Windows 7

### Expected results

work in Windows 7, or ignore in windows 7

### Actual results

nothing, but app can't start

### Code sample

now i use other package in github, add implementation in pubspec.yaml

dependency_overrides:
  permission_handler_windows:
    git:
      url: https://github.com/localsend/permission_handler_windows_noop.git

### Version

11.3.1

### Flutter Doctor output

nothing, but app can't start

**Comment by YancyHsu** [comment]
dependency_overrides:
  permission_handler_windows:
    git:
      url: https://github.com/localsend/permission_handler_windows_noop.git

**Comment by mvanbeusekom** [comment]
Hi @YancyHsu,

Since Flutter itself only [support Windows 10 and up](https://docs.flutter.dev/reference/supported-platforms), we don't put any effort in maintaining compatibility in other Windows version.
