### ISSUE TITLE
[Question]: why set calendar Deprecated ? Forces me to use calendarFullAccess？

### ISSUE THREAD

**Issue by yanashenyang** [Baseflow/flutter-permission-handler#1326]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-permission-handler/blob/main/permission_handler/README.md).

### Please select for which platform(s) you need help

- [ ] Android
- [X] iOS
- [ ] Windows

### Your question

you set calendar Deprecated， and Forces me to use calendarFullAccess,  calendarWriteOnly
but in ios
```
@available(iOS 6.0, *)
public enum EKAuthorizationStatus : Int, @unchecked Sendable {

    case notDetermined = 0

    case restricted = 1

    case denied = 2

    @available(iOS 17.0, *)
    case fullAccess = 3

    @available(iOS 17.0, *)
    case writeOnly = 4

    
    @available(iOS, introduced: 6.0, deprecated: 17.0, message: "Check for full access or write only access")
    public static var authorized: EKAuthorizationStatus { get }
}
```
fullAccess & writeOnly is available in iOS 17.0
And your document also explains how to use calendar in iOS 17

Permission | Info.plist | Macro
-- | -- | --
PermissionGroup.calendar (< iOS 17) | NSCalendarsUsageDescription | PERMISSION_EVENTS
PermissionGroup.calendarWriteOnly (iOS 17+) | NSCalendarsWriteOnlyAccessUsageDescription | PERMISSION_EVENTS
PermissionGroup.calendarFullAccess (iOS 17+) | NSCalendarsFullAccessUsageDescription | PERMISSION_EVENTS_FULL_ACCESS

I only want to use calendar below iOS 17

### Version

11.3.1

**Comment by TimHoogstrate** [comment]
Dear @yanashenyang,

Thanks for offering your issue. Please elaborate a bit on the subject. I don't understand what your question is. Apple changes the functionality of the calendar permission from iOS 17. We only implemented the changes. If you would like to use iOS 17 feel free to use the deprecated methods.

Kind regards,
