### ISSUE TITLE
[Bug]:Permission.isDenied always return true.

### ISSUE THREAD

**Issue by Flucadetena** [Baseflow/flutter-permission-handler#1327]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [ ] Android
- [X] iOS
- [ ] Windows

### Steps to reproduce

When ever I call this it returns status "PermanentlyDenied" but the calls to "isPermanentlyDenied" return false and "isDenied" return true.

The worst is that the permissions are enabled and I can call the sensors and get the response i expect. But I cannot check if the user has given permission confidently to manage that situation.

```
 const permIos = Permission.sensors;
        final status = await permIos.request();
// prints => Status: PermissionStatus.permanentlyDenied
        print('Status: $status');
// prints => denied: true
        print('denied: ${await permIos.isDenied}');
// prints => isPermanentlyDenied: false
        print('isPermanentlyDenied: ${await permIos.isPermanentlyDenied}');
// prints => isRestricted: false
        print('isRestricted: ${await permIos.isRestricted}');
```

### Expected results

Return true and permissions granted.

### Actual results

PermanentlyDenied

### Code sample

<details><summary>Code sample</summary>

```dart
 const permIos = Permission.sensors;
        final status = await permIos.request();
// prints => Status: PermissionStatus.permanentlyDenied
        print('Status: $status');
// prints => denied: true
        print('denied: ${await permIos.isDenied}');
// prints => isPermanentlyDenied: false
        print('isPermanentlyDenied: ${await permIos.isPermanentlyDenied}');
// prints => isRestricted: false
        print('isRestricted: ${await permIos.isRestricted}');
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

11.3.1

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.4.1 23E224 darwin-arm64, locale es-ES)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.89.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by mvanbeusekom** [comment]
Hi @Flucadetena, 

Did you enable the necessary permissions in the `ios/Podfile` in your project as described in the README?

If so can you include the contents of the `ios/Podfile` to this issue?

**Comment by Flucadetena** [comment]
This a dependency of an old plugin, and although the talked about the info.plist. They did not talk about the podfile.

My bad sorry, thanks for the help.
