### ISSUE TITLE
[Question]: How to release or close camera after take photo in web flutter app ?

### ISSUE THREAD

**Issue by rhomayouni** [Baseflow/flutter-permission-handler#1328]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-permission-handler/blob/main/permission_handler/README.md).

### Please select for which platform(s) you need help

- [ ] Android
- [ ] iOS
- [ ] Windows

### Your question

When I  take photo in web browser, after close that page, the camera resource is involved and it doesnt released.
What should I do ?

### Version

^11.3.1

**Comment by mvanbeusekom** [comment]
This doesn't seem to be an issue related to the permission_handler plugin.

I will close this issue. However if you feel this is an issue related to the permission_handler, explain detailed steps on how to reproduce the problem.
