### ISSUE TITLE
[Question]: Is POST_NOTIFICATIONS permission missing?

### ISSUE THREAD

**Issue by p3pp8** [Baseflow/flutter-permission-handler#1331]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-permission-handler/blob/main/permission_handler/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [ ] iOS
- [ ] Windows

### Your question

POST_NOTIFICATIONS permission is missing!

### Version

11.3.1

**Comment by mvanbeusekom** [comment]
Hi @p3pp8,

The POST_NOTIFICATIONS permissions can be requested on any Android device running TIRAMISU or higher using the `Permission.notification` permission.  

Important is to still add the POST_NOTIFICATIONS permission to the `android/app/src/main/AndroidManifest.xml` file.

Devices running pre TIRAMISU  Android version don't require separate permission request to handle notifications. 

Please let me know if this answers your question.

**Comment by p3pp8** [comment]
@mvanbeusekom Thank You, it works like a charm! Does notification permission work for iOS as well or do i have to use another one? Thanx!

**Comment by lybur** [comment]
> Hi @p3pp8,
> 
> The POST_NOTIFICATIONS permissions can be requested on any Android device running TIRAMISU or higher using the `Permission.notification` permission.
> 
> Important is to still add the POST_NOTIFICATIONS permission to the `android/app/src/main/AndroidManifest.xml` file.
> 
> Devices running pre TIRAMISU Android version don't require separate permission request to handle notifications.
> 
> Please let me know if this answers your question.

Great! Does that mean devices running pre TIRAMISU will not prompt the permission dialog? Cause I'm wondering if I should check the API level before requesting permission.

**Comment by mvanbeusekom** [comment]
> @mvanbeusekom Thank You, it works like a charm! Does notification permission work for iOS as well or do i have to use another one? Thanx!

The `Permission.notification` indeed works on iOS as well.

**Comment by mvanbeusekom** [comment]
> Great! Does that mean devices running pre TIRAMISU will not prompt the permission dialog? Cause I'm wondering if I should check the API level before requesting permission.

@lybur there is no need to check for API level, this is handled internally in the permission_handler implementation.
