### ISSUE TITLE
[Question]: How do we access the READ_PHONE_NUMBERS permission

### ISSUE THREAD

**Issue by vivekkartha7** [Baseflow/flutter-permission-handler#1332]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-permission-handler/blob/main/permission_handler/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [ ] iOS
- [ ] Windows

### Your question

I see that Permissions.phone is used for READ_PHONE_STATE. How can I explicitly request READ_PHONE_NUMBERS as well? I'm using permission_handler v11.3.1.

### Version

11.3.1

**Comment by kjw3676** [comment]
I have same issue. How can I access READ_PHONE_STATE permission?

**Comment by TimHoogstrate** [comment]
Dear @vivekkartha7,

You can do this on Android > 10 and by adding the READ_PHONE_NUMBERS to the manifest. Then request phone permissions.

Kind regards,
