### ISSUE TITLE
Kotlin version of package

### ISSUE THREAD

**Issue by Alok082** [Baseflow/flutter-permission-handler#1337]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-permission-handler/blob/main/permission_handler/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [ ] iOS
- [ ] Windows

### Your question

The error indicates that a dependency, specifically the ar_flutter_plugin, is using an outdated version of the Kotlin Gradle plugin (1.3.50) , android. gradle plugin supports only Kotlin Gradle plugin version 1.5.20 

### Version

0.7.3

**Comment by TimHoogstrate** [comment]
Dear @Alok082,

Can you elaborate a bit on the subject? We are not the maintainers of ar_flutter_plugin. 

Kind regards,
