### ISSUE TITLE
[Question]: how can I request only a single permission ACCESS_COARSE_LOCATION (Android)

### ISSUE THREAD

**Issue by bin-xgo** [Baseflow/flutter-permission-handler#1340]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-permission-handler/blob/main/permission_handler/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [ ] iOS
- [ ] Windows

### Your question

Some countries don't allow precise location permissions, so how can I request only a single permission ACCESS_COARSE_LOCATION (Android)

### Version

11.3.1

**Comment by TimHoogstrate** [comment]
Dear @bin-xgo,

You can add ACCESS_COARSE_LOCATION permission to your manifest 
` <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />` and request location permission in the plugin.

Kind regards,
