### ISSUE TITLE
SMS Permission on iOS: it's unclear if it's necessary to edit Info.plist and eventually how

### ISSUE THREAD

**Issue by simonecaf** [Baseflow/flutter-permission-handler#1342]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-permission-handler/blob/main/permission_handler/README.md).

### Please select for which platform(s) you need help

- [ ] Android
- [X] iOS
- [ ] Windows

### Your question

How should I setup Info.plist to give permission to send SMS on iOS?

### Version

latest

**Comment by TimHoogstrate** [comment]
Dear @simonecaf,

Can you elaborate a bit on the subject. Can you point me to some documentation that you need permissions for this?

https://developer.apple.com/documentation/messageui

Kind regards,
