### ISSUE TITLE
[Regression]: Permission.notification.request() not showing dialog modal Android & iOS

### ISSUE THREAD

**Issue by ridefox-abarbosa** [Baseflow/flutter-permission-handler#1348]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).

### Please select affected platform(s)

- [X] Android
- [X] iOS
- [ ] Windows

### Old behavior

Expecting to see a modal like this (My App is not boat trader)
![thumbnail_Screenshot_20240717_150947_Permission controller](https://github.com/user-attachments/assets/b3fd779e-9e59-4cee-b4cd-bc5262563830)

### Current behavior

When attempting to ask for `notification` permissions no modal pops up. However to make sure my code was correct I asked for `location` permissions which work flawlessly. This happens with both Android and iOS.

PLEASE NOTE: I am going off of ticket #888 for last version without regression 

### Steps to reproduce

Boot up Android and/or iOS device and request notification permissions. I can reproduce this on multiple platforms and on both physical devices and emulators

### Code sample

Code I am using to request permissions

```dart
static Future<List<PermissionStatus>> _requestPermissions(List<Permission> permissionsToRequest) async {
    final List<PermissionStatus> permissions = [];
    for (var permission in permissionsToRequest) {
      permissions.add(await permission.request());
    }

    return permissions;
  }
```

My Android Manifest 
```xml
<uses-permission android:name="android.permission.ACCESS_NOTIFICATION_POLICY"/>
<uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>
```

build.gradle
![Screenshot 2024-07-19 at 2 30 05 PM](https://github.com/user-attachments/assets/52d4c248-9446-47a0-9283-f2e680003dc9)

Flutter doctor
![Screenshot 2024-07-19 at 2 32 24 PM](https://github.com/user-attachments/assets/b2b93c97-3bee-4c45-945d-edd9602dd758)

### Current version

11.3.1

### Last version without regression

10.4.3

**Comment by TimHoogstrate** [comment]
Dear @ridefox-abarbosa,

Thanks for filing your issue. Can you check that this is working in the example app? For iOS, maybe you missed the info.plist and podfile changes for iOS as described in the README e.g. PERMISSION_NOTIFICATIONS=1.

Also from the README (iOS):

```Some permissions will not show a dialog asking the user to allow or deny the requested permission.
This is because the OS setting(s) of the app are being retrieved for the corresponding permission.
The status of the setting will determine whether the permission is granted or denied.

The following permissions will show no dialog:

Notification
```

Then for Android, what Android version are you testing. From Android 13 the behaviour is different: (https://developer.android.com/develop/ui/views/notifications/notification-permission)

Kind regards,

**Comment by ridefox-abarbosa** [comment]
Hey Tim, 
So it turns out it works for iOS and what I was experiencing was just apples way of handling permanently denied permissions and the permission modal for notifications does pop up in the beginning of our app. 

However I am still finding trouble with Android 11 and 12. In my app when it starts up no modal shows up and notifications are not set to enabled. In the example app notifications are turned on by default however no modal shows asking me to enable. In the example app when I turn notifications off in my settings and go back to the app and attempt to turn them back on no modal shows up and it just returns a `PermissionStatus.denied` (Which might be intended by Android just like in iOS).  

In Android 13 & 14 it DOES work if I call the code manually and does not appear automatically like it does on iOS.

**Comment by ridefox-abarbosa** [comment]
Actually thank you for the clarification. I see the difference between Android OS versions. I guess I was expecting something else to happen. Closing for now!
