### ISSUE TITLE
Not asking permission in Many devices in production

### ISSUE THREAD

**Issue by VarunSaini23** [Baseflow/flutter-permission-handler#135]
## 🐛 Bug Report

Initially does not ask for permission. But once we give permission manually, and then turn on/off permission manually, the library works perfectly fine.
### Configuration

**Version:** 3.1.0

**Platform:** 
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
@VarunSaini23 we can not reproduce this using our example app (see [here]()) or any of the other apps we build. 

Can you provide an example application demonstrating this behaviour? Output from `flutter doctor -v` might also help.

**Comment by readuo** [comment]
in my case, it works fine on debug mode and virtual device. when I build release apk and install on device, it doesn't ask for permission. I tested this on Galaxy Note 9 and LG G7 ThinQ. Both have the same issue.

This is the line. I know this line is executed, but nothing happens
var result = await PermissionHandler().requestPermissions([PermissionGroup.contacts]);

**Comment by DanielZ87** [comment]
I am facing the exact same problem. The compiler gives me following hint:

**permission_handler-3.3.0\android\src\main\java\com\baseflow\permissionhandler\PermissionHandlerPlugin.java uses or overrides a deprecated API**

**Comment by ened** [comment]
@readuo @DanielZ87 did you add `android.permission.READ_CONTACTS` to your AndroidManifest.xml?

**Comment by DanielZ87** [comment]
Hmm my first intention was to say yes, but then I double-checked it and realized that there are multiple AndroidManifest.xml files. Adding to the release manifest did solve that. Thx to lead me to this one.:-)

**Comment by VarunSaini23** [comment]
> Hmm my first intention was to say yes, but then I double-checked it and realized that there are multiple AndroidManifest.xml files. Adding to the release manifest did solve that. Thx to lead me to this one.:-)

<app dir>/android/app/src/main this is the location of androidManifest file. what is the location of release manifest file??

**Comment by mvanbeusekom** [comment]
closing due to lack of response
