### ISSUE TITLE
[Bug]: No such file or directory: 'permission_handler_apple'

### ISSUE THREAD

**Issue by narimetisaigopi** [Baseflow/flutter-permission-handler#1350]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [ ] Android
- [X] iOS
- [ ] Windows

### Steps to reproduce

permission_handler: ^10.0.0
using this version it is throwing the error

### Expected results

should build on xcode

### Actual results

Xcode unable to built

### Code sample

<details><summary>Code sample</summary>

```dart

```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

<img width="1440" alt="Screenshot 2024-07-23 at 15 17 57" src="https://github.com/user-attachments/assets/4fffcac0-5b91-45d8-8ed6-6adb7f5f3ab2">

</details>

### Version

10.0.0

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.9, on macOS 14.5 23F79 darwin-arm (Rosetta), locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[!] Android Studio (version 2024.1)
    ✗ Unable to find bundled Java version.
[✓] VS Code (version 1.91.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```

</details>

**Comment by TimHoogstrate** [comment]
Dear @narimetisaigopi,

Thanks for filing your issue. It seems you are working with an old version of Flutter and the permission_handler. I would suggest updating to the latest versions. If this is not possible try `flutter clean` and `flutter build ios`. Furthermore, be sure that you have opened the xcWorkspace.

Kind regards,
