### ISSUE TITLE
[Regression]: permissions_handler_html: Failed to execute 'query' on 'Permissions': Failed to read the 'name' property from 'PermissionDescriptor': Required member is undefined.

### ISSUE THREAD

**Issue by mrcsh** [Baseflow/flutter-permission-handler#1353]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).

### Please select affected platform(s)

- [ ] Android
- [ ] iOS
- [ ] Windows

### Old behavior

no exception thrown from code 
``` await Permission.notification.status```

### Current behavior

exception is thrown

### Steps to reproduce

 ```await Permission.notification.status```

### Code sample

<details><summary>Code sample</summary>

```dart
 await Permission.notification.status
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Current version

0.1.2

### Last version without regression

0.1.1

**Comment by bloemy7** [comment]
Running into the same issue

**Comment by wzbearb** [comment]
also has a same issue

**Comment by bloemy7** [comment]
This is quite an urgent problem, could it be looked at? It's breaking our ability to make an update here, especially because `permissions_handler` is directly importing the local version of the HTML, so we cannot override.

**Comment by TimHoogstrate** [comment]
Dear @mrcsh or @wzbearb or @bloemy7,

Can you elaborate a bit on the subject? Can you add the contents of `flutter doctor -v` to this issue? And can you also add some clear steps to reproduce, on other words: How are you testing this?

Kind regards

**Comment by mrcsh** [comment]
Simply calling ```await Permission.notification.status``` causes an exception on the web.  My guess is something with the switch to platform:web isn't quite right.

forcing permission_handler_html to 0.1.1 with a dependency_override in pubspec.yaml eliminates the exception.

Here is my flutter doctor -v output

```
[✓] Flutter (Channel stable, 3.22.3, on Fedora Linux 40 (Forty) 6.9.7-200.fc40.x86_64, locale en_US.UTF-8)
    • Flutter version 3.22.3 on channel stable at /svr/home/csh/lib/flutter3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (2 weeks ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/csh/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /svr/home/csh/lib/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 18.1.6 (Fedora 18.1.6-3.fc40)
    • cmake version 3.28.2
    • ninja version 1.12.1
    • pkg-config version 2.1.1

[✓] Android Studio (version 2023.3)
    • Android Studio at /svr/home/csh/lib/android-studio
    • Flutter plugin version 79.0.2
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] Android Studio (version 2023.2)
    • Android Studio at /server/home/csh/lib/android-studio
    • Flutter plugin version 78.4.1
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.91.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.92.0

[✓] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • sdk gphone64 x86 64 (mobile) • emulator-5556 • android-x64    • Android 14 (API 34) (emulator)
    • Linux (desktop)              • linux         • linux-x64      • Fedora Linux 40 (Forty)
      6.9.7-200.fc40.x86_64
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 127.0.6533.72

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by Kancheraj** [comment]
any update..?

**Comment by mrcsh** [comment]
> @mrcsh, on what web? MacOs Chrome?
> 
> Kind regards,

At least Chrome on macos, windows and Linux.  I can test other browsers later today after my primary internet connection has been restored.

**Comment by mrcsh** [comment]
Also happens on Brave on Linux,
Firefox on linux produces this error 
```TypeError: Missing required 'name' member of PermissionDescriptor.```
Brave on Windows produces
```TypeError: Failed to execute 'query' on 'Permissions': Failed to read the 'name' property from 'PermissionDescriptor': Required member is undefined.```
Chromium on linux produces:
```TypeError: Failed to execute 'query' on 'Permissions': Failed to read the 'name' property from 'PermissionDescriptor': Required member is undefined.```

**Comment by kurosh-bz** [comment]
Any update? I have same issue on web

**Comment by Kancheraj** [comment]
Future<PermissionStatus> permissionStatus(Permission permission) async {
    if (kIsWeb) {
      var permissionStatus = await html.window.navigator.permissions?.query({
        'name': permission.toString().split('.')[1] == 'location' ? 'geolocation' : permission.toString().split('.')[1],
      });

      // ignore: unrelated_type_equality_checks
      if (permissionStatus == 'granted') {
        return PermissionStatus.granted;
      // ignore: unrelated_type_equality_checks
      } else if (permissionStatus == 'denied') {
        return PermissionStatus.permanentlyDenied;
      } else {
        return PermissionStatus.denied;
      }
    } else {
      return await permission.status;
    }
  }

**Comment by tomasweigenast** [comment]
Is there any update on this? Issue on web

**Comment by mvanbeusekom** [comment]
I have just release version 0.1.3+1 of the `permission_handler_html` package which should resolve this issue. To update please run `flutter pub upgrade permission_handler_html`.
