### ISSUE TITLE
[Feature request]: Flutter V3.24 - Android Compile SDK Version 34 Not Supported

### ISSUE THREAD

**Issue by damientms** [Baseflow/flutter-permission-handler#1365]
### Is there already an issue requesting this feature?

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Windows

### Use case

To support latest android release

### Proposal

Flutter last week release V3.24 which uses **API LEVEL 34** But permission handler doesn't return results and throw Exception

**Comment by TimHoogstrate** [comment]
Dear @damientms,

Can you elaborate a bit on the subject? What exception is it throwing?  Do you have some steps to reproduce? Did you try the example app? And can you add the output of 'flutter doctor -v' to the issue?

Kind regards,
