### ISSUE TITLE
[Question]: how to solve this please

### ISSUE THREAD

**Issue by issemou** [Baseflow/flutter-permission-handler#1372]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-permission-handler/blob/main/permission_handler/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [ ] iOS
- [ ] Windows

### Your question

![erreur_bug_close_app](https://github.com/user-attachments/assets/cd676637-04e2-4799-a7b6-1d0604646b42)

### Version

13.0.1

**Comment by issemou** [comment]
version of geolocator .  sdk flutter sdk: '>=3.4.3 <4.0.0',

**Comment by mvanbeusekom** [comment]
Does the `android/app/src/main/AndroidManifest.xml` file contain the required permissions as mentioned in the "Android" section of the README.md file?

Would it be possible to provide a small application replicating this behavior?

**Comment by issemou** [comment]
yes ! Can you confirm that this error is caused by the permission_handler plugin

**Comment by issemou** [comment]
![manifest](https://github.com/user-attachments/assets/f354e048-efbb-401d-95db-698612838f24)

**Comment by issemou** [comment]
![mainkotlin](https://github.com/user-attachments/assets/86109cef-f2db-4c3b-9b87-74aab8748404)

**Comment by mvanbeusekom** [comment]
Hi @issemou,

Can you provide an example that reproduces the error? The example application works fine, as well as me making a quick new flutter application requesting location permissions. Meaning I cannot reproduce the error making it really hard for me to help.

More information would also help, for example:

- Output of the `flutter doctor -v` command.
- Information about the setup of your application (add-to-app or 100% flutter).

P.S. for future reference, please provide code samples, configuration snippets or error messages in text form and don't use screenshots. We cannot copy code or configuration from screenshots making it difficult for us to simulate similar setup which makes it more unlikely we are willing to help.
