### ISSUE TITLE
[Question]: About [Connection status] like Wifi, 4G, 5G, Not connected, etc.

### ISSUE THREAD

**Issue by alphanumericaracters** [Baseflow/flutter-permission-handler#1385]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-permission-handler/blob/main/permission_handler/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [ ] iOS
- [ ] Windows

### Your question

**Well:** 
- Working on a project, the main task is to be able to know the network and connection status of the device (wifi, 4G, 5G, offline, etc.). [Well, I need to download maps and updated information for offline mode, etc.]

But due to the lack of explicitness in the documentation regarding the permissions (which each one contains). I can't figure out which one I should request and how I should operate with it.

When I open the options tree, I don't find anything (implicit) regarding connection and network status.

- Flutter version 3.24.2
- Dart version 3.5.2
- DevTools version 2.37.2

```Dart
import 'package:flutter/material.dart';
import 'package:permission_handler/permission_handler.dart';

class PermisosConexionProvider with ChangeNotifier {
  bool permisoConcedido = false;
  bool permisoSolicitado = false;
  String errorMensaje = '';

  Future<void> solicitarPermiso() async {
    if (!permisoSolicitado) {
      try {
        var estadoPermiso = await Permission.phone.request(); //Here i need to ask (Phone it's just to don't get error)
        permisoConcedido = estadoPermiso.isGranted;
        permisoSolicitado = true;

        if (!permisoConcedido) {
          errorMensaje = 'Permisos de conexión denegados. La app necesita este permiso para funcionar correctamente.';
        }

        notifyListeners();
      } catch (e) {
        errorMensaje = 'Error al solicitar permisos: $e';
        notifyListeners();
      }
    }
  }
}
```

![ScreenShot of options 1](https://github.com/user-attachments/assets/03a4a755-1e5f-44c6-a346-ba739505b4e7)

![Screensot of options 2](https://github.com/user-attachments/assets/9691cfed-c003-4188-9794-088c79198c57)

### Version

^11.3.1

**Comment by mvanbeusekom** [comment]
Hi @alphanumericaracters, 

For both Android and iOS it is not required to explicitly request permission to access the internet. Therefore the internet (or network) connectivity level or status is not considered a feature that concerns the permission_handler. 

Please have a look at the [connectivity_plus](https://pub.dev/packages/connectivity_plus) plugin, which should be able to help out.

**Comment by alphanumericaracters** [comment]
- Sorry, I didn't have the slightest idea that was like that. 

So, broadly speaking... The only permissions that are necessary to ask for, are the ones listed in the plugin, the rest of them (so to speak) are not necessary. 

Thank you very much for your response, its speed and certainty.
