### ISSUE TITLE
[Question]: why camera  permission popup is not showing again when restart or reopen the app when user has selected Allow Once 

### ISSUE THREAD

**Issue by Akshay77380** [Baseflow/flutter-permission-handler#1398]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-permission-handler/blob/main/permission_handler/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [X] iOS
- [ ] Windows

### Your question

import 'dart:io';

import 'package:brain_revamp/app/modules/Unsplash/views/unsplash_view.dart';
import 'package:brain_revamp/app/utils/custom_utils.dart';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:image_picker/image_picker.dart';
import 'package:image_picker_platform_interface/image_picker_platform_interface.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../../generated/locales.g.dart';
import '../modules/Unsplash/controllers/unsplash_controller.dart';
import '../theme/dark_theme_colors.dart';
import '../theme/light_theme_colors.dart';
import 'elevation.dart';
import 'log_helper.dart';

class MediaPicker {
  final ImagePicker _picker = ImagePicker();

// ···
  final ImagePickerPlatform imagePickerImplementation =
      ImagePickerPlatform.instance;

  Future<bool> _checkAndRequestCameraPermission() async {
    var status = await Permission.camera.status;
    Logger().d("Camera permission status: $status");

    if (status.isGranted) {
      return true;
    } else if (status.isLimited || status.isDenied) {
      var result = await Permission.camera.request();
      Logger().d("Camera permission request result: $result");

      // Save the permission status
      SharedPreferences prefs = await SharedPreferences.getInstance();
      await prefs.setBool('camera_permission_limited', result.isLimited);

      return result.isGranted || result.isLimited;
    } else {
      return false;
    }
  }

  Future<void> checkCameraPermissionOnRestart() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    bool isLimited = prefs.getBool('camera_permission_limited') ?? false;

    if (isLimited) {
      // Request permission again
      await _checkAndRequestCameraPermission();
    }
  }

  Future<File?> getImage({
    required bool fromCamera,
    int quality = 100,
    double? maxWidth,
    double? maxHeight,
    CameraDevice cameraDevice = CameraDevice.rear,
  }) async {
    if (fromCamera) {
      bool hasPermission = await _checkAndRequestCameraPermission();
      if (!hasPermission) {
        Get.snackbar(
          'Permission Denied',
          'Camera permission is required to take a photo.',
          icon: const Icon(Icons.error, color: Colors.white),
          snackPosition: SnackPosition.BOTTOM,
          backgroundColor: Get.isDarkMode
              ? DarkThemeColors.primary
              : LightThemeColors.primary,
          borderRadius: 20,
          margin: const EdgeInsets.all(15),
          colorText: Colors.white,
          isDismissible: true,
          dismissDirection: DismissDirection.horizontal,
          forwardAnimationCurve: Curves.easeOutBack,
        );
        return null;
      }
    }

    var pickType = fromCamera ? ImageSource.camera : ImageSource.gallery;

    try {
      final XFile? pickedFile = await _picker.pickImage(
        source: pickType,
        imageQuality: quality,
        maxWidth: maxWidth,
        maxHeight: maxHeight,
        preferredCameraDevice: cameraDevice,
      );

      if (pickedFile != null) {
        Logger().d("Picked file: ${pickedFile.path}");
        return File(pickedFile.path);
      } else {
        Logger().d("No file picked");
        return null;
      }
    } catch (e) {
      Logger().d("Error picking image: $e");
      return null;
    }
  }

  /// Title null
  Future<File?> showUploadPicker(
      {String? title,
      int quality = 100,
      double? maxWidth,
      double? maxHeight,
      bool showAvtarPicker = false,
      bool showSearchPicker = true,
      CameraDevice cameraDevice = CameraDevice.rear,
      bool isAttachment = false}) async {
    File? pickedImage;

    await showModalBottomSheet(
      isScrollControlled: true,
      context: Get.context!,
      showDragHandle: true,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadiusDirectional.only(
          topEnd: Radius.circular(25),
          topStart: Radius.circular(25),
        ),
      ),
      builder: (context) => Container(
        padding: const EdgeInsetsDirectional.only(
          start: 20,
          end: 20,
          bottom: 30,
          top: 8,
        ),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Container(
              padding:
                  const EdgeInsets.symmetric(vertical: Elevation.elevation8),
              child: Text(
                title ??
                    ((isAttachment == true)
                        ? LocaleKeys.addAttachment.tr
                        : LocaleKeys.addCoverImage.tr),
                style: Get.textTheme.titleLarge,
                textAlign: TextAlign.start,
              ),
            ),
            const SizedBox(height: Elevation.elevation10),
            InkWell(
              splashColor: context.theme.colorScheme.primary,
              splashFactory: InkSplash.splashFactory,
              onTap: () async {
                pickedImage = null;
                var mainImage = await getImage(
                    fromCamera: false,
                    cameraDevice: cameraDevice,
                    maxHeight: maxHeight,
                    maxWidth: maxWidth,
                    quality: quality);

                if (mainImage != null) {
                  pickedImage =
                      await CustomUtils.resizeImage(mainImage, 500, 500);
                } else {
                  pickedImage = null;
                }
                Get.back();
              },
              child: Container(
                  decoration: BoxDecoration(
                    color: Get.context!.theme.colorScheme.onPrimary,
                    borderRadius: const BorderRadius.all(
                      Radius.circular(Elevation.elevation16),
                    ),
                  ),
                  padding:
                      const EdgeInsets.symmetric(vertical: 15, horizontal: 10),
                  width: double.infinity,
                  child: Row(
                    children: [
                      const Icon(Icons.photo_size_select_actual_outlined),
                      const SizedBox(width: Elevation.elevation8),
                      Text(
                        LocaleKeys.pickFromGallery.tr,
                        style: Get.textTheme.bodyLarge?.copyWith(),
                      ),
                    ],
                  )),
            ),
            const SizedBox(height: Elevation.elevation10),
            InkWell(
              splashColor: context.theme.colorScheme.primary,
              splashFactory: InkSplash.splashFactory,
              child: Container(
                  decoration: BoxDecoration(
                    color: Get.context!.theme.colorScheme.onPrimary,
                    borderRadius: const BorderRadius.all(
                      Radius.circular(Elevation.elevation16),
                    ),
                  ),
                  padding:
                      const EdgeInsets.symmetric(vertical: 15, horizontal: 10),
                  width: double.infinity,
                  child: Row(
                    children: [
                      const Icon(Icons.camera_alt_outlined),
                      const SizedBox(width: Elevation.elevation8),
                      Text(
                        LocaleKeys.pickFromCamera.tr,
                        style: Get.textTheme.bodyLarge,
                      ),
                    ],
                  )),
              onTap: () async {
                pickedImage = null;
                var mainImage = await getImage(
                    fromCamera: true,
                    cameraDevice: cameraDevice,
                    maxHeight: maxHeight,
                    maxWidth: maxWidth,
                    quality: quality);
                if (mainImage != null) {
                  pickedImage =
                      await CustomUtils.resizeImage(mainImage, 500, 500);
                } else {
                  pickedImage = null;
                }

                Get.back();
              },
            ),
            const SizedBox(height: Elevation.elevation10),
            if (!showAvtarPicker && showSearchPicker)
              InkWell(
                splashColor: context.theme.colorScheme.primary,
                splashFactory: InkSplash.splashFactory,
                child: Container(
                    decoration: BoxDecoration(
                      color: Get.context!.theme.colorScheme.onPrimary,
                      borderRadius: const BorderRadius.all(
                        Radius.circular(Elevation.elevation16),
                      ),
                    ),
                    padding: const EdgeInsets.symmetric(
                        vertical: 15, horizontal: 10),
                    width: double.infinity,
                    child: Row(
                      children: [
                        const Icon(Icons.travel_explore),
                        const SizedBox(width: Elevation.elevation8),
                        Text(
                          LocaleKeys.search.tr,
                          style: Get.textTheme.bodyLarge,
                        ),
                      ],
                    )),
                onTap: () async {
                  pickedImage = null;
                  Get.lazyPut(() => UnsplashController());

                  final result = await Get.to(() => const UnsplashView());

                  if (result != null) {
                    var path = File(result);
                    pickedImage = path;
                  } else {
                    pickedImage = null;
                  }

                  Get.back();
                },
              ),
            const SizedBox(height: Elevation.elevation10),
            if (isAttachment)
              InkWell(
                splashColor: context.theme.colorScheme.primary,
                splashFactory: InkSplash.splashFactory,
                child: Container(
                    decoration: BoxDecoration(
                      color: Get.context!.theme.colorScheme.onPrimary,
                      borderRadius: const BorderRadius.all(
                        Radius.circular(Elevation.elevation16),
                      ),
                    ),
                    padding: const EdgeInsets.symmetric(
                        vertical: 15, horizontal: 10),
                    width: double.infinity,
                    child: Row(
                      children: [
                        const Icon(Icons.file_present),
                        const SizedBox(width: Elevation.elevation8),
                        Text(
                          LocaleKeys.pickFile.tr,
                          style: Get.textTheme.bodyLarge,
                        ),
                      ],
                    )),
                onTap: () async {
                  pickedImage = null;
                  FilePickerResult? result =
                      await FilePicker.platform.pickFiles(
                    type: FileType.custom,
                    allowMultiple: false,
                    allowedExtensions: ['pdf', 'jpg', 'jpeg', 'png'],
                  );

                  if (result != null) {
                    File file = File(result.files.single.path!);
                    String extension = file.path.split('.').last;
                    List<String> videoExtensions = [
                      'mp4',
                      'avi',
                      'mkv',
                      'flv',
                      'mov',
                      'wmv'
                    ];

                    int sizeInBytes = file.lengthSync();
                    double sizeInMb = sizeInBytes / (1024 * 1024);
                    if (videoExtensions.contains(extension)) {
                      Get.snackbar(
                        'Cannot upload video file',
                        'only image and pdf allowed',
                        icon: const Icon(Icons.error, color: Colors.white),
                        snackPosition: SnackPosition.BOTTOM,
                        backgroundColor: Get.isDarkMode
                            ? DarkThemeColors.primary
                            : LightThemeColors.primary,
                        borderRadius: 20,
                        margin: const EdgeInsets.all(15),
                        colorText: Colors.white,
                        isDismissible: true,
                        dismissDirection: DismissDirection.horizontal,
                        forwardAnimationCurve: Curves.easeOutBack,
                      );
                      return;
                    }
                    if (sizeInMb > 10) {
                      Get.snackbar(
                        LocaleKeys.error.tr,
                        LocaleKeys.attachmentSizeError.tr,
                        icon: const Icon(Icons.error, color: Colors.white),
                        snackPosition: SnackPosition.BOTTOM,
                        backgroundColor: Get.isDarkMode
                            ? DarkThemeColors.primary
                            : LightThemeColors.primary,
                        borderRadius: 20,
                        margin: const EdgeInsets.all(15),
                        colorText: Colors.white,
                        isDismissible: true,
                        dismissDirection: DismissDirection.horizontal,
                        forwardAnimationCurve: Curves.easeOutBack,
                      );
                      return;
                    }
                    pickedImage = file;
                  } else {
                    // User canceled the picker
                  }

                  Get.back();
                },
              ),
            if (showAvtarPicker)
              InkWell(
                splashColor: context.theme.colorScheme.primary,
                splashFactory: InkSplash.splashFactory,
                child: Container(
                    decoration: BoxDecoration(
                      color: Get.context!.theme.colorScheme.onPrimary,
                      borderRadius: const BorderRadius.all(
                        Radius.circular(Elevation.elevation16),
                      ),
                    ),
                    padding: const EdgeInsets.symmetric(
                        vertical: 15, horizontal: 10),
                    width: double.infinity,
                    child: Row(
                      children: [
                        const Icon(Icons.person_outline_outlined),
                        const SizedBox(width: Elevation.elevation8),
                        Text(
                          LocaleKeys.pickAvatar.tr,
                          style: Get.textTheme.bodyLarge,
                        ),
                      ],
                    )),
                onTap: () async {
                  pickedImage = null;
                  // open avtar picker
                  pickedImage = File('avtar');
                  Get.back();
                },
              ),
          ],
        ),
      ),
    );
    Logger().d("pickedimg $pickedImage");

    return pickedImage;
  }
}

### Version

permission_handler:11.3.1

**Comment by mvanbeusekom** [comment]
This is Android specific behavior. Android itself will reset the permission back to denied when the application is closed. 

However this is done in a background process and doesn't happen instantly. Therefore it might happen that when you restart the app directly after closing it, Android hasn't reset the permissions and the app will still function correctly. This is especially noticeable during debug sessions as it takes a bit longer to really terminate the application.

**Comment by mvanbeusekom** [comment]
There is no real need to force Android to deny the permission. Android will not deny the permission if the App is currently open (even when it is a different session). 

So you should handle this as normal, before accessing protected resources, check if you have permission.
