### ISSUE TITLE
[Bug]: When I use the add photos only permission, the returned permission is always isGranted

### ISSUE THREAD

**Issue by ShineYangGod** [Baseflow/flutter-permission-handler#1402]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [ ] Android
- [X] iOS
- [ ] Windows

### Steps to reproduce

When I use the add photos only permission, the returned permission is always isGranted

### Expected results

The expectation is that it should return normal, and that it should return isDenied when I reject it.

### Actual results

flutter: The permissions obtained are=========PermissionStatus.granted
flutter: Allow photo saving permissions

### Code sample

Permission permission;

  if (await Permission.photosAddOnly.isRestricted ||
      await Permission.photosAddOnly.isPermanentlyDenied) {
    permission = Permission.photosAddOnly;
  } else {
    permission = Permission.storage;
  }
  // 检查权限状态
  var status = await permission.status;

  if (status.isDenied) {
    // 如果权限被拒绝，请求权限
    status = await permission.request();
  }
  print('The permissions obtained are=========$status');
  if (status.isGranted) {
    print('Allow photo saving permissions');
    onJumpTab();
    SensorsUtil.instance.track(
        eventName: "permission_accept", properties: {"type": "选取手机照片授权"});
  } else if (status.isDenied) {
    // 权限被拒绝
    print("Permission denied. Cannot save photos to the album.");
    SensorsUtil.instance.track(
        eventName: "permission_reject", properties: {"type": "选取手机照片授权"});
  } else if (status.isPermanentlyDenied) {
    // 权限被永久拒绝，需要去设置页面手动开启
    SensorsUtil.instance.track(
        eventName: "permission_reject", properties: {"type": "选取手机照片授权"});
    openAppSettings();

  }

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>
![IMG_B2FB42CEFADE-1](https://github.com/user-attachments/assets/adc7ea14-31d9-40c0-aec0-d310e57f58c9)

### Version

11.3.1

### Flutter Doctor output

flutter: The permissions obtained are=========PermissionStatus.granted
flutter: Allow photo saving permissions

**Comment by TimHoogstrate** [comment]
Dear @ShineYangGod,

Do you still have the issue? I cannot reproduce this.

Kind regard,
