### ISSUE TITLE
[Enhancement proposal]: Handle denied permission for notifications as permanentlyDenied on older Androids

### ISSUE THREAD

**Issue by slaci** [Baseflow/flutter-permission-handler#1412]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Windows

### Proposal

[Currenlty](https://github.com/Baseflow/flutter-permission-handler/blob/c1a6a9babcdccb426a00de457f86bafaf368954d/permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java#L639) on Android 12 and below the `areNotificationsEnabled()` method checks if notifications are enabled or not, which is good. However, when they are disabled the `denied` status is returned by the plugin which implies that you may request runtime permission, but you can't as the permission does not exists. The `permanentlyDenied` status would fit more as you can't take any action to enable them runtime.

### Pitch

This would make it possible to show a "Request permission" button without additional platform (version) checks. As from my experience:

- `denied` = Show request permission button
- `permanentlyDenied` = Show go to settings button

**Comment by TimHoogstrate** [comment]
Dear @slaci,

We are working currently on a refactor. This refactor will resolve the issue. However, until we finish the refactor we are not going to  implement this.

Kind regards,
