### ISSUE TITLE
problem to ask multiple permission

### ISSUE THREAD

**Issue by singlakaran** [Baseflow/flutter-permission-handler#144]
## 🐛 Bug Report

i use this code

PermissionHandler().requestPermissions([PermissionGroup.storage, PermissionGroup.camera])

it firstly ask me storage permission and then i ahve to call again 
then it ask camera permission.

### Expected behavior

it should ask both permissions in one time.

### Reproduction steps

pass list of size 2 in `requestPermissions`. 

### Configuration

```
PermissionStatus permission = await PermissionHandler().checkPermissionStatus(PermissionGroup.storage);
    PermissionStatus permissionCamera =
        await PermissionHandler().checkPermissionStatus(PermissionGroup.camera);
    print(permission);
    if (permission == PermissionStatus.granted && permissionCamera == PermissionStatus.granted)
 {
    } else {
      Map<PermissionGroup, PermissionStatus> permissions =
          await PermissionHandler().requestPermissions(
              [PermissionGroup.storage, PermissionGroup.camera]);
 
      if (permissions[PermissionGroup.storage] == PermissionStatus.granted &&
          permissions[PermissionGroup.camera] == PermissionStatus.granted) {
        print("permission granted after request");
      }
```

**Version:** 1.x

3.2.2

**Platform:** 
- [x] :robot: Android

**Comment by emassa93** [comment]
I have the same problem with Flutter and permision_handler 4.0.0. Also tried with permission.dart but the result is the same!. I think it's a problem of the sdk or flutter

**Comment by emassa93** [comment]
I have found one solution!... For example, my code on flutter was:
`_primerInicio() async {
    // Primero verifico permisos de la APP
    final PermissionHandler _permissionHandler = PermissionHandler();
    var permissionStatusPhone = await _permissionHandler.checkPermissionStatus(PermissionGroup.phone);
    //var permissionStatusLocation = await _permissionHandler.checkPermissionStatus(PermissionGroup.location);

   if(permissionStatusPhone != PermissionStatus.granted || permissionStatusLocation != PermissionStatus.granted){
      await _permissionHandler.requestPermissions([PermissionGroup.phone,PermissionGroup.location]);
   }
    _loadSesionState();
    _loadsettings();
  }` 

Now I made this modification and it worked: 
`  _primerInicio() async {
    // Primero verifico permisos de la APP
    final PermissionHandler _permissionHandler = PermissionHandler();
_permissionHandler.requestPermissions([PermissionGroup.phone,PermissionGroup.location]);
    _loadSesionState();
    _loadsettings();
  }`

apparently when checking permissions also asks for them and there the error occurs. This image can help you to understand the error: 
![0_LuQugCqLUU26Vwp-](https://user-images.githubusercontent.com/42580739/71263581-e835ff80-2320-11ea-9bf9-28ba2c8f5017.png)
