### ISSUE TITLE
requestPermissions crashes from time to time on iOS - NSGenericException

### ISSUE THREAD

**Issue by exilonX** [Baseflow/flutter-permission-handler#160]
## 🐛 Bug Report

The app just crashes without any error in Android Studio - 
And if I run it from Xcode I could catch a log:

*** Terminating app due to uncaught exception 'NSGenericException', reason: '*** Collection <__NSDictionaryM: 0x28118b780> was mutated while being enumerated.'
*** First throw call stack:
(0x191b6498c 0x19188d0a4 0x191b6434c 0x1053cf154 0x1053cf7f4 0x1053cc4c4 0x1034e8814 0x1034e9060 0x1034e9824 0x1034e8ddc 0x1034e85d0 0x1053cc42c 0x105367dbc 0x1053be654 0x1053759e8 0x10537a09c 0x191ae2e1c 0x191ae2b58 0x191ae2228 0x191add364 0x191adc8bc 0x19b948328 0x195b726d4 0x102e81764 0x191967460)
libc++abi.dylib: terminating with uncaught exception of type NSException

### Reproduction steps
It happens randomly from time to time 

### Configuration

**Version:**  3.2.2

**Platform:** 
- [ ] :iphone: iOS

**Comment by danielroek** [comment]
Hi @exilonX , 

Please refer to [the Flutter repository](https://github.com/flutter/flutter) for Flutter specific issues.
