### ISSUE TITLE
Request location permission on iOS 11 and above

### ISSUE THREAD

**Issue by gary6lin** [Baseflow/flutter-permission-handler#161]
On iOS 11 and above, the plugin should check for the key NSLocationAlwaysAndWhenInUseUsageDescription instead of NSLocationAlwaysUsageDescription, since it is deprecated and not required to be defined in the plist on iOS 11 and above.

**Comment by lpfasd123** [comment]
同样遇到该问题，请求一直返回的是unknown

**Comment by danielroek** [comment]
NSLocationAlwaysAndWhenInUseUsageDescription is defined in Info.plist. Closing this issue.
