### ISSUE TITLE
Permission status is "ALWAYS DENIED" for devices managed by EMM (Enterprise Mobility Management)

### ISSUE THREAD

**Issue by jawad89** [Baseflow/flutter-permission-handler#171]
## 🐛 Bug Report
On devices setup using Android Enterprise Mobility Management (EMM) as [Company-owned devices for knowledge workers](https://developers.google.com/android/work/overview#company-owned-devices-for-knowledge-workers), where the user does not have access to the system setting the permission status is always returned as `PermissionStatus.denied`.
On checking or asking for permissions using native Android, the correct permission status is returned, but on using this plugin the status returned is always `PermissionStatus.denied`.
The method `PermissionHandler.shouldShowRequestPermissionRationale(perm)` returns the value `false` in this scenario, which shows the plugin is treating this as 'Do not ask again' use case.

### Expected behavior
On checking for permissions using the method `PermissionHandler().checkPermissionStatus(permission)` the permission status returned should be `PermissionStatus.granted` if the permission is already granted by the device admin.

### Reproduction steps
Setup an android device using an EMM tools such as [ScaleFusion](https://scalefusion.com/). Upload a release apk as an enterprise app, and restrict the user access to the device system settings. Automatically grant permissions to the uploaded app. Check for permissions status using the method `PermissionHandler().checkPermissionStatus(permission)`.

### Configuration
- The device should have Android version 6 or higher.
- The android device should be setup using an EMM tool such as [ScaleFusion](https://scalefusion.com/).
- The user should not have access to the system settings on the device.
- The permissions should be granted automatically to the app without user interaction.
![Screenshot_20191114-121027](https://user-images.githubusercontent.com/7666210/68837577-ae008f00-06de-11ea-8e7f-448f847adb85.png)

**Version:** 4.0.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by danielroek** [comment]
Does the user have the ability to accept of decline the request for permission? If that is the case, the functionality works as intended. 

If the application is granted permission automatically the employee's privacy could also be violated automatically.
