### ISSUE TITLE
Does not support Add2App after requesting permission for first time

### ISSUE THREAD

**Issue by samuelchanx** [Baseflow/flutter-permission-handler#172]
### Expected behavior
- Should not return `ERROR_ALREADY_REQUESTING_PERMISSIONS` on double permission request for Add2App flutter projects
### Reproduction steps
1. Add the library to flutter module with native app, wrapped in Activity
2. Call `PermissionHandler().requestPermission()`
3. Result is never returned, because the callback is triggered in embedding native activity `onRequestPermissionsResult`
### Configuration
```
[✓] Flutter (Channel beta, v1.10.7, on Mac OS X 10.15.1 19B88, locale en-HK)
    • Flutter version 1.10.7 at /Users/SC/flutter
    • Framework revision e70236e36c (6 weeks ago), 2019-10-02 09:32:30 -0700
    • Engine revision 9e6314d348
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 1103600280)
```
**Version:** 4.0.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by samuelchanx** [comment]
My current forked version fix involves disabling the null checking for requesting permission
https://github.com/void-meditation/flutter-permission-handler/commit/e23f8762fe752c117707c016492ccac52822996c

**Comment by joshuadeguzman** [comment]
> My current forked version fix involves disabling the null checking for requesting permission

Hi Samuel, unfortunately, this solution doesn't work either. Have you tested the changes on your end?

**Comment by mvanbeusekom** [comment]
@samuelchanx can you make a small example project reproducing the issue? Would be very helpful to see what you exactly mean with "Add the library to flutter module with native app, wrapped in Activity".

**Comment by joshuadeguzman** [comment]
Hi @mvanbeusekom, I believe he's referring to the Add-to-App feature of Flutter. Using **permission_handler** inside a Flutter module embedded inside an Android App does not work.
