### ISSUE TITLE
Permission to whitelist app

### ISSUE THREAD

**Issue by adithyak04** [Baseflow/flutter-permission-handler#174]
I would like to know whether there is any method by which I can whitelist my app while trying to install my app in any device

**Comment by mvanbeusekom** [comment]
Sorry @adithyak04 I am not sure what you mean by "whitelist my app while trying to install my app in any device"?

Can you explain what you are trying to accomplish?

**Comment by adithyak04** [comment]
Sorry. It was my mistake. It actually needs to be done in Ionic. So I am closing this. Sorry once again.
