### ISSUE TITLE
bluetooth permission

### ISSUE THREAD

**Issue by yiguozhen0510** [Baseflow/flutter-permission-handler#177]
why it does't support the permission of bluetooth?

**Comment by psycura** [comment]
@yiguozhen0510  I think its because iOS doesn`t support request for BT permissions - you should write native code that will init BlueToothCoreManager - and on this step iOS automatically will ask for permissions

**Comment by danielroek** [comment]
To use bluetooth, please refer to [pub.dev](https://pub.dev) to find a bluetooth plugin. These plugins also give functionality to actually use the devices bluetooth.
