### ISSUE TITLE
ANSWER_PHONE_CALLS

### ISSUE THREAD

**Issue by babulpatel1309** [Baseflow/flutter-permission-handler#183]
## 🚀 Can you please add permission ANSWER_PHONE_CALLS in PHONE group.

case PERMISSION_GROUP_PHONE:
                if (hasPermissionInManifest(Manifest.permission.READ_PHONE_STATE))
                    permissionNames.add(Manifest.permission.READ_PHONE_STATE);

                if (hasPermissionInManifest(Manifest.permission.CALL_PHONE))
                    permissionNames.add(Manifest.permission.CALL_PHONE);

                if (hasPermissionInManifest(Manifest.permission.READ_CALL_LOG))
                    permissionNames.add(Manifest.permission.READ_CALL_LOG);

                if (hasPermissionInManifest(Manifest.permission.WRITE_CALL_LOG))
                    permissionNames.add(Manifest.permission.WRITE_CALL_LOG);

                if (hasPermissionInManifest(Manifest.permission.ADD_VOICEMAIL))
                    permissionNames.add(Manifest.permission.ADD_VOICEMAIL);

                if (hasPermissionInManifest(Manifest.permission.USE_SIP))
                    permissionNames.add(Manifest.permission.USE_SIP);

                if (hasPermissionInManifest(Manifest.permission.PROCESS_OUTGOING_CALLS))
                    permissionNames.add(Manifest.permission.PROCESS_OUTGOING_CALLS);

                if (VERSION.SDK_INT >= VERSION_CODES.O && hasPermissionInManifest(Manifest.permission.ANSWER_PHONE_CALLS))
                    permissionNames.add(Manifest.permission.ANSWER_PHONE_CALLS);
                break;

- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
Fixed in #184 (thanks for the PR).
