### ISSUE TITLE
playstore warning for READ_PHONE_STATE

### ISSUE THREAD

**Issue by Xgamefactory** [Baseflow/flutter-permission-handler#194]
is it possible to prevent this pluging adding READ_PHONE_STATE permission to androidManifest in order to prevent this Warning so that users can upgrade app without such warning.

This is suspicious permission and we dont use such functionality in our app to need this perm.

```
1 message for Android App Bundle 47

New permissions added
Warning:

Users that have the APK with version code 42 may need to accept the android.permission.READ_PHONE_STATE permission, which may result in them not upgrading to this version of the app.
<img width="781" alt="Screen Shot 2020-01-22 at 18 28 45" src="https://user-images.githubusercontent.com/22529051/72902527-0e4a2780-3d45-11ea-8c12-0bf691e34af1.png">

```

**Comment by maxlapides** [comment]
This seems pretty important. I am seeing this permission on my Android app as well, even though we don't need it.

**Comment by Xgamefactory** [comment]
our current solution was to add  **tools:node="remove"** to Manifest xml

 ```
<uses-permission
    android:name="android.permission.READ_PHONE_STATE"
    tools:node="remove" />
```

**Comment by mvanbeusekom** [comment]
On Android you can simply remove all permissions you don't need from the AndroidManifest.xml file. Please do only add those permissions your App needs.

**Comment by bluemix** [comment]
I hope `android.permission.READ_PHONE_STATE` can be added to the library permissions list
