### ISSUE TITLE
Unexpected content of Location permission popup under iOS

### ISSUE THREAD

**Issue by bambinoua** [Baseflow/flutter-permission-handler#197]
### Expected behavior

When permission _locationAlways_ is asked it is expected popup screen with option _Allow Always_ but there is no such option. Only those ones are visible _Allow when using app_, _Allow once_, _Never_.

### Reproduction steps

Just call:
`PermissionHandler().requestPermissions([PermissionGroup.locationAlways]);`

### Configuration

**Version:** 4.2.0-hotfix.2

**Platform:** 
- [x] :iphone: iOS

**Comment by mvanbeusekom** [comment]
Hello @bambinoua, just to start and help us debug this issue, which keys did you register in your `Info.plist` (should be inside the iOS folder of your Flutter App)?  

For always permissions the `Info.plist` should have the `NSLocationAlwaysAndWhenInUseUsageDescription` key listed. Can you verify that it is there?

**Comment by bambinoua** [comment]
I checked `Info.plist` and these keys are present:
`NSLocationAlwaysAndWhenInUseUsageDescription`
`NSLocationWhenInUseUsageDescription`
`NSLocationAlwaysUsageDescription`

**Comment by arok** [comment]
Same for me

**Comment by arok** [comment]
Looks like it is expected behaviour https://medium.com/better-programming/understanding-new-location-permission-changes-in-ios-13-6c34dc5f54da

**Comment by mvanbeusekom** [comment]
Closing this issue, as it seems it is indeed expected behaviour. Thanks @arok for helping out.
