### ISSUE TITLE
Google Play warning with WRITE_EXTERNAL_STORAGE

### ISSUE THREAD

**Issue by maxlapides** [Baseflow/flutter-permission-handler#201]
## 🐛 Bug Report

We added this to the AndroidManifest.xml:

```
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```

Google Play now issues this warning:

<img width="625" alt="Screen Shot 2020-02-01 at 11 18 11 AM" src="https://user-images.githubusercontent.com/1874682/73597790-de3d1a00-44e4-11ea-85b8-de0a5608ae19.png">

### Configuration

**Version:** 4.2.0+hotfix.2

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by Saifallak** [comment]
that's normal google is telling you " `you have a new permission , users might get confused why this is added, just tell them why it's added in whats-new` ",, just ignore it

**Comment by mvanbeusekom** [comment]
Like mentioned this is normal behavior. You are adding functionality to your App that users might not appreciate. Google is giving you an heads up on it.
