### ISSUE TITLE
Support for android 10 permissions 

### ISSUE THREAD

**Issue by sarinupreti** [Baseflow/flutter-permission-handler#203]
## 🐛 Bug Report

![image](https://user-images.githubusercontent.com/18618641/73816909-ddbcc000-4811-11ea-9a26-a460096b69d8.png)

it keeps on asking permissions again and again when clicked **Keep while in-use access**. 

### Configuration

**Version:** 1.12.13+hotfix.7

**Platform:** 

- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
This is supported since version 3.3.0
