### ISSUE TITLE
How can I request android permission com.android.settings.TRUSTED_CREDENTIALS_USER

### ISSUE THREAD

**Issue by certaintls** [Baseflow/flutter-permission-handler#210]
## 💬 Questions and Help

I need to use `com.android.settings.TRUSTED_CREDENTIALS_USER` permission to access `/data/misc/keychain/cacerts-added` folder, according to https://stackoverflow.com/a/35132508/1966269

I can't find the right `PermissionGroup` group to use. Is this supported? If not, anyway to get around it?

**Comment by mvanbeusekom** [comment]
That would not be something the `permission_handler` is meant for. This plugin is meant to deal with Manifest.permissions on Android and contains the most popular permissions from this list: https://developer.android.com/reference/android/Manifest.permission

Not sure what you want to accomplish in your App, but it really seems you need to look a bit further. I you feel this should be in the permission_handler plugin you can make a Enhancement request with links to the required documentation on how to implement it.
