### ISSUE TITLE
Initial location check returns neverAskAgain 

### ISSUE THREAD

**Issue by rkl555** [Baseflow/flutter-permission-handler#211]
## 🐛 Bug Report

The initial location checkPermissionStatus(PermisshonGroup.location) returns different values for debug and production mode.  For production mode, the initial check permission value is neverAskAgain which means it will not allow to ask for permission. For debug mode, the value is denied which will ask for permission. Bug occurs on 4.2.0 through 4.2.0+hotfix.3. Version 4.1.0 initial value are denied on Android and unknown on iOS which is workable.

Not sure if this is overlapping some of the existing issues. If so, please point to the issue or issues for tracking this fix.

### Expected behavior
The initial check permission value should be anything but neverAskAgain to allow asking for permission.
### Reproduction steps
Check permission on initial install and afterward.
### Configuration
Flutter 3.5.3
**Version:** 1.x

**Platform:** 
- [x ] :iphone: iOS
- [x ] :robot: Android

**Comment by kwent** [comment]
Seeing the same issue

**Comment by smasinde** [comment]
Any fix?

**Comment by Sempakonka** [comment]
Hi  
Can you check if this issue still persists in 5.0.1+1?
Thanks
