### ISSUE TITLE
Support for CMMotionActivity

### ISSUE THREAD

**Issue by mvanbeusekom** [Baseflow/flutter-permission-handler#221]
## 🏗 Enhancement Proposal

The "permission_hanlder" plugin already supports the Android Activity Recognition permissions but doesn't support the iOS equivalent as of yet. The iOS documentation can be found here: https://developer.apple.com/documentation/coremotion/cmmotionactivitymanager

### Pitch

Implement the iOS equivalent of Android's Activity Recognition permissions.

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by JDDV** [comment]
Issue is closed due to the fact that this is implemented for iOS. support for CMMotionActivity is implemented in the sensor permission.
