### ISSUE TITLE
Haven't adapted androidx yet, how to I use it in my project？

### ISSUE THREAD

**Issue by hasonguo** [Baseflow/flutter-permission-handler#223]
Haven't adapted androidx yet, how to I use it in my project？

There are two choices:

1. Migrate to AndroidX (it is coming and you'll have to move there anyway shortly). The migration is well documented here and should be very easy;

1. If you really cannot migrate to AndroidX you can use permission_handler version 3.0.2 or lower. Note that these are not maintained and not all the functionality that is supported now, will be available.

I really cannot migrate to AndroidX ,but  permission_handler version 3.0.2  came across problem.

`   Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
        is also present at [androidx.core:core:1.0.1] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
        Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:15:5-38:19 to override.`
  
 I see permission_handler version 3.0.2   depends below:

`project :permission_handler
|    +--- androidx.annotation:annotation:1.0.1 -> 1.1.0
|    +--- androidx.core:core:1.0.1
|    |    +--- androidx.annotation:annotation:1.0.0 -> 1.1.0
|    |    +--- androidx.collection:collection:1.0.0
|    |    |    \--- androidx.annotation:annotation:1.0.0 -> 1.1.0
|    |    +--- androidx.lifecycle:lifecycle-runtime:2.0.0
|    |    |    +--- androidx.lifecycle:lifecycle-common:2.0.0
|    |    |    |    \--- androidx.annotation:annotation:1.0.0 -> 1.1.0
|    |    |    +--- androidx.arch.core:core-common:2.0.0
|    |    |    |    \--- androidx.annotation:annotation:1.0.0 -> 1.1.0
|    |    |    \--- androidx.annotation:annotation:1.0.0 -> 1.1.0
|    |    \--- androidx.versionedparcelable:versionedparcelable:1.0.0
|    |         +--- androidx.annotation:annotation:1.0.0 -> 1.1.0
|    |         \--- androidx.collection:collection:1.0.0 (*)`

permission_handler version 3.0.2   depends AndroidX,how do I use this version.thanks

see [#213](https://github.com/Baseflow/flutter-permission-handler/issues/213)

**Comment by mvanbeusekom** [comment]
@hasonguo seems like I made a mistake and 3.0.2 indeed already uses AndroidX. You best bet would be moving back to 2.2.0 in this case.

**Comment by hasonguo** [comment]
@mvanbeusekom  Thanks for your attention.I checked permission_handler‘s changelog,so I found  2.1.2 don't use AndroidX.But 2.1.2 was ancient version,I was afraid it can’t Satisfy my function.

**Comment by mvanbeusekom** [comment]
I am sorry to say, but that is all I can offer. Personally I would move to AndroidX a.s.a.p. it will only get harder since more and more plugins are supporting AndroidX. 

What is it exactly that is preventing you to move to AndroidX?

**Comment by hasonguo** [comment]
In a word，My project is very big;Many teams contribute to it.Many components and man plugins depends support,not AndroidX.now Migrates to AndroidX still not on the agenda.So I also can't promote it now. Thanks for your attention.

**Comment by mvanbeusekom** [comment]
Understand, but in that case I am not really able to help you. Hopefully version 2.1.2 covers your needs, otherwise I am afraid you'd have to fork the repo and convert it into a Android Support version (which should be relative easy to accomplish). Then when you do convert to AndroidX you will be able to switch back to this plugin.
