### ISSUE TITLE
Deprecation of LOCATION_MODE and LOCATION_PROVIDERS_ALLOWED

### ISSUE THREAD

**Issue by MysthawkCanada** [Baseflow/flutter-permission-handler#225]
## 🔙 Regression

When running my app with permission handler I'm getting the following warnings:

- PermissionHandlerPlugin.java:776: warning: [deprecation] LOCATION_MODE in Secure has been deprecated

        locationMode = Settings.Secure.getInt(context.getContentResolver(), Settings.Secure.LOCATION_MODE);

- PermissionHandlerPlugin.java:784: warning: [deprecation] LOCATION_PROVIDERS_ALLOWED in Secure has been deprecated

      final String locationProviders = Settings.Secure.getString(context.getContentResolver(), Settings.Secure.LOCATION_PROVIDERS_ALLOWED);

Is this being addressed?  I couldn't find an issue that was recent that discussed this.

Thank you,
Michael

### Reproduction steps
Use version 4.3.0 of permission handler and Flutter 1.12.13+hotfix.8.

### Configuration

**Version:** 4.3.0

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi @MysthawkCanada, we are aware of these warnings. They are there for backwards compatibility reasons, and are only executed on the platform versions where these APIs are still available. 

See also this issue https://github.com/Baseflow/flutter-permission-handler/issues/206 for more details.

Of course we would be happy to make changes if you have a better solution without breaking the backwards compatibility.
