### ISSUE TITLE
Cancelling the "Ignore Battery Optimizations" permission request crashes App

### ISSUE THREAD

**Issue by ened** [Baseflow/flutter-permission-handler#237]
## 🔙 Regression

The permission dialog for "ignoreBatteryOptimizations" can be accepted/denied or cancelled (by pressing the Android back button). Pressing Android Back will cause a full app crash due to invalid Hash Map instantiation.

### Old (and correct) behavior

Not sure, but as far as I'm aware 3.3.0 did not crash.

### Current behavior

Crashes when cancelling.

### Reproduction steps

Adjust develop-branch / example Android manifest and include the following lines:

```
    <!-- Permissions options for the `ignoreBatteryOptimizations` group -->
    <uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS" />
```

open Example App, scroll to "ignoreBatteryOptimizations", tap it. Press android back button.

### Configuration

**Version:** 4.4.0

**Platform:** 
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
Thanks @ened for reporting and fixing the issues. Will release a hotfix later today.
