### ISSUE TITLE
After request permission the record audio opens

### ISSUE THREAD

**Issue by gilvangobbato** [Baseflow/flutter-permission-handler#239]
## 🐛 Bug Report
It's reali strange, but I've a problem after request permission that open the audio record on my device, but any exeption is showing.
I'v tried to run in profile mode as well, but did not sove it.

### Expected behavior
After request permission and do it, they need to keep on the screen of my application and not send to an option that I never used and I don't want.

### Reproduction steps
An example to reproduce [https://github.com/gilvangobbato/file_demo](https://github.com/gilvangobbato/file_demo)

### Configuration

```
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  permission_handler: ^4.4.0+hotfix.2
  image_picker: ^0.6.3+4
  file_picker: ^1.5.0+2
```

**Version:** v1.12.13+hotfix.8

**Platform:** 
- [ ] :iphone: iOS
- [ x ] :robot: Android

**flutter doctor -v**

> [√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [versÃ£o 10.0.18363.752], locale pt-BR)
>     • Flutter version 1.12.13+hotfix.8 at C:\src\flutter
>     • Framework revision 0b8abb4724 (6 weeks ago), 2020-02-11 11:44:36 -0800
>     • Engine revision e1e6ced81d
>     • Dart version 2.7.0
> 
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at C:\Users\gilva\AppData\Local\Android\sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-29, build-tools 28.0.3
>     • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
>     • All Android licenses accepted.
> 
> [√] Android Studio (version 3.6)
>     • Android Studio at C:\Program Files\Android\Android Studio1
>     • Flutter plugin version 44.0.2
>     • Dart plugin version 192.7761
>     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
> 
> [√] VS Code (version 1.43.2)
>     • VS Code at C:\Users\gilva\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.8.1
> 
> [√] Connected device (1 available)
>     • CPH1707 • c4b5ca06 • android-arm64 • Android 7.1.1 (API 25)

Someone could help me?
Thanks

**Comment by mvanbeusekom** [comment]
@gilvangobbato this could be related to other issues we were experiencing for people that haven't updated there app to match the 1.12 Flutter App. 

Could you try to migrate your app as per these [instructions](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects) and see if that resolves your problem?

**Comment by gilvangobbato** [comment]
> @gilvangobbato this could be related to other issues we were experiencing for people that haven't updated there app to match the 1.12 Flutter App.
> 
> Could you try to migrate your app as per these [instructions](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects) and see if that resolves your problem?

So, thank you for your answer.
I've migrated the app to 1.12 some days ago, but the error keep doing.
One thing that I've observed is that only is ocuring in this related device 

> [√] Connected device (1 available)
> • CPH1707 • c4b5ca06 • android-arm64 • Android 7.1.1 (API 25)

So, can be something whit the Android version or my device, who knows? lol
I think that for now we could close this Issue.

Thanks

**Comment by mvanbeusekom** [comment]
Thank you for the feedback. I will indeed close the issue now. If it happens again (on other devices) or you discover more information, please don't hesitate to contact again and we can re-open the issue.
