### ISSUE TITLE
5.0.0 The getter 'isGranted' isn't defined for the class 'PermissionStatus'.

### ISSUE THREAD

**Issue by bulangnisi** [Baseflow/flutter-permission-handler#243]
When I updated to 5.0.0, there was a problem with the sample usage.
I am sure the 5.0.0 version of the file is used and flutter has been clean

PermissionStatus status = await Permission.contacts.request();
if (status.isGranted) {
      // there is problem, The getter 'isGranted' isn't defined for the class 'PermissionStatus'.
}

**Comment by bulangnisi** [comment]
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.8 at /Users/benj/flutter/flutter
    • Framework revision 0b8abb4724 (7 周前), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/benj/android-sdk-macosx
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/benj/android-sdk-macosx
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (2 available)
    • vivo NEX A • 1a987e87                                 • android-arm64 • Android 9 (API 28)
    • Iphone6-2  • 91ad44c49a8876e2ed32db547cf8da7a13631f79 • ios           • iOS 12.4.5

**Comment by mvanbeusekom** [comment]
Thank you for reporting this issue @bulangnisi. We forgot to export all enums from the `permission_handler_platform_interface` package causing this issue. 

It was quickly fixed and we have now released a hotfix for it (version 5.0.0+hotfix.1).
