### ISSUE TITLE
Submission to App Store fails do to permissions 

### ISSUE THREAD

**Issue by rlee1990** [Baseflow/flutter-permission-handler#249]
Each time I upload my app to the App Store Connect it fails saying that I am missing the purpose string. But per the instructions, you have put on the page. I changed the pod file and am running the latest version on the package.

```
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  generated_key_values = {}
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) do |line|
    next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
    plugin = line.split(pattern=separator)
    if plugin.length == 2
      podname = plugin[0].strip()
      path = plugin[1].strip()
      podpath = File.expand_path("#{path}", file_abs_path)
      generated_key_values[podname] = podpath
    else
      puts "Invalid plugin specification: #{line}"
    end
  end
  generated_key_values
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  
  # Flutter Pod

  copied_flutter_dir = File.join(__dir__, 'Flutter')
  copied_framework_path = File.join(copied_flutter_dir, 'Flutter.framework')
  copied_podspec_path = File.join(copied_flutter_dir, 'Flutter.podspec')
  unless File.exist?(copied_framework_path) && File.exist?(copied_podspec_path)
    # Copy Flutter.framework and Flutter.podspec to Flutter/ to have something to link against if the xcode backend script has not run yet.
    # That script will copy the correct debug/profile/release version of the framework based on the currently selected Xcode configuration.
    # CocoaPods will not embed the framework on pod install (before any build phases can generate) if the dylib does not exist.

    generated_xcode_build_settings_path = File.join(copied_flutter_dir, 'Generated.xcconfig')
    unless File.exist?(generated_xcode_build_settings_path)
      raise "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter pub get is executed first"
    end
    generated_xcode_build_settings = parse_KV_file(generated_xcode_build_settings_path)
    cached_framework_dir = generated_xcode_build_settings['FLUTTER_FRAMEWORK_DIR'];

    unless File.exist?(copied_framework_path)
      FileUtils.cp_r(File.join(cached_framework_dir, 'Flutter.framework'), copied_flutter_dir)
    end
    unless File.exist?(copied_podspec_path)
      FileUtils.cp(File.join(cached_framework_dir, 'Flutter.podspec'), copied_flutter_dir)
    end
  end

  # Keep pod path relative so it can be checked into Podfile.lock.
  pod 'Flutter', :path => 'Flutter'

  # Plugin Pods

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.each do |name, path|
    symlink = File.join('.symlinks', 'plugins', name)
    File.symlink(path, symlink)
    pod name, :path => File.join(symlink, 'ios')
  end
end

# Prevent Cocoapods from embedding a second Flutter framework and causing an error with the new Xcode build system.
install! 'cocoapods', :disable_input_output_paths => true

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',

        ## dart: PermissionGroup.calendar
        # 'PERMISSION_EVENTS=0',

        ## dart: PermissionGroup.reminders
        # 'PERMISSION_REMINDERS=0',

        ## dart: PermissionGroup.contacts
        # 'PERMISSION_CONTACTS=0',

        ## dart: PermissionGroup.speech
        # 'PERMISSION_SPEECH_RECOGNIZER=0',

        ## dart: [PermissionGroup.locationAlways]
        # 'PERMISSION_LOCATION=0',

        ## dart: PermissionGroup.sensors
        # 'PERMISSION_SENSORS=0'
      ]
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

**Comment by rlee1990** [comment]
@mvanbeusekom do you know whats wrong here?

**Comment by ChiHwe** [comment]
Hi rlee, do you manage to solve the issue?

**Comment by rlee1990** [comment]
> Hi rlee, do you manage to solve the issue?

@ChiHwe yes and not I got it to remove all but the one for requesting location always in uses but the app got approved. I also moved `config.build_settings['ENABLE_BITCODE'] = 'NO'` above `config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [`

**Comment by PierreLeGuen** [comment]
@rlee1990 remove the # before each statement, based on your config, change to : 
```
'PERMISSION_EVENTS=0',
'PERMISSION_REMINDERS=0',
'PERMISSION_CONTACTS=0',
'PERMISSION_SPEECH_RECOGNIZER=0',
'PERMISSION_LOCATION=0',
'PERMISSION_SENSORS=0'
```

**Comment by mvanbeusekom** [comment]
Like PierreLeGuen explains, you will need to remove the `#` character in front of the permissions you want to disable (so those you are NOT using in your app). By default all permissions are enabled and all the switches in the `Podfile` are commented out (using the # character). So to disable certain permissions you don't need in your App simply remove the `#` character.

**Comment by rlee1990** [comment]
> Like PierreLeGuen explains, you will need to remove the `#` character in front of the permissions you want to disable (so those you are NOT using in your app). By default all permissions are enabled and all the switches in the `Podfile` are commented out (using the # character). So to disable certain permissions you don't need in your App simply remove the `#` character.
> 
> 
> 
> I will update the README.md file, since personally I also had difficulty understanding it at once.

Question if I want to use location while in use and not always in use is there a way to not have always in use requested but just while in use?

**Comment by PierreLeGuen** [comment]
This is not related to the current issue, but just use: `Permission.locationWhenInUse.request();`

**Comment by rlee1990** [comment]
> This is not related to the current issue, but just use: `Permission.locationWhenInUse.request();`

By that I meant from it requesting permission in the pod file because they both are under the location permission

**Comment by mvanbeusekom** [comment]
The code in the Podfile is only related to the API you want to use, not how you want to use it. Meaning if you need to access the users location you will have to use the location API on iOS. This is not related to using in “when in use” or “always”.

You can distinguish between those modes by adding the correct values in the `info.plist` file. For example by only adds the key related to the “when in use” mode and leaving the other keys out.

**Comment by ChiHwe** [comment]
Hi guys, may i know anyone success upload the file to ios and get approve? After i get this library, i try my one and get rejected for many times ...it is always conflict with the one signal and give me below error:

ERROR ITMS-90206: "Invalid Bundle. The bundle at 'Runner.app/PlugIns/OneSignalNotificationServiceExtension.appex' contains disallowed file 'Frameworks'."

do you guy facing this before ?

**Comment by mvanbeusekom** [comment]
This looks like a different issue. Maybe you can submit a new issue and provide at least the following:

- description of you problem;
- version of the plugin you are using;
- full contents of your Podfile.

**Comment by ChiHwe** [comment]
ok, Thank you,  i will submit a new issue :)
