### ISSUE TITLE
Breaks in V2 embedding in background service

### ISSUE THREAD

**Issue by ened** [Baseflow/flutter-permission-handler#251]
## 🔙 Regression

The plugin currently calls the `startListening` like so:
```
    @Override
    public void onAttachedToActivity(@NonNull ActivityPluginBinding binding) {
        if(flutterPluginBinding == null) {
            return;
        }

        startListening(
                flutterPluginBinding.getApplicationContext(),
                binding.getActivity(),
                flutterPluginBinding.getBinaryMessenger(),
                binding::addActivityResultListener,
                binding::addRequestPermissionsResultListener);
    }
```

However, in a background service, with V2 embedding, this won't ever be called, thus rendering the plugin dysfunctional.

### Old (and correct) behavior

V1 embedding is not affected.

### Reproduction steps

Build a background service, request permission status.

### Configuration

**Version:** 4.4.0.hotfix.2

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

This should be fixed in both a 4.4.0.hotfix.3 version and 5.0.0.hotfix.2

I will prepare a PR as it's urgently needed (against the 4.4.0.hotfix.2 tag).

@mvanbeusekom perhaps you could create a 4.4.0.hotfix.2 branch so two releases can be pushed to pub (should be possible, no?).

**Comment by mvanbeusekom** [comment]
@ened I have pushed a branch called `hotfix/4.4.0` based on the tag `4.4.0+hotfix.2` (I was unable to push a branch called `4.4.0+hotfix.2`).

**Comment by ened** [comment]
@mvanbeusekom opened the PR. There are still issues to be solved in a future version:
 - activity&permission result listeners are added but not removed
 - no v1 testing activity in the example
 - no e2e testing
 - should have deeper NPE checks for activity, activityRegistry and permissionRegistry, but not without tests

**Comment by mvanbeusekom** [comment]
@ened new versions have been released:

- 4.4.0+hotfix.4
- 5.0.0+hotfix.3
