### ISSUE TITLE
 error: cannot find symbol

### ISSUE THREAD

**Issue by klaszlo8207** [Baseflow/flutter-permission-handler#253]
[        ]                                     ^
[        ]   symbol:   variable ACCESS_BACKGROUND_LOCATION
[        ]   location: class permission
[        ] C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-5.0.0+hotfix.3\android\src\main\java\com\baseflow\permissionhandler\PermissionUtils.java:47: error: cannot find symbol
[        ]             case Manifest.permission.BIND_CALL_REDIRECTION_SERVICE:
[   +1 ms]                                     ^
[        ]   symbol:   variable BIND_CALL_REDIRECTION_SERVICE
[        ]   location: class permission
[        ] C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-5.0.0+hotfix.3\android\src\main\java\com\baseflow\permissionhandler\PermissionUtils.java:60: error: cannot find symbol
[   +1 ms]             case Manifest.permission.ACCESS_MEDIA_LOCATION:
[   +1 ms]                                     ^
[        ]   symbol:   variable ACCESS_MEDIA_LOCATION
[        ]   location: class permission
[        ] C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-5.0.0+hotfix.3\android\src\main\java\com\baseflow\permissionhandler\PermissionUtils.java:62: error: cannot find symbol
[   +2 ms]             case Manifest.permission.ACTIVITY_RECOGNITION:
[        ]                                     ^
[        ]   symbol:   variable ACTIVITY_RECOGNITION
[        ]   location: class permission
[        ] C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-5.0.0+hotfix.3\android\src\main\java\com\baseflow\permissionhandler\PermissionUtils.java:97: error: cannot find symbol
[        ]                 if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
[        ]                                                                 ^
[        ]   symbol:   variable Q
[        ]   location: class VERSION_CODES
[        ] C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-5.0.0+hotfix.3\android\src\main\java\com\baseflow\permissionhandler\PermissionUtils.java:98: error: cannot find symbol
[        ]                     if (hasPermissionInManifest(context, permissionNames, Manifest.permission.ACCESS_BACKGROUND_LOCATION))
[        ]                   

I got a lot of red line if I want to build in release mode, android

**Comment by MichelMelhem** [comment]
Same issue @klaszlo8207  did you found a fix ?

**Comment by KohlsAdrian** [comment]
You are using minSdk lower than 29

[Check this manifest additions](https://developer.android.com/reference/android/Manifest.permission#ACCESS_BACKGROUND_LOCATION)

The new permission_handler is using the new Android SDK >=29 features

**Comment by Sempakonka** [comment]
hi @klaszlo8207 
Is your issue resolved using the method described by @KohlsAdrian?
If so, I think this issue can be closed!
