### ISSUE TITLE
Requesting permission stuck on 'await Permission.request()' call

### ISSUE THREAD

**Issue by kami-mehar38** [Baseflow/flutter-permission-handler#255]
## 🐛 Bug Report

I am trying to request storage permission on Android P and the request call keep awaiting and doesn't return the control to the code.
I have debugged it and came to know that it's because of a plugin that i'm using in my project i.e [file_picker].
I have tried removing this file_picker plugin and everything worked fine. 

### Reproduction steps
Just add [file_picker] plugin in your pubspec.yaml file and try requesting permission using [permission_hanlder] plugin.

**Version:** 5.0.0+hotfix.3

**Platform:** 
- [ ] Android

**Comment by mvanbeusekom** [comment]
@kami-mehar38, please have a look and make sure your code is updated to the 1.12 Flutter Android project: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

This looks similar to the issue described here: #245.

You can also find a similar explanation in the [README.md](https://github.com/Baseflow/flutter-permission-handler/blob/develop/permission_handler/README.md) file (under the Android section).

Let me know if this helps.

**Comment by kami-mehar38** [comment]
@mvanbeusekom , **Thanks** for your helpful response and pointing me to the [Upgrading pre 1.12 Android projects
](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects)

**My Mistake:** I came to know that flutter projects have to upgrade prior to 1.12 but didn't bother until now :) 

The Issue is resolved and everything seems to work fine now.

Thanks again and keep developing 👍
