### ISSUE TITLE
Cannot use class PermissionWithService

### ISSUE THREAD

**Issue by bambinoua** [Baseflow/flutter-permission-handler#259]
I cannot use class `PermissionWithService` in the code. VS Code says `The name PermissionWithService isn't defined...` And so I cannot get `statusService` property. I saw the source code and this class is in the same place where `Permission` is, i.e. it is defined! So what is the problem?

Version: 5.0.0+hotfix.3

**Comment by mvanbeusekom** [comment]
@bambinoua there is no class `PermissionWithService`, the idea is that some permissions have a backing service that you can check. In those cases you can access it's status through the extension property on that specific permission's enum value. An example could be `Permission.location.serviceStatus`.

If you just want to get a boolean value you can use the `isEnabled` convenience property like so (snippet is taken from the [README.md](https://github.com/Baseflow/flutter-permission-handler/blob/develop/permission_handler/README.md)):

```
if (await Permission.locationWhenInUse.serviceStatus.isEnabled) {
  // Use location.
}
```

**Comment by bambinoua** [comment]
And what about this example code:
```dart
check(Permission.camera);
...
check(Permission.location);
void check(Persmission permission) {
  Map<PermissionStatus, ServiceStatus> statuses = {};
  PermissionStatus ps = ...; // Get permission status

  if (permission is PermissionWithService) { // <--- !
    ServiceStatus ss = ...; // Get permission service status
  }
  return {ps: ss}
}
```
I understand how to create a workaround now but...  `check` procedure is `interface` method and it does not considered to be dependend on particular `permission`. Maybe in the future other `persmission with service` will appear.

**Comment by JDDV** [comment]
Hi @bambinoua, the explanation provided by mvanbeusekom is correct. The code snippet (with a few adjustments) you provided will work as well and will return a Map of <PermissionStatus, ServiceStatus>.

```
check(Permission.camera);
check(Permission.locationWhenInUse);  //changed locationInUse to locationWhenInUse
check(Permission.locationAlways);
check(Permission.photos);  //changed photo to photos

/// Check the permission and service (if applicable) statuses
Map<PermissionStatus, ServiceStatus> check(Permission permission) {  //changed Persmission in to Permission
  // Get permission status
  PermissionStatus ps = permission.status;
  if (permission is PermissionWithService) { 
    // Get permission service status
    ServiceStatus ss = permission.statusService;
    return {ps: ss}  // Return statement moved in the if-scope, not every Permission has a PermissionWithService where you can ask for the statusService so the return statement outside the if-statement will not work
  }
  return {null : null} // If the permission you're checking is no permission with PermissionWithService return another value here
}
```

The permission who do have a backing service you can check are:

- location
- locationAlways
- locationWhenInUse
- phone
- notification

Please let us know if this does answer your question so we can close the issue, thanks in advance!
