### ISSUE TITLE
Widget testing permissions?

### ISSUE THREAD

**Issue by HerrNiklasRaab** [Baseflow/flutter-permission-handler#262]
Hi, i just wanted to ask, how can i test permission request in widget tests?

For example this one:

``` dart
               ColoredButton(
                  text: loc.locationPermissionMissingButtonText,
                  isPrimary: false,
                  onTap: () async {
                    if (await Permission.location.isPermanentlyDenied)
                      await openAppSettings();
                    else
                      _bikeBloc.add(StartScanEvent());
                  },
                )
```

How would i write a widget test for this, can I mock out Permission in some way?

**Comment by duongtruong12** [comment]
Add this method channel below to yourtest.dart. 
"2" is the permission for me here is Contacts permission, and "1" is permission granted, in case you want to test isPermanentlyDenied it will be "4".

```  const MethodChannel('flutter.baseflow.com/permissions/methods')
        .setMockMethodCallHandler((MethodCall methodCall) async {
        return <dynamic, dynamic>{
          2: 1,
        }; // set initial values here if desired
    });```

**Comment by data987** [comment]
I have the same issue when I'm going to find an expected widget with all the contact's phone, the test fails, I suppose that I have to get the permissions granted but I tried the @duongtruong12 solution and doesn't work

**Comment by elvisun** [comment]
@duongtruong12 's solution worked for me, thanks! I'll only add that you can use `.value` for better readability:

```
          const MethodChannel('flutter.baseflow.com/permissions/methods')
              .setMockMethodCallHandler((MethodCall methodCall) async {
            return <int, int>{
              PermissionGroup.camera.value: PermissionStatus.denied.value,
            }; // set initial values here if desired
          });
```

**Comment by elvisun** [comment]
Update, if you are on `5.0.1+`, you need to set permission individually.
```
          const MethodChannel('flutter.baseflow.com/permissions/methods')
              .setMockMethodCallHandler((MethodCall methodCall) async {
            return PermissionStatus.denied.index;
          });
```

**Comment by flutter-clutter** [comment]
I extended your example @elvisun. The method `_setupPermissions()` expects a Map with Permissions as key and the status (granted, denied, ...) as value.
It then sets up a mock that reacts according to the map on `requestPermissions` and `checkPermissionStatus`. This way, I only need to define the currently granted or denied permissions once (every undefined permission returns `undetermined`) and have no need to duplicate the code.

```
  Set<int> askedPermissions = {};

  void _setupPermissions(Map<int, int> permissions) {
    MethodChannel('flutter.baseflow.com/permissions/methods')
        .setMockMethodCallHandler((MethodCall methodCall) async {
      switch (methodCall.method) {
        case 'requestPermissions':
          return permissions;
        case 'checkPermissionStatus':
          int askedPermission = methodCall.arguments;
          askedPermissions.add(askedPermission);
          for (MapEntry<int, int> permissionKey in permissions.entries) {
            if (permissionKey.key == methodCall.arguments) {
              return permissionKey.value;
            }
          }
          return PermissionStatus.undetermined;
      }
    });
  }
```

If I want to test for instance if a permission popup shows up, I can just check this:

```
  expect(askedPermissions.contains(Permission.camera.value), true);
```

If I want to test if the Widget behaves correctly when a certain permission is denied, I can do it as follows:
```
    _setupPermissions(
      <int, int> {
        Permission.camera.value: PermissionStatus.denied.index,
      }
    );

    expect(find.text('Camera permission denied'), findsOneWidget);
```

**Comment by Sempakonka** [comment]
Hi @HerrNiklasRaab 
Is this issue resolved using the methods provided by the responses?
If so, I think this issue can be closed!

**Comment by Sempakonka** [comment]
closing the ticket.
If you have any follow-up, don't hestitate to re-open.

**Comment by lukepighetti** [comment]
My recommendation is to wrap the functionality so you can mock it. I have personally found stimulating platform channels to be super flakey and they end up testing an implementation detail in the package. The testing boundary is too deep.

```dart
import 'package:permission_handler/permission_handler.dart';
import 'package:permission_handler/permission_handler.dart' as permissionHandler
    show openAppSettings;

class PermissionsService {
  /// Check the status of a specific [Permission]
  Future<PermissionStatus> status(Permission permission) {
    return permission.status;
  }

  /// Open the app settings.
  Future<bool> openAppSettings() {
    return permissionHandler.openAppSettings();
  }

  /// Request permissions for a single permission.
  Future<PermissionStatus> request(Permission permission) {
    return permission.request();
  }
}

```
