### ISSUE TITLE
IOS Photos permissions have always been unknown

### ISSUE THREAD

**Issue by mulieli** [Baseflow/flutter-permission-handler#263]
<img width="966" alt="WeChatc043e0063c34c0f70820e6aa6317113a" src="https://user-images.githubusercontent.com/24307960/79035341-1ef59580-7bf0-11ea-9bfc-d35600e0f4a3.png">
<img width="422" alt="WeChatbceddf35a0674e759fcf8b0a051e9ec0" src="https://user-images.githubusercontent.com/24307960/79035351-2f0d7500-7bf0-11ea-8e2e-df1bb4849bb7.png">
And my phone permissions are turned on

**Comment by mvanbeusekom** [comment]
@mulieli did you add the required information to the `Info.plist` file?

In case of Photos you will need to add the following entry to the `ios/Runner/Info.plist` file:

```
    <!-- Permission options for the `photos` group -->
    <key>NSPhotoLibraryUsageDescription</key>
    <string>{explain why your app need access to the photo library}</string>
```

If you did this then please provide more information:
- Version of the plugin
- Contents of the `Info.plist`
- Output of `flutter doctor -v` command

Even better would be if you could supply a small example app that reproduces the problem.
