### ISSUE TITLE
Flutter permissions handler doesn't allow to run lines bellow

### ISSUE THREAD

**Issue by israelmarmar** [Baseflow/flutter-permission-handler#264]
I am trying to make a request of a permission for camera, but Permission.camera.request() doesn't return result and it doesn't allow to run the bellow lines on Android.

Flutter version v1.12.13+hotfix.5
```
Future<bool> _requestPermission() async {

if(resultReq==null)
resultReq = await Permission.camera.request();

print("it works!");

if (resultReq.isGranted) {
  return true;
}
return false;
}


```

**Comment by mvanbeusekom** [comment]
Please next time provide a little bit more information (mainly about the platform you are running on). If you are running on Android, please make sure your app is migrated to post 1.12 Flutter template. You can find instructions here in the [README.md](https://github.com/Baseflow/flutter-permission-handler/blob/develop/permission_handler/README.md). You could also have a look at these issues: #255 and #245.

Please let us know if this helps.

**Comment by Sempakonka** [comment]
Closing this issue due to no response.
But don't hestitate to re-open if needed!
