### ISSUE TITLE
iOS remove of permissions

### ISSUE THREAD

**Issue by danysz** [Baseflow/flutter-permission-handler#268]
## 🔙 Regression

Now we need to "remove" the permissions we don't need in iOS using the `Pod` file. The problem with that is that the `Pod` file for iOS in Flutter projects is not a file which "have" to be stored in the version control.
The `Pod` file is automatically recreated and update when the iOS version is build. Also Flutter team suggest for some issues 

> "remove the `Pod` file"

 as a solution.
**Version:** 5.x

I suggest to have an "external" configuration file which should be stored or something else and not the `Pod` file

**Platform:** 
- [x] :iphone: iOS

**Comment by mvanbeusekom** [comment]
Hi @danysz, at the moment I am not very familiar with the Xcode build configuration. The code you need to add to the podfile ensures that before the iOS code is compiled some macros will be set, which in turn make sure certain parts of the code base is not compiled and thus omitted from the final binary.

I am not sure how we could accomplish this using a external configuration file. There needs to be a hook into the compile process and be able to turn on these macros. If you have any suggestions please let me know. 

Second I am a bit surprised be your statement the Flutter would suggest to remove the `Podfile` file. Do you have any examples of this? I know that sometimes it is suggested to delete the `Podfile.lock` file but never really the `Podfile` it self.

**Comment by MichaelM97** [comment]
> Hi @danysz, at the moment I am not very familiar with the Xcode build configuration. The code you need to add to the podfile ensures that before the iOS code is compiled some macros will be set, which in turn make sure certain parts of the code base is not compiled and thus omitted from the final binary.
> 
> I am not sure how we could accomplish this using a external configuration file. There needs to be a hook into the compile process and be able to turn on these macros. If you have any suggestions please let me know.
> 
> Second I am a bit surprised be your statement the Flutter would suggest to remove the `Podfile` file. Do you have any examples of this? I know that sometimes it is suggested to delete the `Podfile.lock` file but never really the `Podfile` it self.

This could be achieved by using a Build Phase Run Script, for example, I currently use one to switch which `GoogleService-Info.plist` to use depending on which Firebase environment the app should point at, which is done pre-compilation.

<img width="869" alt="Screenshot 2020-05-02 at 16 58 55" src="https://user-images.githubusercontent.com/22373058/80869123-607cdc00-8c96-11ea-92c2-ab9a52eb9109.png">

**Comment by mvanbeusekom** [comment]
Hi @MichaelM97, thank you for offering a suggestion. Would you be able to give me some information on how I would write such a script? Maybe you could point me to some resource?

**Comment by MichaelM97** [comment]
> Hi @MichaelM97, thank you for offering a suggestion. Would you be able to give me some information on how I would write such a script? Maybe you could point me to some resources?
> 
> I am not familiar with Xcode build system so any information which would help me to understand this would be appreciated and I will try to create such a script.

There's a decent guide on how to create a script [here](https://www.mokacoding.com/blog/better-build-phase-scripts/)

I've been trying to create one for this purpose, however, I'm having issues creating a reference to `GCC_PREPROCESSOR_DEFINITIONS`. 

Flutter has a run script at `$FLUTTER_ROOT/packages/flutter_tools/bin/xcode_backend.sh` which references `ENABLE_BITCODE` in the image below, but I can't seem to modify `GCC_PREPROCESSOR_DEFINITIONS` by referencing it in this way.

<img width="423" alt="Screenshot 2020-05-03 at 12 41 59" src="https://user-images.githubusercontent.com/22373058/80913354-e30ba700-8d3b-11ea-95ee-138cc54b8a98.png">

I will have to take a look at this again later today

**Comment by MichaelM97** [comment]
@mvanbeusekom A simpler alternative to a Build Phase may just be adding these exclusions to all defined schema in `XCode` -> `Runner` -> `Build Settings`. I definitley think that the `PodFile` approach is simpler, but this is an alternative for those that need it (like @danysz).

Below is a screenshot showing where these would be added for an app that has a `dev` and `production` build flavour. As most will have no build flavours setup, they would just need to add the exclusions to `Debug`, `Profile`, and `Release`. (Note that you can search for `GCC_PREPROCESSOR_DEFINITIONS` to make finding this setting easier)

<img width="860" alt="Screenshot 2020-05-03 at 15 30 01" src="https://user-images.githubusercontent.com/22373058/80916846-32110680-8d53-11ea-8517-86bc8e9ef5f0.png">

That method is a little time consuming as you can't copy and paste, so you could just search through `PROJECT/ios/Runner.xcodeproj/project.pbxproj` for all instances of `GCC_PREPROCESSOR_DEFINITIONS` and update them there.

<img width="464" alt="Screenshot 2020-05-03 at 15 38 21" src="https://user-images.githubusercontent.com/22373058/80917041-5c16f880-8d54-11ea-9a68-499e74845cb6.png">

**Comment by djmuhlestein** [comment]
This isn't working for me to add GCC_PREPROCESSING_DEFINITIONS to the Target or the Project.  Either way, the pod is still being compiled without those macros.  If I edit the pods xcconfig file instead (permission_handler.release.xcconfig), the settings will be applied.  That isn't preferable though of course since that is generated.  I seem to be missing the proper way to get the pod to be compiled with my custom preprocessor definitions.

**Comment by orestesgaolin** [comment]
Same as @djmuhlestein adding GCC_PREPROCESSING_DEFINITIONS in iOS project doesn't work for me. I cannot add them to my Pods project as it's regenerated every time.

**Comment by ahmedqais6** [comment]
same here in GCC_PREPROCESSING_DEFINITIONS

**Comment by TimHoogstrate** [comment]
It seems that this issue has been resolved. Feel free to reopen or create a new issue when new information pops-up. Don't forget to place the output of `flutter doctor -v` and some minimal reproducible code or steps to reproduce in that issue.

Kind regards,
