### ISSUE TITLE
Fix package documentation links

### ISSUE THREAD

**Issue by kallaspriit** [Baseflow/flutter-permission-handler#272]
Several links in the [package documentation page](https://pub.dev/packages/permission_handler) are broken.

- [Here](https://github.com/Baseflow/flutter-permission-handler/blob/develop/example/ios/Runner/Info.plist)'s an example Info.plist with a complete list of all possible permissions
- The permission_handler plugin use [macros](https://github.com/BaseflowIT/flutter-permission-handler/blob/develop/ios/Classes/PermissionHandlerEnums.h) to control whether a permission is supported.
- By default, all the permissions listed [here](https://github.com/Baseflow/flutter-permission-handler#list-of-available-permissions) are supported.
- There are a number of [Permission](https://pub.dev/documentation/permission_handler_platform_interface/latest/permission_handler_platform_interface/PermissionGroup-class.html)s.

Copied the texts as they are in the documentation and all the links above don't point at the right places.

**Comment by mvanbeusekom** [comment]
@kallaspriit thank you for reporting this issue, the links have been fixed in the `develop` branch. The correct documentation can be found [here](https://github.com/Baseflow/flutter-permission-handler/blob/develop/permission_handler/README.md).
