### ISSUE TITLE
Camera usage description is required when only using microphone

### ISSUE THREAD

**Issue by kallaspriit** [Baseflow/flutter-permission-handler#273]
## 🐛 Bug Report

When the only permission not disabled is `PERMISSION_MICROPHONE`, Apple says that NSCameraUsageDescription is missing.

> ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSCameraUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).

### Expected behavior

Only `NSMicrophoneUsageDescription` should be required but Apple still requests `NSCameraUsageDescription` as well.

### Reproduction steps

Configure project with Podfile `post_install` section of

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'

      # You can remove unused permissions here
      # for more infomation: https://github.com/BaseflowIT/flutter-permission-handler/blob/develop/ios/Classes/PermissionHandlerEnums.h
      # e.g. when you don't need camera permission, just add 'PERMISSION_CAMERA=0'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',

        # dart: PermissionGroup.calendar
        'PERMISSION_EVENTS=0',

        # dart: PermissionGroup.reminders
        'PERMISSION_REMINDERS=0',

        # dart: PermissionGroup.contacts
        'PERMISSION_CONTACTS=0',

        # dart: PermissionGroup.camera
        'PERMISSION_CAMERA=0',

        # dart: PermissionGroup.microphone
        # 'PERMISSION_MICROPHONE=0',

        # dart: PermissionGroup.speech
        'PERMISSION_SPEECH_RECOGNIZER=0',

        # dart: PermissionGroup.photos
        'PERMISSION_PHOTOS=0',

        # dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
        'PERMISSION_LOCATION=0',

        # dart: PermissionGroup.notification
        'PERMISSION_NOTIFICATIONS=0',

        # dart: PermissionGroup.mediaLibrary
        'PERMISSION_MEDIA_LIBRARY=0',

        # dart: PermissionGroup.sensors
        'PERMISSION_SENSORS=0'
      ]
    end
  end
end
```

### Configuration

**Version:** ^5.0.0+hotfix.4

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by SudoSharma** [comment]
I see this is still open - @kallaspriit were you able to figure something out, or did you end up just adding NSCameraUsageDescription in Info.plist?

**Comment by JeroenWeener** [comment]
Hi @kallaspriit, thank you for reaching out with your issue!

This issue has been open for 3+ years, of which almost 3 years without comments. The plugin has had substantial changes in these years. Therefore, we will close this issue for now.

If anyone encounters this issue on the latest version of the plugin, please let us know by commenting here. We can reopen the issue and investigate.
