### ISSUE TITLE
After hotfix.7 update , Permission handler is not working

### ISSUE THREAD

**Issue by saravananmnm** [Baseflow/flutter-permission-handler#274]
permission_handler: ^5.0.0+hotfix.2

[√] Flutter (Channel stable, v1.12.13+hotfix.7, on Microsoft Windows [Version 10.0.18362.778], locale en-IN)
    • Flutter version 1.12.13+hotfix.7 at C:\Saravanan\Flutter_Sdk\flutter
    • Framework revision 9f5ff2306b (3 months ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Admin\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.2
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] Connected device (1 available)
    • Genymotion • 192.168.215.101:5555 • android-x86 • Android 9 (API 28)

! Doctor found issues in 1 category.
Process finished with exit code 0

**Comment by saravananmnm** [comment]
`class LocationSwitch extends StatefulWidget {
  CustomLocationUpdates customLocationUpdates;

  LocationSwitch({this.customLocationUpdates});

  @override
  _CustomSwitchState createState() => _CustomSwitchState();
}

class _CustomSwitchState extends State<LocationSwitch> {
  var switchStatus = new BehaviorSubject<bool>();
  Permission permission = Permission.location;
  PermissionStatus permissionStatus = PermissionStatus.undetermined;
  int stopRecursion;

  @override
  void initState() {
    super.initState();
    getStatus(true);
    // WidgetsBinding.instance.addObserver(this);
  }

  @override
  Widget build(BuildContext context) {
    return StreamBuilder(
        initialData: false,
        stream: switchStatus.stream,
        builder: (context, snapShot) {
          if (snapShot.data) {
            startLocationUpdates();
          } else {
            stopLocationUpdates();
          }
          return Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              getStatusText(snapShot.data),
              getStatusSwitch(snapShot.data)
            ],
          );
        });
  }

  Widget getStatusText(bool status) {
    return Container(
      alignment: Alignment.center,
      child: Text(
        status ? StringConstant.Available : StringConstant.Offline,
        style: TextStyle(
            fontSize: 18.0,
            color:
                status ? ColourConstant.COLOR_BLUE : ColourConstant.COLOR_GREY),
      ),
    );
  }

  Widget getStatusSwitch(bool status) {
    return Container(
      child: Switch.adaptive(
          value: status,
          onChanged: (val) {
            getStatus(val);
          }),
    );
  }

  void getStatus(bool val) async {
    stopRecursion = 0;
    permissionStatus = await permission.status;
    statusChange(false);
    if (val) {
      if (!permissionStatus.isGranted) {
        if (await handlePermission(permissionStatus)) {
          if (await checkGPSStatus()) {
            statusChange(true);
          } else {
            statusChange(false);
            enableGPS();
          }
        } else {
          statusChange(false);
        }
      } else {
        if (await checkGPSStatus()) {
          statusChange(true);
        } else {
          statusChange(false);
          enableGPS();
        }
      }
    } else {
      statusChange(false);
    }
  }

  void statusChange(bool val) {
    switchStatus.sink.add(val);
  }

  void listenForPermissionStatus() async {
    stopRecursion = 0;
    permissionStatus = await permission.status;
    statusChange(false);
    if (!permissionStatus.isGranted) {
      if (await handlePermission(permissionStatus)) {
        if (await checkGPSStatus()) {
          statusChange(true);
        } else {
          statusChange(false);
          enableGPS();
        }
      } else {
        statusChange(false);
      }
    } else {
      if (await checkGPSStatus()) {
        statusChange(true);
      } else {
        statusChange(await handlePermission(permissionStatus));
        enableGPS();
      }
    }
  }

  Future<bool> requestPermission(Permission permission) async {
    permissionStatus = await permission.request();
    return permissionStatus.isGranted;
  }

  Future<bool> checkGPSStatus() async {
    var enable = await new Geolocator().isLocationServiceEnabled();
    return enable;
  }

  void enableGPS() {
    CustomAlerts.showAlertWithOkCancel(
        context,
        "Please turn on the location so we can offer you more orders",
        "Ok",
        "Cancel",
        null, () async {
      await Utils.openLocationSettings();
    }, () {
      clickCancel();
    });
  }

  void clickCancel() {
    statusChange(false);
  }

  Future<bool> checkGPSEnabled() async {
    bool result = false;
    result = await new Geolocator().isLocationServiceEnabled();
    return result;
  }

  Future<bool> handlePermission(PermissionStatus status) async {
    bool result;
    if (permissionStatus.isDenied && stopRecursion == 3) {
      result = false;
    } else {
      switch (status) {
        case PermissionStatus.undetermined:
          result = false;
          break;
        case PermissionStatus.denied:
          stopRecursion++;
          result = await requestPermission(permission);
          break;
        case PermissionStatus.granted:
          result = permissionStatus.isGranted;
          break;
        default:
          result = false;
      }
    }
    return result;
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) async {
    if (state == AppLifecycleState.resumed) {
      statusChange(await checkGPSStatus() && permissionStatus.isGranted);
    } else if (state == AppLifecycleState.detached) {
      print('App is destroyed..');
    }
  }

  void startLocationUpdates() async {
    await widget.customLocationUpdates.startLocationUpdates();
  }

  void stopLocationUpdates() async {
    await widget.customLocationUpdates.stopLocationUpdates();
  }
}`

**Comment by mvanbeusekom** [comment]
@saravananmnm please make sure your Flutter project is updated to support the latest Android plugin APIs. Here are the instructions from the `README.md` file:

>Upgrade pre 1.12 Android projects
>
>Since version 4.4.0 this plugin is implemented using the Flutter 1.12 Android plugin APIs. Unfortunately this means App developers also need to migrate their Apps to support the new Android infrastructure. You can do so by following the [Upgrading pre 1.12 Android projects migration guide](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects). Failing to do so might result in unexpected behaviour. Most common known error is the permission_handler not returning after calling the .request() method on a permission.

**Comment by saravananmnm** [comment]
i have used only stable versions

**Comment by mvanbeusekom** [comment]
Sorry not sure what you mean? You mentioned that you have upgraded to Flutter v1.12.13+hotfix.7. This means that if you want to use the `permission_handler 4.4.0 and higher` you will also need to make sure your Flutter project needs to be migrated as mentioned in my previous comment.

**Comment by saravananmnm** [comment]
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18362.778], locale en-IN)
    • Flutter version 1.12.13+hotfix.9 at C:\Saravanan\Flutter_Sdk\flutter
    • Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

**Comment by saravananmnm** [comment]
permission_handler 4.4.0

I have used above version for permission handler. But still it is not working properly, And i have upgraded by clicking Flutter upgrade from tools menu.

**Comment by saravananmnm** [comment]
Upgrade pre 1.12 
Am not getting what version you mentioned.

**Comment by mvanbeusekom** [comment]
You will have to upgrade your project as mentioned in this migration guide: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

The thing is that you created your project with an earlier version of Flutter. If you want to use Flutter 1.12.x to its full extend you will also need to manually upgrade some of you project files (simply hitting the Flutter upgrade button only update the Flutter runtime but not your projects source code)

**Comment by saravananmnm** [comment]
if follow that upgrade. 
What will happen below libraries. will it impact?


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  package_info: ^0.4.0+3
  http: ^0.12.0+1
  kiwi: ^0.1.0
  rxdart: ^0.20.0
  shared_preferences: ^0.5.7
  sembast: ^2.0.1+2
  fluttertoast:
  font_awesome_flutter: ^8.8.1
  jaguar_serializer:
  device_info: ^0.4.0+2
  imei_plugin: ^1.1.4
  permission_handler: ^5.0.0
  jaguar_retrofit: ^2.8.8
  loadmore: ^1.0.3
  url_launcher: ^5.1.3
  intl:
  tree_view:
  flutter_google_places:
  google_maps_webservice:
  geolocator:
  google_maps_flutter: ^0.5.21+2
  flutter_local_notifications: ^1.4.1
  firebase_messaging:
  signature: ^2.0.0
  path_provider: ^1.3.0
  image_picker: ^0.6.1+4
  flutter_map: ^0.7.2
  flutter_native_timezone: ^1.0.4
  image:
  flutter_polyline_points: ^0.1.0
  path: ^1.6.4
  app_settings: ^3.0.1

dev_dependencies:
  build_runner:
  jaguar_retrofit_gen:
  jaguar_serializer_cli:
  flutter_test:
    sdk: flutter

**Comment by saravananmnm** [comment]
these lib's i have used my projects.That's y asking

**Comment by mvanbeusekom** [comment]
Theoretically it should all keep working. But I am not familiar with all plug-ins so no guarantees (btw the migration guide is written by Flutter not by us).

So I am assuming you are using version control so I suggest to make a separate branch and do the migration and give it a test run. When it fails no harm is done (simply switch back to the original branch). If all is good merge your changes.

When you are not using version control, make a copy of your project so you can fallback to it.

**Comment by mvanbeusekom** [comment]
You can also have a look at these issues #245 and #255 which shows other users successfully migrated.
