### ISSUE TITLE
Request write permission for SD Card

### ISSUE THREAD

**Issue by jinyus** [Baseflow/flutter-permission-handler#275]
I am trying to write data to the SD card for android but it seems that PermissionGroup.storage only request permission for internal storage. Is what I'm trying to do possible?

This is the my code for requesting permission:
```
Future<bool> _checkPermission() async {
    PermissionStatus permission = await Permission.storage.status;
    if (permission == PermissionStatus.granted) {
      return true;
    } else if (permission == PermissionStatus.denied) {
      return false;
    } else if (await Permission.storage.request().isGranted) {
      return true;
    } else {
      return false;
    }
  }
```

And this is the error I get when I try to create a folder on the sd card.
PS: This works for internal storage

```
Unhandled Exception: FileSystemException: Creation failed, path = '/storage/1EFF-130C/Music/2020' (OS Error: Permission denied, errno = 13)
```

**Comment by mvanbeusekom** [comment]
@jinyus the exception you receive seems not related to the user consent (which is what the permission_handler plugin is all about), but more a problem with actual data access permissions to the location on disk. I am not an expert on writing files to the SD card but there are a few things you could check:
1. Make the SD card is not write protected (if I am correct all cards have a little switch on them that makes them write protected);
2. If this problem occurs on Android 10 you could try adding the `android:requestLegacyExternalStorage="true"` attribute to the `<application>` element of your `AndroidManifest.xml` file (more info [here](https://github.com/miguelpruivo/flutter_file_picker/issues/169)).

Hope this helps.

**Comment by jinyus** [comment]
After doing some testing, I think that I only have write permission for the app's directory on the SD card because I was able to write to it. Thanks for you input.

**Comment by violet-dev** [comment]
Isn't there a write permission to a folder other than the app' directory?
All directories on sdcard have rwxr-x--- permissions, but the app doesn't seem to have write permissions.
How can I give write permission to a directory other than the app directory?
