### ISSUE TITLE
Being able to request access to a protected permission

### ISSUE THREAD

**Issue by joanofdart** [Baseflow/flutter-permission-handler#279]
## 🚀 Feature Requests

There should be a way to request permission to a protected resource, like for example the UsageStatsManager

### Contextualize the feature
As a permission handler, there should be an option to extend the base line and request more permissions available.

### Describe the feature
Continuing the example, one should just be able to pass an extra argument for any feature and request access to it.

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [X] :robot: Android

**Comment by shinriyo** [comment]
```
final PermissionStatus status = await Permission.notification.request();
```

it never popup in Android.

**Comment by Sempakonka** [comment]
Hi @joanofdart 
I think Baseflow would love to see a PR coming!
@shinriyo, I'm not sure what you mean by that, and possibly what it has to do with this issue. Could you explain?

**Comment by JDDV** [comment]
Hi @joanofdart, this feature request is a bit unclear, it sounds like you want to see more permissions, but not specific ones. You can always make a new feature request where you request a certain permission so it can be added in the permission handler! This issue will be closed, but we would love to see feature request coming about specific permissions!
