### ISSUE TITLE
How can I "override" NSBluetoothAlwaysUsageDescription somehow on iOS?

### ISSUE THREAD

**Issue by MrHazee** [Baseflow/flutter-permission-handler#290]
Hi,

I am trying to catch NSBluetoothAlwaysUsageDescription and NSBluetoothPeripheralUsageDescription, can I somehow achieve that with this awesome plugin?

Thanks 
/Rasmus

**Comment by mvanbeusekom** [comment]
@MrHazee thank you for the compliments.

What exactly are you trying to achieve?

If you simply want to change or update the text that is displayed in the permission dialog, your should probably want to edit the `Info.plist` (or `InfoPlist.string` files for multilingual apps).

If you like to read read the description text from the `Info.plist` file (or `InfoPlist.string` files) and get it send back to your Dart code. Then I am sorry to say this plugin cannot help you at the moment (it might be interesting to build a feature for it).

**Comment by dprophete** [comment]
I am trying to get a bluetooth permission popup as well, like this:
![image](https://user-images.githubusercontent.com/518393/83161339-9c298b00-a108-11ea-8088-12bb46330bab.png)

but somehow I can't see it in the list of permissions:

```
  static const List<Permission> values = <Permission>[
    calendar,
    camera,
    contacts,
    location,
    locationAlways,
    locationWhenInUse,
    mediaLibrary,
    microphone,
    phone,
    photos,
    reminders,
    sensors,
    sms,
    speech,
    storage,
    ignoreBatteryOptimizations,
    notification,
    accessMediaLocation,
    activityRecognition,
    unknown,
  ];
```

Am I missing something ? @mvanbeusekom @MrHazee

**Comment by MrHazee** [comment]
Thanks for your reply and Im sorry for the late reply back @mvanbeusekom !
@dprophete made my problem really clear, thanks! That is exactly what Im trying to achieve.
I am aware that Bluetooth permissions also goes under Location-permissions, but at least iOS need explicit bluetooth permission, i.e NSBluetoothAlwaysUsageDescription and NSBluetoothPeripheralUsageDescription in info.plist.
Please let me know of I need to elaborate my problem more.
Thanks

**Comment by MrHazee** [comment]
@dprophete did you find a solution to the matter? 
Thanks

**Comment by JDDV** [comment]
@MrHazee, are you still having this issue?
Support for bluetooth permissions is added now in the newest version of the permission handler, can you please let us know if this solved your problem. thanks in advance!

**Comment by MrHazee** [comment]
I did a workaround at the time and now Im in other projects. But I sure will get back to you if I try it out. Thanks for letting me know

**Comment by JeroenWeener** [comment]
Closing this issue as this seems to be fixed in newer versions of the permission handler. If you are still experiencing this issue, please let us know by opening a new issue, mentioning this one.
