### ISSUE TITLE
flutter-permission-handler not working for android 6 and 5 devices  

### ISSUE THREAD

**Issue by kw2019ltd** [Baseflow/flutter-permission-handler#292]
hi, 

iam using flutter-permission-handler and its working just fine , i have only issue in android 6 and 5 where users getting below error

note i have WRITE_EXTERNAL_STORAGE/READ_EXTERNAL_STORAGE in my AndroidManifest.xml.

as isaid its working fine but not on android 6 and 5.

Non-fatal Exception: java.lang.Exception:     

    Try to add thes lines to your AndroidManifest.xml file

          **`<uses-permission android:name='android.permission.WRITE_EXTERNAL_STORAGE'/>`
          `<uses-permission android:name='android.permission.READ_EXTERNAL_STORAGE'/>`**

    and grant storage permissions to your applicaion from app settings
    

```
FileSystemException: Directory listing failed, path = '/storage/emulated/0/Download/' (OS Error: No such file or directory, errno = 2)
       at FileManager.dirsTree(file_manager.dart:110)
       at FileManager.filesTree(file_manager.dart:132)
       at FileManager.recentFilesAndDirs(file_manager.dart:42)
       at _VideoDownloadPageState._initFiles(video_page.dart:106)
       at _VideoDownloadPageState._initFilesAfterGrantPermission(video_page.dart:99)
       at _VideoDownloadPageState.initDownloadsDirectoryState(video_page.dart:58)
```

![image](https://user-images.githubusercontent.com/47334522/82129631-e5a2dd80-97cc-11ea-8670-158544c78eb1.png)

**Comment by ened** [comment]
@kw2019ltd please share the permission_handler version you have been using in the App.

**Comment by kw2019ltd** [comment]
hi i am using 5.0.0+hotfix.5

**Comment by mvanbeusekom** [comment]
@kw2019ltd do you get the permission dialog at all when requesting permissions? And do you know if permissions are granted? 

I noticed you attached a screenshot from (I assume) Google Analytics which indicates this error occurs. Could it be that permissions are denied and the users are still somehow able to access the filesystem?

**Comment by kw2019ltd** [comment]
> 
> 
> @kw2019ltd do you get the permission dialog at all when requesting permissions? And do you know if permissions are granted?
> 
> I noticed you attached a screenshot from (I assume) Google Analytics which indicates this error occurs. Could it be that permissions are denied and the users are still somehow able to access the filesystem?

hi hard to tell according to the code its requesting permission if permission granted then code is accessing filesystem. 

as i told its only occurred on android 5 and 6 most users its working fine with android 7+.

**Comment by bidex160** [comment]
Hi, same issue Here no permission dialog comes up on real TV but works on emulator tv
