### ISSUE TITLE
Permission Dialog with Custom locale

### ISSUE THREAD

**Issue by payam-zahedi** [Baseflow/flutter-permission-handler#298]
My problem is when I request a Permission in android the incoming dialog is adapted with system current locale and language. I need an English dialog always. if it is possible please help me to solve this issue.

**thanks for this awesome package.**

**Comment by mvanbeusekom** [comment]
Hi @payam-zahedi, 

Thank you for your feedback and the compliments, I am very happy you like the package.

As far as I am aware the dialog is fully controlled by the Android sub system and I have no control on which locale should be used when showing the permission dialog. 

One approach you could use is to force the locale for your application to English in your main activity. This article describes in length how this could be accomplished in Android (which should be similar to your Flutter application): https://proandroiddev.com/change-language-programmatically-at-runtime-on-android-5e6bc15c758

**Comment by payam-zahedi** [comment]
thank you @mvanbeusekom,
this is a great Idea I will work on it.
