### ISSUE TITLE
is this permission handle is able to set app as a default dialer

### ISSUE THREAD

**Issue by hssn-hassnain** [Baseflow/flutter-permission-handler#299]
## 🚀 Feature Requests
hi this plugin covers almost all the features. is there a way i can set my app dialer as default by using this plugin since i am using this plugin to get other permissions. or you can help me to get the default dialer permission for a call making. thanks

**Comment by mvanbeusekom** [comment]
Hi @hssn-hassnain, 

Setting your App as default dialer is not a feature that is supported by this plugin. I am not really sure this is something that would fit into this plugin as it is aimed at handling permissions and not updating settings of default applications.

However I am not very familiar with this feature so if you are able to give me details on how one would implement this feature in iOS and Android (i.e. links to the documentation pages) I can do some research to see if this would be something that should be supported by the `permission_handler` plugin.

**Comment by hssn-hassnain** [comment]
Thankyou for the detailed help. Yes as I went to the native code to make it default at Android manifest and adding some permission checkers on start of the app. So basically I want to make a phone call directly through my app instead of opening phone default UI for that I am creating permissions. Maybe you can help me at this. Thankyou
