### ISSUE TITLE
Hi, I have an app that depends on 'android.permission.PACKAGE_USAGE_STATS' package. It looks like the permission for this package is not available currently. Will it be possible for you to add permission for this package?

### ISSUE THREAD

**Issue by gunjchhetri** [Baseflow/flutter-permission-handler#301]
### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by gunjchhetri** [comment]
Hi, I have an app that depends on 'android.permission.PACKAGE_USAGE_STATS' package. It looks like the permission for this package is not available currently. Will it be possible for you to add permission for this package?

**Comment by Sankalpjadhav** [comment]
@gunjchhetri  did you solved this issue?..... I'm also working on the same. If you solved it then please let me know.

**Comment by JDDV** [comment]
Hi @gunjchhetri, @Sankalpjadhav. According to the [documentation](https://developer.android.com/reference/android/app/usage/UsageStatsManager.html) it is not possible to implement the UsageStatsManager permission in the parmission-handler plugin. 

The documentation mentions this:

> NOTE: Most methods on this API require the permission android.permission.PACKAGE_USAGE_STATS. However, declaring the permission implies intention to use the API and the user of the device still needs to grant permission through the Settings application. See Settings.ACTION_USAGE_ACCESS_SETTINGS. Methods which only return the information for the calling package do not require this permission. E.g. getAppStandbyBucket() and queryEventsForSelf(long, long). 

More information can be found [here](https://stackoverflow.com/a/36822181/5167831).
