### ISSUE TITLE
iOS notification permission request does not wait for user answer

### ISSUE THREAD

**Issue by fvisticot** [Baseflow/flutter-permission-handler#304]
## 🐛 Bug Report

final status = await permission.request(); // permission is notification
1. status returns immediately with the status underterminated
2. iOS popup displayed to ask for notification permission
3. User click on Allow

### Expected behavior
permission / notification.request returns grantedStatus regarding user answer Allow / Not allow
### Reproduction steps

final status = await permission.request(); // permission is notification

### Configuration

**Version:** 1.x

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi @fvisticot, thank you for reporting this issue. I have just released a hotfix (version: 5.0.0+hotfix.7) which solves this issue (thanks to @phranck for supplying the fix, see #297).
