### ISSUE TITLE
Support for Draw Over Other Apps permission on android

### ISSUE THREAD

**Issue by awazgyawali** [Baseflow/flutter-permission-handler#306]
## 🚀 Feature Requests

Add support for Draw Over Other Apps permission on android.

### Contextualize the feature
I am using Flutter to develop a calling application(VOIP) and I need that permission to show the calling screen built withing flutter and I wanted to wake the phone up as well as show the caller screen in front of the background state. For this, we need to enable Draw Over Other Apps permission/

### Describe the feature
https://stackoverflow.com/a/59421118/3931968
This should describe the change needed. Not much of a work, I myself am ready to contribute. I just want a green signal for the feature.

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [X] :robot: Android

**Comment by mvanbeusekom** [comment]
@awazgyawali would be awesome if you could add this, looking forward to your PR.

**Comment by awazgyawali** [comment]
@mvanbeusekom Here it is https://github.com/Baseflow/flutter-permission-handler/pull/307

**Comment by JDDV** [comment]
This is added in version 7.1.0 of the permission handler.
