### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method requestPermissions on channel flutter.baseflow.com/permissions/methods)

### ISSUE THREAD

**Issue by RizanPSTU** [Baseflow/flutter-permission-handler#308]
## 🐛 Bug Report

E/flutter (16782): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method requestPermissions on channel flutter.baseflow.com/permissions/methods)

 When I try to run
 
  Future<void> _handleCameraAndMicPermission() async {
    // You can request multiple permissions at once.
    Map<Permission, PermissionStatus> statuses = await [
      Permission.camera,
      Permission.microphone,
    ].request();
    print(statuses[Permission.camera]);
  }

### Expected behavior
There should be popup for camera and microphone permission

### Configuration
Using permission_handler: ^5.0.0+hotfix.8
AndroidX enabled 
android.useAndroidX=true
android.enableJetifier=true

**Platform:** 
- [ ] :iphone: iOS
- [x ] :robot: Android

**Comment by RizanPSTU** [comment]
Used 

flutter clean
flutter run

Still the same error

**Comment by RizanPSTU** [comment]
When I run this 

I also get the same error

https://github.com/Meherdeep/agora-flutter-broadcast

**Comment by TMSantos** [comment]
Also having this, Android only.
Tried:
- brand new android project
- flutter clean
- full clean (delete all cache folders etc)

Same issue.

But if I started brand new project, it works

**Comment by mvanbeusekom** [comment]
@TMSantos, @RizanPSTU, have you updated your App to support AndroidX (see also #87)?

@TMSantos looks like you undid AndroidX when you copied back the Android folder into the newly created project.

Please let me know?

**Comment by TMSantos** [comment]
hey @mvanbeusekom  thanks for replying.
I believe I'm not entirely sure what "converting to androidX" means?

My gradle.properties has indication to use it:
```
org.gradle.jvmargs=-Xmx1536M
android.enableR8=true
android.useAndroidX=true
android.enableJetifier=true

```

But if I try to convert it using Intellij I get this error:
![Screenshot 2020-05-31 at 18 22 50](https://user-images.githubusercontent.com/5798822/83358506-eeb6b180-a36b-11ea-8b6b-6ab55d0e16e5.png)

I think the project is already AndroidX, I don't see any indication to not be, also no differences between your example, or brand new flutter project (which works).

**Comment by TMSantos** [comment]
I fixed it finally, @RizanPSTU my problem was simply because MainActivity was missing:
`GeneratedPluginRegistrant.registerWith(flutterEngine)`

I overrided this method in MainActivity:
`configureFlutterEngine`

It seems that if you override it, you need to explicitly call this method, not sure if it's your case, but adding this line fixed the problem with permission_handler package. 

Other things you can try:
- Migrate to androidX using android Studio
- delete gradle caches
- Good post about this topic: https://stackoverflow.com/questions/50985468/flutter-missingpluginexception-with-several-plugins

Hope you can fix it, this issue is not related to permission_handler project, but to flutter engine.

have a good day

**Comment by RizanPSTU** [comment]
Problem solved :) You are great :)

**Comment by ricrsantos** [comment]
Hi Folks!
I tried a lot of things and any thing working. After long time I discovered the root problem. In my case the problema was conflict between two plugins, Facebook signIn and Permissions. So I cut office the Facebook Plugin and all works!

**Comment by DenisKen** [comment]
I'm having this issue. I just tried to apply all solutions to solve it, but none worked.
The bug happens with Facebook-Sign-in Plugin, but I depend on it.

I've tried to apply **multiDexEnabled true** and change
**minSdkVersion 16** to **minSdkVersion 21**. None worked.

**Comment by r-silver1** [comment]
hey, this fixed it for me... it was a simple issue of not stopping and restarting the application fully after changing gradle settings in my code https://stackoverflow.com/a/54940371/10432596

**Comment by ZaifSenpai** [comment]
> Hi Folks!
> I tried a lot of things and any thing working. After long time I discovered the root problem. In my case the problema was conflict between two plugins, Facebook signIn and Permissions. So I cut office the Facebook Plugin and all works!

Thank you for pointing out the issue. Yes the problem is with [flutter_facebook_auth](https://pub.dev/packages/flutter_facebook_auth) package. My app is having problem with both [google_fonts](https://pub.dev/packages/google_fonts) and [permission_handler](https://pub.dev/packages/permission_handler) packages due to this Facebook package.

I need all of these packages in my app. How can we "isolate" the facebook login package so it does not effect the other packages?

The packages versions I am using:
permission_handler: ^5.0.1+1
shared_preferences: ^0.5.12+4
google_fonts: ^1.1.2

**Comment by aniketsongara** [comment]
> Hi Folks!
> I tried a lot of things and any thing working. After long time I discovered the root problem. In my case the problema was conflict between two plugins, Facebook signIn and Permissions. So I cut office the Facebook Plugin and all works!

In my case problem is occurring due to uses of permission_handler and file_picker plugin in same project.

**Comment by aniketsongara** [comment]
> > Hi Folks!
> > I tried a lot of things and any thing working. After long time I discovered the root problem. In my case the problema was conflict between two plugins, Facebook signIn and Permissions. So I cut office the Facebook Plugin and all works!
> 
> Thank you for pointing out the issue. Yes the problem is with [flutter_facebook_auth](https://pub.dev/packages/flutter_facebook_auth) package. My app is having problem with both [google_fonts](https://pub.dev/packages/google_fonts) and [permission_handler](https://pub.dev/packages/permission_handler) packages due to this Facebook package.
> 
> I need all of these packages in my app. How can we "isolate" the facebook login package so it does not effect the other packages?
> 
> The packages versions I am using:
> permission_handler: ^5.0.1+1
> google_fonts: ^1.1.2
> 
> Edit:
> Having same problem with [flutter_login_facebook](https://pub.dev/packages/flutter_login_facebook)

Did you get any solution of it ?
With same issue I am struggling, I need to have both packages in the app is permission_handler & file_picker

**Comment by ZaifSenpai** [comment]
> > > Hi Folks!
> > > I tried a lot of things and any thing working. After long time I discovered the root problem. In my case the problema was conflict between two plugins, Facebook signIn and Permissions. So I cut office the Facebook Plugin and all works!
> > 
> > 
> > Thank you for pointing out the issue. Yes the problem is with [flutter_facebook_auth](https://pub.dev/packages/flutter_facebook_auth) package. My app is having problem with both [google_fonts](https://pub.dev/packages/google_fonts) and [permission_handler](https://pub.dev/packages/permission_handler) packages due to this Facebook package.
> > I need all of these packages in my app. How can we "isolate" the facebook login package so it does not effect the other packages?
> > The packages versions I am using:
> > permission_handler: ^5.0.1+1
> > google_fonts: ^1.1.2
> > Edit:
> > Having same problem with [flutter_login_facebook](https://pub.dev/packages/flutter_login_facebook)
> 
> Did you get any solution of it ?
> With same issue I am struggling, I need to have both packages in the app is permission_handler & file_picker

I have not tried this solution yet, but the developer of [flutter-facebook-auth](https://github.com/darwin-morocho/flutter-facebook-auth) posted this in their:
[darwin-morocho comment on Issue #48](https://github.com/darwin-morocho/flutter-facebook-auth/issues/48#issuecomment-788944092)

**Comment by aniketsongara** [comment]
> > > > Hi Folks!
> > > > I tried a lot of things and any thing working. After long time I discovered the root problem. In my case the problema was conflict between two plugins, Facebook signIn and Permissions. So I cut office the Facebook Plugin and all works!
> > > 
> > > 
> > > Thank you for pointing out the issue. Yes the problem is with [flutter_facebook_auth](https://pub.dev/packages/flutter_facebook_auth) package. My app is having problem with both [google_fonts](https://pub.dev/packages/google_fonts) and [permission_handler](https://pub.dev/packages/permission_handler) packages due to this Facebook package.
> > > I need all of these packages in my app. How can we "isolate" the facebook login package so it does not effect the other packages?
> > > The packages versions I am using:
> > > permission_handler: ^5.0.1+1
> > > google_fonts: ^1.1.2
> > > Edit:
> > > Having same problem with [flutter_login_facebook](https://pub.dev/packages/flutter_login_facebook)
> > 
> > 
> > Did you get any solution of it ?
> > With same issue I am struggling, I need to have both packages in the app is permission_handler & file_picker
> 
> I have not tried this solution yet, but the developer of [flutter-facebook-auth](https://github.com/darwin-morocho/flutter-facebook-auth) posted this in their:
> [darwin-morocho comment on Issue #48](https://github.com/darwin-morocho/flutter-facebook-auth/issues/48#issuecomment-788944092)

Thanks you for your response but it is not useful in my case I am getting same [darwin-morocho comment on Issue #48](https://github.com/darwin-morocho/flutter-facebook-auth/issues/48#issuecomment-788944092) 
with
pubspec.yaml

```
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  file_picker: ^2.1.6
  permission_handler: ^5.1.0+2
```

**Comment by aniketsongara** [comment]
Issues resolved by adding this

> buildTypes {
>        release {
>            shrinkResources false
>            minifyEnabled false
>            signingConfig signingConfigs.release
>        }
>    }

in `android/app/build.gradle`

**Comment by Sheharyar566** [comment]
Any progress on this? My issue relates to permission_handler and image_picker plugin

**Comment by eademir** [comment]
I have similar situation. I am using agora video call in my app and I need microphone and camera permissions. it's working on iOS but not working on Android.

`[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method requestPermissions on channel flutter.baseflow.com/permissions/methods)`

**Comment by Sheharyar566** [comment]
@eademir  which plugins you are using? In my case, image_picker and permission_handler were in sort of a clash, so I replaced the image_picker with images_picker plugin (an entirely different plugin) and now it's working.

**Comment by eademir** [comment]
Thank you for reply @Sheharyar566. Unfortunately, agora is must for my project and there is no any substitution for agora. By the way, I updated agora_rtc_engine to 3.1.3 and permission_handler to 5.0.1 and I am still getting same error. I will ask to agora help desk.

**Comment by moninm** [comment]
Hi, if this can help, I solved that issue by adding in "MainActivity.kt" for Kotlin :

override fun onCreate(savedInstanceState: Bundle?, persistentState: PersistableBundle?) {
    super.onCreate(savedInstanceState, persistentState)
    GeneratedPluginRegistrant.registerWith(FlutterEngine(this))
}
override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
    super.configureFlutterEngine(flutterEngine)
    flutterEngine.plugins.add(PathProviderPlugin())
    flutterEngine.plugins.add(SqflitePlugin())
    **flutterEngine.plugins.add(PermissionHandlerPlugin())**
}

**Comment by benwinding** [comment]
As per this comment here: https://stackoverflow.com/a/66862134/2419584

1. Goto `android/app/build.gradle`
2. Add the following lines:
``` diff
android {

   // other config stuff here

   buildTypes {
       release {
           signingConfig signingConfigs.release
+          minifyEnabled false
+          shrinkResources false
       }
   }
}
```

I think this prevents some build optimisations, which break the plugin registration, is that right?

**Comment by noufel-boulkroune** [comment]
> 
I solved Flutter_Facebook_auth essues by adding shrinkResources false and minifyEnabled false to android/app/build.gradel.

android {
    buildTypes {
        release {
            crunchPngs false
            shrinkResources false
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

}
