### ISSUE TITLE
check permission status of multiple permissions at once

### ISSUE THREAD

**Issue by visual-velocity** [Baseflow/flutter-permission-handler#310]
## 💬 Questions and Help

// You can request multiple permissions at once.
Map<Permission, PermissionStatus> statuses = await [
  Permission.location,
  Permission.storage,
].request();
print(statuses[Permission.location]);

Just as the request for all permissions is code, is there any similar functionality where we can know the status of all permissions together?
Because we need it to implement our production app. Please help us

**Comment by VisualMafia** [comment]
Future<List> checkPermissions() async {
    try {
      List responses = await Future.wait([
        Permission.camera.status, Permission.microphone.status
      ]);
      return responses;
    } catch (e) {
      return throw e;
    }
  }

**Comment by Sempakonka** [comment]
Hi @visual-velocity 
Reading your question, the response provided by @VisualMafia should answer your question.
I am going to close this issue. But don't hestitate to re-open if needed.

**Comment by visual-velocity** [comment]
Sure and thank you
