### ISSUE TITLE
Not able to change dialog message to open setting page in iOS

### ISSUE THREAD

**Issue by shahnawazahmed88** [Baseflow/flutter-permission-handler#311]
## 🐛 Bug Report

Not able to change dialog message to open setting page

### Configuration

**Version:** 5.0.0+hotfix.3

**Platform:** 
- [ ] :iphone: iOS
<img width="768" alt="attachment-9846865907848528985Screenshot-0602-184245" src="https://user-images.githubusercontent.com/20417533/83606370-235a8100-a597-11ea-94c3-c31196315987.png">

**Comment by mvanbeusekom** [comment]
Before iOS 6 it was possible to set the `purpose` property on the `CLLocationManager` class but this has long been deprecated in favor of using the `NSLocationAlwaysUsageDescription` and `NSLocationWhenInUseUsageDescription` strings in the `Info.plist`. 

As far as I am aware there is no other way to replace this message. See original documentation [here](https://developer.apple.com/documentation/corelocation/cllocationmanager/1423742-purpose).
