### ISSUE TITLE
 Unhandled Exception: MissingPluginException(No implementation found for method checkPermissionStatus on channel flutter.baseflow.com/permissions/methods)

### ISSUE THREAD

**Issue by shahnawazahmed88** [Baseflow/flutter-permission-handler#315]
Install app in Marshmallow
2.Getting Unhandled Exception: MissingPluginException(No implementation found for method checkPermissionStatus on
channel flutter.baseflow.com/permissions/methods)

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.19.0-3.0.pre, on Linux, locale en_IN)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Android Studio (version 3.6)
[✓] Android Studio (version 4.0)
[✓] Connected device (1 available)

• No issues found!

**Version:** 5.0.0+hotfix.3

**Platform:** 
- [ ] :robot: Android

**Comment by connyhald** [comment]
I'm having the same issue with Flutter `1.17`. After downgrading to Flutter `1.12` the plugin works again.

**Comment by shahnawazahmed88** [comment]
@connyhald my issue was due to e2e plugin, either update it or remove (If not required) from pubspec.yaml
