### ISSUE TITLE
PlatformException(ERROR_ALREADY_REQUESTING_PERMISSIONS, A request for permissions is already running, please wait for it to fini

### ISSUE THREAD

**Issue by Faiyyaz** [Baseflow/flutter-permission-handler#316]
## 🐛 Bug Report

Getting already requesting permission when asked for multiple permissions

### Expected behavior
It should not give such error

### Reproduction steps

You can use this code for reproduction of the bug

```
_requestSelectedPermission() async {
    bool contactPermissionGranted = false;
    List<Permission> permissions = [];

    if (_contactPermissionSwitch) {
      permissions.add(Permission.contacts);
    }

    if (_notificationPermissionSwitch) {
      permissions.add(Permission.notification);
    }

    if (_cameraPermissionSwitch) {
      permissions.add(Permission.camera);
    }

    // You can request multiple permissions at once.
    Map<Permission, PermissionStatus> statuses = await permissions.request();
    print(statuses[Permission.contacts]);
  }
```

### Configuration

**Version:**  ^5.0.0+hotfix.8

**Platform:** 
- [ ] :iphone: iOS - 13.4

**Comment by Faiyyaz** [comment]
Hey this issue was mine because of calling the method twice but now i see one popup and its flicker and then the other popup comes and it works fine

**Comment by Sempakonka** [comment]
Hi @Faiyyaz 
I see this issue was solved.
I am going to close this ticker, but don't hestitate to re-open if needed.

**Comment by jordantsap** [comment]
I have the same error with nested ifs, can you paste your working code to understand what iam doing wrong?

My code is:

// sms permission function on screen Initialization
void askSmsPermission() async {
  var smsStatus = await Permission.sms.status;
  if (Platform.isAndroid) {
    if (!smsStatus.isGranted) {
      print("Sms permission is Not Granted ask for sms permission");
      await Permission.sms.request();
    } else if (smsStatus.isDenied) {
      print('Sms permission isDenied');
      await Permission.sms.request();
    } else if (smsStatus.isPermanentlyDenied) {
      print('Sms permission is Permanently Denied');
      openAppSettings();
    }
  } else {
    print("Apple mobile");
  }
}

**Comment by Sempakonka** [comment]
Hi @jordantsap 
Are you sure you are not calling you method twice within a short period of time? Your code should work.
