### ISSUE TITLE
App does not show in battery optimization settings

### ISSUE THREAD

**Issue by miguelcmedeiros** [Baseflow/flutter-permission-handler#318]
## 🐛 Bug Report

After granting "permission" for  ignoring the app for battery optimization, the app is still not whitelisted.

### Expected behavior
In case we have grant the permission, we should go to battery optimization settings and we should see the app as not being optimized.

### Reproduction steps
1. Using `permission_handler`, request permission to ignore app for battery optimization: `Permission.ignoreBatteryOptimizations.request()`
2. When native prompt shows, grant access
3. Go to battery optimization settings
4. App is listed as being optimized

If I check the status from the app (`Permission.ignoreBatteryOptimizations.status`), it says that it's granted.

### Configuration

**Version:** 5.0.0+hotfix.8

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android 7.1.1

**Comment by miguelcmedeiros** [comment]
@ened 
I noticed that you added this feature to the plugin. From my reproduction steps, did I miss something?

**Comment by ened** [comment]
@miguelcmedeiros I noticed that different phones show the current status in different settings pages.

Go to the app settings of your app and check the permissions item there? Is it included?

**Comment by miguelcmedeiros** [comment]
I can find the app in battery optimization settings, but it's shown with "optimize battery" instead of "don't optimize battery". From that settings page I can manually change the setting.

**Comment by ened** [comment]
Can you upload your repro case online? Is the issue re-roducible with the permission handler "example" project?

**Comment by miguelcmedeiros** [comment]
Also reproducible with the example app:
![ezgif com-video-to-gif-19](https://user-images.githubusercontent.com/31278849/83955654-76f9f280-a855-11ea-93c2-d9d9d3dc5a91.gif)

**Comment by ened** [comment]
@miguelcmedeiros ok what phone are you using exactly? I’ll set up a test next week..

**Comment by ened** [comment]
Also, could you please take logs with pidcat for the example app that record the exact process as shown in the gif video you shared?

**Comment by miguelcmedeiros** [comment]
I'm using a Moto Z2 Play to test.

Here's the log from pidcat:
[pidcat.log](https://github.com/Baseflow/flutter-permission-handler/files/4742698/pidcat.log)

I got the log by running `pidcat com.example.permissionhandlerexample`. Should I run it again with some options.

**Comment by miguelcmedeiros** [comment]
After some googling, I found someone with similar issue:
https://stackoverflow.com/questions/52617790/action-request-ignore-battery-optimizations-does-nothing#comment92169913_52617790

It seems that the whitelist gets updated after a phone reboot. At least for some devices/OS versions, although it's not clear where the issue actually is...

@ened, I'm closing the issue since I think there's not much we can do (coming from someone with little Android knowledge 😅).

**Comment by ened** [comment]
Yeah but you didn’t reboot the phone, didn’t you?

Also, is the behavior different on other phones?
