### ISSUE TITLE
Android permissions(REQUEST_INSTALL_PACKAGES)

### ISSUE THREAD

**Issue by chengxushi** [Baseflow/flutter-permission-handler#319]
Excuse me, this does not seem to support requesting application permissions above Android 8.0 (REQUEST_INSTALL_PACKAGES). Can you add this??

**Comment by NoldyNayoan** [comment]
Yes, could you please add REQUEST_INSTALL_PACKAGES permission?

**Comment by Omario64** [comment]
Could you please add REQUEST_INSTALL_PACKAGES permission?

**Comment by ZionPi** [comment]
Could you please add REQUEST_INSTALL_PACKAGES permission?How to check this permission status?

**Comment by sidazhang123** [comment]
The plugin somehow totally takes over the management of granting a permission. So we can't use it if not fixed.

**Comment by JDDV** [comment]
Hi, this is added in the newest version of the permission handler plugin (version 7.2.0).
