### ISSUE TITLE
Android storage permission status is PermissionStatus.undetermined incorrectly.

### ISSUE THREAD

**Issue by m-j-g** [Baseflow/flutter-permission-handler#327]
## 🐛 Bug Report

Storage permission on Android will have a Status of .undetermined when it should be .isDenied and .isPermanentlyDenied.  It correctly identifies Status.isGranted when accepted.

### Reproduction steps
Deny Storage permission on Android. (or perma deny)
Check Status
Says PermissionStatus.undetermined.

**Comment by chloe722** [comment]
same thing happen on me. 
Is there any workaround?

**Comment by m-j-g** [comment]
> same thing happen on me.
> Is there any workaround?

I don't think so.  Don't know if anyone is maintaining this anymore.

**Comment by mikeesouth** [comment]
Same as #336 ?

**Comment by Sempakonka** [comment]
Hi,
To keep the issues on this repo more organized I am going to close this ticket, as I think it is a duplicate of #336. 
Don't hestitate to re-open if you think otherwise!
