### ISSUE TITLE
PermissionGroupStorage missing PermissionGroupBluetooth for iOS 13.0 later

### ISSUE THREAD

**Issue by LongXiangGuo** [Baseflow/flutter-permission-handler#329]
### Describe the feature

file: permission_handler/ios/Classes/PermissionHandlerEnums.h 
PermissionHandlerEnums should add  `PermissionGroupBluetooth` case

```
#ifndef PERMISSION_BLUETOOTH
    #define PERMISSION_BLUETOOTH 1
#endif
```

directory: permission_handler/ios/Classes/strategies 
should add class for Bluetooth status check

### Platforms affected (mark all that apply)
- [iOS 13.0 ] :iphone: iOS
- [/ ] :robot: Android

Thanks, if you granted my git permission, I'am pleasure to raise the PR

**Comment by JDDV** [comment]
@LongXiangGuo Thanks for the feature request, this is added in version ^6.1.0 of the permission-handler plugin
