### ISSUE TITLE
Build Fails on Windows

### ISSUE THREAD

**Issue by vahidkarimane** [Baseflow/flutter-permission-handler#332]
### Expected behavior
Android Build Fails on windows android studio
### Reproduction steps
When I Add dependency on pubspec.yaml, it fails on the build. When I remove it from pubspec.yaml, build become successful

### Configuration
windows 10,
 compileSdkVersion 28
android.useAndroidX=true
android.enableJetifier=true
Flutter1.17,
permission_handler: ^5.0.1

Error Info : **Platform:** 
: Android
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':permission_handler:javaPreCompileDebug'.
> Could not resolve all files for configuration ':permission_handler:debugCompileClasspath'.
   > Could not find core.jar (androidx.core:core:1.1.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/core/core/1.1.0/core-1.1.0.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin contacts_service...
Running Gradle task 'assembleAarRelease'...

FAILURE: Build failed with an exception.

**Comment by Sempakonka** [comment]
Hi @vahidkarimane 

I don't think this is an issue with the plugin.
There are a few things you could try:

- Running `flutter upgrade --force`
- Checking the setup instructions provided in the [README.md](https://github.com/Baseflow/flutter-permission-handler/blob/develop/permission_handler/README.md) file.
- Maybe the command `flutter clean` solves this issue.
- Make sure your `build.gradle` file matches this:
```
buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}
```
