### ISSUE TITLE
crash on ios 13.5 when request storage permission

### ISSUE THREAD

**Issue by Slim1991** [Baseflow/flutter-permission-handler#333]
## 🐛 Bug Report

This happens on all my ios devices. We should fix it asap, this is critical.
ps: It works fine on all my android devices

**Version:** 5.0.1

**Platform:** 
- [ ] :iphone: iOS

**Comment by mvanbeusekom** [comment]
@Slim1991 can you supply some more details?  What does you code look like? In general the permission handler doesn't support `Permissions.storage` and as such always returns `granted` according to the current code base. I think this is a small mistake as it should always return `denied` if permissions are not available on a platform.  This however should not crash the application (at least it doesn't  when I try it in the example App).

So can you:

1. Supply a stack trace?
2. Submit some of the code you are using?
3. Or supply a sample application?

**Comment by Slim1991** [comment]
This should be closed because of my mistake. Turns out,  I put wrong permission name in the info.plist that I did not notice.
