### ISSUE TITLE
cannot access my storage in flutter in a real android device after installing the apk

### ISSUE THREAD

**Issue by simo9900** [Baseflow/flutter-permission-handler#335]
I access to my internal storage and camera in release mode with intellij idea. But when I generate the apk and deploy in a real android device it does not work.

Can you help me please?

This is my android manifest. When I want to access to the camera or the storage or googlemaplocation. It does nothing.

Thanks

This is my whole manifest:

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
package="lesvoisins.app.simo.rafik.lesvoisins_flutterV2">
<!-- io.flutter.app.FlutterApplication is an android.app.Application that
     calls FlutterMain.startInitialization(this); in its onCreate method.
     In most cases you can leave this as-is, but you if you want to provide
     additional functionality it is fine to subclass or reimplement
     FlutterApplication and put your custom class here. -->
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission
        android:name="android.permission.ACCESS_FINE_LOCATION" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.CAMERA"/>
<application
    android:name="io.flutter.app.FlutterApplication"
    android:label="lesvoisins_flutterV2"
    android:icon="@mipmap/ic_launcher">
    <activity
        android:name=".MainActivity"
        android:launchMode="singleTop"
        android:theme="@style/LaunchTheme"
        android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
        android:hardwareAccelerated="true"
        android:windowSoftInputMode="adjustResize">
        <!-- Specifies an Android theme to apply to this Activity as soon as
             the Android process has started. This theme is visible to the user
             while the Flutter UI initializes. After that, this theme continues
             to determine the Window background behind the Flutter UI. -->
        <meta-data
          android:name="io.flutter.embedding.android.NormalTheme"
          android:resource="@style/NormalTheme"
          />
        <!-- Displays an Android View that continues showing the launch screen
             Drawable until Flutter paints its first frame, then this splash
             screen fades out. A splash screen is useful to avoid any visual
             gap between the end of Android's launch screen and the painting of
             Flutter's first frame. -->
        <meta-data
          android:name="io.flutter.embedding.android.SplashScreenDrawable"
          android:resource="@drawable/launch_background"
          />
        <intent-filter>
            <action android:name="android.intent.action.MAIN"/>
            <category android:name="android.intent.category.LAUNCHER"/>
        </intent-filter>
    </activity>
    <activity
            android:name="com.yalantis.ucrop.UCropActivity"
            android:screenOrientation="portrait"
            android:theme="@style/Theme.AppCompat.Light.NoActionBar"/>
    <!-- Don't delete the meta-data below.
         This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
    <meta-data
        android:name="flutterEmbedding"
        android:value="2" />
    <meta-data
            android:name="com.google.android.geo.API_KEY"
            android:value="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"/>
</application>
```

**Comment by simo9900** [comment]
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
package="lesvoisins.app.simo.rafik.lesvoisins_flutterV2">

<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission
        android:name="android.permission.ACCESS_FINE_LOCATION" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.CAMERA"/>
<application
    android:name="io.flutter.app.FlutterApplication"
    android:label="lesvoisins_flutterV2"
    android:icon="@mipmap/ic_launcher">
    <activity
        android:name=".MainActivity"
        android:launchMode="singleTop"
        android:theme="@style/LaunchTheme"
        android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
        android:hardwareAccelerated="true"
        android:windowSoftInputMode="adjustResize">
        
        <meta-data
          android:name="io.flutter.embedding.android.NormalTheme"
          android:resource="@style/NormalTheme"
          />
        
        <meta-data
          android:name="io.flutter.embedding.android.SplashScreenDrawable"
          android:resource="@drawable/launch_background"
          />
        <intent-filter>
            <action android:name="android.intent.action.MAIN"/>
            <category android:name="android.intent.category.LAUNCHER"/>
        </intent-filter>
    </activity>
    <activity
            android:name="com.yalantis.ucrop.UCropActivity"
            android:screenOrientation="portrait"
            android:theme="@style/Theme.AppCompat.Light.NoActionBar"/>
    
    <meta-data
        android:name="flutterEmbedding"
        android:value="2" />
    <meta-data
            android:name="com.google.android.geo.API_KEY"
            android:value="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"/>
</application>

**Comment by simo9900** [comment]
[AndroidManifest.xml.txt](https://github.com/Baseflow/flutter-permission-handler/files/4815107/AndroidManifest.xml.txt)

**Comment by mvanbeusekom** [comment]
@simo9900, not sure which `AndroidManifest.xml` is the one you are actually using in your release app. However the one attached as "AndroidManifest.xml.txt" misses the permissions for storage and camera which would make sense why this is not working.

Note that in your applications `android/app/src` folder you have a `debug`, `main` and `profile` folder each holding an AndroidManifest.xml file. Usually you would only add items to the `android/app/src/AndroidManifest.xml` file and only in rare cases where you need special setting for debug or profile mode only you would add items to those files.

**Comment by mvanbeusekom** [comment]
sorry didn't mean to close it, I am curious if this is helps though.

**Comment by simo9900** [comment]
> @simo9900, not sure which `AndroidManifest.xml` is the one you are actually using in your release app. However the one attached as "AndroidManifest.xml.txt" misses the permissions for storage and camera which would make sense why this is not working.
> 
> Note that in your applications `android/app/src` folder you have a `debug`, `main` and `profile` folder each holding an AndroidManifest.xml file. Usually you would only add items to the `android/app/src/AndroidManifest.xml` file and only in rare cases where you need special setting for debug or profile mode only you would add items to those files.

I added the permissions but still not work

    
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>

    
    <uses-permission android:name="android.permission.CAMERA"/>

**Comment by omkartralsawala** [comment]
Experiencing a simillar issue

**Comment by yalzeee** [comment]
Experiencing the same issue after application is uploaded to playstore. This works in release mode but when released to the store it suddenly stops working

**Comment by spyderbibek** [comment]
same issue for me added all the permission in manifest file but when installed in real device it doesn't ask for storage permission.

**Comment by simo9900** [comment]
I solved this issue after struggling for days. I found that the version of gradle was not compatible with the sdk. I created a new project and insert all the files needed and implemented the android manifest and it worked perfectly

**Comment by yalzeee** [comment]
What version of gradle did you end up using

**Comment by mvanbeusekom** [comment]
In the example app we are on Gradle 3.5.0

**Comment by spyderbibek** [comment]
> I solved this issue after struggling for days. I found that the version of gradle was not compatible with the sdk. I created a new project and insert all the files needed and implemented the android manifest and it worked perfectly

How did you fix it? which gradle version are you using?

**Comment by Beautylivery** [comment]
i am also curious about a solution... should not be necessary to copy all the data ...  i check permissions with permission handler, and i receive a null value on the build version of the tool.... really curious whaat could be done :(

**Comment by satyendrasingh8** [comment]
I'm also facing same issue here. my physical device denied to copy all such data in the adjust path. After full restart of my app its looses content.

**Comment by dharmadeveloper108** [comment]
I'm having the same problem: everything works fine on the release build, but when I upload the apk to Googleplay, in that uploaded version of the app anything accessing device folders (including sqlite db) just doesn't work.

**Comment by dharmadeveloper108** [comment]
Sharing this hoping it'll be helpful to other people facing this problem: 
Gradle 3.5.4 worked fine for me (Flutter SDK >=2.7.0 <3.0.0).
Switching to that version fixed all problems with device folder access.

**Comment by maseappsltd** [comment]
Using flutter with vscode, i hade to give the full path to my assets, otherwise i got this crash. 
so in wherever you load external assets give the full path: 

**String dataWeightGirls = await rootBundle.loadString('assets/xxx/xxx.txt');**

it didn't matter if i specified the asset directories in the pubspec.yaml file. 

What worked was to provide the full path.

Though if i run it/test on an IOS device, i can't use the full path.

On IOS:
**String dataWeightGirls = await rootBundle.loadString('xxx/xxx.txt');**

On Android:
**String dataWeightGirls = await rootBundle.loadString('assets/xxx/xxx.txt');**
