### ISSUE TITLE
openAppSettings() issue - Android 10 - Back button redirects to the application

### ISSUE THREAD

**Issue by viplavrawal** [Baseflow/flutter-permission-handler#342]
## 🐛 Bug Report

openAppSettings() opens the appSettings properly. But coming back from an internal screen in that settings page say Notifications page, redirects the user back to the main app.

### Reproduction steps
1. Use openAppSettings() to open app settings in Android 10
2. Go to an internal page in appSettings like Notifications
3. Press the back button from this page

### Expected behavior
User should go one step up in settings to the main appSettings page.

### Actual behavior
User is redirected to our app

### Configuration

**Version:** ^5.0.0+hotfix.3

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by tmacLiu001** [comment]
I have the same issue

**Comment by Sempakonka** [comment]
Hi @viplavrawal 
This is an expected behavior. It is the way the intent that opens settings is set up. `addFlags(Intent.FLAG_ACTIVITY_NO_HISTORY);` causes this behavior.
My guess as to why they did this is that this improves the flow of quickly changing a permission and backing out.

Let me know if this clarifies your question, so we can close this issue!

**Comment by viplavrawal** [comment]
Is there anyway to change this behaviour so that the history can be maintained within the settings screen? If not, then can it be provided by this plugin?

**Comment by Sempakonka** [comment]
There are a few ways explained [here](https://flutter.dev/docs/development/packages-and-plugins/using-packages#dependencies-on-unpublished-packages) to modify this package.

Now what you need to look for is a file called ` AppSettingsManager.java`. In this file on line 29 you can see `settingsIntent.addFlags(Intent.FLAG_ACTIVITY_NO_HISTORY);`. Remove this and see if it works. If it does not make sure you are using your modified package.
