### ISSUE TITLE
huawei protected app permision

### ISSUE THREAD

**Issue by mamonraab** [Baseflow/flutter-permission-handler#347]
## 💬 Questions and Help

 
can i ask user one open app in huawei to add app in the huawei protected app
any example will be helpfull , since there is alot of huawei devices and  app cant for example get push notification  if it not added to huawei protected app

**Comment by Sempakonka** [comment]
I think such funtionality has yet to be implemented, if it is even possible. According to [this](https://stackoverflow.com/questions/31638986/protected-apps-setting-on-huawei-phones-and-how-to-handle-it) stackoverflow question Huawei is giving developers a hard time managing this setting. In [this](https://stackoverflow.com/questions/52655837/how-to-make-my-app-protected-on-huawei-devices) stackoverflow question someone is stating that the app does get "protected" by default.

**Comment by JDDV** [comment]
@mamonraab, After researching a bit I found the following explanation:

> Huawei devices have enabled by default a battery safe mode called 'Protected Apps'. Freshly installed apps are flagged by default (if not popular enough) as 'not protected'. This feature prevents the apps from receiving push notifications (GCM, FCM, ...) in background.

It seems like this is not something we can fix with the permission-handler plugin.
