### ISSUE TITLE
Unable to publish to apple store NSContactsUsageDescription

### ISSUE THREAD

**Issue by martinmc666** [Baseflow/flutter-permission-handler#350]
I've added the permission_handler module. and used a very basic request for Camera permission.

My publish failed on Apple store saying my app needs NSContactsUsageDescription in the info.plist file.

Does the handler code require this permission for some reason?

This is the only thing I've added since my last build which was ok.

**Comment by kuhnroyal** [comment]
Read the Setup iOS in the README

**Comment by JDDV** [comment]
Hi @martinmc666, have you removed the permissions you didn't need as mentioned in the README.md iOS setup? and did you also remove the corresponding permission description in Info.plist? Please let us know if you fixed the problem!

**Comment by martinmc666** [comment]
Yes i did this and worked fine. Many thanks for this.
