### ISSUE TITLE
Access to notification group permission

### ISSUE THREAD

**Issue by jheimesilveirazup** [Baseflow/flutter-permission-handler#352]
## 💬 Questions and Help

Is there a way to know if a notification group's permission within the application?
an example is this group that is in print, I want to be able to know if it is selected or not.

![print](https://user-images.githubusercontent.com/63818444/87493546-5fb3df00-c623-11ea-8a69-3f7c8de57453.jpg)

**Comment by Sempakonka** [comment]
I am afraid such functionality has yet to be implemented.
If you want, I think Baseflow would love to see a PR!

**Comment by TimHoogstrate** [comment]
I doubt if this is the responsibility of the permission-handler. We have to discuss this in the team to see if we should add support for this.

**Comment by mvanbeusekom** [comment]
We have discussed this issue within the team and decided that it is indeed out of scope for the permission_handler. One should expect this functionality in a plugin or package that is focussing on handling notifications.
