### ISSUE TITLE
Location permission dialog appear after being denied but not for notification permission

### ISSUE THREAD

**Issue by newbieflutter** [Baseflow/flutter-permission-handler#353]
Hi,
    I have the following codes as below. This code works perfectly fine for location. So I go to my settings and I close the permission for location and it keep asking for permission. I just replace it with await Permission.notification.status and replace everything with notification it does not work the same after its denied. Why its behaving differently for notification permission?

```
var status = await Permission.location.status;
    print("location STATUS is" + status.toString());
    if (status.isRestricted) {
      // We didn't ask for permission yet.
      print("RESTRICTED IN THE IF NOW");
      Map<Permission, PermissionStatus> statuses = await [
        Permission.location,
      ].request();
      print("ÄFTER GET " + statuses[Permission.location].toString());
    }
    if (status.isUndetermined) {
      // We didn't ask for permission yet.
      print("UN DETERMINED IN THE IF NOW");
      Map<Permission, PermissionStatus> statuses = await [
        Permission.location,
      ].request();
      print("ÄFTER GET " + statuses[Permission.location].toString());
    }
    if (status.isDenied) {
      // We didn't ask for permission yet.
      print("DENIED IN THE IF NOW");
      Map<Permission, PermissionStatus> statuses = await [
        Permission.location,
      ].request();
      print("ÄFTER GET " + statuses[Permission.location].toString());
    }
```

**Comment by JDDV** [comment]
Hi @newbieflutter! I was checking what you meant with your question, it seems like you used version ^5.0.1+1 or older for your code snippet you provided. the if statement with `status.isUndetermined` doe not exist any longer. It would be good practice to update to the current version of the permission_handler (^6.1.1). 

That being said, When the app asks for the location permission, and you allow it, the status will be PermissionStatus.granted. As soon as you go to the settings on your phone (tip: you can use openAppSettings() from the plug-in to go directly to the settings of your app), and you change the permission to 'Deny'. The status of the location permission will be 'denied' (`PermissionStatus.denied`) as well. So it shows the behavior how you mentioned it in the issue as well.

For notifications this works a bit different, the notification permission doesn't bring up a rationale (pop-up screen for allowing or denying the permission). It uses the Android's `NotificationManagerCompat` library as mentioned [here](https://developer.android.com/reference/androidx/core/app/NotificationManagerCompat). The PermissionStatus will either be `granted` or `denied` depending on whether the notifications are on or off for your app.

I tested this using your code snippet with the newest permission_handler plug-in version.
I hope this answered your question, please let me know if this helped you so the issue can be closed!
