### ISSUE TITLE
How to identify that user allowed the permission for the particular permission request.

### ISSUE THREAD

**Issue by DhavalRKansara** [Baseflow/flutter-permission-handler#354]
Using this plugin I requested the camera permission and after that how we can identify that user choose allowed or denied on the same screen. 

In my use case If the user allowed then I have to open the camera but I don't found any method from which I can get he acknowledge of user selection.

**Comment by mvanbeusekom** [comment]
When you request permissions the `request()` method will return a status object which contains the selection from the user. So you could simply do something like this:

```dart
final permissionStatus = await Permission.camera.request();

if (permissionStatus == PermissionStatus.granted) {
  // Open the camera here...
}
```

We also have a convenience extension method so you can write the above a bit shorter:

```dart
if (await Permission.camera.request().isGranted()) {
  // Open the camera here...
}
```

Hope this helps

**Comment by DhavalRKansara** [comment]
No this is not working.

**Comment by Sempakonka** [comment]
Hi,
I think this is an issue rather than a question and we can close this and continue in issue [#336](https://github.com/Baseflow/flutter-permission-handler/issues/336), as you mentioned.
If you think otherwise don't hesitate to re-open.
