### ISSUE TITLE
BatteryOptimization permission

### ISSUE THREAD

**Issue by AlexBacich** [Baseflow/flutter-permission-handler#357]
## 🚀 Feature Requests

BatteryOptimization permission enhancement

### Contextualize the feature

Battery permission is special type of permission and requires special handling

**First** - phones before Android M don't support it and there's no special handling for that permission. It simply returns PermissionResult.granted. 
**Second** - library allows sending users to Settings to give certain permissions. To all except for the BatteryOptimization. Again, that is special case and should fire intent: ACTION_IGNORE_BATTERY_OPTIMIZATION_SETTINGS

Not sure someone else needs such granularity, just in case. 

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [X] :robot: Android

**Comment by JDDV** [comment]
This is added and available in the permission handler. The permission is called  `ignoreBatteryOptimizations`. Thanks for your input!
