### ISSUE TITLE
notification   The permission pop-up window cannot be activated

### ISSUE THREAD

**Issue by yingqiang006** [Baseflow/flutter-permission-handler#370]
## 🐛 Bug Report

notification   The permission pop-up window cannot be activated

**Version:** ^5.0.1+1

**Platform:** 
- [ ] :robot: Android

**Comment by renefloor** [comment]
Can you explain a bit more? 
Are you requesting a permission for an app that doesn't have it yet? It would be handy if you can provide a piece of source code. Does the example work for you.

Please note that you need at least Android 6.0 to request permissions.

**Comment by ncuillery** [comment]
I have the same, after upgrading to Flutter 1.20.2, the following doesn't nothing on iOS:

```dart
final status = await Permission.notification.status;
print('$status'); // Print: "PermissionStatus.undetermined"
final newStatus = await Permission.notification.request(); // Nothing happen
print('$newStatus'); // Still print: "PermissionStatus.undetermined"
```

**Comment by ncuillery** [comment]
Was gonna provide a sample app to repro... but it actually works on a new project created directly in 1.20.2...

I'm investigating.

**Comment by ncuillery** [comment]
Nevermind, the issue was on my side, I've copy-pasted the code from [here](https://github.com/Baseflow/flutter-permission-handler/issues/365#issuecomment-679085408) and forgot to update to my own needs 🤦

**Comment by Sempakonka** [comment]
Hi @yingqiang006 
Has the issue been resolved?
If so, this issue can be closed.
If not, it would be helpfull to supply some extra infromation.
[this](https://stackoverflow.com/questions/37294076/push-notifications-gcm-permission-at-runtime) would also be worth checking regarding the notification permission's.
