### ISSUE TITLE
Error no 13, permission denied on accessing external card files

### ISSUE THREAD

**Issue by rrkas** [Baseflow/flutter-permission-handler#371]
Flutter doctor -v:
[✓] Flutter (Channel master, 1.20.0, on Linux, locale en_IN)
    • Flutter version 1.20.0 at /home/rohnak/Documents/Development/flutter
    • Framework revision ec3368ae45 (7 weeks ago), 2020-07-02 01:58:01 -0400
    • Engine revision 65ac8be350
    • Dart version 2.9.0 (build 2.9.0-20.0.dev f8ff12008e)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/rohnak/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /home/rohnak/Downloads/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Android Studio (version 3.6)
    • Android Studio at /home/rohnak/Downloads/android-studio
    • Flutter plugin version 47.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
[✓] Connected device (1 available)
    • SM J701F (mobile) • 5200785efeef3547 • android-arm    • Android 9 (API 28)

---------------------------------------------------------------------------------------------------------------------------------------------------------------
My Code:
 if (await Permission.storage.request().isDenied) {
        return null;
 }

--------------------------------------------------------------------------------------------------------
Then i try to access the files on external storage.
Error: 
FileSystemException: Creation failed, path = '/storage/9016-4EF8/My Ext Dir' (OS Error: Permission denied, errno = 13)

Please help!

**Comment by Sempakonka** [comment]
Hi,
Have you added the needed permissions to the `AndroidManifest file`?
More information about the setup is provided in the [README.md](https://github.com/Baseflow/flutter-permission-handler/blob/develop/README.md)

**Comment by sergiocasero** [comment]
I'm getting the same issue, and yes, they are on manifest, in fact, `Permission.storage.status'  returns `Granted`

**Comment by TimHoogstrate** [comment]
Dear @rrkas or @sergiocasero or @Shahzadah,

Is this still relevant?

Kind regards,
