### ISSUE TITLE
ios Bluetooth Always

### ISSUE THREAD

**Issue by windswrold** [Baseflow/flutter-permission-handler#372]
### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by Sempakonka** [comment]
Hi @windswrold 
This feature request containes very little information.
Is it possible it is a duplicate of [issue #329 ](https://github.com/Baseflow/flutter-permission-handler/issues/329)?
If not, can you supply the asked information in the ticket?

**Comment by windswrold** [comment]
重复的＃
