### ISSUE TITLE
Requesting user permission with the AppTrackingTransparency

### ISSUE THREAD

**Issue by ethanwheatthin** [Baseflow/flutter-permission-handler#375]
## 🚀 Feature Requests

IDFA (Identifier for Advertisers) is an Apple iOS feature that identifies a user's mobile device. On iOS 13 and earlier, the IDFA was available by default with the exception of users who had limited ads personalization in the settings on their iOS device. 

With the release of iOS 14, users will be required to explicitly give permission in order to use the IDFA. Adding the AppTrackingTransparency permission to your apps adds an ATT alert that asks users to allow access to and use of identifiers like IDFA.

Just like all the permissions this package can handle can we get an additional feature to get the UUID from the AppTrackingTransparency framework using this package. Using the article that Google sent out to all AdMob users is what I am referencing. 
https://support.google.com/admob/answer/9997589?hl=en
### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by JDDV** [comment]
Hi @ethanwheatthin, the permission is added in the newest version of the permission handler plugin! the newest version is version ^8.0.0 since we introduced a breaking change.
