### ISSUE TITLE
Android: isUndetermined returned for status if permission was requested by different plugin

### ISSUE THREAD

**Issue by champeauxr** [Baseflow/flutter-permission-handler#380]
## 🐛 Bug Report

If `permission_handler` is used to check the status of a permission after another plugin has requested it, the correct status is not returned if a user has denied or permanently denied the permission. Instead, it returns `isUndetermined`

This was encountered when using the `camera` plugin. The `camera` plugin requests the permission itself and if the user denies the permission, it returns `CameraError.cantInitializeCamera`. Upon receiving this error, if you then attempt to use `permission_handler` to get the camera permission status, it returns `isUndetermined` instead of `isDenied` or `isDeniedPermanently`.

This is because the `permission_handler` stores a boolean in the shared preferences indicating whether the `permission_handler` has requested the permission before. And when `PermissionManager.determinePermissionStatus` is called to check the permission status, it will check the shared preference and return `PermissionConstants.PERMISSION_STATUS_NOT_DETERMINED` if the shared preference hasn't been set.

Here is the code from `PermissionManager.determinePermissionStatus`
```
                final int permissionStatus = ContextCompat.checkSelfPermission(context, name);
                if (permissionStatus == PackageManager.PERMISSION_DENIED) {
                    if (!PermissionUtils.getRequestedPermissionBefore(context, name))
                    {
                        return PermissionConstants.PERMISSION_STATUS_NOT_DETERMINED;
                    } else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M &&
                            PermissionUtils.isNeverAskAgainSelected(activity, name)) {
                        return PermissionConstants.PERMISSION_STATUS_NEWER_ASK_AGAIN;
                    } else {
                        return PermissionConstants.PERMISSION_STATUS_DENIED;
                    }
                } else if (permissionStatus != PackageManager.PERMISSION_GRANTED) {
                    return PermissionConstants.PERMISSION_STATUS_DENIED;
                }
```
If the `permissionStatus` is `PERMISSION_DENIED`, it checks the shared preference and always returns `PERMISSION_STATUS_NOT_DETERMINED` if it's not set.

I have worked around this issue by setting the shared preference for the camera permission myself. With this hack, it seems to work fine.

**Version:** 5.0.1

**Platform:** 
- [x] :robot: Android

**Comment by bhavinwebdesk** [comment]
@champeauxr

I am getting exact same issue. Have you changed in the camera plugin?

**Comment by visual-velocity** [comment]
I'm getting same issue

**Comment by JDDV** [comment]
Hi @champeauxr, can you try using the newest plugin version (version 7.1.0) and see if the problem still occurs?
I think it should solve the problem since version 6.0.0 (as mentioned [here](https://github.com/Baseflow/flutter-permission-handler/wiki/Changes-in-6.0.0)). Let me know if it worked!

**Comment by JDDV** [comment]
Due to inactivity I will close this issue. Please feel free to start a new issue if this is still a problem!
