### ISSUE TITLE
Android version of my app shows RECORD_AUDIO permission even though I don't specifically ask for it

### ISSUE THREAD

**Issue by subhash279** [Baseflow/flutter-permission-handler#382]
Hi,
I don't specifially ask for RECORD_AUDIO permission anywhere in my code but when I upload my final build for release, playstore shows my app needs RECORD_AUDIO permission.
Is this because of using permission_handler plugin? Do I have to disable this somewhere because I only read about disabling it for iOS in docs but not for Android.
Thanks!

**Comment by chillbrodev** [comment]
Can you post your pubspec.yaml file and run `flutter pub deps` then post the results? This will help us better understand which packages you have. Thanks

**Comment by JDDV** [comment]
Hi @subhash279, in your app, do you use your microphone or something? Because the `RECORD_AUDIO` permission is needed when you use your microphone. There is no need to disable the permission or something like on iOS. Android works with the AndroidManifest.xml where you add the `<uses-permission android:name="android.permission.RECORD_AUDIO" />` permission if you want to use the permission. Let me know if the problem is solved, otherwise feel free to comment!

**Comment by JDDV** [comment]
Due ti inactivity I will close this issue. if this is still a problem for you, please feel free to staart a new issue!

**Comment by neroaCu** [comment]
@JDDV I think the question is very clear that the author does not explicitly add RECORD_AUDIO permission in the AndroidManifest.xml. But it somehow shows that the app needs this permission. 

I faced exactly the same issue. When I globally search, it shows highly possibility that it comes from permission_handler. But I can't very sure about it.  

Appreciate if you can take a look into this case again. Thanks

**Comment by modeefarouq** [comment]
@JDDV I am facing the same problem, the app got rejected from google play for assuming that I am requesting record_audio, I am not requesting that, not in code and not in android manifest.

**Comment by Theunodb** [comment]
This is the message from playstore:

Security and trust
Anomalous Permission Usage

Warning Privacy
Your app is requesting permissions which are used by less than 1% of functionally similar apps:

android.permission.RECORD_AUDIO
Users prefer apps that request fewer permissions and requesting unnecessary permissions can affect your app's visibility on the Play Store. If these permissions aren't necessary, you may be able to use alternative methods in your app and request fewer permissions. If they are, we recommend providing an explanation to users of why you need the permissions.

Note: This guidance is based on a comparison with functionally similar apps, which change over time as new apps get published and existing apps change behavior. Therefore the warning may change even if you don't change your permission usage.
