### ISSUE TITLE
Android Permission request only popping in debug mode

### ISSUE THREAD

**Issue by pohpas** [Baseflow/flutter-permission-handler#383]
## 🐛 Bug Report

hi there,

When I run the App via flutter run in debug mode, the requests both in virtual and real device pop upon request.
However when I bring the release build to a real device, no request pops up.
I have the corresponding permissions in the main Android manifest.

**Version:** current

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by babaosoftware** [comment]
Same here. I was using this code (Android only):
  if (Platform.isAndroid) {
    var status = await Permission.location.status;
    if (status.isUndetermined) await Permission.location.request();
  }
On a fresh install, DEBUG, it would popup the permissions dialog, thus the returned status was undetermined.
On a fresh install, RELEASE, it would not popup the permission dialog. Turns out the returned sate was permanently denied. I don't even know how you set a permission like that in Android.
Anyway, changed my code to this:
  if (Platform.isAndroid) {
    var status = await Permission.location.status;
    if (status.isUndetermined || status.isPermanentlyDenied) await Permission.location.request();
  }

**Comment by pohpas** [comment]
> Same here. I was using this code (Android only):
> if (Platform.isAndroid) {
> var status = await Permission.location.status;
> if (status.isUndetermined) await Permission.location.request();
> }
> On a fresh install, DEBUG, it would popup the permissions dialog, thus the returned status was undetermined.
> On a fresh install, RELEASE, it would not popup the permission dialog. Turns out the returned sate was permanently denied. I don't even know how you set a permission like that in Android.
> Anyway, changed my code to this:
> if (Platform.isAndroid) {
> var status = await Permission.location.status;
> if (status.isUndetermined || status.isPermanentlyDenied) await Permission.location.request();
> }

**Comment by pohpas** [comment]
@babaosoftware did your changes solve the issue?

**Comment by babaosoftware** [comment]
@pohpas yes it did. But it's just a workaround. On the other hand, like I said, I don't see how isPermanentlyDenied can ever be returned as a status for Android.

**Comment by Purvik** [comment]
@babaosoftware  @pohpas You must have defined permission in AndroidManifest file, I guess. If you have not put that it wont work in release mode.

**Comment by babaosoftware** [comment]
@Purvik This is what I have in manifest:
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
By the way, I'm talking about a published app that worked before, and it always used the location services. After the app is installed I can change the permission in app's properties, so it is detecting them.

**Comment by pohpas** [comment]
@babaosoftware sorry for the late response.
I have the following class defined: 

import 'dart:async';
import 'package:permission_handler/permission_handler.dart';

class PermissionException implements Exception {}

class PermissionRepository {
  /// {@macro authentication_repository}
  PermissionRepository({
    Permission contacts,
    Permission microphone,
  })  : _contacts = contacts ?? Permission.contacts,
        _microphone = microphone ?? Permission.microphone;

  final Permission _contacts;
  final Permission _microphone;

  Future<bool> get permissionStatus async {
    if (await _contacts.status == PermissionStatus.granted &&
        await _microphone.status == PermissionStatus.granted) {
      return true;
    } else {
      return false;
    }
  }

  void requestPermissions() async {
    // Request for microphone (recording voice messages) and contact_read permission
/*     setState(() {
      error = 'lala';
    });

    

    openAppSettings(); */
    await [_contacts, _microphone].request();
  }

**Comment by babaosoftware** [comment]
@pohpas I don't see anything wrong with your code. Are you sure permissionStatus returns false?  Maybe the app already has those permissions granted. Check your app settings on the phone. Also, make sure you include those in the manifest too.

**Comment by callmejm** [comment]
same happen to me , only happen on android release

**Comment by callmejm** [comment]
> same happen to me , only happen on android release

I fixed by changing the gradle version on build.gradle and gradle-wrapper.properties, find out my colleague commit wrong version due to different flutter version

**Comment by pohpas** [comment]
> > same happen to me , only happen on android release
> 
> I fixed by changing the gradle version on build.gradle and gradle-wrapper.properties, find out my colleague commit wrong version due to different flutter version

@callmejm could you specify more in detail which lines (with examples) you changed?

**Comment by callmejm** [comment]
> > > same happen to me , only happen on android release
> > 
> > 
> > I fixed by changing the gradle version on build.gradle and gradle-wrapper.properties, find out my colleague commit wrong version due to different flutter version
> 
> @callmejm could you specify more in detail which lines (with examples) you changed?

what I change

 1. android/build.gradle 

```
    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
       //other
    }
```

 2. android/gradle/wrapper/gradle-wrapper.properties

`    distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip`

**Comment by pohpas** [comment]
> > > > same happen to me , only happen on android release
> > > 
> > > 
> > > I fixed by changing the gradle version on build.gradle and gradle-wrapper.properties, find out my colleague commit wrong version due to different flutter version
> > 
> > 
> > @callmejm could you specify more in detail which lines (with examples) you changed?
> 
> what I change
> 
> 1. android/build.gradle
> 
> ```
>     dependencies {
>         classpath 'com.android.tools.build:gradle:3.5.0'
>        //other
>     }
> ```
> 
> 1. android/gradle/wrapper/gradle-wrapper.properties
> 
> ` distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip`

ok, thank you. I am on a much higher version in either file (4.0.1 and 6.1.1)

**Comment by callmejm** [comment]
@pohpas before I change (3.5.0 and 5.6.2) was (4.0.1 and 6.1.1)

**Comment by pohpas** [comment]
@babaosoftware changing the gradle version and gradle plugin version as @callmejm suggested worked for me, too. 
Does that help, finding the cause of the issue?

**Comment by kustraslawomir** [comment]
@babaosoftware On the ios release application, the permission dialogs won't show too. 
https://github.com/Baseflow/flutter-permission-handler/issues/406

**Comment by babaosoftware** [comment]
@kustraslawomir I don't use this plugin for iOS, you don't need it. Not to mention it was forcing me add all sorts of unwanted permissions to the app. All you need for iOS is to add this to your Info.plist
	<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
	<string>Reason</string>
	<key>NSLocationAlwaysUsageDescription</key>
	<string>Reason</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>Reason</string>

**Comment by babaosoftware** [comment]
@kustraslawomir the previous post stripped the "key" and "string" tags, but you get the idea.

**Comment by TimHoogstrate** [comment]
Dear @pohpas,

I will close this issue because it does not seem relevant to me anymore. Feel free to reopen the issue if new information pops-up. 

Kind regards,

**Comment by Elyes159** [comment]
any solution ?
