### ISSUE TITLE
Caused by: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.ContactsProvider2 from ProcessRecord{...} (pid=29712, uid=10468) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS

### ISSUE THREAD

**Issue by giacomok** [Baseflow/flutter-permission-handler#384]
## 🐛 Bug Report

Even if I added this line in AndroidManifest.xml

`<uses-permission android:name="android.permission.READ_CONTACTS"/>`

This code line `Permission.contacts.request()` throws the error 

> Caused by: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.ContactsProvider2 from ProcessRecord{...} (pid=29712, uid=10468) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS

### Expected behavior

The app asks for `READ_CONTACTS` permissions

**Version:** 5.0.1+1

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android

**Comment by muarachmann** [comment]
Same issue here

**Comment by michaeldwu** [comment]
same issue here

**Comment by SpencerLindemuth** [comment]
Facing this issue as well

**Comment by SpencerLindemuth** [comment]
Actually solved this on my own. I was requesting the permission, but when the system prompt opened, in the background I pushed the new route that initiated a call to access the contacts and that call was causing the error because technically the permission hadn't been granted yet. Instead I waited for the Permission.contacts.request() call to return PermissionStatus.granted then pushed the new route to access contacts and all works as expected!

**Comment by dromeroSL** [comment]
Same issue here

**Comment by andropixels** [comment]
anybody has the solution??

**Comment by Khane1** [comment]
Same issue

**Comment by purvajg** [comment]
Any progress on this?

**Comment by Khane1** [comment]
This worked for me I don't know if it applies... Create a checker in your **permissions class** to see if the permissions are active.
`
**Permission checker**
  static Future<PermissionStatus> _contactsPermissions() async {
    PermissionStatus permission = await Permission.contacts.status;
    if (permission != PermissionStatus.granted &&
        permission != PermissionStatus.denied) {
      Map<Permission, PermissionStatus> permissionStatus =
          await [Permission.contacts].request();
      return permissionStatus[Permission.contacts] ??
          PermissionStatus.undetermined;
    } else {
      return permission;
    }
  }
}

**Boolean checker to check if permissions are granted**
  static Future<bool> contactPermissionsGranted() async {
    PermissionStatus contactsPermissionsStatus = await _contactsPermissions();
    if (contactsPermissionsStatus == PermissionStatus.granted) {
      return true;
    } else {
      return false;
    }
  }
**Finally where you use the actual function**
Permissions.contactPermissionsGranted()
        ? (await ContactsService.getContacts()).toList()
        : [];`

Hope this helps.

**Comment by JDDV** [comment]
Hi @giacomok, I tried to reproduce the issue, but I can't reproduce it.
The steps I took to reproduce are:

1. Create the standard flutter app
2. added in the ```pubspec.yaml``` the newest version of the plugin ```permission_handler: ^6.1.1```
3. In the _incrementCounter() method I do the request call using ```Permission.contacts.request()```
4. I accept/deny the permission

This seems to work using Android 9, 10, and 11.

<details>
 <summary> flutter doctor -v </summary>
[√] Flutter (Channel beta, 2.0.0, on Microsoft Windows [Version 10.0.19041.867], locale nl-NL)
    • Flutter version 2.0.0 at C:\Baseflow\flutter
    • Framework revision 60bd88df91 (4 weeks ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Jan-Derk\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Users\Jan-Derk\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.7042882\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\Jan-Derk\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.7042882
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at C:\Users\Jan-Derk\AppData\Local\JetBrains\Toolbox\apps\IDEA-C\ch-0\202.7660.26
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (3 available)
    • SM G780F (mobile) • RZ8R10RN1NF • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 89.0.774.57

• No issues found!
</details>

If the issue still exsist, can you provide a more information like flutter doctor -v, the android version you are using, and an example code? Thanks in advance!
