### ISSUE TITLE
IOS 14 Allow Apps Having Access to Local Network

### ISSUE THREAD

**Issue by HelloBytes** [Baseflow/flutter-permission-handler#387]
## 🚀 Feature Requests

In IOS 14, users have to give permission to access local network

**Comment by niktses** [comment]
any update on this?

**Comment by Abkholy** [comment]
any update on this ?

**Comment by ened** [comment]
This permission is requested & accepted _implicitly_ when a App tries to access the local network. Requesting it through this plugin may require a major workaround.

**Comment by KrystofM** [comment]
This is one "official" workaround I found for iOS apps: https://developer.apple.com/forums/thread/663768 
I am going to investigate this issue more, but I think there might be a way of just creating a dummy call in flutter to trigger the permission.

**Comment by jakobleck** [comment]
https://stackoverflow.com/questions/63525026/what-triggers-the-would-like-to-find-and-connect-to-devices-on-your-local-netwo#comment119607816_64210041

**Comment by mvanbeusekom** [comment]
At the moment both Android and iOS don't provide APIs to explicitly check or request local network permissions. 

On Android the `ACCESS_NETWORK_STATE` permission is considered a "normal permission" which means it is granted by default if the application declares it in its `AndroidManifest.xml` file. See also "[Connect to the network](https://developer.android.com/training/basics/network-ops/connecting)" article in the Android documentation.

On iOS the permissions are implicitly handled by the operating system as soon as on of the connection APIs are accessed. This means there isn't a reliable way for us to determine if permissions are granted or not.

In the light of this I will close this issue as "not planned".
