### ISSUE TITLE
Can we see all the Permission types supported by this Plugin?

### ISSUE THREAD

**Issue by aytunch** [Baseflow/flutter-permission-handler#391]
There is no such info in the plugins readme. I need to go through issues to find if PushNotifications, or Camera or Photos permissions are supported or not. 

If someone can at least reply here with all of the possible Apis it would be great.

Thanks

**Comment by mvanbeusekom** [comment]
You can look up `Permission` enum in the API reference to get a full (documented) overview of all possible permissions covered by this plugin. Here is a direct link: https://pub.dev/documentation/permission_handler_platform_interface/latest/permission_handler_platform_interface/Permission-class.html
