### ISSUE TITLE
How to request for READ_PHONE_STATE

### ISSUE THREAD

**Issue by avvari-da** [Baseflow/flutter-permission-handler#392]
## 💬 Questions and Help

What is the property that we need to request to get `READ_PHONE_STATE` permission?

**Comment by Sempakonka** [comment]
Hi,
I think `Permission.phone` shall request this permission.
Would love to hear if this was what you were looking for, so we can close this issue!

**Comment by pakeng** [comment]
Permission.phone just request  phone call  ，and I want get IMEI , there is no way.

**Comment by malbolged** [comment]
So ... ?
is it `Permission.phone` or not ?

**Comment by darixsamani** [comment]
How to request for READ_PHONE_STATE

**Comment by ADZF** [comment]
well, using permission_handler and use the Permission.phone.request() work just fine for me

**Comment by darix15** [comment]
Thanks
