### ISSUE TITLE
Execution failed for task ':permission_handler:parseDebugLibraryResources'

### ISSUE THREAD

**Issue by aloev** [Baseflow/flutter-permission-handler#393]
## 🐛 Bug Report

I have created a new flutter project with VS, imported permission_handler in my yaml, and the corresponding permission in my Android.manifest, but it is giving me an error.

My flutter version is 1.20.2, Dart: 2.9.1

This is the error I get

![Screen Shot 2020-09-22 at 11 04 20 AM](https://user-images.githubusercontent.com/67180148/93908387-2b643b00-fcc4-11ea-90ec-df4ad31134e1.png)

These are the permissions I imported on the Androidmanifest.xml
![Screen Shot 2020-09-22 at 11 15 27 AM](https://user-images.githubusercontent.com/67180148/93909118-0de3a100-fcc5-11ea-9125-56e4b115f888.png)

When I run flutter doctor -v the only issue I get is that I do not have Xcode installed ( As I am on a mac ) .

### Expected behavior

Deploy the app.

### Configuration

**Version:** 1.x

Permission_handler: ^5.0.1+1

**Platform:** 
- [ ] :iphone: iOS
- [ x] :robot: Android

As I am using an Android Emulator.

**Comment by Sempakonka** [comment]
It seems like it is having trouble with the android sdk.
Can you double check if you have configured the right android SDK (29) in flutter?
And if so, provide the output of `flutter doctor -v` command?
