### ISSUE TITLE
bad maintencance incompatible with other versions

### ISSUE THREAD

**Issue by paulobreim** [Baseflow/flutter-permission-handler#395]
I was using permission_handler: ^4.4.0+hotfix.1 and i my code the instrution:
await PermissionHandler()
          .requestPermissions([PermissionGroup.locationWhenInUse]);

Today I change to permission_handler: ^5.0.1+1 and there are no method PermissionHandler anymore.
the programmer who did this is certainly an amateur, and needs to learn that you can't change things that impact what already exists.
Want to change everything? Make another lib and leave the one that already worked quiet.

**Comment by mvanbeusekom** [comment]
Well I read up on semantic versioning and nicely incremented the mayor number indicating breaking changes.

If you don't like it look for something else.
