### ISSUE TITLE
The iOS location dialog cannot be displayed when a permission other than locationWhenInUse is requested.

### ISSUE THREAD

**Issue by dark-chocolate** [Baseflow/flutter-permission-handler#397]
## 🐛 Bug Report

When you request a permission using `Permission.locationAlways` or `Permission.location` in iOS, it doesn't popup system location dialog, however when I use `Permission.locationWhenInUse` it works. Every time before I request permission, I delete the app and do a fresh install.

`info.plist` file: 
```
<key>NSLocationAlwaysUsageDescription</key>
<string>This app needs access to location when in the background.</string>
<key>NSLocationWhenInUseUsageDescription</key>
<string>This app needs access to location when open.</string>
<key>UIBackgroundModes</key>
<array>
	<string>location</string>
</array>
```

### Expected behavior
It should pop up the location dialog like it does when the permission is `Permission.locationWhenInUse`. 

### Reproduction steps

Run this method on click of a button:

```
void checkPermission() async{
  var permission = Permission.locationAlways; // Works only for `Permission.locationWhenInUse`
  var status = await permission.status;
  if (status == PermissionStatus.undetermined) {
    status = await permission.request();
  }
}
```

### Versions
```
permission_handler: ^5.0.1+1
iOS: 14.0
Flutter: v1.23.0-7.0.pre
Dart: v2.7.2
```

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by JDDV** [comment]
Hi @dark-chocolate, the newest version of the permission_handler should work as expected, except for the `locationAlways` permission. To get the `locationAlways` permission to work you first have to request the `WhenInUse` permission, followed by the `locationAlways` request.

I see you've used the permission handler ^5.0.1+1, if you update to version ^8.0.0 or higher you need to update the podfile as mentioned in the documentation [here](https://github.com/Baseflow/flutter-permission-handler/tree/master/permission_handler#setup). I will close this issue for now, but feel free to open the issue if this did not solve your problem.
