### ISSUE TITLE
NEW PERMISSION

### ISSUE THREAD

**Issue by JeanRoldanDev** [Baseflow/flutter-permission-handler#398]
android.permission.ACCESS_LOCATION_EXTRA_COMMANDS
android.permission.LOCATION_HARDWARE

**Comment by ashleymooney123** [comment]
What does this mean? We have to include this permission now ? For the plugin to function ?

**Comment by jeancarlos2020** [comment]
no, you need these permissions if you are working in depth with gps

**Comment by JDDV** [comment]
Hi @JeanRoldanDev, I google searched the permissions, and from what I see on the internet it should be enough to just add those permissions to the AndroidManifest of your app.

For the ACCESS_LOCATION_EXTRA_COMMANDS it should be: `<uses-permission android:name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" />`
For the LOCATION_HARDWARE it should be: `<uses-permission android:name="android.permission.LOCATION_HARDWARE"/>`

I will close this issue for now, if it didn't work then please let me know!
