### ISSUE TITLE
wrong debug console message encoding in android studio 4.x

### ISSUE THREAD

**Issue by softboy99** [Baseflow/flutter-permission-handler#400]
wrong debug console message encoding in android studio 4.x

**Comment by Sempakonka** [comment]
Hi @softboy99,
Could you provide some more information?

- Summary description of the bug 
- Expectend behavior
- Reproduciton steps if possible
- Output of the `flutter doctor -v` command.

**Comment by etakuma** [comment]
like this?
```
permissionhandler\PermissionManager.java:321: �G���[: �V���{�����������܂���
            if (Build.VERSION.SDK_INT < Build.VERSION_CODES.S) {
```

This is NOT come from `flutter-permission-handler`.
Add `set DEFAULT_JVM_OPTS="-Dfile.encoding=UTF-8"` to gradle.bat (Windows), or gradle(others) to fix.
(Change UTF-8 for your locale)
