### ISSUE TITLE
I found a problem

### ISSUE THREAD

**Issue by zhuoCreator** [Baseflow/flutter-permission-handler#401]
After I agree to any permission and then close it from the system settings, it will not detect the shutdown. It will think that the permission is in the open state, so is the process killing and restarting.

**Comment by JDDV** [comment]
I don't entirely understand what you mean, can you elaborate a bit more on your problem?
What do you mean with 'close it from the system settings', and what do you exactly mean with 'the permission is in the open state'?

Do you mean that for example you allow the camera permission in your app, go to the settings of the app and turn the allowed permission off again (deny the camera permission), that it will not detect the status of the permission?

I would like to get some more information so I can help you better! Thanks in advance!
