### ISSUE TITLE
They are caused a new issue that flutter app could not determiner the correct localization strings  

### ISSUE THREAD

**Issue by LongXiangGuo** [Baseflow/flutter-permission-handler#402]
https://github.com/Baseflow/flutter-permission-handler/blob/eb7ef50a35be6023948147c08178844a317430d5/permission_handler/ios/Classes/strategies/LocationPermissionStrategy.m#L126

```
  case kCLAuthorizationStatusAuthorizedWhenInUse:
  case kCLAuthorizationStatusAuthorizedAlways:
                return PermissionStatusGranted;
```

expected results: 
```
  case kCLAuthorizationStatusAuthorizedWhenInUse:
                return PermissionStatusGrantedPartially;
  case kCLAuthorizationStatusAuthorizedAlways:
                return PermissionStatusGranted;
```

**Comment by LongXiangGuo** [comment]
Duplicate to #403

**Comment by JeroenWeener** [comment]
Hi @LongXiangGuo, thank you for filing this bug report.

I realize we are quite late to the party, as this bug has been open for almost 3 years.
The plugin does not distinguish between permissions being granted or partially granted. Could you tell us why you need `kCLAuthorizationStatusAuthorizedWhenInUse` to be labeled as such?
