### ISSUE TITLE
Scoped Storage Permission Request

### ISSUE THREAD

**Issue by msarkrish** [Baseflow/flutter-permission-handler#404]
## 🚀 Feature Requests

Android 11 must use Scoped Storage, so modify, deleting the file we need to ask permission from user. creating a file or directory also we need to ask permission.

![](https://www.solutionanalysts.com/wp-content/uploads/2020/03/1_FnKkxpDgq5y4ZJQtPiF4pg.png)

![](https://www.solutionanalysts.com/wp-content/uploads/2020/03/Android-Q.png)

### Describe the feature
Android 10 Introduces Scoped Storage, with Scoped storage app can't access all files directly. We need to ask permission for creating a file or directory, for modification we need to ask permission, In Android 10 we can avoid this by adding requestLegacyExternalStorage flag in AndroidManifest file. From Android 11 this flag will not work, we must need to use scoped storage.

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [x] :robot: Android

https://developer.android.com/about/versions/11/privacy/storage
https://developer.android.com/training/data-storage#scoped-storage
https://blog.mindorks.com/understanding-the-scoped-storage-in-android
https://www.solutionanalysts.com/blog/scoped-storage-in-android-10/

**Comment by JDDV** [comment]
Hi @msarkrish, thank you for your clear description of the feature request and the documentation links. This PR #185  includes the permission needed for scoped storage. Please let us know if this is the feauture you wanted to see implemented so this issue can be closed. Thanks in advance!

**Comment by JDDV** [comment]
@msarkrish, the 'MANAGE_EXTERNAL_STORAGE' is also implemented in version 7.0.0 of the permission handler.
