### ISSUE TITLE
Dont work Permission_handler in release mode

### ISSUE THREAD

**Issue by MonsterDKing** [Baseflow/flutter-permission-handler#406]
### Expected behavior
that such currently in debug mode works perfectly but at the moment of launching a release the allow_handler is totally without response

### Reproduction steps
Build apk 
install apk
Freezing

### Configuration
![image](https://user-images.githubusercontent.com/6463552/97282695-98f41180-1804-11eb-95ee-fb65b0590034.png)
![image](https://user-images.githubusercontent.com/6463552/97282729-a3161000-1804-11eb-9e1d-e0ebd5781509.png)

**Version:** 1.x
  permission_handler: ^5.0.1+1

**Platform:** 
- [ ] :iphone: iOS
- [x ] :robot: Android

Example : 

![image](https://user-images.githubusercontent.com/6463552/97282819-c214a200-1804-11eb-8d77-61df58f973bc.png)

i have this logs in debug mode all execute correctly

but in release mode 

nothing returns

**Comment by ashleymooney123** [comment]
I am having the same issue! Everything works in debug mode (android simulator & syncing app too my iPhone) but not when I upload to AppStore.

**Comment by kustraslawomir** [comment]
Same issue here!

**Comment by MonsterDKing** [comment]
help ?

**Comment by ashleymooney123** [comment]
Any news or suggestions to try?

**Comment by vitoramerico** [comment]
> Any news or suggestions to try?

try to do that in gradle.properties
android.enableR8=true
change to
android.enableR8=false

**Comment by Eliander** [comment]
Same problem, works perfectly in debug mode, no response in release mode.

**Comment by jhonantanErnane** [comment]
> try to do that in gradle.properties
> android.enableR8=true
> change to
> android.enableR8=false

thank you so much, I was searching for two days for any possible solutions, and was the only way that worked on my project.

**Comment by ktos** [comment]
It looks like it's some problem with minification/shrinking/ProGuard. 

Solved it with:

```
minifyEnabled false
useProguard false
shrinkResources false
```

added to release build type in `android/app/build.gradle`.

**Comment by simone40love** [comment]
Same issue. Using Visual Studio Code.

android.enableR8=false doesn't work.

I don't use proguard.

Please advise,

**Comment by sami-kouatli-act** [comment]
Same issue, none of the previous workaround seems to work.
Any new solution ?

**Comment by vitoramerico** [comment]
this should solve

1- change this in android/gradle.properties
org.gradle.jvmargs=-Xmx1536M
android.useAndroidX=true
android.enableJetifier=true

2- add this in android/app/build.gradle
buildTypes {
        release {
            minifyEnabled false
            useProguard false
            shrinkResources false
        }
}

3 - (optional) my versions in android/app/build.gradle
compileSdkVersion 30
minSdkVersion 21
targetSdkVersion 30

4 - version of the package i use
permission_handler: ^5.1.0+2

**Comment by erayhamurlu** [comment]
2- add this in android/app/build.gradle
buildTypes {
release {
minifyEnabled false
useProguard false
shrinkResources false
}
}

work fine Thanks

**Comment by JDDV** [comment]
I tried to reproduce the same issue by running the example app in release mode on a Samsung S20 FE (Android 11), I could not reproduce the issue though, the app didn't freeze. I used the newest version of the plug-in (version: ^6.1.1). Please let us know if the solutions mentioned here above don't work and this is still an issue that occurs. Thanks in advance!
