### ISSUE TITLE
Flutter & IOS : permission.camera.request() doesn't work on IOS device

### ISSUE THREAD

**Issue by punreachrany** [Baseflow/flutter-permission-handler#407]
I am using this permission_handle. My permission request was fine with android but not iOS.
My photo gallery request works just fine. But how come the camera request() doesn't work?

Dart 
await permission.photos.request(); // Working fine
await permission.camera.request(); // NOT WORKING

Info.plist
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>RecycleX</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(MARKETING_VERSION)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>fb3010934279005293</string>
			</array>
		</dict>
	</array>
	<key>CFBundleVersion</key>
	<string>$(CURRENT_PROJECT_VERSION)</string>
	<key>FacebookAppID</key>
	<string>3010934279005293</string>
	<key>FacebookDisplayName</key>
	<string>PhotoEarn</string>
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>fbapi</string>
		<string>fb-messenger-share-api</string>
		<string>fbauth2</string>
		<string>fbshareextension</string>
		<string>f860ce37bf409742799266b5b698b7d1</string>
		<string>kakaokompassauth</string>
		<string>storykompassauth</string>
		<string>kakaolink</string>
		<string>kakaotalk-5.9.7</string>
	</array>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSCameraUsageDescription</key>
	<string>NSMicrophoneUsageDescription</string>
	<key>NSLocationAlwaysUsageDescription</key>
	<string>This app doesn&apos;t need access to location when in the background.</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>This app needs access to location when open.</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>NSPhotoLibraryAddUsageDescription</string>
	<key>UIBackgroundModes</key>
	<array>
		<string>remote-notification</string>
	</array>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UIStatusBarStyle</key>
	<string>UIStatusBarStyleDarkContent</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIUserInterfaceStyle</key>
	<string>Light</string>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
</dict>
</plist>
```

Podfile
```
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'
project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}
def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end
  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end
require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)
flutter_ios_podfile_setup
# Added for OneSignal configuration for iOS devices
# https://documentation.onesignal.com/docs/flutter-sdk-setup
target 'OneSignalNotificationServiceExtension' do
  use_frameworks!
  pod 'OneSignal', '>= 2.9.3', '< 3.0'
end
target 'Runner' do
  use_frameworks!
  use_modular_headers!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
     # Here are some configurations automatically generated by flutter

      # You can remove unused permissions here
      # for more infomation: https://github.com/BaseflowIT/flutter-permission-handler/blob/develop/permission_handler/ios/Classes/PermissionHandlerEnums.h
      # e.g. when you don't need camera permission, just add 'PERMISSION_CAMERA=0'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',

        ## dart: PermissionGroup.calendar
        # 'PERMISSION_EVENTS=0',

        ## dart: PermissionGroup.reminders
        # 'PERMISSION_REMINDERS=0',

        ## dart: PermissionGroup.contacts
        # 'PERMISSION_CONTACTS=0',

        ## dart: PermissionGroup.camera
        'PERMISSION_CAMERA=0',

        ## dart: PermissionGroup.microphone
        # 'PERMISSION_MICROPHONE=0',

        ## dart: PermissionGroup.speech
        # 'PERMISSION_SPEECH_RECOGNIZER=0',

        ## dart: PermissionGroup.photos
        'PERMISSION_PHOTOS=0',

        ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
        'PERMISSION_LOCATION=0',

        ## dart: PermissionGroup.notification
        # 'PERMISSION_NOTIFICATIONS=0',

        ## dart: PermissionGroup.mediaLibrary
        # 'PERMISSION_MEDIA_LIBRARY=0',

        ## dart: PermissionGroup.sensors
        # 'PERMISSION_SENSORS=0'
      ]

    end
  end
end

```

**Comment by iwpz** [comment]
Look at your Podfile
`# e.g. when you don't need camera permission, just add 'PERMISSION_CAMERA=0'`
Uncomment items you don't needed,  but uncomment what you need to use.

And in your Info.plist you have this:
`<key>NSCameraUsageDescription</key>
<string>NSMicrophoneUsageDescription</string>`

I don't know if you saw NSMicrophoneUsageDescription Alert and you think it's microphone access.

**Comment by Omrankabalan** [comment]
Any updates ?

**Comment by wiktoriasobczyk** [comment]
I have the same problem :/

**Comment by punreachrany** [comment]
@wiktoriasobczyk @Omrankabalan I couldn't get the camera permission because I added this `'PERMISSION_CAMERA=0',` in my pod file

**Comment by Omrankabalan** [comment]
@punreachrany I don't have this 'PERMISSION_CAMERA=0' in my podfile

**Comment by Omrankabalan** [comment]
> So, turns out, this is not a bug but the expected result on iOS (as per this [SO answer](https://stackoverflow.com/a/29980902/10758800)).

**Comment by charlbarrera** [comment]
I have the same issue :( I read, that it's normal, because the request for permission happens once, if the user deny, it won't appear again. But in my case, with my device this request for permissions never happen the first time. I think that the comment #405 above is talking about it. Someone else has extra information?

**Comment by iwpz** [comment]
> I have the same issue :( I read, that it's normal, because the request for permission happens once, if the user deny, it won't appear again. But in my case, with my device this request for permissions never happen the first time. I think that the comment #405 above is talking about it. Someone else has extra information?

If your problem is around iOS, just check your Info.plist, maybe you miss some NS**UsageDescription
For make sure this, just run your app with Xcode and look at the console

> This app has attempted to access privacy-sensitive data without a usage description. The app's Info.plist must contain both “NSLocationAlwaysAndWhenInUseUsageDescription” and “NSLocationWhenInUseUsageDescription” keys with string values explaining to the user how the app uses this data

And the exception in flutter console when you request again:

> Unhandled Exception: PlatformException(ERROR_ALREADY_REQUESTING_PERMISSIONS, A request for permissions is already running, please wait for it to finish before doing another request (note that you can request multiple permissions at the same time)., null, null)

Hope help.

**Comment by charlbarrera** [comment]
@iwpz thanks!, I descovered that my problem was that I was expecting at least the window asking me for permissions in my ios emulator. But it is not possible. I tried in a real device and everything was perfect.

**Comment by mvanbeusekom** [comment]
Closing issue as seems to be solved according to this [comment](https://github.com/Baseflow/flutter-permission-handler/issues/407#issuecomment-756697325).

**Comment by urvashihirpara** [comment]
I added 'PERMISSION_CAMERA=0' in my podfile. but it doesn't work.

**Comment by mvanbeusekom** [comment]
@urvashihirpara You are probably using version 8.0.0 or higher, please carefully read the:

- [CHANGELOG.md](https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler/CHANGELOG.md#800)
- [README.md (iOS section)](https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler/README.md)
- Issue #596

**Comment by milanobrenovic** [comment]
> Adding 'PERMISSION_CAMERA=1' in pod.file in my flutter app work
> 
> ```
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     flutter_additional_ios_build_settings(target)
>     target.build_configurations.each do |config|
>                 config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
>                    '$(inherited)',
>                    ## dart: PermissionGroup.camera
>                    'PERMISSION_CAMERA=1'
>                  ]
>      end
>   end
> end
> ```

i added the same but for contacts and i still get `PermissionStatus.permanentlyDenied`

**Comment by akhiljohny** [comment]
post_install do |installer|
installer.pods_project.targets.each do |target|
flutter_additional_ios_build_settings(target)
target.build_configurations.each do |config|
config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
'$(inherited)',
#comment dart: PermissionGroup.camera
'PERMISSION_CAMERA=1'
]
end
end
end

Add this in pod file and delete pod lock and pod install then it will work

**Comment by ricardogobbo** [comment]
Is it normal the option for camera permission is not present on app configs? I've tried all this stuff but nothing works.

**Comment by hassan-2040** [comment]
Any ideas what to do on macOS? PermissionHandler doesnt work on macOS, can anyone suggest me a workaround?

**Comment by Mounix99** [comment]
> Is it normal the option for camera permission is not present on app configs? I've tried all this stuff but nothing works.

+1 no camera option on release
