### ISSUE TITLE
iOS never reports PermissionStatus.permanentlyDenied, only PermissionStatus.denied is reported

### ISSUE THREAD

**Issue by yanivshaked** [Baseflow/flutter-permission-handler#408]
## 🐛 Bug Report

Even after user denies permissions and the OS popup is not displayed, the value reported is PermissionStatus.denied instead of PermissionStatus.permanentlyDenied.

### Expected behavior
If user already rejected the permissions, the value returning on subsequent calls should be PermissionStatus.permanentlyDenied.

### Reproduction steps
On iOS, request for contacts permissions, deny them and ask for the same permissions again.

### Configuration

**Version:** 5.0.1+1

**Platform:** 
- [X] :iphone: iOS

**Comment by yanivshaked** [comment]
I just read the code comments saying that PermissionStatus.permanentlyDenied is only supported by Android. Closing.

**Comment by thphuc** [comment]
I saw that part of the comment too, however when I tested on iPhone 11, iOS 14.5 (simulator), when tapping on Don't allow, the status is **PermissionStatus.permanentlyDenied**. Confusing!
