### ISSUE TITLE
AppStoreConnect ITMS-90683 NSLocationWhenInUseUsageDescription

### ISSUE THREAD

**Issue by krgutierrez** [Baseflow/flutter-permission-handler#409]
## 🐛 Bug Report
I am encountering *ITMS-90683* which tells me that I need to specify *NSLocationWhenInUseUsageDescription* in my info.plist. 

I DON'T use the location permission and I already set `PERMISSION_LOCATION` to 0.

`'PERMISSION_LOCATION=0',`

### Expected behavior
Permission should not be added and so it will be accepted by AppStoreConnect

### Reproduction steps
1. Add the code below to Podfile
2. run `Flutter build ios --release`
3. Archive via XCode
4. Upload
5. Wait for e-mail from AppStoreConnect about binary rejection.

### Configuration
Flutter 1.22.2
Dart 2.10.2
Podfile additional code to remove permission:

    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'

      # Here are some configurations automatically generated by flutter
      # You can remove unused permissions here
      # for more infomation: https://github.com/BaseflowIT/flutter-permission-handler/blob/develop/permission_handler/ios/Classes/PermissionHandlerEnums.h
      # e.g. when you don't need camera permission, just add 'PERMISSION_CAMERA=0'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        ## dart: PermissionGroup.calendar
        'PERMISSION_EVENTS=0',

        ## dart: PermissionGroup.reminders
        'PERMISSION_REMINDERS=0',

        ## dart: PermissionGroup.contacts
        'PERMISSION_CONTACTS=0',

        ## dart: PermissionGroup.camera
        # 'PERMISSION_CAMERA=0',

        ## dart: PermissionGroup.microphone
        #'PERMISSION_MICROPHONE=0',

        ## dart: PermissionGroup.speech
        'PERMISSION_SPEECH_RECOGNIZER=0',

        ## dart: PermissionGroup.photos
        # 'PERMISSION_PHOTOS=0',

        ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
        'PERMISSION_LOCATION=0',

        ## dart: PermissionGroup.notification
        'PERMISSION_NOTIFICATIONS=0',

        ## dart: PermissionGroup.mediaLibrary
        'PERMISSION_MEDIA_LIBRARY=0',

        ## dart: PermissionGroup.sensors
        'PERMISSION_SENSORS=0'
      ]
    end
`

**Version:** 1.x
5.0.1+1

**Platform:** 
- [x] :iphone: iOS

**Comment by dgilperez** [comment]
I just got notified on Google Play / Android for the same reason, with LocationAlways or background location.

**Comment by krgutierrez** [comment]
I found the cause of this issue. I am using the `Connectivity` library which uses permission.

**Comment by dgilperez** [comment]
Oh crap, same here. Thanks @krgutierrez
