### ISSUE TITLE
Get informed when App-Settings is closed after opening with openAppSettings

### ISSUE THREAD

**Issue by ReveredMachine** [Baseflow/flutter-permission-handler#410]
## 🚀 Feature Requests

After opening the App-Settings with openAppSettings, it would be helpful to be informed in case it is closed in order to update the App.

### Contextualize the feature
The Intent beeing used in the AppSettingsManager could do something like activity.startActivityForResult

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [ X ] :robot: Android

**Comment by JDDV** [comment]
Hi @ReveredMachine, I'm afraid the `openAppSettings` implementation is not possible to return that information. A good solution would be to save the `bool` value that `openAppSettings` returns in a variable, and keep track of the AppLifeCycle when you get back to the app from the settings screen. The AppLifeCycle will be `AppLifecycleState.paused` when going into the settings screen. When returning back to your app the AppLifeCycle status will be `AppLifecycleState.resumed`. When it goes back to the 'resume' state, and the boolean variable from `openAppSettings()` is set to true, than you know that you've returned from the app settings. Documentation on how to use the AppLifeCycle can be found [here](https://levelup.gitconnected.com/app-lifecycle-in-flutter-e4ba686d16fe).
