### ISSUE TITLE
How to determine calendar permission status in Android?

### ISSUE THREAD

**Issue by wanchao-xu** [Baseflow/flutter-permission-handler#417]
## 💬 Questions and Help

For questions or help we recommend checking:

- There are two permissions about calendar in android platform, READ_CALENDAR and WRITE_CALENDAR. If used allow the READ_CALENDAR and deny WRITE_CALENDAR, wh's the result status of calendar?

**Comment by Sempakonka** [comment]
If not requested by this plug-in it will return as not determined, if GENERIC_PREFERENCES is not set. If requested by this plug-in it will request both constants.

**Comment by JDDV** [comment]
Hello @XuWanchaoS, I'm not sure what your question exactly is, can you provide a bit more information?

I added the permission options for the calendar permission in the AndroidManifest 
```<uses-permission android:name="android.permission.READ_CALENDAR" />```
```<uses-permission android:name="android.permission.WRITE_CALENDAR" />```

When using ```PermissionStatus permission = await Permission.calendar.request();``` it will ask a single question 'Allow <app name> to access your calendar?'. This pop-up permission question will also come up even if you only have one of the two ```android.permission.READ_CALENDAR``` or ```android.permission.WRITE_CALENDAR``` in the AndroidManifest.

When clicking allow the ```Permission.Status``` will be ```PermissionStatus.granted```
When clicking deny the ```Permission.Status``` will be ```PermissionStatus.denied```

I hope this will answer your question, if not please provide us with more information
