### ISSUE TITLE
ios location quest no result 

### ISSUE THREAD

**Issue by lmr520** [Baseflow/flutter-permission-handler#418]
### Expected behavior
await Permission.location
          .request()
### Reproduction steps
no result
### Configuration

**Version:** 5.1

**Platform:** 
- [ ] :iphone: iOS

PlatformException(ERROR_ALREADY_REQUESTING_PERMISSIONS, A request for permissions is already running, please wait for it to finish before doing another request (note that you can request multiple permissions at the same time)., null, null)

**Comment by zgosalvez** [comment]
@lmr520 were you able to resolve this, if so how? I'm encountering the same issue.

**Comment by lmr520** [comment]
like add
<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
	<string>This app needs access to location when open and in the background.</string>
	<key>NSLocationAlwaysUsageDescription</key>
	<string>App需要您的同意, APP才能始终访问位置</string>
	<key>NSLocationUsageDescription</key>
	<string>需要您的同意, APP才能访问位置</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>App需要您的同意, APP才能在使用期间访问位置</string>
in info.polist

**Comment by zgosalvez** [comment]
Thanks for getting back to me @lmr520. Strange. We already have those. Have you encountered this? https://github.com/Baseflow/flutter-permission-handler/issues/386

**Comment by zgosalvez** [comment]
Ok. We got it to work by using the correct `Info.plist` keys.
