### ISSUE TITLE
Migrate package to support sound null safety

### ISSUE THREAD

**Issue by divyanshub024** [Baseflow/flutter-permission-handler#419]
## 🏗 Enhancement Proposal

With sound null safety in beta we should migrate the project to support it. Users using in Flutter beta will get this dart analysis warning. 

```
info: The library 'package:permission_handler/permission_handler.dart' is legacy, and should not be imported into a null safe library.
```

### Migration guide

https://dart.dev/null-safety/migration-guide

**Comment by alfinbi** [comment]
any progress?

**Comment by SirusCodes** [comment]
Is this worked upon?

**Comment by kushalgoel786** [comment]
Any update ?

**Comment by savs90** [comment]
Any update on this one ? We have null safety on stable already and i think all package dependencies are already migrated to null safety

**Comment by SirusCodes** [comment]
I guess it is worked on but latest package is not published yet...

**Comment by LuisGrt** [comment]
Hello, I consider this topic critical. It is holding back several dependencies from migrating to null-safety.

Do we already have a date for this?

**Comment by JDDV** [comment]
plugin is migrated to nullsafety since version ^6.0.0
