### ISSUE TITLE
iOS 14 Tracking permission

### ISSUE THREAD

**Issue by chris-rutkowski** [Baseflow/flutter-permission-handler#426]
Hey, as per title, would you add a possibility to check the tracking permission status and to request the permission?

Appreciate, great plugin.

**Comment by aloisdeniel** [comment]
Any plan to include this permission?

It is [now mandatory for iOS 14.5](https://developer.apple.com/app-store/user-privacy-and-data-use/).

**Comment by firatcetiner** [comment]
This permission is included with the latest version of this plugin.

`await Permission.appTrackingTransparency.request()`

However, the PermissionStatus always returns `PermissionStatus.denied` and the permission request doesn't work, at least on iOS 14.4. I haven't been able to test it on 14.5.

**Comment by magicleon94** [comment]
Hi, looking at the [example](https://github.com/Baseflow/flutter-permission-handler/blob/089b6bd239fde462c42e0a6298ce0f076093a28e/permission_handler/example/lib/main.dart#L55) for the latest version it seems they've implemented it!

**Comment by JDDV** [comment]
Hi @chris-rutkowski and @aloisdeniel, this has indeed be added since version `^8.0.0`.
This issue will be closed for now.

**Comment by furkay** [comment]
I have to use non-null-safety package and i need this. Are you considering adding it for non-null packages?

**Comment by firatcetiner** [comment]
> I have to use non-null-safety package and i need this. Are you considering adding it for non-null packages?

@furkay You can use the latest version of this package in your non-nullsafe projects. There is no need to use another non-nullsafe version of this package since null-safety feature is backwards compatible. See [this](https://dart.dev/null-safety/migration-guide).
