### ISSUE TITLE
Feature request: monitor state of permissions for usage of local network

### ISSUE THREAD

**Issue by Quietly-20201113** [Baseflow/flutter-permission-handler#427]

**Comment by renefloor** [comment]
Please could you provide a clear english description? We cannot give support in all languages, so for us it is best to do everything in English.

**Comment by tmacLiu001** [comment]
> Please could you provide a clear english description? We cannot give support in all languages, so for us it is best to do everything in English.

His question is：’IOS and some Android phones have the function of denying network permissions, but they cannot monitor whether they are disabled or not‘

**Comment by MadeBugs** [comment]
me too,have the same problem

**Comment by 1x2x3x4x** [comment]
I think he's talking about this: https://stackoverflow.com/questions/63940427/ios-14-how-to-trigger-local-network-dialog-and-check-user-answer

That's would be indeed helpful to have nu I'm not sure it's possible at least just for now on iOS.

**Comment by Sempakonka** [comment]
related to #387

**Comment by mvanbeusekom** [comment]
At the moment both Android and iOS don't provide APIs to explicitly check or request local network permissions. 

On Android the `ACCESS_NETWORK_STATE` permission is considered a "normal permission" which means it is granted by default if the application declares it in its `AndroidManifest.xml` file. See also "[Connect to the network](https://developer.android.com/training/basics/network-ops/connecting)" article in the Android documentation.

On iOS the permissions are implicitly handled by the operating system as soon as on of the connection APIs are accessed. This means there isn't a reliable way for us to determine if permissions are granted or not.

In the light of this I will close this issue as "not planned".
