### ISSUE TITLE
openAppSettings not opening App Settings Menu.

### ISSUE THREAD

**Issue by VOIDCRUSHER** [Baseflow/flutter-permission-handler#429]
## 🐛 Bug Report

When the storage permission is permanently denied by selecting 'deny' on the permission request dialog menu twice, calls to openAppSettings return with a `true` result without actually navigating to the settings menu. This is the worst case for the developer since the result value doesn't notify the application that anything went wrong, leaving the application permanently locked out without more intelligent intervention from the end user.

### Expected behavior

Open System settings menu when permission is permanently denied and print `true` on exit or else print `false` if the settings menu could not be opened.

### Reproduction steps

Flutter 1.22.4

```dart
  var galleryWritePermission = Permission.storage;
  var permissionStatus = await galleryWritePermission.status;
  // Gallery write permissions are required so if the user has opted to
  // never see the permissions dialog, we have to send them to the
  // system's settings to manually permit it.
  if (permissionStatus.isPermanentlyDenied) {
    print('${await openAppSettings()}'); // returns true but does not actually open the app settings
  }
  // Request gallery write permissions if not permanently denied. If successful,
  // the user may continue to make their selection.
  // Otherwise, we back out and the user may try again.
  permissionStatus = await galleryWritePermission.request();
  if (!permissionStatus.isGranted) return;

 ////// APPLICATION CODE //////
```

### Configuration

**Version:** 5.0.1+1

**Platform:** 
- [ ] : iphone: iOS
- [ x] :robot: Android API 29

**Comment by Sempakonka** [comment]
Hi,
I think the reason why this behaviour is occuring is because you make a request directly after you open the app setings. The plugin does actually open settings app, or at least it completes the intent. Thats why `await openAppSettings()` returns `true`.
The flutter app re-opens when `await galleryWritePermission.request();` runs. 

Anyway, I think a workaround would be something like this:
```
    var galleryWritePermission = Permission.storage;
    var permissionStatus = await galleryWritePermission.status;
    
    if (permissionStatus.isPermanentlyDenied) {
      await openAppSettings();
    } else if (!permissionStatus.isGranted) {
      permissionStatus = await galleryWritePermission.request();
    }

    if (!permissionStatus.isGranted) return;
```
 Thus ensuring no request gets executed after the intent has ran.
I also don't exactly understand why you would want to request permissions if it could have been pernamently denied. :D

**Comment by VOIDCRUSHER** [comment]
@Sempakonka Thanks, I got it working with the following.

```dart
var galleryWritePermission = Platform.isAndroid ? Permission.storage : Permission.photos;
  var permissionStatus = await galleryWritePermission.status;
  // Gallery write permissions are required so if the user has opted to
  // never see the permissions dialog, we have to send them to the
  // system's settings to manually permit it.
  if (permissionStatus.isPermanentlyDenied) {
    await openAppSettings();
  }
  else {
    permissionStatus = await galleryWritePermission.request();
  }
  if (!permissionStatus.isGranted) return;
```

Think the key insight here was

> The flutter app re-opens when await galleryWritePermission.request(); runs.

I was most likely mistaken. From the permission-handler documnentation, it was my understanding was that if if a permission was permanently denied, then `await *.request()` would essentially be a no-op just as is the case when the permission is granted. Thanks for the help. I'll close the ticket now.

**Comment by zainulhassan815** [comment]
I have struggled a lot with this issue and finally come to a solution which works fine for me. I have noticed that if you call `.status` on a permission, the result obtained is not proper in cases when permission is permanently denied. It returns `PermissionStatus.denied` even when I have permanently denied the permission. So the fix is quite simple. Instead of calling `.status` on a permission, call `.request` method as it returns Permission Status. This status returned is proper and works fine.

```
  Future<PermissionStatus?> askPermission() async {
    Permission _permission = Permission.storage;
    PermissionStatus _status = await _permission.request();
    if (_status.isPermanentlyDenied) {
      print('denied');
      await openAppSettings();
    }
    return _status;
  }
```

This function works fine for me.

**Comment by zzyakenzz** [comment]
> I have struggled a lot with this issue and finally come to a solution which works fine for me. I have noticed that if you call `.status` on a permission, the result obtained is not proper in cases when permission is permanently denied. It returns `PermissionStatus.denied` even when I have permanently denied the permission. So the fix is quite simple. Instead of calling `.status` on a permission, call `.request` method as it returns Permission Status. This status returned is proper and works fine.
> 
> ```
>   Future<PermissionStatus?> askPermission() async {
>     Permission _permission = Permission.storage;
>     PermissionStatus _status = await _permission.request();
>     if (_status.isPermanentlyDenied) {
>       print('denied');
>       await openAppSettings();
>     }
>     return _status;
>   }
> ```
> 
> This function works fine for me.

Hi @zainulhassan815 , But how I do if I only need the status to show my custom popup ( popup tell user go to settings)?

The expectation: get status >> show custom popup >> request() permission

The wrong:  request() permission ( show OS's popup) >> get isPermanentlyDenied >> show custom popup(WRONG)

I checked that: 
+ iOS: Permission.camera.status ( OK, isPermanentlyDenied is working)
+ Android: Permission.camera.status ( NO, always return denied status although I choose option "Don't ask again" )
I don't know somebody meet this case like me

**Comment by MiroslavZB** [comment]
I believe this is the best solution I stumbled across. This is the onPressed function of my button that opens the app settings. [onPressed: () async {
                      await openAppSettings();
                      BasicMessageChannel<String?> lifecycleChannel = SystemChannels.lifecycle;
                      lifecycleChannel.setMessageHandler((msg) async {
                        if (msg!.endsWith("resumed")) {
                          lifecycleChannel.setMessageHandler(null);
                          List permissionslist = [
                            await Permission.locationWhenInUse.isGranted,
                            await Permission.bluetoothConnect.isGranted,
                            await Permission.bluetoothScan.isGranted,
                            await Permission.storage.isGranted
                          ];
                          if (permissionslist.firstWhereOrNull((element) => element != true) ==
                              null) {
                            setState(() => arePermissionsGiven = true);
                          }
                          else {
                            setState(() => arePermissionsGiven = false);
                          }
                        }
                        return Future(() => null);
                      });
                    }](url)
