### ISSUE TITLE
Switch detection of notification messages on iOS

### ISSUE THREAD

**Issue by yy1300326388** [Baseflow/flutter-permission-handler#43]
## 🚀 Feature Requests

On the iOS platform, the permission check for message notifications is urgently needed.

### Describe the feature
Check the permissions as you do for other permissions. If you refuse, open the settings page.

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by laurisvan** [comment]
+1

**Comment by darren-f5s** [comment]
How is this not implemented yet?

**Comment by JDDV** [comment]
Hi @yy1300326388, I just checked for the notification permission by using the example app included in the permission-handler repo. I do see a permission called Permission.notification, Is this the one you meant? Please let us know so the issue can be closed.

**Comment by yy1300326388** [comment]
@JDDV  What i want is this https://stackoverflow.com/a/1535427/4501068

**Comment by JDDV** [comment]
Hi @yy1300326388, after careful consideration we decided to not implement this feature since it's not the responsibility of the permission handler to handle the settings status of the notifications. The permission handler can be used to see if the user allowed the permission for notifications.
