### ISSUE TITLE
Add iOS Motion and Fitness permission

### ISSUE THREAD

**Issue by dark-chocolate** [Baseflow/flutter-permission-handler#430]
## 🚀 Feature Requests
Add the Motion and Fitness permission on iOS.

### Contextualize the feature
To use Pedometer feature on iOS, we need this permission.

![IMG_737AAD3B3999-1](https://user-images.githubusercontent.com/40364434/102445278-69ef6480-402b-11eb-9b95-89894d10407a.jpeg)

### Describe the feature
Currently in Android, we're using `Permission.activityRecognition` but it doesn't do anything on iOS, why not make this work for Motion and Fitness on the iOS?

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by bikcrum** [comment]
Related to #379

**Comment by JDDV** [comment]
@dark-chocolate, this is included in the `Permission.sensors`.
I will close this issue, if you still have questions about it then please feel free to ask!
