### ISSUE TITLE
The app's Info.plist file should contain a NSLocationAlwaysUsageDescription IOS 

### ISSUE THREAD

**Issue by AmjadKhan2k18** [Baseflow/flutter-permission-handler#432]
## 💬 Questions and Help

``` 
We identified one or more issues with a recent delivery for your app, "My_App 0.0.9 (0.0.9). 
Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that 
access sensitive user data. The app's Info.plist file should contain a NSLocationAlwaysUsageDescription 
key with a user-facing purpose string explaining clearly and completely why your app needs the data.
``` 

after adding permission_handler i had same error in 0.0.7 version but it was solved by adding these lines in pod file and it solved. now i uploaded 0.0.9 version and i got email again.

i am using location but i don't need it Always so i added.

i have added `NSLocationWhenInUseUsageDescription` in info.plist file & `## dart: PermissionGroup.locationAlways` `         'PERMISSION_LOCATION=0',` to avoid using location always but i am still getting error for always location how do i solve it ? 

**POD**
``` 
 ## dart: PermissionGroup.calendar
         'PERMISSION_EVENTS=0',

        ## dart: PermissionGroup.reminders
         'PERMISSION_REMINDERS=0',

        ## dart: PermissionGroup.contacts
         'PERMISSION_CONTACTS=0',

        ## dart: PermissionGroup.camera
        # 'PERMISSION_CAMERA=0',

        ## dart: PermissionGroup.microphone
         'PERMISSION_MICROPHONE=0',

        ## dart: PermissionGroup.speech
         'PERMISSION_SPEECH_RECOGNIZER=0',

        ## dart: PermissionGroup.photos
        # 'PERMISSION_PHOTOS=0',

        ## dart: PermissionGroup.locationAlways
         'PERMISSION_LOCATION=0',

        ## dart: PermissionGroup.notification
        # 'PERMISSION_NOTIFICATIONS=0',

        ## dart: PermissionGroup.mediaLibrary
         'PERMISSION_MEDIA_LIBRARY=0',

        ## dart: PermissionGroup.sensors
         'PERMISSION_SENSORS=0'
```

**Comment by sergiocasero** [comment]
Yep, I have the same issue

**Comment by AmjadKhan2k18** [comment]
> Yep, I have the same issue
> 
> Edit: After flutter clean it just works

i will test in next build Thanks

**Comment by patelnirav48** [comment]
> Yep, I have the same issue
> 
> Edit: After flutter clean it just works

I tried it but not working for me. I had to add permission in plist with description "The app doesn't require access to location".

**Comment by HetalGohil** [comment]
i have added this plugin...i m also getting this error..even i have not used this permission but mail from app store pls add in info.plist..how to solve that

**Comment by mahessh29** [comment]
I am facing this issue too. Is there any way to fix it? @AmjadKhan2k18 was you able to fix it?

**Comment by Hasilt** [comment]
Any update on this issue? removing permission that I do not use in the app is not working. I'm using xcode 12 and flutter 2.0.1

**Comment by mahesh2904** [comment]
My iOS build accepted by Apple Store by adding the following lines in plist.info

<key>NSLocationAlwaysUsageDescription</key>
<string>[App Name] app doesn't require access to location when in the background.</string>

**Comment by JDDV** [comment]
Hi @AmjadKhan2k18, the newest version of the `permission_handler` plugin (version `^8.1.4+2`) should fix this problem.
In the [`info.plist`](https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler/example/ios/Runner/Info.plist) from the `permission_handler` example app you can see the `NSLocationWhenInUseUsageDescription` key and value.

If you use the newest version of the plugin, make sure you read the setup part of the documentation since the podfile should be changed because of a change in version `^8.0.0`.

I'll close this issue for now since I'm pretty sure this would fix the problem, if there are any questions please feel free to ask.
