### ISSUE TITLE
error: The getter 'status' isn't defined for the type 'Permission'. (undefined_getter at [feelsafe] lib\managerDetails.dart:271)

### ISSUE THREAD

**Issue by jordantsap** [Baseflow/flutter-permission-handler#434]
permission_handler: ^5.0.1+1

flutter doctor -v
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19042.685], locale en-US)
    • Flutter version 1.22.5 at D:\flutter
    • Framework revision 7891006299 (4 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:/Users/jordan/AppData/Local/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:/Users/jordan/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\jordan\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.0

[√] Connected device (1 available)
    • M2003J15SC (mobile) • 059ce7280405 • android-arm64 • Android 10 (API 29)

# No issuie when using:

// sms permission function on screen Initialization
void askSmsPermission() async {
  var smsStatus = await Permission.sms.status;
  if (Platform.isAndroid) {
    if (smsStatus.isUndetermined) {
      print("Sms permission is undetermined");
      await Permission.sms.request();
    } else if (smsStatus.isDenied) {
      print('Sms permission isDenied');
      await Permission.sms.request();
    } else if (smsStatus.isPermanentlyDenied) {
      print("Sms permission isPermanentlyDenied");
      BuildContext context;
      Navigator.push(
        // or snackbar
        context,
        new MaterialPageRoute(
            builder: (context) => new UserPermanentDeny()),
      );
    } else if (smsStatus.isGranted) {
      print('Sms permission is Granted, go on');
    }
  } else {
    print("Apple mobile");
  }
}
# but the error shows when:
void _sendSms() async {
    print("SendSms Start");
    // var smsStatus = await Permission.sms.status;
    if (await Permission.sms.isGranded) {
      openAppSettings();
    } else {
      await Smsker.sendSms(
          phone: bookerPhoneController.text,
          message:
          "New user from feelsafe application needs permission, userphone number: ${userPhoneController
              .text} ");
      print("Send Sms End");
    }
  }

**Comment by Sempakonka** [comment]
You have made a typo.
`await Permission.sms.isGranded`
should be
`await Permission.sms.isGranted`
Let me know if this solves the issue!

**Comment by jordantsap** [comment]
I t was o typo in the initial github issue, i changed it to:
error: The getter 'status' isn't defined for the type 'Permission'. (undefined_getter at [feelsafe] lib\managerDetails.dart:271) #434

**Comment by JDDV** [comment]
@jordantsap I t hink Sempakonka meant that you had a typo in the code.
```
void _sendSms() async {
       print("SendSms Start");
       // var smsStatus = await Permission.sms.status;
       if (await Permission.sms.isGranded) {
              openAppSettings();
       } else ...
```

is the code where the error shows according to your issue. the line ```if (await Permission.sms.isGranded)``` should be changed to ```if (await Permission.sms.isGranted)```. The difference is in ```isGran*D*ed``` and ```isGran*T*ed ```. Let me know if this solved your issue!
