### ISSUE TITLE
[4.2.0+hotfix.3] storage permission is granted but permission denied when trying to write to downloads folder

### ISSUE THREAD

**Issue by stijnie2210** [Baseflow/flutter-permission-handler#435]
## 🐛 Bug Report

I'm running a version of the package a bit older, but basically I would like to download a file and write it to the downloads folder. I request the permission for storage and I can see in my logs it is granted, but when I try to write the file it gives me an OS error with permission denied.

### Expected behavior
Being able to write to the external downloads folder on Android without getting permission problems.

### Reproduction steps
install version `4.2.0+hotfix.3` of the package, try to write a file to any folder in external storage

### Configuration

**Version:** 4.2.0+hotfix.3

**Platform:** 
- [ ] :iphone: iOS
- [x ] :robot: Android

Update 14-01-2021:
I've updated to the latest version, but still i'm getting permission denied on writing to the Download folder on Android.

**Comment by Clashkid155** [comment]
Android 11?

**Comment by stijnie2210** [comment]
@Clashkid155 Android 10, probably should’ve mentioned that

**Comment by leanhro2812** [comment]
Same problem, But on IOS

**Comment by shatanikmahanty** [comment]
Can you confirm that you have added `android:requestLegacyExternalStorage="true"` under `application` tag in androidmanifest.xml

**Comment by stijnie2210** [comment]
@shatanikmahanty wow, I can't believe I actually forgot to add that tag.. That solved my current issue! My follow up question is actually will it be impossible to access the Download folder from Android 11 on?

**Comment by shatanikmahanty** [comment]
https://developer.android.com/about/versions/11/privacy/storage 
You can find all information on how to access storage for android 11 from the above link

**Comment by daybson** [comment]
Same issue here:
I can read the /Downloads directory, but cant write on Android 11 (emulator and physical device)

```
compileSdkVersion 30
minSdkVersion 21
targetSdkVersion 29
```
app\src\main\AndroidManifest.xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.xxx.zzz">
    <application      
        android:requestLegacyExternalStorage="true"  
        android:allowBackup="false"
        android:label="xxx"
        android:icon="@mipmap/ic_launcher">
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
        <meta-data 
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-999999999"/>
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        
        <provider
        android:name="androidx.core.content.FileProvider"
        android:authorities="${applicationId}.provider"
        android:exported="false"
        android:grantUriPermissions="true">
         <meta-data
           android:name="android.support.FILE_PROVIDER_PATHS"
          android:resource="@xml/provider_paths"/>
        </provider>    
    </application>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_INTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="com.android.vending.BILLING"/>
    <uses-permission android:name="android.permission.INTERNET"/> 
</manifest>


```

[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [versÃ£o 10.0.19043.1165], locale pt-BR)
    • Flutter version 2.2.3 at C:\src\flutter
    • Framework revision f4abaa0735 (10 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\daybs\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java      
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31624.102
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.60.0)
    • VS Code at C:\Users\daybs\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[√] Connected device (5 available)
    • Moto G 5S Plus (mobile)    • 0040665429    • android-arm64  • Android 11 (API 30)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 11 (API 30) (emulator)
    • Windows (desktop)          • windows       • windows-x64    • Microsoft Windows [versÃ£o 10.0.19043.1165]
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 92.0.4515.159
    • Edge (web)                 • edge          • web-javascript • Microsoft Edge 93.0.961.38

• No issues found!


environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  downloads_path_provider: ^0.1.0
  dropdown_search: ^0.6.3
  encrypt: ^5.0.1
  filesystem_picker: ^1.0.4  
  firebase_core: ^1.6.0
  firebase_remote_config: ^0.10.0+5
  flutter_screenutil: ^2.3.1
  flutter_spinbox: ^0.5.4
  get: ^4.3.8
  google_mobile_ads: ^0.13.4
  image_picker: ^0.8.3+2
  launch_review: ^3.0.1
  open_file: ^3.2.1
  package_info: ^2.0.2 
  path: ^1.8.0
  path_provider: ^2.0.2
  path_provider_macos: ^2.0.2
  path_provider_windows: ^2.0.3
  pdf: ^3.5.0
  permission_handler: ^8.1.4+2
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  sqflite_sqlcipher: ^2.0.0
  url_launcher: ^6.0.10
  uuid: ^3.0.4
```

Help pls! ~__~
