### ISSUE TITLE
 popup is not coming to ask permission to access camera

### ISSUE THREAD

**Issue by mohamedenab** [Baseflow/flutter-permission-handler#438]
i try to request camera permission on real iphone to scan qr code using `qr_code_scanner` but the popup doesn't open i add `NSCameraUsageDescription` in `info.plist` and added in my `podfile` this

    post_install do |installer|
    installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
         'PERMISSION_CAMERA=0',
         'PERMISSION_PHOTOS=0',
         'PERMISSION_MEDIA_LIBRARY=0',
      ]
        end
      end 
    end
and this my code for ask 
i try this 

    getCamera() async {
       var status = await Permission.camera.status;
      if (!status.isGranted) {
      final result = await Permission.camera.request();
      if (result.isGranted) {
        setState(() {
        getPerm = true;
        });
      }
      } else {
      setState(() {
        getPerm = true;
      });
      }
    }
 and this 
    
    void initState() {
    super.initState();
      WidgetsBinding.instance.addPostFrameCallback(onLayoutDone);
     }
          void onLayoutDone(Duration timeStamp) async {
        _permissionStatus = await Permission.camera.status;
        if (_permissionStatus.isGranted) {
          setState(() {
            getPerm = true;
          });
        }
      }
    
      void _askCameraPermission() async {
        await Permission.camera.request();
        if (await Permission.camera.request().isGranted) {
          _permissionStatus = await Permission.camera.status;
          setState(() {
            getPerm = true;
          });
        }
      } 

 
and call _askCameraPermission function on pressed in button 
nothing of this ways is working with me and all Permission other than camera working

**Comment by mohamedenab** [comment]
i just remove the request and it worked

**Comment by cahix** [comment]
how did you solve it exactly?

**Comment by mohamedenab** [comment]
@cahix sorry for late response
I was trying to request it manually with permission handler but i remove it and r move the condition i hide the camera with it then  when i go to the page it show the request
