### ISSUE TITLE
ios build error in flutter 

### ISSUE THREAD

**Issue by rohitsainik** [Baseflow/flutter-permission-handler#442]
while running Flutter Build IOS I Got these warning and was unable to build the app can any help me in resolving these issue

/Users/ganpat/develop/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-4.4.0/ios/Classes/strategies/NotificationPermissionStrategy.m:71:37: warning:
implicit conversion from enumeration type 'UIRemoteNotificationType' (aka 'enum UIRemoteNotificationType') to different enumeration type 'UNAuthorizationOptions' (aka
'enum UNAuthorizationOptions') [-Wenum-conversion]
UNAuthorizationOptions type = [[UIApplication sharedApplication] enabledRemoteNotificationTypes];

**Comment by mvanbeusekom** [comment]
Hi @rohitsainik, version 4.4.0 is pretty outdated. Please try updating to 5.1.0+2 (if you can't support null-safety) or 6.0.0 if you want sound null safe support.
