### ISSUE TITLE
Storage permission on some Android devices detects as `undetermined` after last `permission_handler_platform_interface` update

### ISSUE THREAD

**Issue by GeorgeOblomov** [Baseflow/flutter-permission-handler#448]
After latest `permission_handler_platform_interface` update on some Android devices (Nokia 5.1, Honor 8) storage permission cannot detect but on some other devices (Huawei P40 Lite and Xiaomi Redmi Note 7) all works fine. Permission status on "broken" devices is `undetermined` and library also request permission in `AndroidManifest`. If use latest plugin version and rollback `permission_handler_platform_interface` plugin to version `2.0.1` it works correctly.

### Reproduction steps

1. Call `final storagePermissionStatus = await Permission.storage.request()` and wait for permission check;
2. `storagePermissionStatus` always `undetermined`.

### Configuration

**Version:** 5.0.1+1

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

### Flutter doctor

```shell
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-arm, locale
    en-RU)
    • Framework revision 9b2d32b605 (2 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Platform android-30, build-tools 30.0.3
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

! Doctor found issues in 1 category.
```

**Comment by mvanbeusekom** [comment]
This problem has been solved with version 5.1.0+2 of the permission_handler, I recommend updating.

**Comment by AKA-LinCoder** [comment]
i have some question about Storage in HONOR(Android),my permission_handler is 10.2.0,hope you can see it

**Comment by knight0zh** [comment]
> 我对 HONOR(Android) 中的存储有一些疑问，我的 permission_handler 是 10.2.0，希望你能看到它

10.2.0 same problem

**Comment by AKA-LinCoder** [comment]
nfg

**Comment by knight0zh** [comment]
> > 我对 HONOR(Android) 中的存储有一些疑问，我的 permission_handler 是 10.2.0，希望你能看到它
> 
> 10.2.0 same problem

it solved. https://github.com/Baseflow/flutter-permission-handler/issues/907#issuecomment-1375999027
