### ISSUE TITLE
Android 11 background location permission issue

### ISSUE THREAD

**Issue by spdeol20** [Baseflow/flutter-permission-handler#452]
If we request Permmision.locationAlways.request()
It doesnt do anything on android 11

**Comment by rsydor** [comment]
I have the same problem

**Comment by elocwem** [comment]
Same here.

**Comment by lukino563** [comment]
but can devs add this override for android 11 location always ? i dont want to rewrite my app logic only for android 11+

**Comment by mvanbeusekom** [comment]
@lukino563 I am not really sure how that will help you. Theoretically I would be able to check first if permission for the `location` (which on Android translates to `ACCESS_FINE_LOCATION`) permissions has been granted. If not we can request those permissions instead. But this still means you will need to request the `locationAlways` permissions again to make sure they are presented to the user.

I could also quickly ask the two questions after each other but that will not be very user friendly and will probably also get your App rejected on the Play Store. As the Play Store requires you to show a special message to the end user explaining why your app requires background permissions before actually requesting them. So in the end I don't thinks this would be possible for me to solve and you will have to update your App if you want to comply to the Android 11 location permission requirements. 

More details on the Google Play Store guidelines can be found [here](https://support.google.com/googleplay/android-developer/answer/9799150?hl=en).

I will close this issue for now. If you feel this issue shouldn't be close, please leave a comment describing why and I would be happy to re-open it.
