### ISSUE TITLE
the android PermissionConstants file lacks the photosAddOnly enumeration value

### ISSUE THREAD

**Issue by ZRQ1010110087** [Baseflow/flutter-permission-handler#457]
## 🐛 Bug Report

1.The android PermissionConstants file lacks the photosAddOnly enumeration value. 
2.The request for storage  permission was turned out to be IGNOTE Battery Optimizations permission at the end of android,resulting in the failure to request the permission normally

**Version:** 5.1.0

**Platform:** 
- [ ] :robot: Android

**Comment by swallowzhang** [comment]
any updates?
