### ISSUE TITLE
MissingPluginException(No implementation found for method checkPermissionStatus on channel flutter.baseflow.com/permissions/methods)

### ISSUE THREAD

**Issue by aniketsongara** [Baseflow/flutter-permission-handler#463]
## 🐛 Bug Report

Having issue only in the release mode 

`Unhandled Exception: MissingPluginException(No implementation found for method checkPermissionStatus on channel flutter.baseflow.com/permissions/methods)`

Doctor summary :
[√] Flutter (Channel dev, 1.27.0-8.0.pre, on Microsoft Windows [Version 10.0.18363.1256], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.47.3)
[√] Connected device (3 available)

• No issues found!

Using packages in pubspec.yaml are :
  
 ```
 permission_handler: ^5.1.0+2
  file_picker: "^1.12.0"

```
 above issue has been solved by adding two line of code in 
 `app/build.gradle
 `
 ```
buildTypes {
        release {
            shrinkResources false
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }
```

**Comment by LUK3D** [comment]
I solve this by changing the app/build.gradle code...
buildTypes {
       release {
            signingConfig signingConfigs.debug
            shrinkResources false //Add this line
            minifyEnabled false //And this line
       }
   }

Then on pubspec.yaml i added this:

dependency_overrides:
  path_provider: ^2.0.1
