### ISSUE TITLE
add null-safety support

### ISSUE THREAD

**Issue by chavesgu** [Baseflow/flutter-permission-handler#466]
## 🚀 Feature Requests

add null-safety support
### Describe the feature

Flutter stable version is `2.0.0`, support null-safety
### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by amebrahimi** [comment]
Please add null safety !!!

**Comment by mvanbeusekom** [comment]
duplicate of #419. 

we are currently testing the migration and should be released soon. See also #450 and #451
