### ISSUE TITLE
which depends on plugin_platform_interface ^1.0.2, permission_handler >=5.1.0 requires plugin_platform_interface ^1.0.2.

### ISSUE THREAD

**Issue by psikosen** [Baseflow/flutter-permission-handler#470]
## 🐛 Bug Report

After updating to latest version I got this one, even thouh your permission_handler_platform_interface seems to be using 3.0.0

 Because permission_handler >=5.1.0 depends on permission_handler_platform_interface ^2.0.2 which depends on plugin_platform_interface ^1.0.2, permission_handler >=5.1.0 requires plugin_platform_interface ^1.0.2.

**Version:** 1.x

**Platform:**  
- [x] :robot: Android

**Comment by ariefwijaya** [comment]
I have this problem too

**Comment by psikosen** [comment]
I even tried forking the library and changing to 2.0.2 to test,  but its still giving me this issue. 🙃 glad I'm not alone, imma hammer at it tommarow , I'll drop a comment, if I figure out something.

**Comment by mvanbeusekom** [comment]
This issue should be solved in version 6.0.0. 

If you can't upgrade then you can choose to use a dependency override in your pubspec.yaml:

```yaml
dependency_overrides:
  plugin_platform_interface ^1.0.2
```

**Comment by psikosen** [comment]
Thanks @ mvanbeusekom I actually ended doing this, but this is great for others who may  encounter this issue.
