### ISSUE TITLE
How to take Storage/files permission for android 11?

### ISSUE THREAD

**Issue by shofizone** [Baseflow/flutter-permission-handler#480]
## 💬 Questions and Help

Some reason its not asking file access permission  in android 11. 
in AndroidManifest.xml
```
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
      <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE"/>
```
And this way I am asking for permission !
```
   Map<Permission, PermissionStatus> statuses = await [
      Permission.mediaLibrary,
      Permission.storage,
      Permission.photos,
    ].request();
```

**Comment by mvanbeusekom** [comment]
duplicate of #491. 

Support for `MANAGE_EXTERNAL_STORAGE` has not yet been implemented.

**Comment by aniketsongara** [comment]
When you guy's are planing to implement it ?

**Comment by canitez** [comment]
If this is not fixed, google play reported that it will restrict apps shortly.
