### ISSUE TITLE
android.permission.RECORD_AUDIO permission not supported

### ISSUE THREAD

**Issue by Stanllley** [Baseflow/flutter-permission-handler#486]
I need use the android.permission.RECORD_AUDIO permission in Android but not supported in Permission-Handler?

**Comment by mvanbeusekom** [comment]
@Stanllley on Android the `android.permission.RECORD_AUDIO` is mapped to the `Permission.speech` or `Permission.microphone` permissions. 

So if you need the Android `android.permission.RECORD_AUDIO` you can do something like this:

```dart
var status = await Permission.speech.status;
if (status.denied) {
  status = await Permission.speech.request();
}
```
or
```dart
var status = await Permission.microphone.status;
if (status.denied) {
  status = await Permission.microphone.request();
}
```
