### ISSUE TITLE
Status throwing an error on first request of permission status

### ISSUE THREAD

**Issue by ericderegt** [Baseflow/flutter-permission-handler#487]
## 💬 Questions and Help

In prior versions of this plugin, there was a property on status of undetermined. Why was this removed? Now when I try to access Permission.camera.status the first time a user opens the app I get an error

```
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method checkPermissionStatus on channel flutter.baseflow.com/permissions/methods)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
<asynchronous suspension>
#1      MethodChannelPermissionHandler.checkPermissionStatus (package:permission_handler_platform_interface/src/method_channel/method_channel_permission_handler.dart:15:20)
<asynchronous suspension>
#2      _EnableContactsScreenState.build.<anonymous closure>.<anonymous closure> (package:whale/screens/onboarding/enable_contacts_screen.dart:92:41)
<asynchronous suspension>
```

What is the recommended way to handle this case?

**Comment by mvanbeusekom** [comment]
To support the `undetermined` status on Android we had to keep (persist) permission information on the device, this always had some minor problems but with the introduction of Android API 30 these problems became more serieus resulting in bugs that users couldn't workaround or overcome. Therefore we decided to remove this status al together. This has been mentioned in the release notes and a detailed explanation can be found on our wiki: https://github.com/Baseflow/flutter-permission-handler/wiki/Changes-in-6.0.0.

The plugin now follows Androids native implementation where permissions are implicitly denied until the user explicitly grants permissions. Meaning when the current status is `denied` you should request permissions and test the result.
