### ISSUE TITLE
MANAGE_EXTERNAL_STORAGE

### ISSUE THREAD

**Issue by aniketsongara** [Baseflow/flutter-permission-handler#491]
Please add the support for Android 11 storage permission of 
`<uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" />`

**Comment by NebiSarigul** [comment]
++

**Comment by JAICHANGPARK** [comment]
I Hope to add this permission

**Comment by JAICHANGPARK** [comment]
I had some issues about permission manageExternalStorage
D/permissions_handler(  602): No permissions found in manifest for: 22

**Comment by JDDV** [comment]
Hi @JAICHANGPARK, that's correct. In the platform_handler_platform_interface the permission is added, but not yet implemented in the permission_handler. I am currently working on it and it will be published probably this week. I'll give you an update as soon as it's published.

**Comment by JAICHANGPARK** [comment]
@JDDV  Thank you for support ~!

**Comment by JDDV** [comment]
@JAICHANGPARK, the manageExternalStorage is implemented now in the newest version of the plugin_handler (version 7.0.0).
I would like to point out that the documentation of using the manageExternalStorage permission says the following:

```
/// Android: Allows an application a broad access to external storage in
  /// scoped storage.
  /// iOS: Nothing
  ///
  /// You should request the Manage External Storage permission only when
  /// your app cannot effectively make use of the more privacy-friendly APIs.
  /// For more information: https://developer.android.com/training/data-storage/manage-all-files
  ///
  /// When the privacy-friendly APIs (i.e. [Storage Access Framework](https://developer.android.com/guide/topics/providers/document-provider)
  /// or the [MediaStore](https://developer.android.com/training/data-storage/shared/media) APIs) is all your app needs the
  /// [PermissionGroup.storage] are the only permissions you need to request.
  ///
  /// If the usage of the Manage External Storage permission is needed,
  /// you have to fill out the Permission Declaration Form upon submitting
  /// your app to the Google Play Store. More details can be found here:
  /// https://support.google.com/googleplay/android-developer/answer/9214102#zippy=
```

So take in good consideration if the permission really is needed. If it's not needed, as mentioned above, you can use the PermissionGroup.storage which is already implemented.

I hope this will help you out!

**Comment by Ch4rl3B** [comment]
> 
> 
> I had some issues about permission manageExternalStorage
> D/permissions_handler( 602): No permissions found in manifest for: 22

I have this issue.. I'm using permission_handler: ^7.1.0
D/permissions_handler( 3208): No permissions found in manifest for: 22

**Comment by JDDV** [comment]
Hi @Ch4rl3B,

> I have this issue.. I'm using permission_handler: ^7.1.0
> D/permissions_handler( 3208): No permissions found in manifest for: 22

To make sure your app is using the newest version of the permission_handler and not a version that's in the cache it would be good practice to run the `flutter clean` command first, followed by `flutter pub get` to make sure you're using the newest version of the permission_handler.

The output in the console says; 'No Permissions found in manifest for: 22'.
So I think in the AndroidManifest of your app you miss the permission line needed for the permission request to work.
if you look at the documentation of the plugin there's an example of the permissions you need and how to add them (which can be found [here](https://github.com/Baseflow/flutter-permission-handler/blob/develop/permission_handler/example/android/app/src/main/AndroidManifest.xml)).

```
    <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" />```

the code snippet above here is what you should add to the AndroidManifest file for it to work.
Let me know if it worked!

**Comment by gurupras** [comment]
Should I be able to request and acquire the `MANAGE_EXTERNAL_STORAGE` permission in `^8.0.1`?
I'm running into the same `No Permissions found in manifest for: 22` error even after having added the following into my manifest:
```<uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE"/>```

**Comment by Ch4rl3B** [comment]
> 
> 
> Hi @Ch4rl3B,
> 
> > I have this issue.. I'm using permission_handler: ^7.1.0
> > D/permissions_handler( 3208): No permissions found in manifest for: 22
> 
> To make sure your app is using the newest version of the permission_handler and not a version that's in the cache it would be good practice to run the `flutter clean` command first, followed by `flutter pub get` to make sure you're using the newest version of the permission_handler.
> 
> The output in the console says; 'No Permissions found in manifest for: 22'.
> So I think in the AndroidManifest of your app you miss the permission line needed for the permission request to work.
> if you look at the documentation of the plugin there's an example of the permissions you need and how to add them (which can be found [here](https://github.com/Baseflow/flutter-permission-handler/blob/develop/permission_handler/example/android/app/src/main/AndroidManifest.xml)).
> 
> `` <!-- Permissions options for the `manage external storage` group --> <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" /> ``
> 
> the code snippet above here is what you should add to the AndroidManifest file for it to work.
> Let me know if it worked!

I've done all you said and nothing... but finally I solved it using a File picker library.

**Comment by burakcbdn** [comment]
Same here on some android devices

**Comment by JDDV** [comment]
@Ch4rl3B and @burakcbdn, is it possible for you to send your manifest and a the code (or code snippet where you ask for the permission) so I can try to reproduce this issue? Also the output from the `flutter doctor -v`  command would be appreciated. Thanks in advance!
