### ISSUE TITLE
Possibility to know permission access to any other app installed in the device

### ISSUE THREAD

**Issue by RohithKilaparthi** [Baseflow/flutter-permission-handler#492]
## 🚀 Feature Requests
Possibility to know permission access to any other app installed in the device. 

Lets say I have 100 apps installed in my device, I would like to understand if any other app on the device has ACTION_MANAGE_OVERLAY_PERMISSION permission.

**Comment by mvanbeusekom** [comment]
@RohithKilaparthi I don't think this is possible. We are restricted to the App we are running in (sandboxed) and cannot query information about other apps as far as I know. 

If it were possible I don't feel this would be something that we would like to incorporate into this plugin. As the intention for this plugin is to manage permissions for the app it is used in. 

If I misunderstood or you have other information that I am not aware about please feel free to add them to this issue and I will have a look at it. For now I will be closing this issue as I don't see it fit for the permission_handler.
