### ISSUE TITLE
None of all permissions (microphone, storage, contacts etc) working in live app mode

### ISSUE THREAD

**Issue by kamleshwebtech** [Baseflow/flutter-permission-handler#495]
I have used this package in my app. It is working well in debug mode on all the screens but when I compile app and upload it to Play store it does not show any popup of permission and user is not able to access further modules of app. Kindly suggest what is the issue and how can we fix it. Thanks a lot. Looking forward to hear you.

**Comment by mvanbeusekom** [comment]
Which of the AndroidManifest.xml files did you register the permissions (as described in the Android section of the README.md)?

It sounds like you might have put them in the `debug` version (located in the `android/app/src/debug` folder). This would mean permissions are only compiled along with the app in the debug version of the App. Permissions should always (and only) be listed in the AndroidManifest.xml file located in the `android/app/src/main` folder of your App.

**Comment by kamleshwebtech** [comment]
@mvanbeusekom Yes, You are right and I am with you. Permissions are added in the AndroidManifest.xml file located in the android/app/src/main folder of my App but sorry to say permission popup does not shown and without granting permission in LIVE mode my app is useless. Any suggestion, will be highly appreciated, please share. Thanks a lot.

**Comment by mvanbeusekom** [comment]
Could you provide any additional information maybe? I really cannot think of any reason why this should happen. We have several App listed in the stores and never experienced this problem. 

Maybe you could provide the following information:

1. Does this only happen on Android?
2. Could you extract the `AndroidManifest.xml` from the Android package you upload to the store and post it's content here?
3. Which version of the plugin are you using? 
4. Could you provide a code snippet of the where you are using the plugin?
5. Please provide the output of the `flutter doctor -v` command.
