### ISSUE TITLE
Error output from Xcode build

### ISSUE THREAD

**Issue by Annelein** [Baseflow/flutter-permission-handler#500]
I have followed the steps on the iOS setup and included permission_handler: ^6.1.1 in my pubspec.yaml

Does anyone have a solution for this?

At flutter run in my terminal I get:

`Error output from Xcode build:
↳
    2021-03-24 13:58:06.975 xcodebuild[65635:4525259]  DVTAssertions: Warning in
    /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17705/DTDeviceKitBase/DTDKRemoteDeviceData.m:371
    Details:  (null) deviceType from 31bcd4e5f9c316dd4d3d9bb31b26c5d606182423 was NULL when -platform called.
    Object:   <DTDKMobileDeviceToken: 0x7f871c8af140>
    Method:   -platform
    Thread:   <NSThread: 0x7f8719c0f8f0>{number = 6, name = (null)}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    2021-03-24 13:58:07.461 xcodebuild[65635:4525259]  DVTAssertions: Warning in
    /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17705/DTDeviceKitBase/DTDKRemoteDeviceData.m:371
    Details:  (null) deviceType from 31bcd4e5f9c316dd4d3d9bb31b26c5d606182423 was NULL when -platform called.
    Object:   <DTDKMobileDeviceToken: 0x7f871c8af140>
    Method:   -platform
    Thread:   <NSThread: 0x7f8719c0f8f0>{number = 6, name = (null)}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    2021-03-24 13:58:07.713 xcodebuild[65635:4525259]  DVTAssertions: Warning in
    /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-17705/DTDeviceKitBase/DTDKRemoteDeviceData.m:371
    Details:  (null) deviceType from 31bcd4e5f9c316dd4d3d9bb31b26c5d606182423 was NULL when -platform called.
    Object:   <DTDKMobileDeviceToken: 0x7f871c8af140>
    Method:   -platform
    Thread:   <NSThread: 0x7f8719c0f8f0>{number = 6, name = (null)}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    ** BUILD FAILED **

Xcode's output:
↳
    warning: Stale file '/Users/anneleinvanreijen/Library/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_blue-0.8.0/ios/gen/Flutterblue.pbobjc.h' is located outside of
    the allowed root paths.

    /Users/anneleinvanreijen/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-6.1.1/ios/Classes/strategies/PhonePermissionStrategy.m:41:16: warning: incompatible pointer
    types initializing 'CTCarrier *' with an expression of type 'NSDictionary<NSString *,CTCarrier *> * _Nullable' [-Wincompatible-pointer-types]
        CTCarrier *carrier = [netInfo serviceSubscriberCellularProviders];
                   ^         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 warning generated.
    /Users/anneleinvanreijen/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-6.1.1/ios/Classes/PermissionManager.m:75:93: error: expected expression
            BOOL success = [[UIApplication sharedApplication] openURL:options:completionHandler::[NSURL URLWithString:UIApplicationOpenSettingsURLString]];
                                                                                                ^
    /Users/anneleinvanreijen/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-6.1.1/ios/Classes/PermissionManager.m:75:67: error: use of undeclared identifier 'options'
            BOOL success = [[UIApplication sharedApplication] openURL:options:completionHandler::[NSURL URLWithString:UIApplicationOpenSettingsURLString]];
                                                                      ^
    /Users/anneleinvanreijen/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-6.1.1/ios/Classes/PermissionManager.m:75:75: error: use of undeclared identifier
    'completionHandler'
            BOOL success = [[UIApplication sharedApplication] openURL:options:completionHandler::[NSURL URLWithString:UIApplicationOpenSettingsURLString]];
                                                                              ^
    3 errors generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the precompiled application for the device.`

**Comment by mhstoller** [comment]
What Xcode version are you running? Try updating to 12.4 if you're not already on the latest.

**Comment by JDDV** [comment]
Hi @Annelein, if you update to the newest version and update your podfile as mentioned in the documentation (version ^8.0.0 has a breaking change in it where you need to adjust your podfile) does it work then? you also added the correct lines to the info.plist?

If it still does not work I would like to have a bit more information when the error occurs and a code snippet where you use the permission handler. please let me know if it helped you so I can close this issue or help you out more!
