### ISSUE TITLE
Update plugin_platform_interface

### ISSUE THREAD

**Issue by ycv005** [Baseflow/flutter-permission-handler#502]
Hey, update the dependency plugin_platform_interface which is present inside- permission_handler_platform_interface
link- https://pub.dev/packages/plugin_platform_interface

**Comment by mvanbeusekom** [comment]
Hey, the `permission_handler` uses the latest version of the `plugin_platform_interface` since version 6.0.0 (current version is 6.1.1). 

Not really sure what you are aiming towards, but maybe you should update your dependency?
