### ISSUE TITLE
Getting app crash on android after selecting deny with don't ask again

### ISSUE THREAD

**Issue by RadheshyamSingh** [Baseflow/flutter-permission-handler#503]
## 🐛 Bug Report

E/AndroidRuntime(30055): java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=24, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.pretlist.ordigo/io.flutter.embedding.android.FlutterActivity}: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(30055): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4445)
E/AndroidRuntime(30055): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4488)
E/AndroidRuntime(30055): 	at android.app.ActivityThread.-wrap20(Unknown Source:0)
E/AndroidRuntime(30055): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1697)
E/AndroidRuntime(30055): 	at android.os.Handler.dispatchMessage(Handler.java:105)
E/AndroidRuntime(30055): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(30055): 	at android.app.ActivityThread.main(ActivityThread.java:6694)
E/AndroidRuntime(30055): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(30055): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
E/AndroidRuntime(30055): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
E/AndroidRuntime(30055): Caused by: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(30055): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:139)
E/AndroidRuntime(30055): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:243)
E/AndroidRuntime(30055): 	at com.shounakmulay.telephony.sms.SmsMethodCallHandler.onPermissionDenied(SmsMethodCallHandler.kt:367)
E/AndroidRuntime(30055): 	at com.shounakmulay.telephony.sms.SmsMethodCallHandler.onRequestPermissionsResult(SmsMethodCallHandler.kt:361)
E/AndroidRuntime(30055): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEnginePluginRegistry.java:664)
E/AndroidRuntime(30055): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onRequestPermissionsResult(FlutterEnginePluginRegistry.java:364)
E/AndroidRuntime(30055): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:579)
E/AndroidRuntime(30055): 	at io.flutter.embedding.android.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:601)
E/AndroidRuntime(30055): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7403)
E/AndroidRuntime(30055): 	at android.app.Activity.dispatchActivityResult(Activity.java:7254)
E/AndroidRuntime(30055): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4441)
E/AndroidRuntime(30055): 	... 9 more
D/TransportRuntime.SQLiteEventStore(30055): Storing event with priority=HIGHEST, name=FIREBASE_CRASHLYTICS_REPORT for destination cct
D/TransportRuntime.JobInfoScheduler(30055): Scheduling upload for context TransportContext(cct, HIGHEST, MSRodHRwczovL2NyYXNobHl0aWNzcmVwb3J0cy1wYS5nb29nbGVhcGlzLmNvbS92MS9maXJlbG9nL2xlZ2FjeS9iYXRjaGxvZ1xBSXphU3lCcnBTWVQ0RkZMMDlyZUhKaTZIOUZZZGVpU25VVE92Mk0=) with jobId=-1012190816 in 1000ms(Backend next call timestamp 0). Attempt 1

### Reproduction steps
Step 1: Ask for permission (tried with contact, camera and storage)
Step 2: Press deny button 
Step 3: Again ask for same permission 
Step 4: This time deny with 'don't ask again' 
Step 5: App got crash
 
### Configuration

**Version:** 5.1.0+2

Flutter 1.22.6
Dart 2.10.5
Channel stable

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by JDDV** [comment]
Hi @RadheshyamSingh, have you tried updating to the newest version of the plugin? I think it should solve the problem. Please let me know if it did.

If it did not help, can you provide more information about which Android device and version you are using? Thanks in advance!
