### ISSUE TITLE
Add New Permission:  REQUEST_INSTALL_PACKAGES

### ISSUE THREAD

**Issue by jjva-xiao** [Baseflow/flutter-permission-handler#508]
## 💬 Questions and Help

For questions or help we recommend checking:

Application permissions: Android. Permission. REQUEST_INSTALL_PACKAGES, this access can be used for the renewal of the Android APP install capabilities, can provide the support for this, thank you very much

**Comment by JDDV** [comment]
Hi @jjva-xiao, thanks for the request, but this is already requested in #319 and it's currently being worked on. This issue will be closed.
