### ISSUE TITLE
Null Safety(Flutter)

### ISSUE THREAD

**Issue by Usman167** [Baseflow/flutter-permission-handler#518]
I'm trying to convert my code on null safety but error line appears under charityText, donateLink and charityLink in brackets. help me if you know...
**Code**
FutureBuilder(
            future: getCharityDetails(),
            builder: (context, snapshot) {
              if (snapshot.connectionState == ConnectionState.done) {

                
                charityText = snapshot.data!['charityText'];

                donateLink = snapshot.data!['donateLink'];
                
                charityLink = snapshot.data!['charityLink'];

**Issue** 
The operator '[]' isn't defined for the type 'Object'.
Try defining the operator '[]'.  

![ppp](https://user-images.githubusercontent.com/50518168/114590180-dad51f00-9ca1-11eb-9898-b4a09977182c.png)

**Comment by mvanbeusekom** [comment]
I don't see how this is related to the permission_handler. But de `snapshot.data` returns a value of type `Object`. So before you can do something with it I guess you should cast it to the type you are expecting (looks like a map but I can't be sure).

Also I see you are using the bang operator (`!`) quite freely. Normally you would only use this if you are absolutely sure the value isn't `null`. In this case (defensive programming) I think you should probably add an if statement and handle `null` values gracefully. Using the bang operator will cause null reference exceptions when used on `null` values.

I will be closing this ticket now as I think this is not related to the permission_handler and you would be better of on StackOverflow (I would also advise to read up on null safety here: https://flutter.dev/docs/null-safety).
