### ISSUE TITLE
syntax issue

### ISSUE THREAD

**Issue by Usman167** [Baseflow/flutter-permission-handler#519]
I'm trying to convert my code on null safety but stuck in syntax error.
![image](https://user-images.githubusercontent.com/50518168/114593905-0fe37080-9ca6-11eb-895b-64245cf65282.png)

**Comment by mvanbeusekom** [comment]
You don't have to specify a length when dealing with lists in Dart. Try something like this to initialize your list:

```dart
_PopupMenuRoute({
  // omitted for brevity
}) : itemSizes = <Size>[];
```

I will be closing this ticket now as I think this is not related to the permission_handler and you would be better of on StackOverflow.
