### ISSUE TITLE
External USB create/write permission errno = 13

### ISSUE THREAD

**Issue by JAICHANGPARK** [Baseflow/flutter-permission-handler#527]
## 💬 Questions and Help

I am using USB connected to android. And I'd like to create a folder and write files to USB in android app.
I also gave write/read permission, but it is not being written.

### USB
```
USB Format : fat32
```

### build.gradle
```
compileSdkVersion 29
targetSdkVersion 29
```

### manifest
```
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

 <application

        android:requestLegacyExternalStorage="true"
```

### packages 
```
 permission_handler: any (6.1.3)
```

![image](https://user-images.githubusercontent.com/19484515/115637217-948b5a00-a34a-11eb-92e8-9af07def20f0.png)

**Comment by JDDV** [comment]
Hi @JAICHANGPARK, can you provide us with more information, a code snippet of your code and a flutter doctor -v would be very useful to start with. I don't think it will fix the error, but can you also try the newest version of the plugin? (^7.1.0).
