### ISSUE TITLE
compile errors

### ISSUE THREAD

**Issue by sgehrman** [Baseflow/flutter-permission-handler#530]
Launching lib/main.dart on sdk gphone x86 arm in debug mode...
/home/steve/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-7.0.0/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java:54: error: cannot find symbol
            status = Environment.isExternalStorageManager()
                                ^
  symbol:   method isExternalStorageManager()
  location: class Environment
/home/steve/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-7.0.0/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java:218: error: cannot find symbol
                    if (permission == PermissionConstants.PERMISSION_GROUP_MANAGE_EXTERNAL_STORAGE && Build.VERSION.SDK_INT < Build.VERSION_CODES.R) {
                                                                                          ^
  symbol:   variable R
  location: class VERSION_CODES
/home/steve/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-7.0.0/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java:232: error: cannot find symbol
            } else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R && permission == PermissionConstants.PERMISSION_GROUP_MANAGE_EXTERNAL_STORAGE) {
                                                                   ^
  symbol:   variable R
  location: class VERSION_CODES
/home/steve/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-7.0.0/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java:234: error: cannot find symbol
                        Settings.ACTION_MANAGE_APP_ALL_FILES_ACCESS_PERMISSION,
                                ^
  symbol:   variable ACTION_MANAGE_APP_ALL_FILES_ACCESS_PERMISSION
  location: class Settings
/home/steve/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-7.0.0/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java:293: error: cannot find symbol
                if (Build.VERSION.SDK_INT < Build.VERSION_CODES.R) {
                                                               ^
  symbol:   variable R
  location: class VERSION_CODES
/home/steve/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-7.0.0/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java:322: error: cannot find symbol
                    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.R) {
                                                                   ^
  symbol:   variable R
  location: class VERSION_CODES
/home/steve/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-7.0.0/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java:326: error: cannot find symbol
                    return Environment.isExternalStorageManager()
                                      ^
  symbol:   method isExternalStorageManager()
  location: class Environment
/home/steve/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-7.0.0/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java:64: error: cannot find symbol
            case Manifest.permission.MANAGE_EXTERNAL_STORAGE:
                                    ^
  symbol:   variable MANAGE_EXTERNAL_STORAGE
  location: class permission
/home/steve/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-7.0.0/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java:223: error: cannot find symbol
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R && hasPermissionInManifest(context, permissionNames, Manifest.permission.MANAGE_EXTERNAL_STORAGE ))
                                                                ^
  symbol:   variable R
  location: class VERSION_CODES
/home/steve/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-7.0.0/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java:223: error: cannot find symbol
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R && hasPermissionInManifest(context, permissionNames, Manifest.permission.MANAGE_EXTERNAL_STORAGE ))
                                                                                          ^
  symbol:   variable MANAGE_EXTERNAL_STORAGE
  location: class permission
/home/steve/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-7.0.0/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java:224: error: cannot find symbol
                    permissionNames.add(Manifest.permission.MANAGE_EXTERNAL_STORAGE);
                                                           ^
  symbol:   variable MANAGE_EXTERNAL_STORAGE
  location: class permission
11 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':permission_handler:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by sgehrman** [comment]
compileSdkVersion 30

fixes it

**Comment by dfdgsdfg** [comment]
https://github.com/Baseflow/flutter-permission-handler/pull/534
