### ISSUE TITLE
How to requestTrackingAuthorization Permission?

### ISSUE THREAD

**Issue by WL2012** [Baseflow/flutter-permission-handler#533]
## 🚀 Feature Requests

A message that informs the user why an app is requesting permission to use data for tracking the user or the device.

### Describe the feature
requestTrackingAuthorization when launch app for ios14 review.

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS

**Comment by JDDV** [comment]
This is added in the newest version of the permission handler plugin version 8.0.0
