### ISSUE TITLE
Failed to compile Android Application

### ISSUE THREAD

**Issue by ederluca** [Baseflow/flutter-permission-handler#536]
Good Morning

I created a project using flutter 2.0.5 using sdk 2.12.0 I needed to use the permission_handler package: ^ 7.0.0. When adding the same to my project and trying to generate the android app I am facing the attached problems, however I just need to remove the package mentioned above and the project works without any problem I added the permissions that I will need to use in my project to the file android / app / src / main / AndroidManifest.xml however I still can't identify the problem.

[log.txt](https://github.com/Baseflow/flutter-permission-handler/files/6392379/log.txt)

**Comment by ederluca** [comment]
See attached print of my flutter doctor.

![Captura de tela de 2021-04-28 11-14-41](https://user-images.githubusercontent.com/51955855/116418988-fe0bdc80-a812-11eb-8631-d95f06583e92.png)

**Comment by mvanbeusekom** [comment]
Hi @ederluca,

Please make sure you set the `compileSdkVersion` in your `android/app/build.gradle` file to `30`. We have just updated the documentation but this is not available on pub.dev yet. You can however check it out on Github: https://github.com/Baseflow/flutter-permission-handler/blob/2425361b4bbd86839de66097948dcbd08582bc75/README.md (read the Android specific section).

**Comment by ederluca** [comment]
Thanks it worked correctly now I had not attempted this a big hug and keep up the good work.
