### ISSUE TITLE
Add body sensors permission

### ISSUE THREAD

**Issue by avkonst** [Baseflow/flutter-permission-handler#540]
## 🚀 Feature Requests

It would be very helpful, if the API of the `Permission` class had `bodySensors` property for requesting and checking for [BODY_SENSORS](https://developer.android.com/reference/android/Manifest.permission.html#BODY_SENSORS) permission, like for any other permission.

### Contextualize the feature

It is the main goal of the library to expose permission handling. This particular permission is not on the list of supported.

### Describe the feature

Add new `bodySensors` property to the `Permission` class, which would take care of requesting and checking for [BODY_SENSORS permission](https://developer.android.com/reference/android/Manifest.permission.html#BODY_SENSORS) (Android). I believe the similar exists for iOS.

### Platforms affected (mark all that apply)
- [v?] :iphone: iOS
- [v] :robot: Android

**Comment by JDDV** [comment]
Hi @avkonst, The permission for the body sensors is already implemented in the plugin. you can request this permission by calling the `request()` method on the sensor permission (`Permission.sensors.request()`). If you take a look [here](https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler/example/android/app/src/main/AndroidManifest.xml) in the Manifest of the example app on line 51/52 you will see that the permission group is called sensors, which uses the body sensor permission.

This issue will be closed but please feel free to comment if you have any questions regarding this issue!

**Comment by avkonst** [comment]
Ok. Thanks!
