### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by isakovsv** [Baseflow/flutter-permission-handler#541]
## 🐛 Bug Report

vs code says

utter\.pub-cache\hosted\pub.dartlang.org\permission_handler-7.1.0\android\src\main\java\com\baseflow\permissionhandler\PermissionManager.java:53: error: cannot find symbol
            status = Environment.isExternalStorageManager()
                                ^
  symbol:   method isExternalStorageManager()
  location: class Environment
C:\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-7.1.0\android\src\main\java\com\baseflow\permissionhandler\PermissionManager.java:222: error: cannot find symbol
                    if (permission == PermissionConstants.PERMISSION_GROUP_MANAGE_EXTERNAL_STORAGE && Build.VERSION.SDK_INT < Build.VERSION_CODES.R) {
                                                                                          ^
  symbol:   variable R
  location: class VERSION_CODES

### Configuration

**Version:** 1.x
 permission_handler: ^7.1.0
**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
Please make sure you upgrade the `compileSdkVersion` in your `android/app/build.gradle` file to API level 30. See also the Android section in the README.
