### ISSUE TITLE
iOS build is failing with 7.1.0 version due to 'openURL:' is deprecated

### ISSUE THREAD

**Issue by sureace** [Baseflow/flutter-permission-handler#544]
Hi @mvanbeusekom ,
                After updating app with 7.1.0, build is failing with below error. NSPhotoLibraryUsageDescription and NSPhotoLibraryAddUsageDescription already exist in info.plist. 
mac os version : 10.15.7. 
xcode version: 12.5

Build Error
-----------
/Users/Sureace/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-7.1.0/ios/Classes/PermissionManager.m:75:59: warning: 'openURL:' is deprecated: first deprecated in iOS 10.0 [-Wdeprecated-declarations]
            BOOL success = [[UIApplication sharedApplication] openURL:[NSURL URLWithString:UIApplicationOpenSettingsURLString]];
                                                              ^~~~~~~
                                                              openURL:options:completionHandler:
    In module 'UIKit' imported from /Users/Sureace/Development/iotecom/ios/Pods/Target Support Files/permission_handler/permission_handler-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.4.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:123:1: note: 'openURL:' has been explicitly marked deprecated here
    - (BOOL)openURL:(NSURL*)url API_DEPRECATED_WITH_REPLACEMENT("openURL:options:completionHandler:", ios(2.0, 10.0)) NS_EXTENSION_UNAVAILABLE_IOS("");
    ^
    1 warning generated.
    /Users/Sureace/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-7.1.0/ios/Classes/strategies/NotificationPermissionStrategy.m:48:7: warning: 'UIUserNotificationType' is deprecated: first deprecated in iOS 10.0 - Use UserNotifications Framework's UNAuthorizationOptions [-Wdeprecated-declarations]
          UIUserNotificationType notificationTypes = 0;
          ^
    In module 'UIKit' imported from /Users/Sureace/Development/iotecom/ios/Pods/Target Support Files/permission_handler/permission_handler-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.4.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIUserNotificationSettings.h:17:32: note: 'UIUserNotificationType' has been explicitly marked deprecated here
    typedef NS_OPTIONS(NSUInteger, UIUserNotificationType) {
                                   ^
    /Users/Sureace/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-7.1.0/ios/Classes/strategies/NotificationPermissionStrategy.m:49:28: warning: 'UIUserNotificationTypeSound' is deprecated: first deprecated in iOS 10.0 - Use UserNotifications Framework's UNAuthorizationOptions [-Wdeprecated-declarations]
          notificationTypes |= UIUserNotificationTypeSound;
                               ^
    In module 'UIKit' imported from /Users/Sureace/Development/iotecom/ios/Pods/Target Support Files/permission_handler/permission_handler-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.4.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIUserNotificationSettings.h:17:32: note: 'UIUserNotificationType' has been explicitly marked deprecated here
    typedef NS_OPTIONS(NSUInteger, UIUserNotificationType) {
                                   ^
    /Users/Sureace/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-7.1.0/ios/Classes/strategies/NotificationPermissionStrategy.m:50:28: warning: 'UIUserNotificationTypeAlert' is deprecated: first deprecated in iOS 10.0 - Use UserNotifications Framework's UNAuthorizationOptions [-Wdeprecated-declarations]
          notificationTypes |= UIUserNotificationTypeAlert;
                               ^
    In module 'UIKit' imported from /Users/Sureace/Development/iotecom/ios/Pods/Target Support Files/permission_handler/permission_handler-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.4.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIUserNotificationSettings.h:17:32: note: 'UIUserNotificationType' has been explicitly marked deprecated here
    typedef NS_OPTIONS(NSUInteger, UIUserNotificationType) {
                                   ^
    /Users/Sureace/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-7.1.0/ios/Classes/strategies/NotificationPermissionStrategy.m:51:28: warning: 'UIUserNotificationTypeBadge' is deprecated: first deprecated in iOS 10.0 - Use UserNotifications Framework's UNAuthorizationOptions [-Wdeprecated-declarations]
          notificationTypes |= UIUserNotificationTypeBadge;
                               ^
    In module 'UIKit' imported from /Users/Sureace/Development/iotecom/ios/Pods/Target Support Files/permission_handler/permission_handler-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.4.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIUserNotificationSettings.h:17:32: note: 'UIUserNotificationType' has been explicitly marked deprecated here
    typedef NS_OPTIONS(NSUInteger, UIUserNotificationType) {
                                   ^
    /Users/Sureace/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-7.1.0/ios/Classes/strategies/NotificationPermissionStrategy.m:52:7: warning: 'UIUserNotificationSettings' is deprecated: first deprecated in iOS 10.0 - Use UserNotifications Framework's UNNotificationSettings [-Wdeprecated-declarations]
          UIUserNotificationSettings *settings = [UIUserNotificationSettings settingsForTypes:notificationTypes categories:nil];
          ^
    In module 'UIKit' imported from /Users/Sureace/Development/iotecom/ios/Pods/Target Support Files/permission_handler/permission_handler-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.4.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIUserNotificationSettings.h:44:12: note: 'UIUserNotificationSettings' has been explicitly marked deprecated here
    @interface UIUserNotificationSettings : NSObject
               ^
    /Users/Sureace/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-7.1.0/ios/Classes/strategies/NotificationPermissionStrategy.m:52:74: warning: 'UIUserNotificationSettings' is deprecated: first deprecated in iOS 10.0 - Use UserNotifications Framework's UNNotificationSettings [-Wdeprecated-declarations]
          UIUserNotificationSettings *settings = [UIUserNotificationSettings settingsForTypes:notificationTypes categories:nil];
                                                                             ^
    In module 'UIKit' imported from /Users/Sureace/Development/iotecom/ios/Pods/Target Support Files/permission_handler/permission_handler-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.4.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIUserNotificationSettings.h:44:12: note: 'UIUserNotificationSettings' has been explicitly marked deprecated here
    @interface UIUserNotificationSettings : NSObject
               ^
    /Users/Sureace/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-7.1.0/ios/Classes/strategies/NotificationPermissionStrategy.m:53:42: warning: 'registerUserNotificationSettings:' is deprecated: first deprecated in iOS 10.0 - Use UserNotifications Framework's -[UNUserNotificationCenter requestAuthorizationWithOptions:completionHandler:] and -[UNUserNotificationCenter setNotificationCategories:] [-Wdeprecated-declarations]
          [[UIApplication sharedApplication] registerUserNotificationSettings:settings];
                                             ^
    In module 'UIKit' imported from /Users/Sureace/Development/iotecom/ios/Pods/Target Support Files/permission_handler/permission_handler-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.4.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:250:1: note: 'registerUserNotificationSettings:' has been explicitly marked deprecated here
    - (void)registerUserNotificationSettings:(UIUserNotificationSettings *)notificationSettings API_DEPRECATED("Use UserNotifications Framework's -[UNUserNotificationCenter requestAuthorizationWithOptions:completionHandler:] and -[UNUserNotificationCenter setNotificationCategories:]", ios(8.0, 10.0)) API_UNAVAILABLE(tvos);
    ^
    /Users/Sureace/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-7.1.0/ios/Classes/strategies/NotificationPermissionStrategy.m:75:5: warning: 'UIUserNotificationSettings' is deprecated: first deprecated in iOS 10.0 - Use UserNotifications Framework's UNNotificationSettings [-Wdeprecated-declarations]
        UIUserNotificationSettings * setting = [[UIApplication sharedApplication] currentUserNotificationSettings];
        ^
    In module 'UIKit' imported from /Users/Suresh-IoTMinds/Development/iotecom/ios/Pods/Target Support Files/permission_handler/permission_handler-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.4.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIUserNotificationSettings.h:44:12: note: 'UIUserNotificationSettings' has been explicitly marked deprecated here
    @interface UIUserNotificationSettings : NSObject
               ^
    /Users/Sureace/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-7.1.0/ios/Classes/strategies/NotificationPermissionStrategy.m:75:79: warning: 'currentUserNotificationSettings' is deprecated: first deprecated in iOS 10.0 - Use UserNotifications Framework's -[UNUserNotificationCenter getNotificationSettingsWithCompletionHandler:] and -[UNUserNotificationCenter getNotificationCategoriesWithCompletionHandler:] [-Wdeprecated-declarations]
        UIUserNotificationSettings * setting = [[UIApplication sharedApplication] currentUserNotificationSettings];
                                                                                  ^
    In module 'UIKit' imported from /Users/Sureace/Development/iotecom/ios/Pods/Target Support Files/permission_handler/permission_handler-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.4.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:253:70: note: property 'currentUserNotificationSettings' is declared deprecated here
    @property(nonatomic, readonly, nullable) UIUserNotificationSettings *currentUserNotificationSettings API_DEPRECATED("Use UserNotifications Framework's -[UNUserNotificationCenter getNotificationSettingsWithCompletionHandler:] and -[UNUserNotificationCenter getNotificationCategoriesWithCompletionHandler:]", ios(8.0, 10.0)) API_UNAVAILABLE(tvos);
                                                                         ^
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.4.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:253:70: note: 'currentUserNotificationSettings' has been explicitly marked deprecated here
    /Users/Sureace/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-7.1.0/ios/Classes/strategies/NotificationPermissionStrategy.m:76:26: warning: 'UIUserNotificationTypeNone' is deprecated: first deprecated in iOS 10.0 - Use UserNotifications Framework's UNAuthorizationOptions [-Wdeprecated-declarations]
        if (setting.types == UIUserNotificationTypeNone) permissionStatus = PermissionStatusDenied;
                             ^
    In module 'UIKit' imported from /Users/Sureace/Development/iotecom/ios/Pods/Target Support Files/permission_handler/permission_handler-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.4.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIUserNotificationSettings.h:17:32: note: 'UIUserNotificationType' has been explicitly marked deprecated here
    typedef NS_OPTIONS(NSUInteger, UIUserNotificationType) {
                                   ^
    10 warnings generated.
    /Users/Sureace/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-7.1.0/ios/Classes/strategies/BluetoothPermissionStrategy.m:31:31: warning: 'CBCentralManagerStatePoweredOn' is deprecated: first deprecated in iOS 10.0 - Use CBManagerState instead [-Wdeprecated-declarations]
        return [manager state] == CBCentralManagerStatePoweredOn ? ServiceStatusEnabled : ServiceStatusDisabled;
                                  ^
    In module 'CoreBluetooth' imported from /Users/Sureace/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-7.1.0/ios/Classes/strategies/BluetoothPermissionStrategy.h:13:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.4.sdk/System/Library/Frameworks/CoreBluetooth.framework/Headers/CBCentralManager.h:35:28: note: 'CBCentralManagerState' has been explicitly marked deprecated here
    typedef NS_ENUM(NSInteger, CBCentralManagerState) {
                               ^
    1 warning generated.
    /Users/Sureace/flutter/.pub-cache/hosted/pub.dartlang.org/in_app_review-2.0.2/ios/Classes/InAppReviewPlugin.m:36:38: error: no known class method for selector 'requestReviewInScene:'
                [SKStoreReviewController requestReviewInScene:scene];
                                         ^~~~~~~~~~~~~~~~~~~~
    /Users/Sureace/flutter/.pub-cache/hosted/pub.dartlang.org/in_app_review-2.0.2/ios/Classes/InAppReviewPlugin.m:99:14: warning: 'openURL:' is deprecated: first deprecated in iOS 10.0 [-Wdeprecated-declarations]
            [app openURL:url];
                 ^~~~~~~
                 openURL:options:completionHandler:
    In module 'UIKit' imported from /Users/Sureace/Development/iotecom/ios/Pods/Target Support Files/in_app_review/in_app_review-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.4.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:123:1: note: 'openURL:' has been explicitly marked deprecated here
    - (BOOL)openURL:(NSURL*)url API_DEPRECATED_WITH_REPLACEMENT("openURL:options:completionHandler:", ios(2.0, 10.0)) NS_EXTENSION_UNAVAILABLE_IOS("");
    ^
    1 warning and 1 error generated.

Pubspec.ymal
---------------
environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.5
  introduction_screen: ^2.1.0
  flutter_swiper: ^1.1.6
  easy_localization: ^3.0.0
  firebase_core: ^1.1.0
  firebase_auth: ^1.1.2
  cloud_firestore: ^1.0.7
  provider: ^5.0.0
  permission_handler: ^7.1.0
  url_launcher: ^6.0.3
  fluttertoast: ^8.0.6
  pin_code_fields: ^7.0.0
  connectivity: ^3.0.3
  cloud_functions: ^1.0.5
  firebase_messaging: ^9.1.3
  flutter_typeahead: ^3.1.2
  uuid: ^3.0.4
  dio: ^4.0.0
  equatable: ^2.0.0
  cached_network_image: ^3.0.0
  package_info: ^2.0.0
  http: ^0.13.2
  flutter_calendar_carousel: ^2.0.1
  in_app_review: ^2.0.2
  razorpay_flutter: ^1.2.5
  ext_storage: ^1.0.3
  image_gallery_saver: ^1.6.9
  sms_autofill: ^2.0.0
  share: ^2.0.1
  cupertino_icons: ^1.0.2

Thanking you,
Sureace

**Comment by JDDV** [comment]
Hi @sureace & @Oshitha, I tried to reproduce the error with the given information but I was not able to reproduce it. Can you please run the 'flutter clean' command, followed by 'pub get' and 'pod install' and then run the app again?

Please let me know if it worked, or let me know when it didn't work.

@sureace if it didn't work, can you please send me a copy of your plist.info because you mentioned something about NSPhotoLibraryUsageDescription and NSPhotoLibraryAddUsageDescription already existed in info.plist.

**Comment by Oshitha** [comment]
Hi, @JDDV I've updated xcode to Version 12.2. In Xcode 12.2 it works perfectly. Thanks
