### ISSUE TITLE
support sdk 29

### ISSUE THREAD

**Issue by tareq55** [Baseflow/flutter-permission-handler#547]
## 🐛 Bug Report

I am using android sdk version 29 I cannot change to 28 because most of the libraries I use do not work with 28 Is there a way to operate the library with version 29
 

 
**Version:** 7.1.0

**Platform:** 
- [ ] :iphone: iOS
- [* ] :robot: Android

**Comment by mvanbeusekom** [comment]
Hello @tareq55, 

If you want to use version 7.1.0 you will have to update to Android SDK version 30 (or at least you should compile against Android SDK version 30). 

This means that in your `android/app/build.gradle` file, you'll have to set the `compileSdkVersion` to `30`. You can have a look in the [example](https://github.com/Baseflow/flutter-permission-handler/blob/39caf3c3856ad9c3758523f0c6d3be8c6584e63f/permission_handler/example/android/app/build.gradle#L28) project on how this might look.

If necessary you can keep you `targetSdkVersion` set to `29`. I am not sure why you mention API 28 but this is not supported in the permission_handler (as we really need API 30 to support the new permissions).

More information on `targetSdkVersion` and `compileSdkVersion` can be found here: https://medium.com/androiddevelopers/picking-your-compilesdkversion-minsdkversion-targetsdkversion-a098a0341ebd
