### ISSUE TITLE
SDK Version: compileSdkVersion 28 > 30 

### ISSUE THREAD

**Issue by quickratio** [Baseflow/flutter-permission-handler#549]
## 🏗 Enhancement Proposal

Update documentation and notes under "Set Up > Android"

Change this:

android {
  compileSdkVersion 28
  ...
}

to this: 

android {
  compileSdkVersion 30
  ...
}

compile does not work for anything less than 30 on permission_handler: ^7.1.0

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by jaween** [comment]
Can confirm that this solutions solves build issues for me. This plugin appears to be using symbols introduced in Android API 30 such as `isExternalStorageManager`, etc.

**Comment by mvanbeusekom** [comment]
Correct, the documentation has already been updated but is not yet released.
