### ISSUE TITLE
Can't check the permission status without request the permission

### ISSUE THREAD

**Issue by efraespada** [Baseflow/flutter-permission-handler#553]
## 🐛 Bug Report

When checking the status of any permission, it is requested.

### Expected behavior

Just simply return the permission status, not request the permission.

### Reproduction steps

Invoke:

```kotlin
await Permission.locationAlways.status == PermissionStatus.granted;
```

Then the permission dialogs appear.

### Configuration

**Version:** ^7.1.0

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android

**Comment by itsJoKr** [comment]
Can you do `await Permission.contacts.status`?

**Comment by efraespada** [comment]
Sorry, It was my mistake. I was firing the request from another place.
