### ISSUE TITLE
permission.status will return denied instead of permanentlyDenied

### ISSUE THREAD

**Issue by itsJoKr** [Baseflow/flutter-permission-handler#554]
## 🐛 Bug Report

On the first permission dialog, I'll press "Deny and don't ask again".

`permission.request();` will not show the dialog and would return permanentlyDenied as expected.

Expected:  `permission.status` will return permanentlyDenied.
Actual: `permission.status` returns denied.

### Versions

After debugging I've noticed this issue appeared in version 6.0.0, so the version before (like 5.1.0+2) would work properly.

**Platform:** 
- [ ] :iphone: iOS (haven't tested it)
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi @itsJoKr, this is expected behavior and is exactly how Android also handles permissions. More details are in the [release notes](https://pub.dev/packages/permission_handler/changelog#600) and on our [wiki](https://github.com/Baseflow/flutter-permission-handler/wiki/Changes-in-6.0.0).
