### ISSUE TITLE
 permissions is already running

### ISSUE THREAD

**Issue by selvam920** [Baseflow/flutter-permission-handler#555]
PlatformException (PlatformException(PermissionHandler.PermissionManager, A request for permissions is already running, please wait for it to finish before doing another request (note that you can request multiple permissions at the same time)., null, null))

in pubspec.yaml
permission_handler: ^7.0.0

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 2.3.0-2.0.pre.220, on Microsoft Windows [Version 10.0.19042.985], locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.0 Preview 3.0)
[✓] Android Studio (version 4.2.0)
[✓] VS Code (version 1.57.0-insider)
[✓] Connected device (3 available)

**Comment by JDDV** [comment]
Hi @selvam920, Can you give a little bit more information about how you ask the permission?
Can you provide a code snippet/example on how you request the permission?
