### ISSUE TITLE
Execution failed for task ':permission_handler:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by eaedev** [Baseflow/flutter-permission-handler#562]
Hi!

I am trying to use this package, actual version 7.1; I have followed instructions for android devices but I always encounter the same error:

`C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-7.1.0\android\src\main\java\com\baseflow\permissionhandler\PermissionManager.java:53: error: cannot find symbol
            status = Environment.isExternalStorageManager()
                                ^
  symbol:   method isExternalStorageManager()
  location: class Environment
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-7.1.0\android\src\main\java\com\baseflow\permissionhandler\PermissionManager.java:222: error: cannot find symbol
                    if (permission == PermissionConstants.PERMISSION_GROUP_MANAGE_EXTERNAL_STORAGE && Build.VERSION.SDK_INT < Build.VERSION_CODES.R) {
                                                                                          ^
  symbol:   variable R
  location: class VERSION_CODES
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-7.1.0\android\src\main\java\com\baseflow\permissionhandler\PermissionManager.java:236: error: cannot find symbol
            } else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R && permission == PermissionConstants.PERMISSION_GROUP_MANAGE_EXTERNAL_STORAGE) {
                                                                   ^
  symbol:   variable R
  location: class VERSION_CODES
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-7.1.0\android\src\main\java\com\baseflow\permissionhandler\PermissionManager.java:238: error: cannot find symbol
                        Settings.ACTION_MANAGE_APP_ALL_FILES_ACCESS_PERMISSION,
                                ^
  symbol:   variable ACTION_MANAGE_APP_ALL_FILES_ACCESS_PERMISSION
  location: class Settings
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-7.1.0\android\src\main\java\com\baseflow\permissionhandler\PermissionManager.java:300: error: cannot find symbol
                if (Build.VERSION.SDK_INT < Build.VERSION_CODES.R) {
                                                               ^
  symbol:   variable R
  location: class VERSION_CODES
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-7.1.0\android\src\main\java\com\baseflow\permissionhandler\PermissionManager.java:329: error: cannot find symbol
                    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.R) {
                                                                   ^
  symbol:   variable R
  location: class VERSION_CODES
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-7.1.0\android\src\main\java\com\baseflow\permissionhandler\PermissionManager.java:333: error: cannot find symbol
                    return Environment.isExternalStorageManager()
                                      ^
  symbol:   method isExternalStorageManager()
  location: class Environment
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-7.1.0\android\src\main\java\com\baseflow\permissionhandler\PermissionUtils.java:64: error: cannot find symbol
            case Manifest.permission.MANAGE_EXTERNAL_STORAGE:
                                    ^
  symbol:   variable MANAGE_EXTERNAL_STORAGE
  location: class permission
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-7.1.0\android\src\main\java\com\baseflow\permissionhandler\PermissionUtils.java:225: error: cannot find symbol
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R && hasPermissionInManifest(context, permissionNames, Manifest.permission.MANAGE_EXTERNAL_STORAGE ))
                                                                ^
  symbol:   variable R
  location: class VERSION_CODES
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-7.1.0\android\src\main\java\com\baseflow\permissionhandler\PermissionUtils.java:225: error: cannot find symbol
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R && hasPermissionInManifest(context, permissionNames, Manifest.permission.MANAGE_EXTERNAL_STORAGE ))
                                                                                          ^
  symbol:   variable MANAGE_EXTERNAL_STORAGE
  location: class permission
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-7.1.0\android\src\main\java\com\baseflow\permissionhandler\PermissionUtils.java:226: error: cannot find symbol
                    permissionNames.add(Manifest.permission.MANAGE_EXTERNAL_STORAGE);
                                                           ^
  symbol:   variable MANAGE_EXTERNAL_STORAGE
  location: class permission
11 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':permission_handler:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.`

Here is my app.build.gradle:

`
android {
    compileSdkVersion 29

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        applicationId "xxxxx"
        minSdkVersion 16
        targetSdkVersion 29
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled true
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.multidex:multidex:2.0.1'
}

and my android.manifest:

 uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="xxx"
        android:icon="@mipmap/ic_launcher">

        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>

**Comment by acportes** [comment]
Same here

**Comment by eaedev** [comment]
Hi there,

I have found that if you change to compileSdkVersion 30, it worked. Hope it helps you. Documentation seems outdated.

**Comment by mx1up** [comment]
indeed, setting sdk to 30 fixes. it _is_ mentioned in the readme though: https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler/README.md#setup

**Comment by mvanbeusekom** [comment]
Closing issue as per @mx1up and @eaedev comments this should work correctly if you set the appropriate `compileSdkVersion` value.
