### ISSUE TITLE
Returned 'granted' when permission is 'Ask Every Time' on Android 11

### ISSUE THREAD

**Issue by PabloTortosaLopez** [Baseflow/flutter-permission-handler#570]
## 🐛 Bug Report

For `camera permission`, returned `granted` when permission is `Ask Every Time` on Android 11

_I don't know how to handle this, I've been following a very similar bug (https://github.com/Baseflow/flutter-permission-handler/issues/411) that some sites say has been fixed, but this is very similar. As I say, I don't know if it's a bug or if it still doesn't manage the Ask Every Time status._

_When is this permission revoked, how do I handle this, how do I ask the user each time they try to open the camera if they select Only this time and the permissions are always granted?_

### Expected behavior

A way to handle `Ask Every Time` option

### Reproduction steps
2 ways to do it:

On Emulator Android API 30:
App Info > Permissions > Camera permission set to 'Ask everytime'

*Recomended*
In app:
Once opened the camera and selected Ask Every Time, close the camera and open it again, it will give granted

<img width="499" alt="Screenshot 2021-05-27 at 17 56 23" src="https://user-images.githubusercontent.com/43600508/119859143-65ea3b80-bf15-11eb-8e12-3f1fe1ecde62.png">

**Version:** 8.0.0+2

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi @PabloTortosaLopez, 

The "Ask Every Time" option basically means "Ask for permissions every time the user restarts the App" and not "Ask for permissions each time the user starts the camera".

Meaning when the user selects the "Ask Every Time" permission the first time the App starts, the permission stays granted for as long as the App is running. The App can safely use the camera as many times as required during the session. Once the App is closed the Android sub-system will then automatically set the permissions to "Denied" and the next time the user starts the App, the App will have to ask for permission again.

I hope this clarifies things for you. If not please let me know, maybe I misunderstood the question.
