### ISSUE TITLE
After updating to the lastest version, not of my permissions request works anymore on iOS.

### ISSUE THREAD

**Issue by armandojimenez** [Baseflow/flutter-permission-handler#573]
## 🐛 Bug Report

After I updated to the latest version, no permission request shows on my app, it just returns denied, and when I go to the app settings, it does not show as requested, or the toggle to turn it on.

**Platform:** 
- [ x] :iphone: iOS

**Comment by febg11** [comment]
Did you manage to fix this? I am getting the same thing

**Comment by armandojimenez** [comment]
Yes, check the read me again, they changed the podfile config, now you have to uncomment the permissions you need, and be equal to 1 instead of 0
