### ISSUE TITLE
iOS requesting contacts access is not showing

### ISSUE THREAD

**Issue by dominicsanto** [Baseflow/flutter-permission-handler#575]
## 🐛 Bug Report

I am trying to gain access to a users contacts but having some issues.

`final PermissionStatus permission = await Permission.contacts.request();`  requesting the contacts simply does not bring up the dialog and the result is Permanently Denied.

Also my application cannot be found under the Privacy section within the settings of the emulator.

**Version:** 8.0.0+2

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
Hello @dominicsanto,

Please make sure you enable the permissions you need in your `ios/Podfile`.

Starting from version 8.0.0 we flipped the configuration in the `ios/Podfile`:
- Pre version 8.0.0 permissions are enabled by default and you disable those permissions you don't need in your `ios/Podfile`;
- From version 8.0.0 and onwards permissions are disabled by default and you need to enable those permissions you need in your `ios/Podfile`.

P.S. this is documented in the README and we added a warning in the CHANGELOG, but maybe you missed it.
