### ISSUE TITLE
Getting Execution failed for task ':permission_handler:compileDebugJavaWithJavac'. after updating packages

### ISSUE THREAD

**Issue by 91priyansh** [Baseflow/flutter-permission-handler#581]
Everything is working well but after i update packages with flutter pub upgrade --major-versions. It is giving me this error

Here is error 
-------------------------------------------------------------------------------------------------------------------------------------------
E:\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-8.0.1\android\src\main\java\com\baseflow\permissionhandler\PermissionManager.java:54: error: cannot find symbol    
            status = Environment.isExternalStorageManager()
                                ^
  symbol:   method isExternalStorageManager()
  location: class Environment
E:\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-8.0.1\android\src\main\java\com\baseflow\permissionhandler\PermissionManager.java:232: error: cannot find symbol   
                    if (permission == PermissionConstants.PERMISSION_GROUP_MANAGE_EXTERNAL_STORAGE && Build.VERSION.SDK_INT < Build.VERSION_CODES.R) {
                                                                                ^
  symbol:   variable R
  location: class VERSION_CODES
E:\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-8.0.1\android\src\main\java\com\baseflow\permissionhandler\PermissionManager.java:246: error: cannot find symbol   
            } else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R && permission == 

PermissionConstants.PERMISSION_GROUP_MANAGE_EXTERNAL_STORAGE) {
                                                                   ^
  symbol:   variable R
  location: class VERSION_CODES
E:\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-8.0.1\android\src\main\java\com\baseflow\permissionhandler\PermissionManager.java:248: error: cannot find symbol   
                        Settings.ACTION_MANAGE_APP_ALL_FILES_ACCESS_PERMISSION,
                                ^
  symbol:   variable ACTION_MANAGE_APP_ALL_FILES_ACCESS_PERMISSION
  location: class Settings
E:\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-8.0.1\android\src\main\java\com\baseflow\permissionhandler\PermissionManager.java:314: error: cannot find symbol   
                if (Build.VERSION.SDK_INT < Build.VERSION_CODES.R) {    
                                                               ^
  symbol:   variable R
  location: class VERSION_CODES
E:\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-8.0.1\android\src\main\java\com\baseflow\permissionhandler\PermissionManager.java:343: error: cannot find symbol   
                    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.R) {
                                                                   ^
  symbol:   variable R
  location: class VERSION_CODES
E:\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-8.0.1\android\src\main\java\com\baseflow\permissionhandler\PermissionManager.java:347: error: cannot find symbol   
                    return Environment.isExternalStorageManager()
                                      ^
  symbol:   method isExternalStorageManager()
  location: class Environment
E:\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-8.0.1\android\src\main\java\com\baseflow\permissionhandler\PermissionUtils.java:64: error: cannot find symbol      
            case Manifest.permission.MANAGE_EXTERNAL_STORAGE:   
                                    ^
  symbol:   variable MANAGE_EXTERNAL_STORAGE
  location: class permission
E:\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-8.0.1\android\src\main\java\com\baseflow\permissionhandler\PermissionUtils.java:227: error: cannot find symbol     
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R && hasPermissionInManifest(context, permissionNames, Manifest.permission.MANAGE_EXTERNAL_STORAGE ))
                                                                ^
  symbol:   variable R
  location: class VERSION_CODES
E:\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-8.0.1\android\src\main\java\com\baseflow\permissionhandler\PermissionUtils.java:227: error: cannot find symbol     
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R && hasPermissionInManifest(context, permissionNames, Manifest.permission.MANAGE_EXTERNAL_STORAGE ))
                                                                                ^
  symbol:   variable MANAGE_EXTERNAL_STORAGE
  location: class permission
E:\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-8.0.1\android\src\main\java\com\baseflow\permissionhandler\PermissionUtils.java:228: error: cannot find symbol     
                    permissionNames.add(Manifest.permission.MANAGE_EXTERNAL_STORAGE);     
                                                           ^
  symbol:   variable MANAGE_EXTERNAL_STORAGE
  location: class permission
11 errors

FAILURE: Build failed with an exception.

**Comment by mvanbeusekom** [comment]
Hi @91priyansh,

Please make sure you update (or add) the `compileSdkVersion` in your `android/app/build.gradle` and set it to 30.

More information can be found in the "Android" section of the README.md file. And an example can be found as part of the permission_handler [example](https://github.com/Baseflow/flutter-permission-handler/blob/274247d0f980538008eb36d7b202197343fc60f1/permission_handler/example/android/app/build.gradle#L28) App.

**Comment by mahdimoaz** [comment]
when I compileSdkVersion set it to 30.
error video_player

**Comment by mvanbeusekom** [comment]
@mahdimoaz I can't reproduce this issue with a new test App, please see your separate issue #628 for details.
