### ISSUE TITLE
run in Android ,happend this error 

### ISSUE THREAD

**Issue by tzt1994** [Baseflow/flutter-permission-handler#583]
/Users/tangzhentao/flutter/.pub-cache/hosted/pub.flutter-io.cn/permission_handler-8.0.1/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java:54: 错误: 找不到符号
            status = Environment.isExternalStorageManager()
                                ^
  符号:   方法 isExternalStorageManager()
  位置: 类 Environment
/Users/tangzhentao/flutter/.pub-cache/hosted/pub.flutter-io.cn/permission_handler-8.0.1/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java:232: 错误: 找不到符号
                    if (permission == PermissionConstants.PERMISSION_GROUP_MANAGE_EXTERNAL_STORAGE && Build.VERSION.SDK_INT < Build.VERSION_CODES.R) {
                                                                                          ^
  符号:   变量 R
  位置: 类 VERSION_CODES
/Users/tangzhentao/flutter/.pub-cache/hosted/pub.flutter-io.cn/permission_handler-8.0.1/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java:246: 错误: 找不到符号
            } else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R && permission == PermissionConstants.PERMISSION_GROUP_MANAGE_EXTERNAL_STORAGE) {
                                                                   ^
  符号:   变量 R
  位置: 类 VERSION_CODES
/Users/tangzhentao/flutter/.pub-cache/hosted/pub.flutter-io.cn/permission_handler-8.0.1/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java:248: 错误: 找不到符号
                        Settings.ACTION_MANAGE_APP_ALL_FILES_ACCESS_PERMISSION,
                                ^
  符号:   变量 ACTION_MANAGE_APP_ALL_FILES_ACCESS_PERMISSION
  位置: 类 Settings
/Users/tangzhentao/flutter/.pub-cache/hosted/pub.flutter-io.cn/permission_handler-8.0.1/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java:314: 错误: 找不到符号
                if (Build.VERSION.SDK_INT < Build.VERSION_CODES.R) {
                                                               ^
  符号:   变量 R
  位置: 类 VERSION_CODES
/Users/tangzhentao/flutter/.pub-cache/hosted/pub.flutter-io.cn/permission_handler-8.0.1/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java:343: 错误: 找不到符号
                    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.R) {
                                                                   ^
  符号:   变量 R
  位置: 类 VERSION_CODES
/Users/tangzhentao/flutter/.pub-cache/hosted/pub.flutter-io.cn/permission_handler-8.0.1/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java:347: 错误: 找不到符号
                    return Environment.isExternalStorageManager()
                                      ^
  符号:   方法 isExternalStorageManager()
  位置: 类 Environment
/Users/tangzhentao/flutter/.pub-cache/hosted/pub.flutter-io.cn/permission_handler-8.0.1/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java:64: 错误: 找不到符号
            case Manifest.permission.MANAGE_EXTERNAL_STORAGE:
                                    ^
  符号:   变量 MANAGE_EXTERNAL_STORAGE
  位置: 类 permission
/Users/tangzhentao/flutter/.pub-cache/hosted/pub.flutter-io.cn/permission_handler-8.0.1/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java:227: 错误: 找不到符号
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R && hasPermissionInManifest(context, permissionNames, Manifest.permission.MANAGE_EXTERNAL_STORAGE ))
                                                                ^
  符号:   变量 R
  位置: 类 VERSION_CODES
/Users/tangzhentao/flutter/.pub-cache/hosted/pub.flutter-io.cn/permission_handler-8.0.1/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java:227: 错误: 找不到符号
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R && hasPermissionInManifest(context, permissionNames, Manifest.permission.MANAGE_EXTERNAL_STORAGE ))
                                                                                          ^
  符号:   变量 MANAGE_EXTERNAL_STORAGE
  位置: 类 permission
/Users/tangzhentao/flutter/.pub-cache/hosted/pub.flutter-io.cn/permission_handler-8.0.1/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java:228: 错误: 找不到符号
                    permissionNames.add(Manifest.permission.MANAGE_EXTERNAL_STORAGE);
                                                           ^
  符号:   变量 MANAGE_EXTERNAL_STORAGE
  位置: 类 permission
11 个错误

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':permission_handler:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 30s
Exception: Gradle task assembleDebug failed with exit code 1

**Version:8.0.1

**Platform:** 
- [ ] :robot: Android

**Comment by tzt1994** [comment]
I need help

**Comment by mvanbeusekom** [comment]
Hello @tzt1994,

Please make sure you update (or add) the `compileSdkVersion` in your `android/app/build.gradle` and set it to 30.

More information can be found in the "Android" section of the README.md file. And an example can be found as part of the permission_handler [example](https://github.com/Baseflow/flutter-permission-handler/blob/274247d0f980538008eb36d7b202197343fc60f1/permission_handler/example/android/app/build.gradle#L28) App.

**Comment by tzt1994** [comment]
ok, I fixed it

**Comment by mvanbeusekom** [comment]
you are welcome
