### ISSUE TITLE
permissions.request() not called or not working 

### ISSUE THREAD

**Issue by heshesh2010** [Baseflow/flutter-permission-handler#584]
Hi ,

I'm using : permission_handler: ^8.0.1 , 
flutter doctor 
 [✓] Flutter (Channel beta, 2.2.0, on macOS 11.3.1 20E241 darwin-x64, locale en-EG)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.56.2)
[✓] Connected device (2 available)
=====

My problem in Ios 14.5 , iphone 12 pro max simulator .

The app never give me microphone or storage permission , it always denied status 

and permissions.request() not called or not do any thing , i opened my app setting but there is no option to microphone 

 var permissions = <Permission>[];
        permissions.add(Permission.microphone);
    permissions.add(Permission.storage);

        /// ask for the permissions.
        await permissions.request(); 

my info plist file  i added 

<key>NSMicrophoneUsageDescription</key>
      <string>My app uses the microphone to record your speech and convert it to text.</string>

**Comment by cacianokroth** [comment]
Hi!
What was the solution?

**Comment by newit-huytt** [comment]
I meet the same error. Is there any solution, please?

**Comment by albemala** [comment]
Check the Setup section in the docs (https://github.com/Baseflow/flutter-permission-handler/tree/master/permission_handler#setup)

Make sure you declared 

```
<key>NSMicrophoneUsageDescription</key>
<string>... your description ...</string>
```

in `ios/Runner/Info.plist`

and 

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      # Preprocessor definitions can be found in:
      # https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler/ios/Classes/PermissionHandlerEnums.h
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        'PERMISSION_MICROPHONE=1',
        # ... other permissions
      ]
    end
  end
end
```

in `ios/Podfile`

Same thing for other permissions you might need.
