### ISSUE TITLE
 MissingPluginException(No implementation found for method checkPermissionStatus on channel flutter.baseflow.com/permissions/methods)

### ISSUE THREAD

**Issue by huangsir0** [Baseflow/flutter-permission-handler#586]
## MissingPluginException

 MissingPluginException(No implementation found for method checkPermissionStatus on channel flutter.baseflow.com/permissions/methods)

**Version:** permission_handler ^7.1.0 

kotlin: ext.kotlin_version = '1.4.10'

#### doctor

[✓] Flutter (Channel stable, 2.2.0, on macOS 11.2.3 20D91 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.56.2)
[✓] Connected device (4 available)

**Platform:** 
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi @huangsir0, 

To resolve this problem please try the following:

1. Make sure you added the necessary permissions to your `AndroidManifest.xml` file;
2. Make sure your Application is migrated to use AndroidX (see [migration guide](https://flutter.dev/docs/development/androidx-migration));
3. Run the `flutter clean` command in the root of your project;
4. If you are using Android Studio or IntelliJ run the `Invalidate caches/ Restart` option.

If the above doesn't work please have a look at this [issue](https://github.com/flutter/flutter/issues/10912#issuecomment-310499594).

Other related issues that might help:
- #463 
- #315
- #308

I am going to close this issue as this doesn't seem related to the plugin itself but more the user environment. However if you have any follow up questions don't hesitate to leave another comment.

**Comment by Farial-mahmod** [comment]
> 

@mvanbeusekom , Thanks for your reply. I have tried your instructions but the error still seems to persist .

**Comment by mvanbeusekom** [comment]
@Farial-mahmod which platform are you targeting? Note that permission_handler doesn't (yet) support web and Linux.

**Comment by CristiCh** [comment]
I have the same error when running on ios device:
`[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method checkPermissionStatus on channel flutter.baseflow.com/permissions/methods)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
<asynchronous suspension>
#1      MethodChannelPermissionHandler.checkPermissionStatus (package:permission_handler_platform_interface/src/method_channel/method_channel_permission_handler.dart:17:20)
<asynchronous suspension>
#2      requestNotificationPermission (package:bmicalculator/main.dart:11:16)
<asynchronous suspension>
#3      main (package:bmicalculator/main.dart:21:3)
<asynchronous suspension>
the Dart compiler exited unexpectedly.`

Can anyone please help?

**Comment by CristiCh** [comment]
`import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:permission_handler/permission_handler.dart';

Future<void> requestNotificationPermission() async {
  if (await Permission.notification.isDenied) {
    await Permission.notification.request();
  }
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await requestNotificationPermission(); // Request permission on app launch

  runApp(MyApp());
}
`

**Comment by mvanbeusekom** [comment]
Hi @CristiCh, 

Can you check the versions of the `permission_handler` and `permission_handler_apple` packages in your `pubspec.lock` file?

Could be a mismatch there. Also which version of the permission_handler are you using? Can you update to the latest version using:

```
flutter pub update permission_handler
flutter pub update permission_handler_apple
```

**Comment by CristiCh** [comment]
> Hi @CristiCh,
> 
> Can you check the versions of the `permission_handler` and `permission_handler_apple` packages in your `pubspec.lock` file?
> 
> Could be a mismatch there. Also which version of the permission_handler are you using? Can you update to the latest version using:
> 
> ```
> flutter pub update permission_handler
> flutter pub update permission_handler_apple
> ```

Hi @mvanbeusekom,

I only had  permission_handler: ^11.3.1 in pubspec.yaml. Do I also need to add the permission_handler_apple? 

Thank you very much!

**Comment by mvanbeusekom** [comment]
No the `permission_handler` package depends on the `permission_handler_apple` package and will automatically be downloaded. 

You can check the version in the `pubspec.lock` file that should be added in the root of your application (note the extension `.lock` and not the `.yaml` file).
