### ISSUE TITLE
[BUG]: Permission.camera.request() don't show request popup in the first time using camera in version 8.1.0 (still work in 7.2.0)

### ISSUE THREAD

**Issue by duy1998** [Baseflow/flutter-permission-handler#592]
### Expected behavior
I wanna this function invokes to add permissions in-app setting in the first time.

### Configuration

**Version:** 8.1.0

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
@duy1998 are you testing on iOS? Did you make sure you flipped the configuration in your `ios/Podfile` when you upgraded to version 8.1.0? 

Please check the [README.md](https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler/README.md) (iOS section), [CHANGELOG.md](https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler/CHANGELOG.md) and this [issue](https://github.com/Baseflow/flutter-permission-handler/issues/588#issuecomment-858621335) for more details.

**Comment by mvanbeusekom** [comment]
Reluctantly closing this issue due to lack of information. If this issue still occurs please supply the requested information and I will be happy to re-open it.
