### ISSUE TITLE
Incorrect location permission status after permission denied pernamently

### ISSUE THREAD

**Issue by fartem** [Baseflow/flutter-permission-handler#594]
## 🐛 Bug Report

Incorrect location permission status after permission denied pernamently but it is `PermissionStatus.denied`.

### Expected behavior

Permission status should be `PermissionStatus.pernamentlyDenied`.

### Reproduction steps

1. call location permission request (`Permission.location.request();`);
2. denie it;
3. call permission request again;
4. denie it;
5. check next permission request, in my case it is `PermissionStatus.denied`, but should be `PermissionStatus.pernamentlyDenied`.

### Configuration

**Version:** 8.1.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
This is on purpose and has been changed since version 6.0.0 please read the [wiki](https://github.com/Baseflow/flutter-permission-handler/wiki/Changes-in-6.0.0) for a more detailed explanation.

You can also have a look at #568 where this behaviour is also explained in detail.

**Comment by fartem** [comment]
@mvanbeusekom Thanks.
