### ISSUE TITLE
Unable to use CI/CD for ios anymore

### ISSUE THREAD

**Issue by itamardo** [Baseflow/flutter-permission-handler#595]
## 🔙 Regression

I develop my flutter app on windows for both android and ios. I use Codemagic for the ios build.
This means that I have no podfile but, rather, Codemagic creates one automatically for me each time it builds the app.
Before version 8, all the permissions were in the plist file and were enough.
Now I need to specify them in a podfile which I don't have and cannot have.
Trying to force a podfile with Codemagic proved disastrous for the build.

### Old (and correct) behavior
Permissions defined in the plist file were enough.

### Current behavior
Permissions need to be specified in a podfile which I don't and cannot have.

### Configuration
Flutter 2.2.2, windows 10 pro, android studio 4.1.3

**Comment by mvanbeusekom** [comment]
@itamardo the `Podfile` file is generated by the `flutter run` or `flutter build` commands when it is missing and should always look the same for your application. 

In your case I would copy the version that Codemagic generates and have it as part of your repo. Then you can add the required configuration necessary. 

Personally I don't have any experience with Codemagic, but using the Podfile works fine in combination with Bitrise.io, GitHub Actions or Cirrus CI. I don't see why this shouldn't work on Codemagic as well.

Note that in previous versions you also needed to add configuration to your `Podfile` file to disable those permissions you didn't need (or add all permissions to your `Info.plist` and risk your app being rejected by Apple).

**Comment by itamardo** [comment]
When developing on windows, flutter run or flutter build do not create a podfile. For this to happen you need to develop on a machine that can run xcode which windows cannot. This is my reason for using Codemagic.
Also, I don't have access to the podfile that Codemagic creates.

**Comment by mvanbeusekom** [comment]
Yes I understand. I was suggesting that you configure Codemagic to print the contents of the `Podfile` to the log so you can copy it from there.

Another option would be to execute a bash script on your CI which adds and commits the missing files to your repo after they are generated.

**Comment by itamardo** [comment]
update: i tried using the podfile linked in your documentation, changing only the permissions i need, and it worked just fine with codemagic and was published ok

**Comment by mvanbeusekom** [comment]
That is great news, happy to hear that. Thank you for reporting back.
