### ISSUE TITLE
iOS gives PermissionStatus.permanentlyDenied initially

### ISSUE THREAD

**Issue by FirdousNath** [Baseflow/flutter-permission-handler#596]
### Expected behaviour
It should ask for permission
```
 PermissionStatus status = await Permission.location.request();
```
but it always gives permanentlyDenied & open the settings page
```
if (status ==PermissionStatus.permanentlyDenied)
           openAppSettings();
```

### Configuration

**Version:** 8.1.0

**Platform:** 
- [ ] :iphone: iOS

### Podfile

```
` # Uncomment this line to define a global platform for your project
platform :ios, '11.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',

        ## dart: PermissionGroup.calendar
       'PERMISSION_EVENTS=0',

        ## dart: PermissionGroup.reminders
        'PERMISSION_REMINDERS=0',

        ## dart: PermissionGroup.contacts
        # 'PERMISSION_CONTACTS=0',

        ## dart: PermissionGroup.camera
        'PERMISSION_CAMERA=0',

        ## dart: PermissionGroup.microphone
        'PERMISSION_MICROPHONE=0',

        ## dart: PermissionGroup.speech
        'PERMISSION_SPEECH_RECOGNIZER=0',

        ## dart: PermissionGroup.photos
        # 'PERMISSION_PHOTOS=0',

        ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
        # 'PERMISSION_LOCATION=0',

        ## dart: PermissionGroup.notification
#        'PERMISSION_NOTIFICATIONS=0',

        ## dart: PermissionGroup.mediaLibrary
        'PERMISSION_MEDIA_LIBRARY=0',

        ## dart: PermissionGroup.sensors
        # 'PERMISSION_SENSORS=0'
      ]

    end
  end
end
`
```

**Comment by mvanbeusekom** [comment]
Hi @FirdousNath, 

Starting from version 8.0.0 we flipped the configuration in the `Podfile`:
- Pre version 8.0.0 permissions are enabled by default and you disable those permissions you don't need in your `Podfile`;
- From version 8.0.0 and onwards permissions are disabled by default and you need to enable those permissions you need in your `Podfile`.

P.S. this is documented in the [README](https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler/README.md) and we added a warning in the [CHANGELOG](https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler/CHANGELOG.md), but maybe you missed it.

I will be closing this issue as the above should explain how to solve the issue. If you have any questions however please leave a comment and I will try to answer them.

**Comment by FirdousNath** [comment]
Thanks alot! i totally missed it, may be the core readme should link to new breaking changes as well.

**Comment by MATTYGILO** [comment]
I have the same problem

**Comment by MATTYGILO** [comment]
> Hi @FirdousNath,
> 
> Starting from version 8.0.0 we flipped the configuration in the `Podfile`:
> 
> * Pre version 8.0.0 permissions are enabled by default and you disable those permissions you don't need in your `Podfile`;
> * From version 8.0.0 and onwards permissions are disabled by default and you need to enable those permissions you need in your `Podfile`.
> 
> P.S. this is documented in the [README](https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler/README.md) and we added a warning in the [CHANGELOG](https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler/CHANGELOG.md), but maybe you missed it.
> 
> I will be closing this issue as the above should explain how to solve the issue. If you have any questions however please leave a comment and I will try to answer them.

This fixes it!!!

**Comment by milanobrenovic** [comment]
> Hi @FirdousNath,
> 
> Starting from version 8.0.0 we flipped the configuration in the `Podfile`:
> 
> * Pre version 8.0.0 permissions are enabled by default and you disable those permissions you don't need in your `Podfile`;
> * From version 8.0.0 and onwards permissions are disabled by default and you need to enable those permissions you need in your `Podfile`.
> 
> P.S. this is documented in the [README](https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler/README.md) and we added a warning in the [CHANGELOG](https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler/CHANGELOG.md), but maybe you missed it.
> 
> I will be closing this issue as the above should explain how to solve the issue. If you have any questions however please leave a comment and I will try to answer them.

this did not fix the issue for me, i'm still always getting `PermissionStatus.permanentlyDenied` status no matter what i do
