### ISSUE TITLE
    /Users/s2yed/.pub-cache/hosted/pub.dartlang.org/permission_handler-8.1.0/ios/Classes/strategies/PhonePermissionStrategy.m:41:16: warning: incompatible pointer types initializing 'CTCarrier *' with an expression of type 'NSDictionary<NSString *,CTCarrier *> * _Nullable' [-Wincompatible-pointer-types]

### ISSUE THREAD

**Issue by s2yed** [Baseflow/flutter-permission-handler#597]
/Users/s2yed/.pub-cache/hosted/pub.dartlang.org/permission_handler-8.1.0/ios/Classes/strategies/PhonePermissionStrategy.m:41:16: warning: incompatible pointer types initializing 'CTCarrier *' with an expression of type 'NSDictionary<NSString *,CTCarrier *> * _Nullable' [-Wincompatible-pointer-types]

**Comment by mvanbeusekom** [comment]
@s2yed we would appreciate it if you could supply some more information.

**Comment by mvanbeusekom** [comment]
Has been fixes in version [8.1.1](https://pub.dev/packages/permission_handler)
