### ISSUE TITLE
[BUG][iOS]: 8.1.1  Permission.notification.isGranted is always false (still work in 7.1.0)

### ISSUE THREAD

**Issue by CarrySniper** [Baseflow/flutter-permission-handler#599]
## 🐛 Bug Report

无论怎么修改应用-设置-通知的开关，获取的授权结果都是false，修改为旧版本7.1.0则是正常的。
Application-Settings-Notifications

### Reproduction steps
```
//The result is always false
bool result = await Permission.notification.isGranted;
```

### Configuration

**Version:** 8.1.1

**Platform:** 
- [ ] :iphone: iOS

**Comment by mvanbeusekom** [comment]
@CarrySniper this is on purpose. Please check this [issue](https://github.com/Baseflow/flutter-permission-handler/issues/596#issuecomment-860456289), the iOS section in the [README.md](https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler/README.md) and the 8.0.0 release notes in the [CHANGELOG.md](https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler/CHANGELOG.md) for explanation.

**Comment by CarrySniper** [comment]
多谢，已解决！Thank you. It's settled!
