### ISSUE TITLE
D/permissions_handler( 5642): No android specific permissions needed for: 9

### ISSUE THREAD

**Issue by perymerdeka** [Baseflow/flutter-permission-handler#600]
I'm trying to request Storage Permission on Android Using permission_handler to change the wallpaper on the lockscreen but it's always permission denied even though I've set it to a condition when permisston denied it will request permission, but I always get a `Permission Denied` response for android storage I get a response like this

```
D/permissions_handler( 5642): No android specific permissions needed for: 9
I/flutter ( 5642): Android Storage Permission Status: PermissionStatus.denied
```
### Steps that I do

1. I tried to set android storage permissions like this

```dart
 // asking permission
  _askPermission() async {
    if (io.Platform.isIOS) {
      var photosStatus = await Permission.photos.status;
      if (photosStatus.isDenied) {
        await Permission.photos.request();
        print("Photos Permission Status" + photosStatus.toString());
      }
    } else {
      var photoStatus = await Permission.photos.status;
      var storageStatus = await Permission.storage.status;
      if (storageStatus.isDenied) {
        await Permission.storage.request();
        print("Android Storage Permission Status: " + storageStatus.toString());

      } else if (photoStatus.isDenied) {
        await Permission.photos.request();
        print("Android Photos Permission Status: " + photoStatus.toString());
      }
      // Map<Permission, PermissionStatus> statuses = await [Permission.storage].request();
      // print(statuses[Permission.storage]);

    }
  }
```
well I always get a denied response for android storage like this

```
D/permissions_handler( 5677): No android specific permissions needed for: 9
```

and storage permission always denied

```
PermissionStatus.denied
```
here is a my android manifest for permission

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.wallpaperapps">
    <!-- Manifest -->
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"  android:maxSdkVersion="29" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.SET_WALLPAPER" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" android:minSdkVersion="30" />

   <application
       android:requestLegacyExternalStorage="true"
 ```
 does anyone know why this is happening?

**Comment by jigarandrutter** [comment]
I am requesting for activityRecognition and getting an error as following.

Version I am using is: **_6.0.1+1_**

```
D/permissions_handler(  778): No android specific permissions needed for: 19

======== Exception caught by services library ======================================================
The following MissingPluginException was thrown while activating platform stream on channel activity_recognition_flutter:
MissingPluginException(No implementation found for method listen on channel activity_recognition_flutter)

When the exception was thrown, this was the stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:545:9)
<asynchronous suspension>
====================================================================================================
```

**Comment by mvanbeusekom** [comment]
@jigarandrutter please update to version 6.1.2 or higher, in this version we resolved an issue regarding the `ACTIVITY_RECOGNITION` permission (see [CHANGELOG.md](https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler/CHANGELOG.md#612)). 

@perymerdeka on the Android version you are testing with it is not necessary to request permissions to access the storage. I think there is a small bug in the permission_handler that by default reports `PermissionStatus.denied` when in these cases we should report that permissions are simply granted. We will look into this.

**Comment by perymerdeka** [comment]
I testing in android 10 (API 29) and here my `flutter doctor -v`

```bash
flutter doctor -v                                                  ~  
[✓] Flutter (Channel stable, 2.2.2, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.2 at /opt/flutter
    • Framework revision d79295af24 (13 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version
    30.0.3)
    • Android SDK at /opt/android-sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /opt/android-sdk
    • ANDROID_SDK_ROOT = /opt/android-sdk
    • Java binary at:
      /ToolBox/Apps/apps/AndroidStudio/ch-0/202.7351085/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /ToolBox/Apps/apps/AndroidStudio/ch-0/202.7351085
    • Flutter plugin version 57.0.2
    • Dart plugin version 202.8488
    • Java version OpenJDK Runtime Environment (build
      11.0.8+0-b944-P17168821)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.77

• No issues found!
```

**Comment by JDDV** [comment]
@perymerdeka, I checked out the Android part of the code snippet you gave, which is this part:
```
var photoStatus = await Permission.photos.status;
      var storageStatus = await Permission.storage.status;
      if (storageStatus.isDenied) {
        await Permission.storage.request();
        print("Android Storage Permission Status: " + storageStatus.toString());

      } else if (photoStatus.isDenied) {
        await Permission.photos.request();
        print("Android Photos Permission Status: " + photoStatus.toString());
      }
```

The print statement will always tell you that the permission is denied, and here's why:

You get the value of the permission by this line: `var storageStatus = await Permission.storage.status;`. You haven't allowed the request at this point of course, so the variable `storageStatus` will be `PermissionStatus.denied` by now.  

Then you have an if statement:
``` 
if (storageStatus.isDenied) {
        await Permission.storage.request();
        print("Android Storage Permission Status: " + storageStatus.toString());
}
```

It will execute the if-statement code since the storageStatus `isDenied` indeed, requesting the user the permission. When clicking on allow, the next line gets executed, which is printing the `storageStatus` variable you've set before asking permission, which will return that it's still **Denied**, even though it isn't anymore.
The next time you go into the same method asking for permission he won't go in the if statement, since the variable value of `storageStatus` will be changed into `PermissionStatus.isGranted`.

For the if statement I mentioned above, can you please try the following code to see if it works?

```
if (await Permission.storage.status.isDenied) {
        var storageStatus = await Permission.storage.request();
        print("Android Storage Permission Status: " + storageStatus.toString());
      }
```

`D/permissions_handler( 5677): No android specific permissions needed for: 9`
This line by the way is because of the photos permission you try to request, the photos permission, as stated in the description when you call the `Permission.photos.request()`, (hover over the word photos in your IDE and it shows you) is for iOS only, and not for Android. So the message stating it's not an Android specific permission is expected behavior since it isn't a permission for Android.

Just to be sure, the code snippet you gave should look like this:

```
_askPermission() async {
    if (io.Platform.isIOS) {
      var photosStatus = await Permission.photos.status;
      if (photosStatus.isDenied) {
        await Permission.photos.request();
        print("Photos Permission Status" + photosStatus.toString());
      }
    } else {
     if (await Permission.storage.status.isDenied) {
        var storageStatus = await Permission.storage.request();
        print("Android Storage Permission Status: " + storageStatus.toString());
      }
    }
  }
```

Let me know if this solved your problem! if not, I would like to know what device and which Android version you're running.

**Comment by pheromone** [comment]
+1 
  permission_handler: 8.1.6   # 权限库
```
 var status = await Permission.camera.status;
          if (status.isDenied) {
            final action = await showDialog(
              context: context,
              builder: (BuildContext context) {
                return CupertinoAlertDialog(
                  title: Text('您未打开相机权限'),
                  content: Text('是否前去打开权限？'),
                  actions: [
                    CupertinoButton(
                      child: Center(
                        child: Text(
                          '确定',
                          style: TextStyle(color: Colors.red),
                        ),
                      ),
                      onPressed: () {
                        openAppSettings();
                        Navigator.pop(context);
                      },
                    ),
                    CupertinoButton(
                      child: Center(
                        child: Text('取消'),
                      ),
                      onPressed: () {
                        Navigator.pop(context);
                      },
                    ),
                  ],
                );
              },
            );
```
```
D/permissions_handler(10762): No android specific permissions needed for: 9
D/CrashReport(10762): >>> tech.sator.power.MainActivity onPaused <<<
I/CrashReport-Native(10762): jni_setNativeInfo: key is 14
I/CrashReport-Native(10762): Set native info: isAppForeground(false)
I/AMapFlutter_AMapPlatformView(10762): onPause==>
I/AMapFlutter_AMapPlatformView(10762): onPause==>
D/CrashReport(10762): >>> tech.sator.power.MainActivity onResumed <<<
```
![image](https://user-images.githubusercontent.com/14305431/153113607-d3f3f0e6-cfaa-4517-8820-1e98a81c3929.png)

**Comment by perymerdeka** [comment]
> @perymerdeka, I checked out the Android part of the code snippet you gave, which is this part:
> 
> ```
> var photoStatus = await Permission.photos.status;
>       var storageStatus = await Permission.storage.status;
>       if (storageStatus.isDenied) {
>         await Permission.storage.request();
>         print("Android Storage Permission Status: " + storageStatus.toString());
> 
>       } else if (photoStatus.isDenied) {
>         await Permission.photos.request();
>         print("Android Photos Permission Status: " + photoStatus.toString());
>       }
> ```
> 
> The print statement will always tell you that the permission is denied, and here's why:
> 
> You get the value of the permission by this line: `var storageStatus = await Permission.storage.status;`. You haven't allowed the request at this point of course, so the variable `storageStatus` will be `PermissionStatus.denied` by now.
> 
> Then you have an if statement:
> 
> ```
> if (storageStatus.isDenied) {
>         await Permission.storage.request();
>         print("Android Storage Permission Status: " + storageStatus.toString());
> }
> ```
> 
> It will execute the if-statement code since the storageStatus `isDenied` indeed, requesting the user the permission. When clicking on allow, the next line gets executed, which is printing the `storageStatus` variable you've set before asking permission, which will return that it's still **Denied**, even though it isn't anymore. The next time you go into the same method asking for permission he won't go in the if statement, since the variable value of `storageStatus` will be changed into `PermissionStatus.isGranted`.
> 
> For the if statement I mentioned above, can you please try the following code to see if it works?
> 
> ```
> if (await Permission.storage.status.isDenied) {
>         var storageStatus = await Permission.storage.request();
>         print("Android Storage Permission Status: " + storageStatus.toString());
>       }
> ```
> 
> `D/permissions_handler( 5677): No android specific permissions needed for: 9` This line by the way is because of the photos permission you try to request, the photos permission, as stated in the description when you call the `Permission.photos.request()`, (hover over the word photos in your IDE and it shows you) is for iOS only, and not for Android. So the message stating it's not an Android specific permission is expected behavior since it isn't a permission for Android.
> 
> Just to be sure, the code snippet you gave should look like this:
> 
> ```
> _askPermission() async {
>     if (io.Platform.isIOS) {
>       var photosStatus = await Permission.photos.status;
>       if (photosStatus.isDenied) {
>         var photoStatus = await Permission.photos.request();
>         print("Photos Permission Status" + photosStatus.toString());
>       }
>     } else {
>      if (await Permission.storage.status.isDenied) {
>         var storageStatus = await Permission.storage.request();
>         print("Android Storage Permission Status: " + storageStatus.toString());
>       }
>     }
>   }
> ```
> 
> Let me know if this solved your problem! if not, I would like to know what device and which Android version you're running.

solved, thanks!

**Comment by iamnabink** [comment]
> > @perymerdeka, I checked out the Android part of the code snippet you gave, which is this part:
> > ```
> > var photoStatus = await Permission.photos.status;
> >       var storageStatus = await Permission.storage.status;
> >       if (storageStatus.isDenied) {
> >         await Permission.storage.request();
> >         print("Android Storage Permission Status: " + storageStatus.toString());
> > 
> >       } else if (photoStatus.isDenied) {
> >         await Permission.photos.request();
> >         print("Android Photos Permission Status: " + photoStatus.toString());
> >       }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The print statement will always tell you that the permission is denied, and here's why:
> > You get the value of the permission by this line: `var storageStatus = await Permission.storage.status;`. You haven't allowed the request at this point of course, so the variable `storageStatus` will be `PermissionStatus.denied` by now.
> > Then you have an if statement:
> > ```
> > if (storageStatus.isDenied) {
> >         await Permission.storage.request();
> >         print("Android Storage Permission Status: " + storageStatus.toString());
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It will execute the if-statement code since the storageStatus `isDenied` indeed, requesting the user the permission. When clicking on allow, the next line gets executed, which is printing the `storageStatus` variable you've set before asking permission, which will return that it's still **Denied**, even though it isn't anymore. The next time you go into the same method asking for permission he won't go in the if statement, since the variable value of `storageStatus` will be changed into `PermissionStatus.isGranted`.
> > For the if statement I mentioned above, can you please try the following code to see if it works?
> > ```
> > if (await Permission.storage.status.isDenied) {
> >         var storageStatus = await Permission.storage.request();
> >         print("Android Storage Permission Status: " + storageStatus.toString());
> >       }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `D/permissions_handler( 5677): No android specific permissions needed for: 9` This line by the way is because of the photos permission you try to request, the photos permission, as stated in the description when you call the `Permission.photos.request()`, (hover over the word photos in your IDE and it shows you) is for iOS only, and not for Android. So the message stating it's not an Android specific permission is expected behavior since it isn't a permission for Android.
> > Just to be sure, the code snippet you gave should look like this:
> > ```
> > _askPermission() async {
> >     if (io.Platform.isIOS) {
> >       var photosStatus = await Permission.photos.status;
> >       if (photosStatus.isDenied) {
> >         var photoStatus = await Permission.photos.request();
> >         print("Photos Permission Status" + photosStatus.toString());
> >       }
> >     } else {
> >      if (await Permission.storage.status.isDenied) {
> >         var storageStatus = await Permission.storage.request();
> >         print("Android Storage Permission Status: " + storageStatus.toString());
> >       }
> >     }
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Let me know if this solved your problem! if not, I would like to know what device and which Android version you're running.
> 
> solved, thanks!

It's a good workaround but, `On Android TIRAMISU and higher this permission is deprecrated and always returns `PermissionStatus.denied`, instead use `Permission.photos`,` , hence I found, `mediaLibrary` permission for android: here is my code:

```
final status = imageSource == ImageSource.gallery
        ? Platform.isIOS
            ? await Permission.photos.request() // since
            : await Permission.mediaLibrary.request() //mediaLibrary/storage seems like working
        : await Permission.storage.request();
```

 ```
 From the docs;  
 
/// Permission for accessing external storage.
  ///
  /// Depending on the platform and version, the requirements are slightly
  /// different:
  ///
  /// **Android:**
  /// - On Android TIRAMISU and higher this permission is deprecrated and always
  /// returns `PermissionStatus.denied`, instead use `Permission.photos`,
  /// `Permission.video`, `Permission.audio` or
  /// `Permission.manageExternalStorage`. For more information see our
  /// [FAQ](https://pub.dev/packages/permission_handler#faq).
  /// - On Android < TIRAMISU the `READ_EXTERNAL_STORAGE` and
  /// `WRITE_EXTERNAL_STORAGE` permissions are requested (depending on the
  /// definitions in the AndroidManifest.xml) file.
  ///
  /// **iOS:**
  /// - Access to folders like `Documents` or `Downloads`. Implicitly granted.
```
