### ISSUE TITLE
How to invoke push notification request dialog in iOS

### ISSUE THREAD

**Issue by thapli9A** [Baseflow/flutter-permission-handler#610]
I'm trying to get request dialog but it's not invoking as per doc.

**Comment by EvGeniyLell** [comment]
have the same issue. for example, i call `Permission.photos.request().isGranted` but nothing happened on ios

**Comment by meng-fucius** [comment]
the same issue.  Is there any solution?

**Comment by thapli9A** [comment]
> have the same issue. for example, i call `Permission.photos.request().isGranted` but nothing happened on ios

Make sure you have update podfile and info.plist for that :)

**Comment by The-Michael-Chen** [comment]
same here :(

**Comment by meng-fucius** [comment]
My issue has been solved.
Look at these codes
```
/// If you should show a rationale for requesting permission.
  ///
  /// This is only implemented on Android, calling this on iOS always returns
  /// [false].
  Future<bool> get shouldShowRequestRationale async {
    if (defaultTargetPlatform != TargetPlatform.android) {
      return false;
    }

    return _handler.shouldShowRequestPermissionRationale(this);
  }
```
On IOS 14, you don't need to use API such as ```Permission.photos.request()``` or ``` Permission.photos.isGranted```. IOS will pop up permission prompt box by itself when using relevant permissions.

**Comment by thapli9A** [comment]
@meng-fucius : There is point of opening app settings when pop is not presented earlier. same things is happening to me as ios native request popup dialog is not coming. as settings will be visible if opted/denied request in past

**Comment by thapli9A** [comment]
I got the answer for iOS. Enable Push Notification capabilities. and Request like this
 
 ```
Future<void> _requestPermission(BuildContext context) async {
    final status = await Permission.notification.status;
    if (status.isDenied) {
      final result = await Permission.notification.request();
      final isPermanentlyDenied = result.isPermanentlyDenied;
      if (result.isGranted) {
        _showDialog(context);
      } else if (isPermanentlyDenied) {
        openAppSettings();
      }
    } else if (status.isGranted) {
      _showDialog(context);
    }
  }

  void _showDialog(BuildContext context) {
    showDialog<void>(
      context: context,
      barrierDismissible: false, // user must tap button!
      builder: (BuildContext context) {
        return AlertDialog(
          title: const Text('Notification Permission Granted'),
          content: Text("Permission Granted"),
          actions: <Widget>[
            TextButton(
                child: const Text('Okay'),
                onPressed: () {
                  Navigator.of(context).pop();
                }),
          ],
        );
      },
    );
  }
```

**Comment by blaueeiner** [comment]
[v8.0.0](https://pub.dev/packages/permission_handler/changelog) introduced a breaking change for the iOS configuration on which pemissions you want to use.

The changelog says the following:

> Starting from this version the permissions on iOS are disabled by default. To enable a permission, specify the correct GCC_PREPROCESSOR_DEFINITIONS in the ios/Podfile file. For an example check out the [Podfile](https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler/example/ios/Podfile) of the example application.

Maybe this might also help someone.

**Comment by thapli9A** [comment]
@blaueeiner : is there any way we get call back receiving notifcation in device in case background/foreground with this library?

**Comment by blaueeiner** [comment]
@thapli9A Listen on flutter application lifecycle and get permission status on resume.

**Comment by JDDV** [comment]
The code shown by @thapli9A should work so the request dialog shows up.

Thank you @blaueeiner for your response, this also helps people out a lot!

> [v8.0.0](https://pub.dev/packages/permission_handler/changelog) introduced a breaking change for the iOS configuration on which pemissions you want to use.
> 
> The changelog says the following:
> 
> > Starting from this version the permissions on iOS are disabled by default. To enable a permission, specify the correct GCC_PREPROCESSOR_DEFINITIONS in the ios/Podfile file. For an example check out the [Podfile](https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler/example/ios/Podfile) of the example application.
> 
> Maybe this might help someone.

This issue will be closed since it's solved, if there are still any questions please let me know!
