### ISSUE TITLE
Permission status not returning proper status.

### ISSUE THREAD

**Issue by RajKateshiya** [Baseflow/flutter-permission-handler#611]
### Expected behavior

- If request for permission and then cancel permission dialog by back pressed then `permissionRequestStatus `received `permanentlyDenied`, it should return `denied `status instead of `permanentlyDenied`.
- If permission is `PermanentlyDenied`, but if we check permission status by `permission.status.isPermanentlyDenied` then it's returning false.

### Reproduction steps

1. Request any permission
2. Cancel permission by dialog by back press
3. Check permission status (received `permanentlyDenied`)

### Configuration

**Version:** 8.1.2

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by elianmortega** [comment]
Im currently facing the same issue.

I have my location and bluetooth permission enabled for iOS, but when I do:
```dart
final location = await Permission.location.request().isGranted;
final bluetooth = await Permission.bluetooth.request().isGranted;
```
I get both in false.

This is only happening on iOS for me, andorid is working great

**Comment by fldvlpr** [comment]
Also I'm trying to request location permission. But, it's not showing dialog prompt anyway.

Also, it shows permanentlydenied status always. 

It works find in android. But, issue persists in iOS devices

**Comment by elianmortega** [comment]
@fldvlpr But that is not a bug. On ios if a permission was already denied the prompt is not shown again the user has to manually go to settings to change the permission. You can read more on it here: https://stackoverflow.com/a/65920169/12933203

**Comment by shtreb** [comment]
@elianmortega  I think @fldvlpr told about other problem. When he call request some permission, he didn't see window with dialog about permission, but plugin had response 'permanentlyDenied' status. I have too this bug

**Comment by xmany** [comment]
I have the similar issue here, on iOS if I ask for camera permission by `await Permission.camera.status`, I got `PermissionStatus.denied`, while in fact the permission is granted, as seen in the app setting page.

**Comment by aayush0208** [comment]
I have this code for android 11 and higher version, it takes  user to the app permission screen when the user selects Allow all the time option and goes back this status throws a permanentlyDenied result.  

var status  = await Permission.locationAlways.request();
              if(status.isGranted)
                {
                  Fluttertoast.showToast(msg: "Permission Granted");
                  loadData();
                }

**Comment by zhihaozhang** [comment]
> @elianmortega I think @fldvlpr told about other problem. When he call request some permission, he didn't see window with dialog about permission, but plugin had response 'permanentlyDenied' status. I have too this bug

I downgrade the plugin to 6.0.1, it works.

**Comment by blaueeiner** [comment]
[v8.0.0](https://pub.dev/packages/permission_handler/changelog) introduced a breaking change for the iOS configuration on which pemissions you want to use.

The changelog says the following:

> Starting from this version the permissions on iOS are disabled by default. To enable a permission, specify the correct GCC_PREPROCESSOR_DEFINITIONS in the ios/Podfile file. For an example check out the [Podfile](https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler/example/ios/Podfile) of the example application.

**Comment by AhmedAbogameel** [comment]
any solutions ?
