### ISSUE TITLE
Permission request always return 'permanentlyDenied'

### ISSUE THREAD

**Issue by shtreb** [Baseflow/flutter-permission-handler#613]
## 🐛 Bug Report

Application don't show permission dialog. When app calling request permission at first time or other time, function return 'permanentlyDenied' without dialog.

Link to repo with simple project: https://github.com/shtreb/test-permission-handler

### Expected behavior

App is show dialog with permission

### Reproduction steps

You must call request permission and thats all.

### Configuration

**Version:** 8.1.2

**Platform:** 
- [X] :iphone: iOS
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
@shtreb please have a look at the iOS section of the [README.md](https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler/README.md) file. It mentions adding the permissions you want to use to your `ios/Podfile` file ([here](https://github.com/shtreb/test-permission-handler/blob/master/ios/Podfile) in your repo project).

If you don't enable the permissions they are not supported and the `permanentlyDenied` permission is returned. See also the breaking changes in version [8.0.0](https://pub.dev/packages/permission_handler/changelog#800).

**Comment by shtreb** [comment]
@mvanbeusekom thanks. Good luck
