### ISSUE TITLE
Contacts Permission returning false for Permanentlydenined everytime

### ISSUE THREAD

**Issue by shivangguptaa** [Baseflow/flutter-permission-handler#616]
## 🐛 Bug Report

Permission.contacts.isPermanentlyDenied returning false everytime.
### Expected behavior
If permission has been permanently denied the getter should return true.
### Reproduction steps
Permission.contacts.isPermanentlyDenied returning false everytime.
### Configuration

**Version:** 8.1.2

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
This is working as intended, please carefully read our [Wiki article](https://github.com/Baseflow/flutter-permission-handler/wiki/Changes-in-6.0.0) where this is discussed. You can also have a look at the following issue: #568.
