### ISSUE TITLE
On Android Permission.camera.request() returns denied while permanentlyDenied

### ISSUE THREAD

**Issue by JonasKuschel** [Baseflow/flutter-permission-handler#619]
## 🐛 Bug Report

This error is similar to #336

The camera permissions are permanentlyDenied however
`await Permission.camera.status;` returns denied

My current workaround:
`await Permission.camera.request();` returns permanentlyDenied

### Expected behavior
`await Permission.camera.status` should return permantly denied

### Configuration

permission_handler: ^8.1.2

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

### flutter doctor

[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale de-DE)
    • Flutter version 2.2.3 at /Users/jonaskuschel/Developer/flutter
    • Framework revision f4abaa0735 (vor 9 Tagen), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/jonaskuschel/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • sdk gphone x86 (mobile) • emulator-5556 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 91.0.4472.114

**Comment by mvanbeusekom** [comment]
Hello @JonasKuschel, this is working as intended. The reason is explained in this [issue](https://github.com/Baseflow/flutter-permission-handler/issues/568#issuecomment-849494650) and also on our [Wiki](https://github.com/Baseflow/flutter-permission-handler/wiki/Changes-in-6.0.0#breaking-changes).

**Comment by JonasKuschel** [comment]
Thank you for your answer 👍 
I would suggest moving it to the readme then. By only checking the installation guide it doesn't work as expected.

**Comment by Lawati97** [comment]
So am facing an issue regarding this and was hoping if someone can help me!

So am trying to track the status that am getting from the requested permission!

If i select deny on the first requested notification and the always allow the status being printed is denied (not am printing in changeDependency and init)

**Comment by akhiljohny** [comment]
post_install do |installer|
installer.pods_project.targets.each do |target|
flutter_additional_ios_build_settings(target)
target.build_configurations.each do |config|
config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
'$(inherited)',
## dart: PermissionGroup.camera
'PERMISSION_CAMERA=1'
]
end
end
end

Add this in pod file and delete pod lock and pod install then it will work

**Comment by akhiljohny** [comment]
post_install do |installer|
installer.pods_project.targets.each do |target|
flutter_additional_ios_build_settings(target)
target.build_configurations.each do |config|
config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
'$(inherited)',
# dart: PermissionGroup.camera
'PERMISSION_CAMERA=1'
]
end
end
end

Add this in pod file and delete pod lock and pod install then it will work
