### ISSUE TITLE
Cannot find symbol error ... what is going on 

### ISSUE THREAD

**Issue by KarthikRamanan16** [Baseflow/flutter-permission-handler#626]
## 💬 Questions and Help
![image](https://user-images.githubusercontent.com/44475571/126045230-59eba5f5-993a-4c98-bbbe-b72343dff0de.png)

**Comment by mvanbeusekom** [comment]
Please update the `compileSdkVersion` to `30` in your build.gradle. This is well documented in the Android section of the [README.md](https://github.com/Baseflow/flutter-permission-handler/blob/30939b0a4759d8120ecce155e781964443ea258f/permission_handler/README.md).
