### ISSUE TITLE
Calling Permission.microphone.request() keep return permanently denied even it was granted

### ISSUE THREAD

**Issue by nizwar** [Baseflow/flutter-permission-handler#632]
### Reproduction steps and expected behavior
First i check for mic permission, it return denied (the mic already granted from previous version 7.2.0 or let say granted from system)
and then it keep return Permanently Denied while i call request()

```dart
PermissionStatus checkPermission = await Permission.microphone.status;
if(checkPermission == PermissionStatus.granted) return true; //Expected the code end up here
if(checkPermission == PermissionStatus.denied) { 
    var request = await Permission.microphone.request();
    return request.isGranted;
}
```

all this happened on IOS with latest plugins, and it working fine on 7.2.0

**Comment by JDDV** [comment]
@nizwar have you updated the podfile? Since version ^8.0.0 the podfile should look different than it did before as stated in the [setup section](https://github.com/Baseflow/flutter-permission-handler/tree/master/permission_handler#setup) of the documentation.

your podfile should say something like:

```
## dart: PermissionGroup.microphone
        'PERMISSION_MICROPHONE=1',
```

Can you also try to run a `flutter clean` followed by a `flutter pub get` and `pod install` to make sure no caching issues will happen?

Let me know this solved your problem!

**Comment by 157163178002** [comment]
同样的问题，无法解决

**Comment by JDDV** [comment]
Hi @157163178002, it should work with the newest version of the permission handler. I tried to reproduce it again, and it still works using the newest version (^8.1.4+1).

Have you tried what I suggested in the last reaction I typed above here?

If it still does not work for you I would like to see your podfile and a small reproduction code snippet, a `flutter doctor -v` would also be appreciated.

thanks in advance!

**Comment by nizwar** [comment]
Its work with this, thanks!

> @nizwar have you updated the podfile? Since version ^8.0.0 the podfile should look different than it did before as stated in the [setup section](https://github.com/Baseflow/flutter-permission-handler/tree/master/permission_handler#setup) of the documentation.
> 
> your podfile should say something like:
> 
> ```
> ## dart: PermissionGroup.microphone
>         'PERMISSION_MICROPHONE=1',
> ```
> 
> Can you also try to run a `flutter clean` followed by a `flutter pub get` and `pod install` to make sure no caching issues will happen?
> 
> Let me know this solved your problem!
