### ISSUE TITLE
Thread 1: EXC_BAD_ACCESS (code=1, address=0x101)

### ISSUE THREAD

**Issue by Mocaris** [Baseflow/flutter-permission-handler#633]
## 🐛 Bug Report

<img width="1209" alt="image" src="https://user-images.githubusercontent.com/14064316/126735946-059fb693-68c1-4379-8339-a9bd271d1169.png">

### Configuration
 permission_handler: ^8.1.4

 '$(inherited)',
            ## dart: PermissionGroup.calendar
            # 'PERMISSION_EVENTS=1',
            ## dart: PermissionGroup.reminders
            # 'PERMISSION_REMINDERS=1',
            ## dart: PermissionGroup.contacts
            # 'PERMISSION_CONTACTS=1',
            ## dart: PermissionGroup.camera
             'PERMISSION_CAMERA=1',
            ## dart: PermissionGroup.microphone
            # 'PERMISSION_MICROPHONE=1',
            ## dart: PermissionGroup.speech
            # 'PERMISSION_SPEECH_RECOGNIZER=1',
            ## dart: PermissionGroup.photos
             'PERMISSION_PHOTOS=1',
            ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
             'PERMISSION_LOCATION=1',
            ## dart: PermissionGroup.notification
             'PERMISSION_NOTIFICATIONS=1',
            ## dart: PermissionGroup.mediaLibrary
            # 'PERMISSION_MEDIA_LIBRARY=1',
            ## dart: PermissionGroup.sensors
            # 'PERMISSION_SENSORS=1'

**Version:** 8.1.4
macOS 11.5
Xcode 12.5.1
**Platform:** 
- [√] :iphone: iOS

**Comment by eldarkk** [comment]
+1

**Comment by Mocaris** [comment]
macOS Big Sur 11.5

**Comment by JDDV** [comment]
@Mocaris & @eldarkk, Thank you for bringing this to our attention.
I can not get the same the error so I was wondering if you could provide us some more information.

Can you send a code snippet so we can reproduce the same issue, and can you also send your `plist.info` file?
That would be much appreciated, thanks in advance!

**Comment by Mocaris** [comment]
> @Mocaris & @eldarkk, Thank you for bringing this to our attention.
> I can not get the same the error so I was wondering if you could provide us some more information.
> 
> Can you send a code snippet so we can reproduce the same issue, and can you also send your `plist.info` file?
> That would be much appreciated, thanks in advance!
<img width="863" alt="image" src="https://user-images.githubusercontent.com/14064316/126750963-dbbba8ff-e3a6-4498-a9dd-e63c0d501c59.png">
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleDisplayName</key>
	<string>密停</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>flutter_matrix_park</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>weixin</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>wx3374cd450ff9f3fb</string>
			</array>
		</dict>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>alipay</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>ap2021001160672101</string>
			</array>
		</dict>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>alipayShare</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>ap2021001160672101</string>
			</array>
		</dict>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>mztc</string>
			</array>
		</dict>
		<dict>
			<key>CFBundleURLName</key>
			<string>app</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>mt</string>
			</array>
		</dict>
	</array>
	<key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
	<key>ITSAppUsesNonExemptEncryption</key>
	<false/>
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>iosamap</string>
		<string>amapuri</string>
		<string>weixin</string>
		<string>weixinULAPI</string>
	</array>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSAppleMusicUsageDescription </key>
	<string>App需要您的同意,才能访问Apple Music媒体资料库</string>
	<key>NSCameraUsageDescription</key>
	<string>APP需要您的同意，才能访问相机进行二维码扫描，如禁止将无法使用二维码扫描功能</string>
	<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
	<string>APP需要您的同意，才能持续访问位置，如禁止将无法持续更新位置信息，这将会影响您的电池续航时间，消耗更多的电量</string>
	<key>NSLocationAlwaysUsageDescription</key>
	<string>App需要您的同意，才能在使用期间持续访问位置</string>
	<key>NSLocationTemporaryUsageDescriptionDictionary</key>
	<dict>
		<key>AMapGeoFenceScene</key>
		<string>AMapLocationKit 地理围栏功能需要一次精确定位权限才可以正常使用</string>
		<key>AMapLocationScene</key>
		<string>AMapLocationKit 需要一次精确定位权限才可以正常使用</string>
	</dict>
	<key>NSLocationUsageDescription</key>
	<string>App需要您的同意，才能访问位置</string>
	<key>CFBundleLocalizations</key>
	<array>
		<string>zh_CN</string>
	</array>
	<key>CFBundleAllowMixedLocalizations</key>
	<true/>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>App需要您的同意，才能在使用期间访问位置</string>
	<key>NSMicrophoneUsageDescription</key>
	<string>App需要您的同意，才能访问麦克风</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>APP需要您的同意，才能访问相册进行选择照片上传/发布信息，如禁止将无法上传选择照片上传/发布信息</string>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
	<key>io.flutter.embedded_views_preview</key>
	<true/>
	<key>kTCCServiceMediaLibrary</key>
	<string>App需要您的同意,才能访问Apple Music媒体资料库</string>
</dict>
</plist>

**Comment by Mocaris** [comment]
> @Mocaris & @eldarkk, Thank you for bringing this to our attention.
> I can not get the same the error so I was wondering if you could provide us some more information.
> 
> Can you send a code snippet so we can reproduce the same issue, and can you also send your `plist.info` file?
> That would be much appreciated, thanks in advance!

This error occurred when I started the App after updating macOS to 11.5, and the flutter-permission-handler 8.1.3->8.1.4. After I removed the flutter-permission-handler dependency, the project worked fine

**Comment by Mocaris** [comment]
> @Mocaris & @eldarkk，感谢您提请我们注意此事。
> 我无法得到同样的错误，所以我想知道您是否能向我们提供更多的信息。
> 
> Can you send a code snippet so we can reproduce the same issue, and can you also send your `plist.info` file?
> 非常感谢，提前感谢！



> @Mocaris & @eldarkk, Thank you for bringing this to our attention.
> I can not get the same the error so I was wondering if you could provide us some more information.
> 
> Can you send a code snippet so we can reproduce the same issue, and can you also send your `plist.info` file?
> That would be much appreciated, thanks in advance!

**Comment by eldarkk** [comment]
on ios also such a bug. after updating ios to 14.6, getting crash

**Comment by eldarkk** [comment]
<img width="1177" alt="Снимок экрана 2021-07-23 в 14 11 16" src="https://user-images.githubusercontent.com/6400167/126755675-ce96aeb3-3d92-486d-8248-346b6e7b3a5e.png">

<img width="1439" alt="Снимок экрана 2021-07-23 в 14 27 11" src="https://user-images.githubusercontent.com/6400167/126756408-dfa62c98-071b-4419-8c5b-c9bd6a6a1c3a.png">


**permission_handler: ^8.1.4**

**Deployment Target: ios 10.**

**Cocoapods: 1.10.1**

**Podfile**
```
# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  
  pod 'Kronos'
  pod 'Alamofire', '~> 4.5'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    target.build_configurations.each do |config|
          # You can remove unused permissions here
          # for more infomation: https://github.com/BaseflowIT/flutter-permission-handler/blob/master/permission_handler/ios/Classes/PermissionHandlerEnums.h
          # e.g. when you don't need camera permission, just add 'PERMISSION_CAMERA=0'
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
            '$(inherited)',

            ## dart: PermissionGroup.calendar
            'PERMISSION_EVENTS=0',

            ## dart: PermissionGroup.reminders
            'PERMISSION_REMINDERS=0',

            ## dart: PermissionGroup.contacts
            'PERMISSION_CONTACTS=0',

            ## dart: PermissionGroup.camera
            'PERMISSION_CAMERA=1',

            ## dart: PermissionGroup.microphone
            'PERMISSION_MICROPHONE=0',

            ## dart: PermissionGroup.speech
            'PERMISSION_SPEECH_RECOGNIZER=0',

            ## dart: PermissionGroup.photos
            'PERMISSION_PHOTOS=1',

            ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
            'PERMISSION_LOCATION=1',
           
            ## dart: PermissionGroup.notification
            'PERMISSION_NOTIFICATIONS=1',

            ## dart: PermissionGroup.mediaLibrary
            'PERMISSION_MEDIA_LIBRARY=1',

            ## dart: PermissionGroup.sensors
            'PERMISSION_SENSORS=0',

            ## dart: PermissionGroup.bluetooth
            'PERMISSION_BLUETOOTH=0',

            ## dart: PermissionGroup.appTrackingTransparency
            'PERMISSION_APP_TRACKING_TRANSPARENCY=0'
          ]

        end
  end
end
```

**Comment by Mocaris** [comment]
We have the same bugs

**Comment by Mocaris** [comment]
We have the same mistake @eldarkk

**Comment by JDDV** [comment]
@Mocaris and @eldarkk, this the same issue occur if you go back one version of the permission handler in the `pub spec.yaml` (version ^8.1.3)?

Also to make sure there is no caching problem try to run a `flutter clean` and then a `flutter pub get` to get the dependencies.

**Comment by Mocaris** [comment]
@JDDV 

> @Mocaris and @eldarkk, this the same issue occur if you go back one version of the permission handler in the `pub spec.yaml` (version ^8.1.3)?
> 
> Also to make sure there is no caching problem try to run a `flutter clean` and then a `flutter pub get` to get the dependencies.

There is no problem with the 8.1.3 version used yesterday, because I submitted the packaged version to TestFlight. This problem occurred after the 8.1.4 version was upgraded

**Comment by Mocaris** [comment]
@JDDV  Thanks

**Comment by JDDV** [comment]
@Mocaris & @eldarkk, you can safely use the newest version which just is published (version ^8.1.4+1). There was a small bug where the code 
```
else if (status != PermissionStatusDenied) {
        completionHandler(status);
    }
```

did not have a `return;` statement, so it would go further to the `requestAlwaysAuthorization` while the `_permissionStatusHandler` was already removed from the memory, resulting in the error as shown in your images. this is fixed now by adding a `return;` statement in the code.

This solved the problem for us, I will close this issue now but please feel free to comment again if it did not solve your problem!

**Comment by WXXXXH** [comment]
> @Mocaris & @eldarkk，您可以安全地使用刚刚发布的最新版本（版本^8.1.4+1）。代码有一个小错误
> 
> ```
> else if (status != PermissionStatusDenied) {
>         completionHandler(status);
>     }
> ```
> 
> 没有`return;`语句，所以当`_permissionStatusHandler`已经从内存中删除时，它会进一步转到`requestAlwaysAuthorization`，导致图像中显示的错误。现在通过在代码中添加`return;`语句来解决这个问题。
> 
> 这为我们解决了问题，我现在将解决这个问题，但如果它没有解决您的问题，请随时再次发表评论！

<img width="964" alt="image" src="https://user-images.githubusercontent.com/35984644/126943867-53101d8f-936a-4531-b0cc-876e6838a813.png">

**Comment by JDDV** [comment]
Hi @WXXXXH, Can you provide us with a bit more information?
Like when does this error happen for you and which permission did you try to request before getting this error?

Can you provide a small minimal reproduction code snippet so I can see where this error is coming from?

Thanks in advance!
