### ISSUE TITLE
isPermanentlyDenied trouble

### ISSUE THREAD

**Issue by ardipermana59** [Baseflow/flutter-permission-handler#643]
## 💬 Questions and Help

For questions or help we recommend checking:
i ran `var status = await Permission.camera.status;` and check status.
when i click Reject Permanently in my app, `status.isPermanentlyDenied` always return `false` and return `true`  in `status.denied`.

how to get true when user click Reject Permanently ?

**Comment by mvanbeusekom** [comment]
Unfortunately you can't because Android doesn't provide this information when "checking" the status. More details can be found in the [Changes in 6.0.0](https://github.com/Baseflow/flutter-permission-handler/wiki/Changes-in-6.0.0) wiki article. 

You can also have a look at issue #568.
