### ISSUE TITLE
camera and location

### ISSUE THREAD

**Issue by goldenplan** [Baseflow/flutter-permission-handler#649]
Version permission_handler 8.1.4+2  iOS

PermissionStatus permissionStatus = await Permission.camera.request(); //location, location, locationAlways, mediaLibrary

This method does not return a correct result about the status of permissions and does not display a window with its request. Does not work in iOS!

**Comment by stoneUoU** [comment]
我也遇到了，Version permission_handler 8.1.4+2 iOS    不能弹出请求权限的弹窗      降为permission_handler: ^6.1.1 就行了，待官方修复

**Comment by JDDV** [comment]
@goldenplan and @stoneUoU, it seems like you went both from an older version to a newer version of the `permission_handler` plugin. In the changelog it says that since version `^8.0.0` the podfile should be updated in your projects since there has been a few changes. To see what has changed you can look in the [setup](https://github.com/Baseflow/flutter-permission-handler/tree/master/permission_handler#setup) section of the documentation.

I always like to do a `flutter clean` followed by a `flutter pub get` and `pod install` to make sure no weird chaching issues happen.
Let me know if it worked!

**Comment by JDDV** [comment]
@CellCS, I tried your code snippet, and for me it works. I got the permission status `isGranted` back. For me it sounds like you didn't change the podfile as mentioned in my previous comment.

> In the changelog it says that since version `^8.0.0` the podfile should be updated in your projects since there has been a few changes. To see what has changed you can look in the [setup](https://github.com/Baseflow/flutter-permission-handler/tree/master/permission_handler#setup) section of the documentation.

Did you try this, and run a `pod install`? I tried it on the newest version of the plugin (version ^ 8.1.6). Let me know if it worked!

**Comment by CellCS** [comment]
Hi JDDV, thanks for your response. so in your test case.: Camera permission dialog pops up? and after your click yes, then console.log has `isGranted`, by the way, may i know your test env and device os version? thanks

I repeat whole test, still directly get log `"isPermanentlyDenied"` and `Permission.camera.request()` does not fire system camera permission dialog.  

Here is my test steps: 

1. `Flutter create my_app`, add testing codes (mentioned above) in `lib/main.dart`
2. `open ios/Runner.xcworkspace` to finish sign
3.  `cd ios`
4.  `pop install` 

`Pod installation complete! There are 2 dependencies from the Podfile and 2 total pods installed.`

5. ` flutter run` 
6.  Select ipad - 6th, iPadOS 14.7.1
7.   Click "+",  no system camera permission request dialog shows up, console.log  has 

```
The Flutter DevTools debugger and profiler on ????’s iPad is
available at:
http://127.0.0.1:9116?uri=http://127.0.0.1:62148/POebxXXXXXXX=/
flutter: ==isDenied=
flutter: ---is permissionStatus.isPermanentlyDenied
```

**Comment by kimwong0919** [comment]
final permissionStatus = await Permission.camera.request();
nothing happened, and the 'permissionStatus.isGranted' return false.

**Comment by CellCS** [comment]
@kimwong0919  so you reproduced the same reported issues.  if you find solutions, let me know. thanks.

**Comment by JDDV** [comment]
Hi @CellCS, I don't have access to an Apple device right now to test it. But I know I did test it using Xcode 12.5 on an emulator (iOS version 14). It does not fire the dialog asking you permission you said, I feel like maybe your `info.plist` is not set up correctly? Could you follow the setup instructions as mentioned [here](https://github.com/Baseflow/flutter-permission-handler/tree/master/permission_handler#setup) and let me know if it worked? An example of the `info.plist` file can be found [here](https://github.com/Baseflow/flutter-permission-handler/blob/develop/permission_handler/example/ios/Runner/Info.plist).

Thanks in advance!
