### ISSUE TITLE
Permission cause a crash in the application

### ISSUE THREAD

**Issue by Lawati97** [Baseflow/flutter-permission-handler#651]
## 💬 Questions and Help

So my issue is that if I set the authentication to true and then I change it from the settings the app crashes and am not sure why I am using permission_handler: ^8.1.4+2 with flutter 2.2.3

Including to that am using the 
-keep class androidx.lifecycle.DefaultLifecycleObserver in the progaurd file

and
try/catch for the runapp

I have tested this with android

**Comment by mvanbeusekom** [comment]
Hi @Lawati97,

I am having troubles understanding the exact issue you are experiencing. 

It is clear to me that your app is crashing but I have the following questions:

1. Which permissions are you requesting exactly?
2. Can you provide a code sample of the code you are using? Or even better can you provide a minimal example application reproducing the bug?

**Comment by Lawati97** [comment]
So am requesting permission for using the Camera and Location

Steps to reproduce the bug:
When I enter the application and the request pops up I accept "while using the app" and then I go to settings and change the permission manually to deny when I go back to the application it gets stuck at the splash screen, and if I restart the application when I open the application it would crash

**Comment by mvanbeusekom** [comment]
Can you provide an example app reproducing the problem?

**Comment by Lawati97** [comment]
Sure ill work on something and share it

**Comment by Lawati97** [comment]
@mvanbeusekom my sincere apologies it ended up being from the camera plugin that am using

**Comment by mvanbeusekom** [comment]
No problem, thank you for letting us know.
