### ISSUE TITLE
Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Activity.getPackageManager()' on a null object reference

### ISSUE THREAD

**Issue by Super-Bin** [Baseflow/flutter-permission-handler#654]
## 🐛 Bug Report

firebase report
![WX20210819-110146](https://user-images.githubusercontent.com/26457469/130001032-a24af95f-a22d-4ac4-98df-f54d4f7d2fbf.png)
![WX20210819-110105](https://user-images.githubusercontent.com/26457469/130001038-21d48917-98ca-4ebf-9659-821c4aae0da3.png)

### Expected behavior
fix bug

### Configuration
[✓] Flutter (Channel unknown, 2.2.0, on Mac OS X 10.15.7 19H1217 darwin-x64, locale
    zh-Hans-CN)
    • Flutter version 2.2.0 at /Users/01400043/Library/flutter
    • Framework revision b22742018b (3 months ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/01400043/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/01400043/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • SM G9730 (mobile) • RF8N304THAB • android-arm64  • Android 11 (API 30)
    • Chrome (web)      • chrome      • web-javascript • Google Chrome
      92.0.4515.159

**Version:** permission_handler-8.1.2

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by JDDV** [comment]
Hi @Super-Bin, This issue came to my attention and I've found out why, in Issue #653 I've also explained why this is happening.

> Hi @nayoTT, I was able to reproduce the same error. I've found the following information about it - [Click Here](https://www.androidpolice.com/2020/08/24/android-11-install-unknown-apps-more-cumbersome/)
> 
> The TL;DR version is that since Android version 11 kills the process when asked for this particular permission.
> Google stated "this is in fact working as intended.". Google explained it had to do with the new Scoped Storage.
> I also saw [this Issue Tracker](https://issuetracker.google.com/issues/154157387?pli=1) from Google where people complained about this issue.
> 
> I tested the behavior on Android 10, and guess what, it worked as it was supposed to do. The app process didn't get killed by the OS. So this seems to be an Android 11 issue.

So the error you show in the picture gives a `NullPointerException` cause the app process is killed by the OS itself, hence the reason why you get the error.

I will close this issue for now since it's something we can not fix since it's an Android 11 issue. But if you still have question(s), feel free to ask them!
