### ISSUE TITLE
iOS microphone permission returns wrong status

### ISSUE THREAD

**Issue by sleith** [Baseflow/flutter-permission-handler#658]
## 🐛 Bug Report
I use iphone 14.4.2
The microphone is already enabled for the app i checked at Settings
But when try:
1. Permission.microphone.request() -> the returned status is `PermissionStatus.permanentlyDenied`, which should only possible for Android.
2. Permission.microphone.status -> this returned status `PermissionStatus.denied`

I tried version 7.2.0 is working good.

### Expected behavior
Both methods should return `PermissionStatus.granted`

### Reproduction steps
1. make sure app microphone is enabled at ios settings
2. try call Permission.microphone.status it will return `PermissionStatus.permanentlyDenied`
3. try call Permission.microphone.request() will return `PermissionStatus.denied`

### Configuration
**Version:** 8.1.4+2

**Platform:** 
- [x] :iphone: iOS 14.4.2

**Comment by mvanbeusekom** [comment]
Hi @sleith,

Please carefully read the CHANGELOG.md (version 8.0.0) and the iOS section in the README.md.

We have flipped the behavior of the configuration in the Podfile. Since version 8.0.0 you have to specifically enable the permissions you want to use.
