### ISSUE TITLE
Forgot Permission status after clear data in android

### ISSUE THREAD

**Issue by dhaval0122** [Baseflow/flutter-permission-handler#66]
## 🐛 Bug Report

very first time grant permission then do clear data in android app, run app again its forgot permission is granted or not.

### Expected behavior

ask permission again if clear data

### Reproduction steps
as explained first grand permission then do clear data. now again check in app permission is granted or not.

### Configuration

**Version:** ^2.1.2

**Platform:** 
- [] :robot: Android

**Comment by mvanbeusekom** [comment]
This is default Android behaviour and working as intended.
