### ISSUE TITLE
Podfile changes still needed?

### ISSUE THREAD

**Issue by SimonHausdorf** [Baseflow/flutter-permission-handler#660]
I am referring to the iOS part from this documentation: https://pub.dev/packages/permission_handler

It says: ~~You will have to include all permission options when you want to submit your App.~~

I added the descriptions to my Info.plist file but did not adjust the Podfile. Submitting the app wasn't a problem and I did not get any warning email from apple. It this deprecated and not needed anymore?

As it is still documented, I am not sure if required or not.

**Comment by JDDV** [comment]
Hi @SimonHausdorf, this used to be the case before version ^4.1.0. Since version ^4.1.0 the issue where you have to include all permission options when you want to submit your app is fixed and not mandatory anymore.
