### ISSUE TITLE
Deprecation warnings when compiling against Android API 31

### ISSUE THREAD

**Issue by Frostlight** [Baseflow/flutter-permission-handler#661]
## 🐛 Bug Report
Similarly to geolocator, deprecation warnings that break compilation occur when using Android API 31.
Link to geolocator issue: https://github.com/Baseflow/flutter-geolocator/issues/828

I quoted the body below for reference. Reproduction steps are exact same as for geolocator:
> ## 🐛 Bug Report
> Using the geolocator plugin on Android API 31 generates the following error:
> 
> ```
> Note: Recompile with -Xlint:deprecation for details.
> 3 warnings
> /Users/efzet/.pub-cache/hosted/pub.dartlang.org/geolocator-7.3.1/android/src/main/java/com/baseflow/geolocator/location/LocationManagerClient.java:10: warning: [deprecation] LocationProvider in android.location has been deprecated
> import android.location.LocationProvider;
>                        ^
> error: warnings found and -Werror specified
> /Users/efzet/.pub-cache/hosted/pub.dartlang.org/geolocator-7.3.1/android/src/main/java/com/baseflow/geolocator/location/LocationMapper.java:29: warning: [deprecation] isFromMockProvider() in Location has been deprecated
>       position.put("is_mocked", location.isFromMockProvider());
>                                         ^
> 1 error
> 2 warnings
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':geolocator:compileDebugJavaWithJavac'.
> > Compilation failed; see the compiler error output for details.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 47s
> Exception: Gradle task assembleStagingDebug failed with exit code 1
> ```
> 
> Starting from Android API 31 the `LocationProvider` class and `isFromMockProvider` method are deprecated. More information can be found in the official documentation:
> 
> * https://developer.android.com/reference/android/location/LocationProvider
> * https://developer.android.com/reference/android/location/Location#isFromMockProvider()
> 
> ### Expected behavior
> Compiling an App depending on the geolocator plugin should work fine on Android 31.
> 
> ### Reproduction steps
> To reproduce this on the example App take the following steps:
> 
> 1. Open `example/android/app/build.gradle` file;
> 2. Change the `compileSdkVersion` to value `31`;
> 3. Build the example app using `flutter build appbundle`
> 
> ### Configuration
> **Version:** 7.6.0
> 
> **Platform:**
> 
> * [x]  🤖 Android

**Comment by Ahmed-elshorbagy** [comment]
also with bluetooth 
```
C:\src\flutter2\.pub-cache\hosted\pub.dartlang.org\permission_handler-8.1.4+2\android\src\main\java\com\baseflow\permissionhandler\ServiceManager.java:152: warning: [deprecation] getDefaultAdapter() in BluetoothAdapter has been deprecated
        final BluetoothAdapter bluetoothAdapter = BluetoothAdapter.getDefaultAdapter();
                                                                  ^
error: warnings found and -Werror specified
1 error
1 warning
```

**Comment by heroqin** [comment]
I've got the same problem with bluetooth.

**Comment by chiragabhani** [comment]
C:\Users\HP\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\permission_handler-7.2.0\android\src\main\java\com\baseflow\permissionha
ndler\ServiceManager.java:152: warning: [deprecation] getDefaultAdapter() in BluetoothAdapter has been deprecated
        final BluetoothAdapter bluetoothAdapter = BluetoothAdapter.getDefaultAdapter();
                                                                  ^
error: warnings found and -Werror specified
1 error
1 warning

**Comment by radhen-thirstydevs** [comment]
is there any hope?

**Comment by heroqin** [comment]
> 
> 
> is there any hope to solve the issue ?

To temporary solve the problem, delete -Werror in build.gradle( third line) under android directory of permission_handler package

**Comment by radhen-thirstydevs** [comment]
if you don't mind can you give the full path of the android file.

> > is there any hope to solve the issue ?
> 
> To temporary solve the problem, delete -Werror in build.gradle( third line) under android directory of permission_handler package

**Comment by ygotthilf** [comment]
I've got the same problem with bluetooth.

**Comment by ygotthilf** [comment]
@radhen-thirstydevs 

As workaround, you could :
1. Clone this repo
2. Remove the `-Werror` in the `permission-handler/android/build.gradle` file
3. Commit and merge
4. Import in your project like that :

```
permission_handler:
    git:
      url: https://github.com/<PROJECT>/flutter-permission-handler.git
      path: permission_handler
```

Hope it helps.

**Comment by radhen-thirstydevs** [comment]
Thank you so much for your help buddy @ygotthilf ....

**Comment by heroqin** [comment]
> 
> 
> if you don't mind can you give the full path of the android file.
> 
> > > is there any hope to solve the issue ?
> > 
> > 
> > To temporary solve the problem, delete -Werror in build.gradle( third line) under android directory of permission_handler package

On my computer, the file build.gradel is under: C:\flutter\.pub-cache\hosted\pub.flutter-io.cn\permission_handler-8.1.4+2\android\
