### ISSUE TITLE
Separate Log group

### ISSUE THREAD

**Issue by ademirtug** [Baseflow/flutter-permission-handler#668]
## 🚀 Feature Requests

Move 
android.permission.READ_CALL_LOG
android.permission.WRITE_CALL_LOG

permissions into their own group. Since READ_CALL_LOG requires app to fully implement incoming/outgoing call interfaces and ask user to set the app as default phone application to just make a phone call using android.permission.CALL_PHONE permission.

**Comment by JDDV** [comment]
Hi @ademirtug, I don't fully understand what you mean with 'requires app to fully implement incoming/outgoing call interfaces and ask user to set the app as default phone application'.

If I understand correctly, you try to request the `phone` permission, using the permission handler, and it prompts you a dialog with the choice to pick between installed apps to select one default app for making a phone call, or does it prompt you to set your app as the default phone application?

I tried to request the `phone` permission while I had another 'phone call/managing' app installed named Drupe. It didn't prompt me to pick a default phone application, so I'm curious about the code you have this problem with.

For me to help you further, I would like to see a (minimal) code snippet so I can reproduce the issue.
Also a `flutter doctor -v` output would be helpful.
Are you testing on a Simulator or a real device, and which Android version do you use?

I hope I can help you out further when I get the extra information, thanks in advance!

**Comment by ademirtug** [comment]
Let us suppose we are building an fully fledged dialer app and imagine the user have refused to set the app as default application and tried to call a number which requires a certain permission. Due to presence of read_call_log permission in manifest file, you will be asking for that permission too and it is against the play store rules. If your app is not default phone/dialer app you can't ask for read_call_log permission.

I have fixed the problem in my own fork. It looks like an extreme case for my situation.
