### ISSUE TITLE
error: cannot find symbol             case Manifest.permission.BLUETOOTH_SCAN:                                     ^   symbol:   variable BLUETOOTH_SCAN

### ISSUE THREAD

**Issue by bugrevealingbme** [Baseflow/flutter-permission-handler#687]
## 🐛 Bug Report

E:\src\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-8.2.2\android\src\main\java\com\baseflow\permissionhandler\PermissionUtils.java:72: error: cannot find symbol
            case Manifest.permission.BLUETOOTH_SCAN:
                                    
  symbol:   variable BLUETOOTH_SCAN
  location: class permission
E:\src\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-8.2.2\android\src\main\java\com\baseflow\permissionhandler\PermissionUtils.java:74: error: cannot find symbol

**Version:** 8.2.2

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by cellininicholas** [comment]
+1
I'm having the same issue.

**Comment by jasonhe88** [comment]
having the same issue

**Comment by cellininicholas** [comment]
I think I just solved it by following this issue: https://github.com/Baseflow/flutter-permission-handler/pull/686
By making sure `compileSdkVersion` in android/app/build.gradle is set to 31 as required by version 8.2.0 of the permission_handler.

**Comment by mvanbeusekom** [comment]
Please also check the `CHANGELOG.md` and the `README.md` which describe the new requirement on `compileSdkVersion` being set to `31`.
