### ISSUE TITLE
Introduce permission_handler and fail to build the project

### ISSUE THREAD

**Issue by 906499861** [Baseflow/flutter-permission-handler#688]
![20211006195406](https://user-images.githubusercontent.com/82579833/136198551-f1401a5b-6129-4d88-9dc1-09671acc2f8f.png)
![20211006195314](https://user-images.githubusercontent.com/82579833/136198556-c33cb24a-77b6-4a3d-b0c4-5a058d48a6db.png)
![20211006200114](https://user-images.githubusercontent.com/82579833/136198569-1448548d-7c5b-479d-b905-075cf418dbf5.png)

**How should I solve this?**

**Comment by 906499861** [comment]
**This is the development tool I use*
![20211006200630](https://user-images.githubusercontent.com/82579833/136199061-f3162328-1387-4592-88e9-74bf081714fa.png)
*

**Comment by mvanbeusekom** [comment]
Please update the `compileSdkVersion` in your `android/app/build.gradle` file to `31` as mentioned in the [CHANGELOG.md](https://pub.dev/packages/permission_handler/changelog#820).
