### ISSUE TITLE
Permissions-Handler claims: No permissions found in manifest for: []30 and 28 but they exist in the Manifest

### ISSUE THREAD

**Issue by ptrckdev** [Baseflow/flutter-permission-handler#691]
## 🐛 Bug Report

I am using this line to request permissions to use Bluetooth and Location Services
`Map<Permission, PermissionStatus> statuses = await [Permission.bluetoothConnect, Permission.bluetoothScan, Permission.location].request();`

### Expected behavior

User Request for Location and Bluetooth permissions shows up.

### Actual behavior

Request for Location service shows up but for Bluetooth, it does not.
Logging output:
`D/permissions_handler( 7688): No permissions found in manifest for: []30`
`D/permissions_handler( 7688): No permissions found in manifest for: []28`

Which are bluetoothConnect and bluetoothScan according to the docs

### Configuration

In Android, minSDK is set to 31. In my `main/AndroidManifest.xml` I added the required tags BLUETOOTH_ADVERTISE, BLUETOOTH_CONNECT, and BLUETOOTH_SCAN for Android 12 and BLUETOOTH and BLUETOOTH_ADMIN for up to SDK 30.

My target is a mobile phone with Android 11.

**Version:** 8.2.2

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by ptrckdev** [comment]
The problem was asking for permissions in Flutter which are not part of my current SDK.
We could add a fail save check to discard unused Permissions from a request in a future release of this plugin.

Otherwise you will need to get the currentSDK via a plugin like [device_info](https://pub.dev/packages/device_info) and adjust the request accordingly:

`
import 'package:device_info/device_info.dart';

Map<Permission, PermissionStatus> statuses;

    DeviceInfoPlugin deviceInfo = DeviceInfoPlugin();

    if(Platform.isAndroid) {
      AndroidDeviceInfo androidInfo  = await deviceInfo.androidInfo;
      if(androidInfo.version.sdkInt >= 31) {
        statuses = await [Permission.bluetoothConnect, Permission.bluetoothScan, Permission.location].request();
      } else {
        statuses = await [Permission.bluetooth, Permission.location].request();
      }
    } else {
      return 'ios not yet supported';
    }
`

**Comment by MohaDevPro** [comment]
there is an error in 8.3.0 
`Running Gradle task 'assembleDebug'...
D:\Programs\flutter\flutter_windows_2.5.2-stable\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-8.2.4\android\src\main\java\com\baseflow\permissionhandler\PermissionManager.java:321: error: cannot find symbol
            if (Build.VERSION.SDK_INT < Build.VERSION_CODES.S) {
                                                           ^
  symbol:   variable S
  location: class VERSION_CODES
D:\Programs\flutter\flutter_windows_2.5.2-stable\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-8.2.4\android\src\main\java\com\baseflow\permissionhandler\PermissionUtils.java:72: error: cannot find symbol
            case Manifest.permission.BLUETOOTH_SCAN:
                                    ^
  symbol:   variable BLUETOOTH_SCAN
  location: class permission
D:\Programs\flutter\flutter_windows_2.5.2-stable\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-8.2.4\android\src\main\java\com\baseflow\permissionhandler\PermissionUtils.java:74: error: cannot find symbol
            case Manifest.permission.BLUETOOTH_ADVERTISE:
                                    ^
  symbol:   variable BLUETOOTH_ADVERTISE
  location: class permission
D:\Programs\flutter\flutter_windows_2.5.2-stable\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-8.2.4\android\src\main\java\com\baseflow\permissionhandler\PermissionUtils.java:76: error: cannot find symbol
            case Manifest.permission.BLUETOOTH_CONNECT:
                                    ^
  symbol:   variable BLUETOOTH_CONNECT
  location: class permission
D:\Programs\flutter\flutter_windows_2.5.2-stable\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-8.2.4\android\src\main\java\com\baseflow\permissionhandler\PermissionUtils.java:259: error: cannot find symbol
                String result = determineBluetoothPermission(context, Manifest.permission.BLUETOOTH_SCAN);
                                                                                         ^
  symbol:   variable BLUETOOTH_SCAN
  location: class permission
D:\Programs\flutter\flutter_windows_2.5.2-stable\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-8.2.4\android\src\main\java\com\baseflow\permissionhandler\PermissionUtils.java:270: error: cannot find symbol
                String result = determineBluetoothPermission(context, Manifest.permission.BLUETOOTH_ADVERTISE);
                                                                                         ^
  symbol:   variable BLUETOOTH_ADVERTISE
  location: class permission
D:\Programs\flutter\flutter_windows_2.5.2-stable\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-8.2.4\android\src\main\java\com\baseflow\permissionhandler\PermissionUtils.java:281: error: cannot find symbol
                String result = determineBluetoothPermission(context, Manifest.permission.BLUETOOTH_CONNECT);
                                                                                         ^
  symbol:   variable BLUETOOTH_CONNECT
  location: class permission
D:\Programs\flutter\flutter_windows_2.5.2-stable\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-8.2.4\android\src\main\java\com\baseflow\permissionhandler\PermissionUtils.java:370: error: cannot find symbol
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S && hasPermissionInManifest(context, null, permission )) {
                                                        ^
  symbol:   variable S
  location: class VERSION_CODES
8 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':permission_handler:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 38s
Exception: Gradle task assembleDebug failed with exit code 1
`

**Comment by ptrckdev** [comment]
Looks like your SDK Version is lower than Android S. Have you set the `compileSdkVersion` to `31` as per the documentation?

**Comment by mvanbeusekom** [comment]
@MohaDevPro version 8.2.0 depends on Android API 31 (Android 12). This means you will have to update the `compileSdkVersion` in your `android/app/build.gradle` file and set it to `31`. Example configuration can be found in our [example App](https://github.com/Baseflow/flutter-permission-handler/blob/56e58fa2c55df330d82cba7c07037b1288a4e779/permission_handler/example/android/app/build.gradle#L28).

This is also documented in the [CHANGELOG.md](https://pub.dev/packages/permission_handler/changelog#820) and the [README.md](https://pub.dev/packages/permission_handler). There are also several closed issues that mention the same problem (e.g. #712, #698, #697, #696).

**Comment by xaviergspintly** [comment]
> The problem was asking for permissions in Flutter which are not part of my current SDK. We could add a fail save check to discard unused Permissions from a request in a future release of this plugin.
> 
> Otherwise you will need to get the currentSDK via a plugin like [device_info](https://pub.dev/packages/device_info) and adjust the request accordingly:
> 
> `import 'package:device_info/device_info.dart';
> 
> ```
> Map<Permission, PermissionStatus> statuses;
> 
> DeviceInfoPlugin deviceInfo = DeviceInfoPlugin();
> 
> if(Platform.isAndroid) {
>   AndroidDeviceInfo androidInfo  = await deviceInfo.androidInfo;
>   if(androidInfo.version.sdkInt >= 31) {
>     statuses = await [Permission.bluetoothConnect, Permission.bluetoothScan, Permission.location].request();
>   } else {
>     statuses = await [Permission.bluetooth, Permission.location].request();
>   }
> } else {
>   return 'ios not yet supported';
> }`
> ```

There is a problem however, running it on Android 12 devices. On android 12 devices location is not required for scanning, connecting and advertising. The Nearby permission pop up should be shown but instead the location permission pops up. What I end up with getting is the location permission rather than the intended bluetooth scan, advertise and connect permission. Below is what I'm doing and adequate permissions are put in the manifest file:

`Map<Permission, PermissionStatus> statuses = await [
      Permission.bluetoothScan,
      Permission.bluetoothAdvertise,
      Permission.bluetoothConnect
    ].request();`

**Comment by xaviergspintly** [comment]
> Have you added
> 
> `android:usesPermissionFlags="neverForLocation"`
> 
> to the `BLUETOOTH_SCAN` Permission in the Manifest? Only then you are free to not ask for location permission.
> 
> See: https://developer.android.com/guide/topics/connectivity/bluetooth/permissions#assert-never-for-location
> 
> Also you shouldn't use my workaround as the issue has been fixed in version `8.2.4` of this package.

Yes I have:

`<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" android:maxSdkVersion="30" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" android:maxSdkVersion="30"/>
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" android:maxSdkVersion="30"/>
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" android:maxSdkVersion="30"/>
    <uses-permission android:name="android.permission.BLUETOOTH" android:maxSdkVersion="30"/>

    <uses-permission android:name="android.permission.BLUETOOTH_SCAN" android:usesPermissionFlags="neverForLocation"/>
    <uses-permission android:name="android.permission.BLUETOOTH_ADVERTISE" />
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />`

**Comment by xaviergspintly** [comment]
> Have you added
> 
> `android:usesPermissionFlags="neverForLocation"`
> 
> to the `BLUETOOTH_SCAN` Permission in the Manifest? Only then you are free to not ask for location permission.
> 
> See: https://developer.android.com/guide/topics/connectivity/bluetooth/permissions#assert-never-for-location
> 
> Also you shouldn't use my workaround as the issue has been fixed in version `8.2.4` of this package.



> Have you added
> 
> `android:usesPermissionFlags="neverForLocation"`
> 
> to the `BLUETOOTH_SCAN` Permission in the Manifest? Only then you are free to not ask for location permission.
> 
> See: https://developer.android.com/guide/topics/connectivity/bluetooth/permissions#assert-never-for-location
> 
> Also you shouldn't use my workaround as the issue has been fixed in version `8.2.4` of this package.

Had done that actually. But, my apologies, I had edited manifest of app/src/profile/ and not app/src/main/
It works now.
