### ISSUE TITLE
Gets Permission Granted Status for Limited Permission.

### ISSUE THREAD

**Issue by rashidkhaleefa** [Baseflow/flutter-permission-handler#693]
## 🐛 Bug Report

The Permission.location.status method is returning PermissionStatus.denied if the location service is limited (precise location disabled) in iPhone (>14). (Note: I experience the same for photo access also)

### Expected behaviour
 Expects the plugin to return PermissionStatus.limited while the user has not enabled the precise location in iPhone

### Reproduction steps
 1) Make a fresh install of the app.
 2) Call Permission.location.status which will bring up the iOS permission dialog.
 3) Disable the precise location on the top left corner.
 4) Select on Allow while using the app.
 5) Now the plugin will return permission granted instead of limited state.
 
**Version:** 8.2.2

**Platform:** 
- [x] :iphone: iOS 14 +
- [ ] :robot: Android

**Comment by rashidkhaleefa** [comment]
Yes I think checking for accuracy and setting it to the status would help. Specifically for applications that required precise location.
 ```
switch locationManager.accuracyAuthorization {
        case .reducedAccuracy:
         // limited access case here
        case .fullAccuracy:
} 
```

Its the similar case for PhotoAccess permission too. Again I understand it's perfectly depends on the use case but, For iOS >14 it is difficult to understand if we have limited access or complete access to photos. 

```
if #available(iOS 14, *) {
            PHPhotoLibrary.requestAuthorization(for: .readWrite) { (status) in
                switch status {
                case .limited:
                  // limited access case here
                    break
                case ..
                }
            }
        }
```

**Comment by mvanbeusekom** [comment]
The current version of the permission_handler will return the `granted` status no matter if the user allowed precise or reduced location access.

Adding more details regarding the accuracy of the locations settings is beyond the scope of this plugin. Plugins like the [Geolocator](https://pub.dev/packages/geolocator) or [Location](https://pub.dev/packages/location) can provide detailed information on the set location precision.
