### ISSUE TITLE
No permission READ_PHONE_STATE about Android

### ISSUE THREAD

**Issue by wenchang1989** [Baseflow/flutter-permission-handler#708]
### Platforms affected (mark all that apply)
- [ ] :robot: Android

**Comment by wenchang1989** [comment]
I need handle phone information, like imei,so i need this permission READ_PHONE_STATE

**Comment by mvanbeusekom** [comment]
Sorry but why three times the same? Also I am missing information regarding the permission on the Android website on how to best implement this.

**Comment by daraul** [comment]
For me the device_information plugin tells me to [request READ_PHONE_STATE at runtime(https://pub.dev/documentation/device_information/latest/). I tried to do that with flutter-permission-handler, but couldn't find a way to do it.

**Comment by bluemix** [comment]
I hope there are updates to this issue

**Comment by biloo-dev** [comment]
any updates for this issue please  !!

**Comment by darixsamani** [comment]
any updates for this issue please !!

**Comment by TimHoogstrate** [comment]
Dear @wenchang1989,

It seems that you can just add: <uses-permission android:name="android.permission.READ_PHONE_STATE"/> to the manifest. Please confirm if this solves your issue. For now I'll close this issue. Feel free to reopen when new information pops-up.

Kind regards,
