### ISSUE TITLE
microphone can not be granted in ios platform

### ISSUE THREAD

**Issue by guqun** [Baseflow/flutter-permission-handler#713]
## 🐛 Bug Report

microphone can not be granted in ios platform.

code:

  Future<void> requestMicPermission() async{
    print("requestMicPermission======1");
    var status = await Permission.microphone.status;
    if (status == PermissionStatus.granted) {
      print("requestMicPermission======2");

      return;
    } else {
      print("requestMicPermission======3");

      status = await Permission.microphone.request();
      if (status == PermissionStatus.granted) {
        print("requestMicPermission======4");

        return ;
      } else {
        print("requestMicPermission======5");
        openAppSettings();
        return ;
      }
    }
  }

### Configuration

**Version:** 8.2.5 

**Platform:** 
iphone: iOS

**Comment by mehroze-zaidi** [comment]
need one more "end"
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      # You can remove unused permissions here
      # for more infomation: https://github.com/BaseflowIT/flutter-permission-handler/blob/master/permission_handler/ios/Classes/PermissionHandlerEnums.h
      # e.g. when you don't need camera permission, just add 'PERMISSION_CAMERA=0'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',

        ## dart: PermissionGroup.microphone
        'PERMISSION_MICROPHONE=1',
        
        # Possibly have other permissions listed here...
      ]
           end
    end
  end
