### ISSUE TITLE
android编译出错

### ISSUE THREAD

**Issue by lmx01** [Baseflow/flutter-permission-handler#722]
你好，最新Flutter编译android时，出现如下错误，麻烦帮忙看下，谢谢：
## 🐛 Bug Report

/Users/linmx/.pub-cache/hosted/pub.dartlang.org/permission_handler-8.2.6/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java:321: 错误: 找不到符号
            if (Build.VERSION.SDK_INT < Build.VERSION_CODES.S) {
                                                           ^
  符号:   变量 S
  位置: 类 VERSION_CODES
/Users/linmx/.pub-cache/hosted/pub.dartlang.org/permission_handler-8.2.6/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java:72: 错误: 找不到符号
            case Manifest.permission.BLUETOOTH_SCAN:
                                    ^
  符号:   变量 BLUETOOTH_SCAN
  位置: 类 permission
/Users/linmx/.pub-cache/hosted/pub.dartlang.org/permission_handler-8.2.6/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java:74: 错误: 找不到符号
            case Manifest.permission.BLUETOOTH_ADVERTISE:
                                    ^
  符号:   变量 BLUETOOTH_ADVERTISE
  位置: 类 permission
/Users/linmx/.pub-cache/hosted/pub.dartlang.org/permission_handler-8.2.6/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java:76: 错误: 找不到符号
            case Manifest.permission.BLUETOOTH_CONNECT:
                                    ^
  符号:   变量 BLUETOOTH_CONNECT
  位置: 类 permission
/Users/linmx/.pub-cache/hosted/pub.dartlang.org/permission_handler-8.2.6/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java:259: 错误: 找不到符号
                String result = determineBluetoothPermission(context, Manifest.permission.BLUETOOTH_SCAN);
                                                                                         ^
  符号:   变量 BLUETOOTH_SCAN
  位置: 类 permission
/Users/linmx/.pub-cache/hosted/pub.dartlang.org/permission_handler-8.2.6/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java:270: 错误: 找不到符号
                String result = determineBluetoothPermission(context, Manifest.permission.BLUETOOTH_ADVERTISE);
                                                                                         ^
  符号:   变量 BLUETOOTH_ADVERTISE
  位置: 类 permission
/Users/linmx/.pub-cache/hosted/pub.dartlang.org/permission_handler-8.2.6/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java:281: 错误: 找不到符号
                String result = determineBluetoothPermission(context, Manifest.permission.BLUETOOTH_CONNECT);
                                                                                         ^
  符号:   变量 BLUETOOTH_CONNECT
  位置: 类 permission
/Users/linmx/.pub-cache/hosted/pub.dartlang.org/permission_handler-8.2.6/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java:370: 错误: 找不到符号
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S && hasPermissionInManifest(context, null, permission )) {
                                                        ^
  符号:   变量 S
  位置: 类 VERSION_CODES
8 个错误

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':permission_handler:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
### Configuration

**Version:** 8.2.6

**Platform:** 
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
Version 8.2.0 depends on Android API 31 (Android 12). This means you will have to update the `compileSdkVersion` in your `android/app/build.gradle` file and set it to `31`. Example configuration can be found in our [example App](https://github.com/Baseflow/flutter-permission-handler/blob/56e58fa2c55df330d82cba7c07037b1288a4e779/permission_handler/example/android/app/build.gradle#L28).

This is also documented in the [CHANGELOG.md](https://pub.dev/packages/permission_handler/changelog#820) and the [README.md](https://pub.dev/packages/permission_handler). There are also several closed issues that mention the same problem (e.g. #717, #712, #698, #697, #696).

**Comment by lmx01** [comment]
ok,thanks.sorry not read that documented.
