### ISSUE TITLE
Cannot build android target

### ISSUE THREAD

**Issue by artnavsegda** [Baseflow/flutter-permission-handler#724]
## 🔙 Regression

Cannot build android target

### Current behavior

/opt/homebrew/Caskroom/flutter/2.5.2/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-8.2.6/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java:321: error: cannot find symbol
            if (Build.VERSION.SDK_INT < Build.VERSION_CODES.S) {
                                                           ^
  symbol:   variable S
  location: class VERSION_CODES
/opt/homebrew/Caskroom/flutter/2.5.2/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-8.2.6/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java:72: error: cannot find symbol
            case Manifest.permission.BLUETOOTH_SCAN:
                                    ^
  symbol:   variable BLUETOOTH_SCAN
  location: class permission
/opt/homebrew/Caskroom/flutter/2.5.2/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-8.2.6/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java:74: error: cannot find symbol
            case Manifest.permission.BLUETOOTH_ADVERTISE:
                                    ^
  symbol:   variable BLUETOOTH_ADVERTISE
  location: class permission
/opt/homebrew/Caskroom/flutter/2.5.2/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-8.2.6/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java:76: error: cannot find symbol
            case Manifest.permission.BLUETOOTH_CONNECT:
                                    ^
  symbol:   variable BLUETOOTH_CONNECT
  location: class permission
/opt/homebrew/Caskroom/flutter/2.5.2/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-8.2.6/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java:259: error: cannot find symbol
                String result = determineBluetoothPermission(context, Manifest.permission.BLUETOOTH_SCAN);
                                                                                         ^
  symbol:   variable BLUETOOTH_SCAN
  location: class permission
/opt/homebrew/Caskroom/flutter/2.5.2/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-8.2.6/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java:270: error: cannot find symbol
                String result = determineBluetoothPermission(context, Manifest.permission.BLUETOOTH_ADVERTISE);
                                                                                         ^
  symbol:   variable BLUETOOTH_ADVERTISE
  location: class permission
/opt/homebrew/Caskroom/flutter/2.5.2/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-8.2.6/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java:281: error: cannot find symbol
                String result = determineBluetoothPermission(context, Manifest.permission.BLUETOOTH_CONNECT);
                                                                                         ^
  symbol:   variable BLUETOOTH_CONNECT
  location: class permission
/opt/homebrew/Caskroom/flutter/2.5.2/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-8.2.6/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java:370: error: cannot find symbol
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S && hasPermissionInManifest(context, null, permission )) {
                                                        ^
  symbol:   variable S
  location: class VERSION_CODES
8 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':permission_handler:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 29s
Running Gradle task 'assembleDebug'...                             30.9s
Exception: Gradle task assembleDebug failed with exit code 1

### Configuration

flutter doctor -v
[✓] Flutter (Channel stable, 2.5.2, on macOS 12.0.1 21A559 darwin-arm, locale en-RU)
    • Flutter version 2.5.2 at /opt/homebrew/Caskroom/flutter/2.5.2/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (5 weeks ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/artnavsegda/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/artnavsegda/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 95.0.4638.69
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [ x ] :robot: Android

**Comment by ionnux** [comment]
Did you follow the android specific instructions on the pub page. Here is a summary of the instructions:
1. Add the following to your "gradle.properties" file if it's not already there:
    android.useAndroidX=true
     android.enableJetifier=true
2. Make sure you set the compileSdkVersion in your "android/app/build.gradle" file to 31:

These should resolve your problem.

**Comment by mvanbeusekom** [comment]
Version 8.2.0 depends on Android API 31 (Android 12). This means you will have to update the `compileSdkVersion` in your `android/app/build.gradle` file and set it to `31`. Example configuration can be found in our [example App](https://github.com/Baseflow/flutter-permission-handler/blob/56e58fa2c55df330d82cba7c07037b1288a4e779/permission_handler/example/android/app/build.gradle#L28).

This is also documented in the [CHANGELOG.md](https://pub.dev/packages/permission_handler/changelog#820) and the [README.md](https://pub.dev/packages/permission_handler). There are also several closed issues that mention the same problem (e.g. #717, #712, #698, #697, #696).

**Comment by ga-bri-el** [comment]
To anyone still having trouble with this:

I was working on a project that was created a while ago. Even after bumping `compileSdkVersion` and `targetSdkVerison` to 31, I was getting a lot of errors. What you need to do is also bump the Android Gradle plugin version.

Open `android/build.gradle`

In dependencies, insert the following line:
`classpath 'com.android.tools.build:gradle:4.1.0'`

Now open `android/gradle/wrapper/gradle-wrapper.properties`

Modify the `distributionUrl` variable to:
`distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-all.zip`

Any following errors resulting from this will require you to bump the version of the offending libraries.
Took me a while to figure this one out... hope it helps.

**Comment by hhstore** [comment]
This unsafe change, shouldn't it be upgraded to the first-version-number?  
 

```ruby

permission_handler: ^8.x  => 9.x


```


This will cause many people's projects won't compile properly.
