### ISSUE TITLE
bug in running

### ISSUE THREAD

**Issue by HosseinAsadi** [Baseflow/flutter-permission-handler#725]
/usr/local/Caskroom/flutter/2.5.0/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-8.2.6/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java:321: error: cannot find symbol
            if (Build.VERSION.SDK_INT < Build.VERSION_CODES.S)
            
:(
            
**Version:*8.2.6

**Comment by mvanbeusekom** [comment]
Ain't no bug. See issues #717, #698, #697, #696 and read the CHANGELOG and README.

**Comment by HosseinAsadi** [comment]
> Ain't no bug. See issues #717, #698, #697, #696 and read the CHANGELOG and README.

thanks
