### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by AhmadFalahian** [Baseflow/flutter-permission-handler#726]
Hi
I am facing the following error in the implementation of the project that used this package. Thank you for your help.

![image](https://user-images.githubusercontent.com/87113603/140816279-0bc7aa0a-0c5b-4fc8-9322-3f471af9993b.png)

**Comment by perepechin** [comment]
I had the same issue with the latest version 8.2.6, and then I found here https://pub.dev/packages/permission_handler/changelog
that compileSdkVersion must be set to 31. you need to make this change in this file: 
android\app\build.gradle

**Comment by mvanbeusekom** [comment]
@AhmadFalahian, this seems like an issue related to a Gradle version mismatch between your App and the permission_handler. I have just published version 8.3.0 which updates the permission_handler to use version 4.1.0 of the Android Gradle Plugin. For more information see also issue #731 or PR #732.

P.S. although @perepechin remark is not related to this particular issue, it is still good to make sure you have set your `compileSdkVersion` in the `android/app/build.gradle` file to `31`.

Let me know if this helps. If not could you provide the following information which would make it easier for us to help you:

- Version of the plugin you are using;
- Output of the `flutter doctor -v` command;
- Contents of your `android/build.gradle` file;
- Contents of your `android/app/build.gradle` file (note the additional `app` sub-folder).
