### ISSUE TITLE
How can I get the status that the authorization pop-up box has not popped up for the first time

### ISSUE THREAD

**Issue by paintingStyle** [Baseflow/flutter-permission-handler#727]
## 🐛 Bug Report

```

1，No pop-up authorization for the first time
2，User denied permission

In both cases, the returned value is，**PermissionStatus.denied**


 static Future<int> getRecordPermission() async {
    PermissionStatus status = await Permission.microphone.status;
    Log.d('getRecordPermission = $status');
    switch (status) {
      case PermissionStatus.denied: 
        Permission.microphone.request();
        return -1;
      case PermissionStatus.granted: 
        return 1;
      default:
        return 0;
    }
```

### Expected behavior

I want to get the status that users have never authorized on Apple devices

or

The two statuses return different values

### Configuration

**Version:**  8.0.1

**Platform:** 
- [ ] :iphone: iOS。 15.1 
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
@paintingStyle on iOS the status `PermissionStatus.denied` means the pop-up was not shown before. If the pop-up was shown and the end user selected "Deny" the result would be `PermissionStatus.permanentlyDenied` on iOS.

We have chosen this approach to keep the flow between Android and iOS as close as possible. The general idea is:

- If the permission status is `PermissionStatus.denied` you should try to request permission;
- If the permission status is `PermissionsStatus.permanentlyDenied` you cannot request permission and you should redirect the end user to the App settings and instruct him/her to manually grant permission.

Hope this answers your question.
