### ISSUE TITLE
Permission Status always granted when user ontap Dont Allow on iOS

### ISSUE THREAD

**Issue by bwrelawan** [Baseflow/flutter-permission-handler#729]
Hello :D i found a bug on iOS, when user get poup and choose *Dont Allow*, The permission status always return PermissionStatus.granted, so user cant load gallery but doesnt show poup anymore. Please help this one thankyou.

Iphone 11 : iOS 14.7

**Comment by mvanbeusekom** [comment]
Hello @bwrelawan, 

Could you provide some more information please?

1. Which version of the permission_handler plugin are you using?
2. Which permissions are you requesting when this behaviour shows up?
3. Could you include the output of the `flutter doctor -v` command?
4. Please include the contents of your `ios/Podfile` file?

Without this information we are unfortunately not able to help you.
