### ISSUE TITLE
[iOS 11.4, 15.1] locationAlways.request() not returning when "When in use"(11.4) "Allow only once"(15.1) selected

### ISSUE THREAD

**Issue by flodaniel** [Baseflow/flutter-permission-handler#733]
## 🐛 Bug Report
When requesting location permission with the following two lines, the code execution just stops and the request variable is not is never populated, nor is the return statement ever called. 
For iOS 11.4: This only happens when the user selects "When in use". When selecting "Always allow", this works fine.
For iOS 15.1: This only happens when the user selects "Allow only once". When selecting "When in use", this works fine. 
So it seems that always when the user selects the not-requested option, the method does not finish its execution.
 
```
var request = await Permission.locationAlways.request();
return Tuple2(request.isGranted, false); 
```

### Expected behaviour
The call `await Permission.locationAlways.request()` should always return a value.

### Reproduction steps
Use the code above to request the always-on permission and select either "When in Use" on iOS 11.4 or "Allow only once" on iOS 15.1 when asked by iOS. Set a breakpoint right after the call.
### Configuration

**Version:** 8.2.6
**Flutter:** 2.5
**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by RohithKilaparthi** [comment]
Any update on this? I am getting this exception:

```
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: PlatformException(ERROR_ALREADY_REQUESTING_PERMISSIONS, A request for permissions is already running, please wait for it to finish before doing another request (note that you can request multiple permissions at the same time)., null, null)
```

**Comment by locskot** [comment]
I got this error 
PlatformException(ERROR_ALREADY_REQUESTING_PERMISSIONS, A request for permissions is already running, please wait for it to finish before doing another request (note that you can request multiple permissions at the same time)., null, null)


when I try to get the permission in the beginning 
![image](https://user-images.githubusercontent.com/16982464/145714760-96b19823-ad92-4159-9fb5-26c1290984cb.png)
