### ISSUE TITLE
cannot find symbol case Manifest.permission.BLUETOOTH_CONNECT:

### ISSUE THREAD

**Issue by Julien0253** [Baseflow/flutter-permission-handler#736]
### Configuration

**Version:** 8.3.0

/Users/infinity/.pub-cache/hosted/pub.dartlang.org/permission_handler-8.3.0/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java:76: error: cannot find symbol
            case Manifest.permission.BLUETOOTH_CONNECT:
                                    ^
  symbol:   variable BLUETOOTH_CONNECT
  location: class permission

**Comment by mvanbeusekom** [comment]
Please carefully read the Android section in the README.md (specifically the part about `compileSdkVersion 31`) or search the closed issues for more information.
