### ISSUE TITLE
[iOS 14.5] Location requests don't work

### ISSUE THREAD

**Issue by blkfry** [Baseflow/flutter-permission-handler#739]
## 🐛 Bug Report

I can't seem to make location requests work on iOS, either once, in use or always. The rationale dialog never shows so I can allow or deny the permission.
I even tried running the example project. It always returns permission permanently denied.

SImulator or real iPhone6 it doesn't work.

### Expected behavior

Permission.location.request() should show the rationale dialog.

### Reproduction steps

Run the example project in the repository and try to access location permission.

### Configuration

Flutter 2.5.3
iOS 14.5

**Version:** 8.3.0

**Platform:** 
- [14.5 ] :iphone: iOS

**Comment by mvanbeusekom** [comment]
@blkfry have you added the required configuration to your `ios/Podfile` file? See the iOS section of the [README.md](https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler/README.md) for more details.

**Comment by Grandpasoul** [comment]
same issue, I removed the # at the `'PERMISSION_LOCATION=1',` line, flutter clean, fluter pub get, pod install, and nothing happens.

this is my code:

```
var status = await Permission.location.status;
debugPrint("ret: $status");

if(status.isGranted){
  navigateTo(true);
} else {
  debugPrint("popup location");
  Permission.location.request();
}
```

the prints return: 

```
flutter: status: PermissionStatus.permanentlyDenied
flutter: popup location
```

**Comment by blkfry** [comment]
Hey, sorry for the late response, indeed it was from the Podfile config. Thanks for you help.

**Comment by mvanbeusekom** [comment]
@Grandpasoul which version of the permission_handler plugin are you using? Can you provide some more information? 

Useful information would be: 
1. Contents of your `ios/Podfile` file;
2. Contents of your `ios/Runner/Info.plist` file;
3. Output of the `flutter doctor -v` command.

**Comment by Grandpasoul** [comment]
Thanks for the quick response.

It was a Privacy Settings issue, Location service was disable on the device. If this helps someone, make sure to validate the Location Privacy Setting is on, if not, the `.request()` always returns permanentDenied and shows no prompt.

Close this issue if you want.
