### ISSUE TITLE
Calendar permission dialog is not showing up on iOS

### ISSUE THREAD

**Issue by mauriceraguseinit** [Baseflow/flutter-permission-handler#743]
## 🐛 Bug Report

Calendar permission dialog is not showing up.

### Expected behavior
after installing the App on iOS device and run 
`final permissionStatus = await Permission.calendar.request();` 
the nativ permission dialog should be shown. But it always gets an status "permanentlyDenied".

### Reproduction steps
run `final permissionStatus = await Permission.calendar.request();` 

### Configuration

**Version:** 8.3.0
(in 6.0.0 it works fine with same app implementation)

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
Probably you need to update the configuration in your `ios/Podfile`.

In version 8.0.0 we flipped the behavior of having all permissions enabled by default to disable all permissions by default. Which means you have to enable the permissions explicitly in the `ios/Podfile`. The "iOS" section in the [README.md](https://github.com/Baseflow/flutter-permission-handler/blob/634b29bf03faf4431fd4bf535eb03eb0d10a6c53/README.md) file contains a more detailed description. You can also have a look at the [CHANGELOG.md](https://pub.dev/packages/permission_handler/changelog#800) file at version 8.0.0 for information about the changes.
