### ISSUE TITLE
iOS - Permission granted when each single option is disabled

### ISSUE THREAD

**Issue by stefanschaller** [Baseflow/flutter-permission-handler#745]
## 🐛 Bug Report

I just recognized that iOS shows "notifications off" in the settings of the app, when each single option is disabled, BUT the actual toggle "Enable push notification" is enabled. 
Check images below. 

### Expected behavior

Permissions NOT granted since no push notifications receive.

### Reproduction steps

1. disable each single option of push notifications, except the actual "enable push notifications"
2. call:  await Permission.notification.status;

### Configuration

**Version:** 

flutter --version

Flutter 2.2.1 • channel unknown • unknown source
Framework • revision 02c026b03c (vor 6 Monaten) • 2021-05-27 12:24:44 -0700
Engine • revision 0fdb562ac8
Tools • Dart 2.13.1

Package:
permission_handler: ^8.1.6

**Platform:** 
- [x] :iphone: iOS 15

![IMG_4353](https://user-images.githubusercontent.com/30521865/144272248-7ea37669-2305-4f27-9a79-1abe619c604f.PNG)
![IMG_4352](https://user-images.githubusercontent.com/30521865/144272255-b1cff733-3117-4ffc-85ff-1ede5c1de903.PNG)

**Comment by JulianBissekkou** [comment]
I am also interested in this fix :D

**Comment by cdignas** [comment]
hope for a quick solution :)

**Comment by cthiele-mogic** [comment]
Me too, i also need a fix for that

**Comment by JulianBissekkou** [comment]
@martijn00 Can you tell if you have time to fix this? We need to know if and when a fix might happen.

**Comment by maxim-ivanchuk-idf** [comment]
@martijn00 reproduced for me too
