### ISSUE TITLE
prevent launch the app  "error: cannot find symbol"

### ISSUE THREAD

**Issue by MohaDevPro** [Baseflow/flutter-permission-handler#748]
## 🐛 Bug Report

When I run the app from android studio doesn't run and this error comes in the logs
`
Launching lib\main.dart on Redmi Note 8 Pro in debug mode...
Running Gradle task 'assembleDebug'...
D:\Programs\flutter\flutter_windows_2.5.2-stable\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-8.3.0\android\src\main\java\com\baseflow\permissionhandler\PermissionManager.java:321: error: cannot find symbol
            if (Build.VERSION.SDK_INT < Build.VERSION_CODES.S) {
                                                           ^
  symbol:   variable S
  location: class VERSION_CODES
D:\Programs\flutter\flutter_windows_2.5.2-stable\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-8.3.0\android\src\main\java\com\baseflow\permissionhandler\PermissionUtils.java:72: error: cannot find symbol
            case Manifest.permission.BLUETOOTH_SCAN:
                                    ^
  symbol:   variable BLUETOOTH_SCAN
  location: class permission
D:\Programs\flutter\flutter_windows_2.5.2-stable\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-8.3.0\android\src\main\java\com\baseflow\permissionhandler\PermissionUtils.java:74: error: cannot find symbol
            case Manifest.permission.BLUETOOTH_ADVERTISE:
                                    ^
  symbol:   variable BLUETOOTH_ADVERTISE
  location: class permission
D:\Programs\flutter\flutter_windows_2.5.2-stable\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-8.3.0\android\src\main\java\com\baseflow\permissionhandler\PermissionUtils.java:76: error: cannot find symbol
            case Manifest.permission.BLUETOOTH_CONNECT:
                                    ^
  symbol:   variable BLUETOOTH_CONNECT
  location: class permission
D:\Programs\flutter\flutter_windows_2.5.2-stable\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-8.3.0\android\src\main\java\com\baseflow\permissionhandler\PermissionUtils.java:259: error: cannot find symbol
                String result = determineBluetoothPermission(context, Manifest.permission.BLUETOOTH_SCAN);
                                                                                         ^
  symbol:   variable BLUETOOTH_SCAN
  location: class permission
D:\Programs\flutter\flutter_windows_2.5.2-stable\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-8.3.0\android\src\main\java\com\baseflow\permissionhandler\PermissionUtils.java:270: error: cannot find symbol
                String result = determineBluetoothPermission(context, Manifest.permission.BLUETOOTH_ADVERTISE);
                                                                                         ^
  symbol:   variable BLUETOOTH_ADVERTISE
  location: class permission
D:\Programs\flutter\flutter_windows_2.5.2-stable\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-8.3.0\android\src\main\java\com\baseflow\permissionhandler\PermissionUtils.java:281: error: cannot find symbol
                String result = determineBluetoothPermission(context, Manifest.permission.BLUETOOTH_CONNECT);
                                                                                         ^
  symbol:   variable BLUETOOTH_CONNECT
  location: class permission
D:\Programs\flutter\flutter_windows_2.5.2-stable\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-8.3.0\android\src\main\java\com\baseflow\permissionhandler\PermissionUtils.java:370: error: cannot find symbol
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S && hasPermissionInManifest(context, null, permission )) {
                                                        ^
  symbol:   variable S
  location: class VERSION_CODES
8 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':permission_handler:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 30s
Exception: Gradle task assembleDebug failed with exit code 1
`
### Expected behavior
Complete run, install the app and launch it in the phone.

### Reproduction steps
pub get these dependencies and just run it
### Configuration
dependencies in the pubspec.yaml

`environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  floor: ^1.2.0
  excel: 2.0.0-null-safety-3
  get: ^4.5.1
  shared_preferences: ^2.0.9
  share: ^2.0.4
  path_provider: any
  pdf: any
  printing: ^5.6.3
  file_picker: ^4.2.7
  intl:
  permission_handler: 8.2.4
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  xml: ^5.3.1
  meta: ^1.7.0
  convert: ^3.0.1
#  build: 1.6.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^1.2.0
  build_runner: ^2.1.5
`

`flutter doctor -v
[√] Flutter (Channel stable, 2.5.2, on Microsoft Windows [Version 10.0.18362.959], locale en-US)
    • Flutter version 2.5.2 at D:\Programs\flutter\flutter_windows_2.5.2-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (9 weeks ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\ASUS\sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\ASUS\sdk
    • ANDROID_SDK_ROOT = C:\Users\ASUS\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.2.2
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.8052

[√] VS Code (version 1.61.1)
    • VS Code at C:\Users\ASUS\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.25.0

[√] Connected device (3 available)
    • Redmi Note 8 Pro (mobile) • ey5hknxomfeelr9x • android-arm64  • Android 10 (API 29)
    • Chrome (web)              • chrome           • web-javascript • Google Chrome 96.0.4664.45
    • Edge (web)                • edge             • web-javascript • Microsoft Edge 96.0.1054.41

• No issues found!`
**Version:** 8.3.0

**Platform:** 
- [ ] :iphone: iOS
- [* ] :robot: Android

**Comment by huangyanxiong01** [comment]
same to you

**Comment by mvanbeusekom** [comment]
@MohaDevPro, @huangyanxiong01, version 8.2.0 depends on Android API 31 (Android 12). This means you will have to update the `compileSdkVersion` in your `android/app/build.gradle` file and set it to `31`. Example configuration can be found in our [example App](https://github.com/Baseflow/flutter-permission-handler/blob/56e58fa2c55df330d82cba7c07037b1288a4e779/permission_handler/example/android/app/build.gradle#L28).

This is also documented in the [CHANGELOG.md](https://pub.dev/packages/permission_handler/changelog#820) and the [README.md](https://pub.dev/packages/permission_handler). There are also several closed issues that mention the same problem (e.g. #735, #712, #698, #697, #696).

**Comment by huangyanxiong01** [comment]
Thank you. I resolved this
