### ISSUE TITLE
D/permissions_handler(28001): No permissions found in manifest for: []22

### ISSUE THREAD

**Issue by walikhan226** [Baseflow/flutter-permission-handler#754]

**Comment by mvanbeusekom** [comment]
Unfortunately you supplied us very little information. The only thing I can advice is to go through the Android section of the [README.md](https://github.com/Baseflow/flutter-permission-handler/blob/634b29bf03faf4431fd4bf535eb03eb0d10a6c53/permission_handler/README.md) and make sure you add all required permissions to your AndroidManifest.xml file as described.
