### ISSUE TITLE
what if i want to use SDK version 30

### ISSUE THREAD

**Issue by TetrixGauss** [Baseflow/flutter-permission-handler#755]
## 💬 Questions and Help

Hello there!!! What version of the package should i use if i want to target SDK version 30 in order not to have the bluetooth building errors ? 

Thank you!

**Comment by mvanbeusekom** [comment]
Hi @TetrixGauss,

In order to be able to use SDK 30 you should pin the permission_handler to version [8.1.6](https://pub.dev/packages/permission_handler/changelog#816).

```yaml
  permission_handler: 8.1.6
```
