### ISSUE TITLE
Android 11 REQUEST_INSTALL_PACKAGES crashed

### ISSUE THREAD

**Issue by azhansy** [Baseflow/flutter-permission-handler#759]
## 🐛 Bug Report
Use the current simple, apply for installation permission, jump to the authorization page, switch back and forth to agree and reject, the app flashes back
------------------------
12-18 11:12:16.294  3917  3917 I AdrenoGLES-0: PFP: 0x016ee190, ME: 0x00000000
12-18 11:12:16.321  3917  3917 W handler.exampl: Accessing hidden method Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J (unsupported,test-api, reflection, allowed)
12-18 11:12:16.321  3917  3917 W handler.exampl: Accessing hidden method Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J (unsupported, reflection, allowed)
12-18 11:12:16.321  3917  3917 W handler.exampl: Accessing hidden field Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray; (unsupported, reflection, allowed)
12-18 11:12:16.321  3917  3917 W handler.exampl: Accessing hidden method Landroid/util/LongArray;->get(I)J (unsupported, reflection, allowed)
12-18 11:12:16.339  3917  3917 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Activity.getPackageManager()' on a null object reference
12-18 11:12:16.339  3917  3917 W System.err: 	at com.baseflow.permissionhandler.PermissionManager.onActivityResult(PermissionManager.java:78)
12-18 11:12:16.339  3917  3917 W System.err: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:840)
12-18 11:12:16.339  3917  3917 W System.err: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:441)
12-18 11:12:16.339  3917  3917 W System.err: 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:759)
12-18 11:12:16.339  3917  3917 W System.err: 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:680)
12-18 11:12:16.339  3917  3917 W System.err: 	at android.app.Activity.dispatchActivityResult(Activity.java:8382)
12-18 11:12:16.339  3917  3917 W System.err: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5297)
12-18 11:12:16.339  3917  3917 W System.err: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4748)
12-18 11:12:16.339  3917  3917 W System.err: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4794)
12-18 11:12:16.339  3917  3917 W System.err: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
12-18 11:12:16.339  3917  3917 W System.err: 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
12-18 11:12:16.339  3917  3917 W System.err: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
12-18 11:12:16.339  3917  3917 W System.err: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
12-18 11:12:16.339  3917  3917 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2214)
12-18 11:12:16.339  3917  3917 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-18 11:12:16.339  3917  3917 W System.err: 	at android.os.Looper.loopOnce(Looper.java:201)
12-18 11:12:16.339  3917  3917 W System.err: 	at android.os.Looper.loop(Looper.java:288)
12-18 11:12:16.339  3917  3917 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7842)
12-18 11:12:16.339  3917  3917 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
12-18 11:12:16.339  3917  3917 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
12-18 11:12:16.339  3917  3917 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
12-18 11:12:16.340  3917  3917 D AndroidRuntime: Shutting down VM
12-18 11:12:16.341  3917  3917 E AndroidRuntime: FATAL EXCEPTION: main
12-18 11:12:16.341  3917  3917 E AndroidRuntime: Process: com.baseflow.permissionhandler.example, PID: 3917
12-18 11:12:16.341  3917  3917 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {com.baseflow.permissionhandler.example/io.flutter.embedding.android.FlutterActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=212, result=0, data=null} to activity {com.baseflow.permissionhandler.example/io.flutter.embedding.android.FlutterActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.baseflow.permissionhandler.PermissionManager$RequestPermissionsSuccessCallback.onSuccess(java.util.Map)' on a null object reference
12-18 11:12:16.341  3917  3917 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4761)
12-18 11:12:16.341  3917  3917 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4794)
12-18 11:12:16.341  3917  3917 E AndroidRuntime: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
12-18 11:12:16.341  3917  3917 E AndroidRuntime: 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
12-18 11:12:16.341  3917  3917 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
12-18 11:12:16.341  3917  3917 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
12-18 11:12:16.341  3917  3917 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2214)
12-18 11:12:16.341  3917  3917 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-18 11:12:16.341  3917  3917 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
12-18 11:12:16.341  3917  3917 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
12-18 11:12:16.341  3917  3917 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7842)
12-18 11:12:16.341  3917  3917 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-18 11:12:16.341  3917  3917 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
12-18 11:12:16.341  3917  3917 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
12-18 11:12:16.341  3917  3917 E AndroidRuntime: Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=212, result=0, data=null} to activity {com.baseflow.permissionhandler.example/io.flutter.embedding.android.FlutterActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.baseflow.permissionhandler.PermissionManager$RequestPermissionsSuccessCallback.onSuccess(java.util.Map)' on a null object reference
12-18 11:12:16.341  3917  3917 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5304)
12-18 11:12:16.341  3917  3917 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4748)
12-18 11:12:16.341  3917  3917 E AndroidRuntime: 	... 13 more
12-18 11:12:16.341  3917  3917 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.baseflow.permissionhandler.PermissionManager$RequestPermissionsSuccessCallback.onSuccess(java.util.Map)' on a null object reference
12-18 11:12:16.341  3917  3917 E AndroidRuntime: 	at com.baseflow.permissionhandler.PermissionManager.onActivityResult(PermissionManager.java:104)
12-18 11:12:16.341  3917  3917 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:840)
12-18 11:12:16.341  3917  3917 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:441)
12-18 11:12:16.341  3917  3917 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:759)
12-18 11:12:16.341  3917  3917 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:680)
12-18 11:12:16.341  3917  3917 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:8382)
12-18 11:12:16.341  3917  3917 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5297)
12-18 11:12:16.341  3917  3917 E AndroidRuntime: 	... 14 more
12-18 11:12:16.344  1707  3963 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
12-18 11:12:16.344  1707  8242 W ActivityTaskManager:   Force finishing activity com.baseflow.permissionhandler.example/io.flutter.embedding.android.FlutterActivity
12-18 11:12:16.350  1707  1803 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
12-18 11:12:16.350  1707  1803 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
12-18 11:12:16.397  3917  3962 I flutter : Observatory listening on http://127.0.0.1:37625/jCArV7U_-YE=/
12-18 11:12:16.845  1707  1784 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{ad615d5 u0 com.baseflow.permissionhandler.example/io.flutter.embedding.android.FlutterActivity t351 f}}
12-18 11:12:16.846  1707  1784 W ActivityTaskManager: Activity pause timeout for ActivityRecord{ad615d5 u0 com.baseflow.permissionhandler.example/io.flutter.embedding.android.FlutterActivity t351 f}}
12-18 11:12:16.875  1707  9556 W InputManager-JNI: Input channel object '54f403c Splash Screen com.baseflow.permissionhandler.example (client)' was disposed without first being removed with the input manager!
12-18 11:12:16.902 15254 15254 I GsaVoiceInteractionSrv: Handling ACTION_START_HOTWORD
12-18 11:12:16.903 15254 15335 I GsaVoiceInteractionSrv: disregardVoiceMatch: false
12-18 11:12:16.903 15254 15335 I GsaVoiceInteractionSrv: Cannot start hotword, hotword has been explicitly disabled.
12-18 11:12:16.904 18227 18615 I OpenGLRenderer: Davey! duration=9222515255289ms; Flags=1, FrameTimelineVsyncId=10096665, IntendedVsync=856781564833974, Vsync=856781564833974, InputEventId=1543025491, HandleInputStart=856781566840140, AnimationStart=856781566841390, PerformTraversalsStart=856781566841963, DrawStart=856781578593734, FrameDeadline=856781598167306, FrameInterval=856781566837276, FrameStartTime=16666666, SyncQueued=856781579308578, SyncStart=856781579414046, IssueDrawCommandsStart=856781579592276, SwapBuffers=856781584560974, FrameCompleted=9223372036854775807, DequeueBufferDuration=3744062, QueueBufferDuration=592552, GpuCompleted=9223372036854775807, SwapBuffersCompleted=856781585556130, DisplayPresentTime=18076,
12-18 11:12:16.916  1707  1784 I ActivityManager: Killing 2532:com.google.android.partnersetup/u0a113 (adj 975): empty #17
12-18 11:12:16.924  2983  2983 W BcSmartspaceCard: No title view to update
12-18 11:12:16.926 18227 18615 I OpenGLRenderer: Davey! duration=13678ms; Flags=0, FrameTimelineVsyncId=10096671, IntendedVsync=856781597978352, Vsync=856781597978352, InputEventId=0, HandleInputStart=856781598789359, AnimationStart=856781598789984, PerformTraversalsStart=856781598790505, DrawStart=856781603161390, FrameDeadline=856781631311684, FrameInterval=856781598787380, FrameStartTime=16666666, SyncQueued=856781603422067, SyncStart=856781603485192, IssueDrawCommandsStart=856781603566703, SwapBuffers=856781604161599, FrameCompleted=856795276759979, DequeueBufferDuration=14063, QueueBufferDuration=1383334, GpuCompleted=856795276759979, SwapBuffersCompleted=856781605733317, DisplayPresentTime=0,
12-18 11:12:16.931  1707  2140 W InputManager-JNI: Input channel object 'aa82f81 com.android.settings/com.android.settings.Settings$ManageAppExternalSourcesActivity (client)' was disposed without first being removed with the input manager!
12-18 11:12:16.931  6326  6326 W BcSmartspaceCard: No title view to update
12-18 11:12:16.932  1707  1805 I libprocessgroup: Successfully killed process cgroup uid 10113 pid 2532 in 13ms
12-18 11:12:16.958   812   812 I Zygote  : Process 2532 exited due to signal 9 (Killed)
12-18 11:12:17.019   903  5001 D DlbDap2Process: process() called [847000] times
12-18 11:12:18.978  1707  2132 D ConnectivityService: NetReassign [no changes]
12-18 11:12:19.123   903  2158 D audio_hw_primary: out_standby: enter: stream (0xf18864c0) usecase(1: low-latency-playback)
12-18 11:12:19.204   903  2158 D audio_hw_primary: stop_output_stream: enter: usecase(1: low-latency-playback)
12-18 11:12:19.204   903  2158 D audio_hw_primary: disable_audio_route: reset and update mixer path: low-latency-playback speaker
12-18 11:12:19.206   903  2158 E soundtrigger: audio_extn_sound_trigger_update_stream_status: invalid input device 0x0, for event 2
12-18 11:12:19.206   903  2158 D soundtrigger: audio_extn_sound_trigger_update_stream_status: uc_info->id 1 of type 0 for Event 2, with Raise=0
12-18 11:12:19.207   903  2158 D msm8974_platform: platform_split_snd_device: snd_device(2) num devices(0) new_snd_devices(0)
12-18 11:12:19.207   903  2158 I msm8974_platform: platform_get_custom_mtmx_params: no matching param with id 0 ip_ch 2 op_ch 2 uc_id 1 snd_dev 2
12-18 11:12:19.207   903  2158 D hardware_info: hw_info_append_hw_type : device_name = speaker
12-18 11:12:19.207   903  2158 D audio_hw_primary: disable_snd_device: snd_device(2: speaker)
12-18 11:12:19.207   903  2158 D msm8974_platform: platform_split_snd_device: snd_device(2) num devices(0) new_snd_devices(0)
12-18 11:12:19.207   903  2158 D hardware_info: hw_info_append_hw_type : device_name = vi-feedback
12-18 11:12:19.207   903  2158 E audio_hw_primary: disable_snd_device: device ref cnt is already 0
12-18 11:12:19.209   903  2158 I soundtrigger: audio_extn_sound_trigger_update_device_status: device 0x2 of type 0 for Event 0, with Raise=0
12-18 11:12:19.209   903  2158 D audio_hw_primary: stop_output_stream: exit: status(0)
12-18 11:12:19.209   903  2158 D audio_hw_primary: out_standby: exit

**Comment by JDDV** [comment]
Hi @azhansy, as annoying as it is, this is the correct behavior. Since Android 11 Google implemented this behavior as a security feature. You can see the issuetracker from Google [here](https://issuetracker.google.com/issues/154157387?pli=1).

I'll close this issue for now since the link provided should give you the answer, but if you still have a question feel free to ask of course!

**Comment by guodong1111** [comment]
It’s a bit different from the killing process on Google.
Now that we are automatically turned on after the killed process, it will crash again

**Comment by JDDV** [comment]
What do you mean with "Now that we are automatically turned on after the killed process"?
Android does try to re-start the app after the process is killed, but for a lot of people this does not work and the app does not restart on it's own. I noticed this also by the standard flutter incremental counter app when you create a new flutter project that it will not start up again after you asked for the permission. Is that what you meant maybe?
