### ISSUE TITLE
v8.1.6 Permission.contacts.request() not popping up permission request screen

### ISSUE THREAD

**Issue by jasonkaruza** [Baseflow/flutter-permission-handler#770]
Flutter Doctor
```
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [Version 10.0.19043.1415], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.63.2)
[√] Connected device (3 available)
```

Package version
`permission_handler: ^8.1.6`

Sample Code
```
status = await Permission.locationWhenInUse.request(); // Shows permission request dialog
status = await Permission.sms.request(); // Shows permission request dialog
status = await Permission.contacts.request(); // DOES NOT show permission request dialog
```

Problem
When calling `await Permission.contacts.request()` the app does not pause to show the permission request dialog for accessing contacts. It moves on to the next line of code with no error thrown. This doesn't occur for location or sms requests (both of those pause the app to display the permission request dialog).

**Comment by hillelcoren** [comment]
This was the problem for us: https://github.com/Baseflow/flutter-permission-handler/issues/568#issuecomment-853681192

**Comment by jasonkaruza** [comment]
Thank you @hillelcoren . Unfortunately, I am compiling for Android only (for now), so the podfile isn't the issue. I have the following in my manifest file, which seems like the right configuration:

```
<!-- Allows reading of contacts on phone to send invites -->
<uses-permission android:name="android.permission.READ_CONTACTS" />
````
