### ISSUE TITLE
App crashes after manually disable a permission

### ISSUE THREAD

**Issue by themmfa** [Baseflow/flutter-permission-handler#771]
## 🐛 Bug Report

I'm trying to test a new app and requesting location permission for it. After requesting and allowing the location permission, when i manually deny the location permission on app settings, app crashes.

### Expected behavior
It should not crash when i manually deny the location permission.

### Reproduction steps
1- Request location permission
2- Allow permission
3- Manually go to app settings and deny the location permission
4- App crashes.

### Configuration

**Version:** ^8.3.0

**Platform:** 
- [ ] :iphone: iOS
- [ x ] :robot: Android

**Comment by schnphil** [comment]
same on iOS but also, if i manually allow permissions in the settings **after** I denied them in the app

**Comment by sonelektrikci** [comment]
> same on iOS but also, if i manually allow permissions in the settings **after** I denied them in the app

I don't know if your problem is same as mine but running code in debug mode crashes the app. If you run it in release mode, everything works as usual.

**Comment by Yukams** [comment]
UP on this issue, I have the same one and it's really problematic

**Comment by TimHoogstrate** [comment]
Dear @themmfa,

It is not crashing in the example app. Do you have the crashlog for me?

Kind regards,
