### ISSUE TITLE
PlatformException while executing Permission.contacts.request()

### ISSUE THREAD

**Issue by aliasgartaksali** [Baseflow/flutter-permission-handler#772]
I am using permission_handler v8.3.0. When I run Permission.contacts.request(), the following exception is thrown and then the app crashes in Android. This occurs when the app is initially run on install:

PlatformException (PlatformException(PermissionHandler.PermissionManager, A request for permissions is already running, please wait for it to finish before doing another request (note that you can request multiple permissions at the same time)., null, null))

My code is as follows:

`@override
  void initState() {
    () async {
      await Provider.of<UserData>(context, listen: false).getProfilePic();
    }();
    _askPermission();
    super.initState();
  }

  Future<void> _askPermission() async {
    if (await Permission.contacts.request().isGranted) {
      final contacts = await ContactsService.getContacts(
          withThumbnails: false, photoHighResolution: false);
      var ctcts = [];
      for (var i = 0; i < contacts.length; i++) {
        for (var j = 0; j < contacts[i].phones!.length; j++) {
          ctcts.add(contacts[i].phones![j].value!.replaceAll(" ", ""));
        }
      }
      print(ctcts.toSet().toList());
    } else {
      print([]);
    }
  }`

**Comment by matthias-steinkamp** [comment]
I got the same issue, when I deny the permission in android settings. Tested with android studio in emulator.

**Comment by aliasgartaksali** [comment]
@matthias-steinkamp I viewed it, but it didn't resolve. What I notice is that the error is only thrown while debugging. Without debugging it works fine.

**Comment by aliasgartaksali** [comment]
@matthias-steinkamp okay. My current workaround in debugging is to start debug, then app crashes and I accept the permission and stop debugging and start it again. It works fine after accepting the permission.
