### ISSUE TITLE
Check Bluetooth is Enable

### ISSUE THREAD

**Issue by themmfa** [Baseflow/flutter-permission-handler#773]
## 💬 Questions and Help

For location, I can check if its enabled or disabled. However, I couldn't see a serviceStatus property for bluetooth. Is there any way to check if bluetooth is enabled or disabled?

**Comment by wujek-srujek** [comment]
Would be nice to get this merged. In the meantime, I import `permission_handler_platform_interface: ^3.11.1` and use `PermissionHandlerPlatform.instance.checkServiceStatus(Permission.bluetooth)`.

**Comment by JeroenWeener** [comment]
Hi @wujek-srujek, thanks for chiming in.

We are aiming to get this in soon.
See #1099, #1100, #1101, #1102 for progress on the feature.

Please note that the changes there exceed the changes in #942, as we found that the iOS implementation does not correctly return the service status. You may therefore find that you get `ServiceStatus.disabled`, regardless of the Bluetooth state, when using #942 in combination with `permission_handler_platform_interface: ^3.11.1` as you described.

**Comment by JeroenWeener** [comment]
This issue is waiting for #1100 to be merged.

**Comment by JeroenWeener** [comment]
Hi everyone!

The feature is now available on the latest version of the plugin. To pull it in, just run `flutter pub upgrade` in your project that has a dependency on either `permission_handler` or `permission_handler_apple`. Check the `pubspec.lock` file to make sure the dependency to `permission_handler_apple` is `9.1.4`. As `permission_handler_apple` is endorsed by `permission_handler`, you do not need to explicitly list it in your `pubspec.yaml` file.
