### ISSUE TITLE
Is there a way to know what the User opted in for Location?

### ISSUE THREAD

**Issue by Basha0** [Baseflow/flutter-permission-handler#774]
## 💬 Questions and Help

Hey, I Just want to know if I can get the Information if the User Opted in for "Allow once" or "While in use".
Both deliver "Granted" but i would like to know what the User used to grant the location Data.

**Comment by mvanbeusekom** [comment]
Hi @Basha0,

Unfortunately Android doesn't provide this information and therefore there is no way to check this in your App. The basic flow is as follows:

1. App requests permission (either `ACCESS_FINE_LOCATION` or `ACCESS_COARSE_LOCATION`);
2. Android shows the permissions dialog to the end-user;
3. The end-user selects one of the options (either "Allow once", "While in use" or "Deny");
4. Android calls the `onRequestPermissionsResult` callback and reports only `granted` (in case user selected "Allow once" or "While in use") or `denied` (in case the user selected "Deny").

There are no other API's available to request more detailed information. More information on the permission handling process on Android can be found here: https://developer.android.com/training/permissions/requesting.

**Comment by Basha0** [comment]
@mvanbeusekom Thanks for the fast answer. I ll closing the issue then.
