### ISSUE TITLE
IOS post Install actions in Podfile cause Firebase To not compile

### ISSUE THREAD

**Issue by ryanheitner** [Baseflow/flutter-permission-handler#776]
If I have a project which includes 
  firebase_core: 1.12.0
and 
  permission_handler: 8.3.0

I cannot add the post install to the podfile without causing firebase to fail with  
ios/Pods/GoogleDataTransport/GoogleDataTransport/GDTCCTLibrary/GDTCCTUploadOperation.m:408:3: error: implicit declaration of function
'pb_release' is invalid in C99 

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
         'PERMISSION_MICROPHONE=1',

**Comment by fartem** [comment]
@ryanheitner, https://stackoverflow.com/a/70912837/10684765

**Comment by JeroenWeener** [comment]
Hi @ryanheitner, thank you for reaching out!

Did the solution linked by @fartem help you resolve your issue?
