### ISSUE TITLE
How to get current location `serviceStatus` when toggling location access via Android system tray menu?

### ISSUE THREAD

**Issue by comatory** [Baseflow/flutter-permission-handler#778]
I'm unsure if this is a bug or my way of implementing it. My issue is that I'm unable to detect when location permission `serviceStatus` has changed or not.

In Flutter I use a widget with `WidgetsBindingObserver` mixin to detect changes to permissions:

```
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.resumed) {
      _setUpdatedStatus();
    }
  }
  
  Future<void> _setUpdatedStatus() async {
    final serviceStatus = await Permission.location.serviceStatus;
    final status = await Permission.location.status;


    setState(() {
      _status = permissionStatusDescriptor.status;
      _serviceStatus = permissionStatusDescriptor.serviceStatus;
    });
  }
```

When app is resumed I get current service status via

However when the app is running and I open system tray and disable the location, the app still reports `ServiceStatus.enabled`. Only when actually putting the app into background and resuming it, does it update correctly to `ServiceStatus.disabled`.

I probably understand that opening/closing system tray is not considered to be pausing and resuming the application but is there some way where I could get updated information. Does the library has some kind of stream that would let me know the `serviceStatus` has changed?

I don't want to use any kind of polling, that seems very ineffective to me.

**Comment by comatory** [comment]
This is the system tray menu item I'm talking about showing it in Android 11 emulator. Turning it off and swiping the menu up does not result in any changes to `serviceStatus`.

![Screenshot 2022-01-31 at 15 00 28](https://user-images.githubusercontent.com/5990424/151807076-2b515bc0-3de7-409a-aa6d-96e0ea3189ed.png)

**Comment by mvanbeusekom** [comment]
Hi @comatory,

The permission_handler doesn't provide this functionality as its core functionality is permission management and permissions work disconnected from the backend services (e.g. it is still possible to check or request permissions when the backend service is not running).

We added a convenience method to check the status of the backend service however it is not our intention to add more support as it deviates too much from what the permission_handler is about. That said however our popular and Flutter Favorite [geolocator](https://pub.dev/packages/geolocator) plugin provides a special stream that when listened to will provide updates of changes in the location service status (both on Android and iOS).

A brief example would look something like this:
```dart
import 'package:geolocator/geolocator.dart';

final LocationSettings locationSettings = LocationSettings(
  accuracy: LocationAccuracy.high,
  distanceFilter: 100,
);
final StreamSubscription<Position> positionStream = Geolocator
  .getPositionStream(locationSettings: locationSettings)
  .listen(
    (Position? position) {
        print(position == null 
          ? 'Unknown' 
          : '${position.latitude.toString()}, ${position.longitude.toString()}');
    });
```

I hope this answers your question, if not please feel free to leave a reply. For now I will close this issue.

**Comment by comatory** [comment]
@mvanbeusekom Hi. Thanks for clearing that up, I did not really notice that `geolocator` exposes that stream, that's good that means there's a solution.

I haven't been doing mobile dev for that long so for me the separation between permission and device capability isn't that clear.

So you are basically treating device capability, like having a sensor for location or that sensor being turned on/off as something that is global, on operating system level, whereas permissions are app specific? Just wanted to know the distinction so I know how to adapt my codebase[^1] better.

Following that logic, this plugin shouldn't really expose `Permission.location.serviceStatus` so is that 

> We added a convenience method to check the status of the backend service however it is not our intention to add more support

what you're referring to? It does makes sense out of convenience like you say.

[^1]: In my codebase I'm using both `permission_handler` and `geolocator`. I have separate module with `permission_handler` that tells me that application is able to receive device location or not. Other module has `geolocator` and provides the location itself. So what you're saying I probably need to use `Geolocator.getServiceStatusStream` to the other part of the codebase.
