### ISSUE TITLE
Background Permission Request

### ISSUE THREAD

**Issue by riccardocescon** [Baseflow/flutter-permission-handler#787]
This package is working perfectly.
I wanted to add a new feature on my app but now i am getting this message (by testing the new feature, the rest of the app is working nicely):
`D/permissions_handler(24213): Unable to detect current Activity.`

Here's what i did:
I added the possibility to have a Widget on the homescreen, i have used home_widget package for this.
When i click on the button from this widget, it runs a callback on flutter. Inside this callback i want to use bluetooth, but as soon as i try i get that error. 
I have already granted all the necessary permissions before using that external widget, so i thought it should automatically grant the access to the Bluetooth, did i so something wrong?
Should this be tagged as a Bug or a Feature request?

**Comment by bhagat-techind** [comment]
@riccardocescon Have you find any solution for this ?

**Comment by bahman2000** [comment]
@riccardocescon  Why you opened this issue and closed without any details?
