### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by azchohfi** [Baseflow/flutter-permission-handler#788]
## 🚀 Feature Requests
Windows applications are now supported by Flutter, and this Plugin have a high usage, so it should support Windows, even if at a stub implementation, since Win32s are not really required to ask for permission for most things.

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [ ] :robot: Android
- [X] 🪟 : Windows

**Comment by azchohfi** [comment]
I'm working on sending a PR to add Windows support.

**Comment by mvanbeusekom** [comment]
Version 9.2.0 of the permission_handler endorsing the permission_handler_windows packages has been released. I will close this issue now, thank you for your excellent contributions.
