### ISSUE TITLE
Build failed due to use of deprecated Android v1 embedding.

### ISSUE THREAD

**Issue by azchohfi** [Baseflow/flutter-permission-handler#790]
## 🐛 Bug Report
Builds are failing using latest Flutter on stable since the Android project is using the deprecated Android v1 embedding.

### Expected behavior
Build works fine on Master branch of Flutter.

### Reproduction steps
CI is failing.

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi @azchohfi, thanks for fixing this issue. PR #791 has been released as part of version 9.0.1 of the permission_handler plugin. 

I will close this issue, let me know if there are any other issues.
