### ISSUE TITLE
Cannot dismiss permission dialog on Android R (10)

### ISSUE THREAD

**Issue by 1encore** [Baseflow/flutter-permission-handler#796]
### Expected behavior
It should be possible to dismiss the permission dialog with back button or by clicking outside of the dialog

### Reproduction steps
1) launch any app with permission_handler
2) request any permission which shows a dialog (allow/deny)
3) press back button or outside of the dialog

### Configuration
flutter 2.5.3
dart 2.14

**Version:** 9.0.2

**Platform:** 
- [ ] :iphone: iOS
- [x ] :robot: Android 10

**Comment by DJafari** [comment]
this is android behavior not related to this plugin

**Comment by JeroenWeener** [comment]
Hi @1encore, thank you for opening this issue!

As @DJafari mentions, this behavior is not related to the plugin, as we hand over the control flow to the OS the moment we request the permission. I.e. the plugin is not the one showing the dialog, Android is.

Nonetheless, I just tested this behavior with the newest version (10.4.1) of the `permission_handler` example application on an Android emulator running API 33 (Android 13). Behavior there is as expected. Dialogs can be closed by pressing the back button, or by tapping outside of the dialog.

It might be that certain versions of Android behave differently, showcasing the behavior you mentioned. In that case, it is an OS issue and not related to the plugin. I am therefore closing this issue.

**Comment by JeroenWeener** [comment]
Thanks for chiming in @mvanbeusekom. Reopening this issue so we can investigate.

**Comment by JeroenWeener** [comment]
This should no longer be an issue. Dialogs that are dismissed also return a result. We made sure the returned results are correct in PR #1125 and #1130.
