### ISSUE TITLE
iOS Permission.*.request() Bug

### ISSUE THREAD

**Issue by anchao-lu** [Baseflow/flutter-permission-handler#798]
When calling `await Permission.*.request()` the app does not pause to show the permission request dialog.
`*` means all permissions

include v8.3.0 and v9.2.0

v7.2.0 is ok on iOS, but android can not compile

v8.3.0 and v9.2.0 needs add any new config?

**Comment by mvanbeusekom** [comment]
Hello @anchao-lu, 

I am assuming you upgraded from 7.2.0 to 8.3.0 (and higher) and the issues are regarding iOS. If so please make sure you updated the configuration in your `ios/Podfile`. See the iOS section of the [README.md](https://pub.dev/packages/permission_handler) and [CHANGELOG](https://pub.dev/packages/permission_handler/changelog#800)). 

Starting from version 8.0.0 the configuration of enabling iOS support for permissions has flipped from enabled by default to disabled by default.

The most likely reason version 7.2.0 (anything below v8.0.0) is not compiling on Android is that you are compiling against Android API 31. Starting from Android API 31 some of the bluetooth related permission are deprecated and split up into new permissions. If you want to use version 7.2.0 make sure you compile against Android API 30 or lower. You can do so by setting the `compileSdkVersion` parameter to `30` in your `android/app/build.gradle` file (for an example have a look at the [build.gradle](https://github.com/Baseflow/flutter-permission-handler/blob/4c5ae3f977a56c30da591afe5a43823c14bf5b0c/permission_handler/example/android/app/build.gradle#L28) in the example project).

Please let me know if this solves your problem. If not could you describe the exact problem you are facing including the output of the `flutter doctor -v` command and the platform you experience the issue on?

**Comment by grumpycatz473** [comment]
I am also experiencing this issue, even with `'PERMISSION_NOTIFICATIONS=1',` to podfile

**Comment by mvanbeusekom** [comment]
Hi @grumpycatz473, 

Could you please post more information:

1. Which version of the permission_handler are you using?
2. Could you post the contents of your `ios/Podfile`?

**Comment by frankcheng2020** [comment]
I have the same problem. permission_handler does not pause to show the permission request dialog.
8.3.0
9.2.0

podfile
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end

**Comment by mvanbeusekom** [comment]
Hi @frankcheng2020,

Please carefully read the iOS section of the [README](https://pub.dev/packages/permission_handler) and apply the necessary configuration to enable the permissions your App needs. 

Currently your `ios/Podfile` doesn't contain any of the required configuration meaning all permissions are disabled by default resulting in the above described behavior.
