### ISSUE TITLE
Refactor "denied" to "not determined"

### ISSUE THREAD

**Issue by mariopepe** [Baseflow/flutter-permission-handler#811]
## 🏗 Enhancement Proposal

Refactor "denied" to "not determined"

### Pitch

When the app is first installed on user device flutter-permission-handler recognise the permission as denied, while the real state is actually not determined. Why don't we refactor "denied" to "not determined" to better model the real use case?

Great plugin btw, congrats and thanks!

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi, thank you for this suggestion.

Unfortunately this will not work on Android. Android treats permissions implicitly as denied and there is no way to determine between the permission state before permission is asked for the first time or why permission has been requested but denied (as is possible on iOS).

To keep things cross-platform compatible we treat permissions similar as Android does:

- permissions are denied implicitly but are open to be requested;
- permissions that can't be requested any more return the `permenantlyDenied` status after requesting (note this doesn't work when checking permissions, see also our Wiki).

I will close this issue now, however feel free to leave additional comments or feedback.
