### ISSUE TITLE
Turn on/Off bluetooth using permission-handler package

### ISSUE THREAD

**Issue by ajaypunekar1** [Baseflow/flutter-permission-handler#816]
I am looking for help to **enable bluetooth** or to **check bluetooth is already turn on or off** by using this package. Right now I need to do some native code to check status of bluetooth. 

To check bluetooth is turn **on or off**.
```
await platformMethodChannel
            .invokeMethod('isBluetoothEnabled')
            .then((value) {
          setState(() {
            this.isBluetoothEnabled = value;
          });
        });
```
To turn it **on or off** 

```
//check if bluetooth permission is granted or not
if (isPermissionGranted) {
  platformMethodChannel
      .invokeMethod('enableBluetooth')
      .then((value) {
    setState(() {
      this.isBluetoothEnabled = value;
    });
  });
}
```

Is there any way to do this using this package?

**Comment by mvanbeusekom** [comment]
Hi @ajaypunekar1,

No that is not supported by this package. This package focusses on handling permissions only. Turning on/off bluetooth would be considered a feature for a plugin that resolves around bluetooth and would not be something we'd consider supporting as part of the permission_handler.

Hoping this would answer your question. I will close this issue now, feel free to leave a comment if you have follow up questions or feedback.
