### ISSUE TITLE
folder not creating in android version 12

### ISSUE THREAD

**Issue by codermonk1** [Baseflow/flutter-permission-handler#820]
E/flutter (32093): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: FileSystemException: Creation failed, path = '/storage/emulated/0/abcd' (OS Error: Operation not permitted, errno = 1)

**Comment by mvanbeusekom** [comment]
Duplicate of #313

**Comment by RehanAhmedKhan** [comment]
use external_path package
https://pub.dev/packages/external_path
