### ISSUE TITLE
even settings allow motion & fitness, still returns PermissionStatus.permanentlyDenied

### ISSUE THREAD

**Issue by moxran** [Baseflow/flutter-permission-handler#825]
## 🐛 Bug Report

I am using permission_fhandler to ask for permissions on motion&fitness. It works fine until in one test, I turn off allowing my app in settings/privacy/motion&fitness.  Even after I turn it on in settings, it still returns PermissionStatus.permanentlyDenied from permission.request(). However, I do get the data from motion&fitness.

I would expect it to return PermissionStatus.granted after re-allow in phone settings.

  Future<void> requestMotionPermission() async {
    Permission permission = Permission.unknown;
    PermissionStatus permissionStatus = PermissionStatus.denied;

    if (Platform.isAndroid ) {
      permission = Permission.activityRecognition;
    } else if (Platform.isIOS) {
      permission = Permission.sensors;
    }
    try {
      permissionStatus = await permission.request();
      if (permissionStatus == PermissionStatus.denied || permissionStatus == PermissionStatus.permanentlyDenied ) {
        debugPrint('permission status $permissionStatus');
        openAppSettings();
      }
    } catch (e) {
      debugPrint('ERROR<requestMotionPermission>: $e');
    }
  }

The output shows: Runner[29012:5869957] flutter: permission status PermissionStatus.permanentlyDenied

Podfile:
## dart: PermissionGroup.sensors
            'PERMISSION_SENSORS=1',

Info.plist
<key>NSMotionUsageDescription</key>
	<string>Please allow access to iPhone's built-in motion tracking function. </string>

**Version:** 9.2.0

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by Christyansoft** [comment]
Same problem here :(

**Comment by simonpham** [comment]
I have similar issue with photo permission https://github.com/Baseflow/flutter-permission-handler/issues/828

**Comment by mvanbeusekom** [comment]
Hi @moxran,

Could you have a look in your `ios/Podfile` file, there should be an `if` statement that ensures permissions are only enabled if the target matches the `permission_handler`. 

With the federation of the permission_handler plugin (version 9.0.0) the target name changed from `permission_handler` to `permission_handler_apple`. This means the particular `if` statement in the `ios/Podfile` should be updated to reflect this new name (thanks to @simonpham for pointing this out in issue #828).  

Pre version 9.0.0 the `if` statement should be: 
```
if target.name == 'permission_handler'
```

Post version 9.0.0 the `if` statement should be:
```
if target.name == 'permission_handler_apple'
```

**Comment by moxran** [comment]
> Hi @moxran,
> 
> Could you have a look in your `ios/Podfile` file if there is an `if` statement that ensures permissions are only enabled if the target matches the `permission_handler`.
> 
> With the federation of the permission_handler plugin (version 9.0.0) the target name changed from `permission_handler` to `permission_handler_apple`. This means the particular `if` statement in the `ios/Podfile` should be updated to reflect this new name (thanks to @simonpham for pointing this out in issue #828).
> 
> Pre version 9.0.0 the `if` statement should be:
> 
> ```
> if target.name == 'permission_handler'
> ```
> 
> Post version 9.0.0 the `if` statement should be:
> 
> ```
> if target.name == 'permission_handler_apple'
> ```
> 
> Note that the `if` statement is not part of the suggested configuration, however some developers add it to their configuration and could influence your project.

Thank you very much for your reply! After adding the 'if target.name == 'permission_handler_apple' statement, the problem is solved!

**Comment by moxran** [comment]
> I have a similar issue with photos permission #828 My last known working version was 8.3.0

Hi, thank you! Yes, your solution works! Adding the 'if target.name == 'permission_handler_apple' statement in Podfile solved my problem!
