### ISSUE TITLE
Permission now working 

### ISSUE THREAD

**Issue by apurvandroid** [Baseflow/flutter-permission-handler#827]
## 🐛 Bug Report

  got a errors 
Unhandled Exception: MissingPluginException(No implementation found for method requestPermissions on channel [flutter.baseflow.com/permissions/methods](http://flutter.baseflow.com/permissions/methods))
- [ ] :robot: Android

 Future downloadFile() async {

   final status = await Permission.storage.request();
   print("status $status");

    if (await Permission.storage.isGranted) {
      await Permission.storage.request();
      await startDownload();

    } else {
      await startDownload();

    }
  }

**Comment by apurvandroid** [comment]
yes it’s working but on old version so i just suggest please check on
update version

**Comment by okbye123** [comment]
This might help https://www.youtube.com/watch?v=uMvGpBOT0ZY

**Comment by TimHoogstrate** [comment]
Dear @apurvandroid,

Is seems to work on Android 13. Can you check if it is working in the example app?

Kind regards,
