### ISSUE TITLE
Permission.photos.status always denied?

### ISSUE THREAD

**Issue by simonpham** [Baseflow/flutter-permission-handler#828]
## 🐛 Bug Report

After updating the lib to the latest version 9.2.0, I noticed that `Permission.photos.status` is always returned `PermissionStatus.denie`, no matter I chose Allow access to all photos or only to the selected photos.

In 8.3.0, it was working fine.

**Version:** 9.2.0

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android - not tested

**Comment by mvanbeusekom** [comment]
Hi @simonpham, 

Unfortunately I cannot reproduce the issue using the example App. Requesting the photo permissions shows me the permission dialog. After selecting "Select photos" and selecting some photos the permission status returns `limited`. Restarting the App will check the status using `Permission.photos.status` and will still return `limited` as expected.

Could you provide a simple reproduction example (listing the configuration of the `ios/Podfile`, `ios/Runner/Info.plist` and the Dart code used)? Please also include the version of iOS you are testing against and the output of the `flutter doctor -v` command.

**Comment by simonpham** [comment]
Turns out that when you separated ios to a separated package, the name changed from 'permission_handler' to 'permission_handler_apple'. I have updated it in my Podfile and it is working fine now. I'll close this issue.
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    if target.name == 'permission_handler_apple'
      target.build_configurations.each do |config|
        # Preprocessor definitions can be found in: https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler/ios/Classes/PermissionHandlerEnums.h
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
          '$(inherited)',

          ## dart: PermissionGroup.camera
          'PERMISSION_CAMERA=1',

          ## dart: PermissionGroup.photos
          'PERMISSION_PHOTOS=1',

          ## dart: PermissionGroup.microphone
          'PERMISSION_MICROPHONE=1'
        ]
      end
    end
  end
end
```

**Comment by mvanbeusekom** [comment]
aaa alright I see the problem indeed. I will need to check the documentation and make sure that this is clearly documented. 

Thank you for submitting the fix to the problem and educating us.

**Comment by UMAIRJM** [comment]
It is not working at all I am using flutters's built in package to get the images from the gallery and i am using manifest file accordingly everything is correct still it is giving me error permission denied below is my code

final image_picker = ImagePicker();
  XFile ? _imageFile;

  Future<void> _pickImage()async{
    final status = await Permission.photos.request();
    if(status.isGranted){
      final XFile ? pickFile = await image_picker.pickImage(source: ImageSource.gallery);
      setState(() {
        _imageFile = pickFile;
      });
    }
    else{
      print("permission denied");
    }


  }

  void uploadImageFunction(){
    print("I am getting tapped");
    _pickImage();
  }
