### ISSUE TITLE
'PermissionHandlerEnums.h' file not found

### ISSUE THREAD

**Issue by yesersin** [Baseflow/flutter-permission-handler#835]
## 🐛 Bug Report

Hi, I am getting the error "'PermissionHandlerEnums.h' file not found" at the time of Xcode compilation. I need help on this. I haven't seen a reported solution to the issue.

### Configuration
**Version:** 
permission_handler: ^8.3.0
permission_handler_apple: ^9.0.4 
plugin_platform_interface: ^2.0.0
location: ^4.2.0 

<img width="1039" alt="Ekran Resmi 2022-04-18 16 56 08" src="https://user-images.githubusercontent.com/3195248/163818821-d242e8c4-e55c-42f6-b5eb-214e8c02dc53.png">

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by TimHoogstrate** [comment]
Dear @yesersin,

Did you manage to solve this issue in the meantime?

Kind regards,
