### ISSUE TITLE
iOS Notification Permission Dialog

### ISSUE THREAD

**Issue by Vasco-90** [Baseflow/flutter-permission-handler#837]
## 💬 Questions and Help

Im trying to implement the notification dialog in iOS. The problem I have, the dialog is shown at the beginning of the app.

i want to modify the trigger point. Lets say I want to display the popup after the Onboarding Screen.

How can I achieve this?

**Comment by TimHoogstrate** [comment]
@Vasco-90, Please call await Permission.notification.request() where you would like to ask the user for a permission. 

Kind regards,
