### ISSUE TITLE
ios notification permission is always true

### ISSUE THREAD

**Issue by ling9400** [Baseflow/flutter-permission-handler#841]
## 💬 Questions and Help
**permission_handler: ^9.2.0**
**info.plist:**
installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Here are some configurations automatically generated by flutter

      # You can remove unused permissions here
      # for more infomation: https://github.com/BaseflowIT/flutter-permission-handler/blob/develop/permission_handler/ios/Classes/PermissionHandlerEnums.h
      # e.g. when you don't need camera permission, just add 'PERMISSION_CAMERA=0'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',

        ## dart: PermissionGroup.calendar
        # 'PERMISSION_EVENTS=0',

        ## dart: PermissionGroup.reminders
        # 'PERMISSION_REMINDERS=0',

        ## dart: PermissionGroup.contacts
        # 'PERMISSION_CONTACTS=0',

        ## dart: PermissionGroup.camera
        # 'PERMISSION_CAMERA=0',

        ## dart: PermissionGroup.microphone
        # 'PERMISSION_MICROPHONE=0',

        ## dart: PermissionGroup.speech
        # 'PERMISSION_SPEECH_RECOGNIZER=0',

        ## dart: PermissionGroup.photos
        # 'PERMISSION_PHOTOS=0',

        ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
        # 'PERMISSION_LOCATION=0',

        # dart: PermissionGroup.notification
        'PERMISSION_NOTIFICATIONS=1',

        ## dart: PermissionGroup.mediaLibrary
        # 'PERMISSION_MEDIA_LIBRARY=0',

        ## dart: PermissionGroup.sensors
        # 'PERMISSION_SENSORS=0',

        ## dart: PermissionGroup.bluetooth
        # 'PERMISSION_BLUETOOTH=0'
      ]
    end
  end
 
i used like this: var staus = await Permission.notification.status;   status.isDenied is always false , then i use openAppSettings() and close the notification switch, status.isDenied is alwasy false. could some one help me ?

**Comment by ling9400** [comment]
the result is "PERMISSION_NOTIFICATIONS=1", if " =1" status.isDenied is always false, if "=0" ststus,isDenied is always true.

**Comment by haydgately** [comment]
> ## 💬 Questions and Help
> **permission_handler: ^9.2.0** **info.plist:** installer.pods_project.targets.each do |target| target.build_configurations.each do |config| # Here are some configurations automatically generated by flutter
> 
> ```
>   # You can remove unused permissions here
>   # for more infomation: https://github.com/BaseflowIT/flutter-permission-handler/blob/develop/permission_handler/ios/Classes/PermissionHandlerEnums.h
>   # e.g. when you don't need camera permission, just add 'PERMISSION_CAMERA=0'
>   config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
>     '$(inherited)',
> 
>     ## dart: PermissionGroup.calendar
>     # 'PERMISSION_EVENTS=0',
> 
>     ## dart: PermissionGroup.reminders
>     # 'PERMISSION_REMINDERS=0',
> 
>     ## dart: PermissionGroup.contacts
>     # 'PERMISSION_CONTACTS=0',
> 
>     ## dart: PermissionGroup.camera
>     # 'PERMISSION_CAMERA=0',
> 
>     ## dart: PermissionGroup.microphone
>     # 'PERMISSION_MICROPHONE=0',
> 
>     ## dart: PermissionGroup.speech
>     # 'PERMISSION_SPEECH_RECOGNIZER=0',
> 
>     ## dart: PermissionGroup.photos
>     # 'PERMISSION_PHOTOS=0',
> 
>     ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
>     # 'PERMISSION_LOCATION=0',
> 
>     # dart: PermissionGroup.notification
>     'PERMISSION_NOTIFICATIONS=1',
> 
>     ## dart: PermissionGroup.mediaLibrary
>     # 'PERMISSION_MEDIA_LIBRARY=0',
> 
>     ## dart: PermissionGroup.sensors
>     # 'PERMISSION_SENSORS=0',
> 
>     ## dart: PermissionGroup.bluetooth
>     # 'PERMISSION_BLUETOOTH=0'
>   ]
> end
> ```
> 
> end
> 
> i used like this: var staus = await Permission.notification.status; status.isDenied is always false , then i use openAppSettings() and close the notification switch, status.isDenied is alwasy false. could some one help me ?

Same problem here! Any fix?

**Comment by ling9400** [comment]
> 

i use it like this to check the permission
`var status = await Permission.notification.request();
    if (status.isGranted) {
      isOpen = true;
    } else {
      isOpen = false;
    }`
