### ISSUE TITLE
why there isn't `PermissionGroupNotification` in `Info.plist`

### ISSUE THREAD

**Issue by horo99** [Baseflow/flutter-permission-handler#842]
## 💬 Questions and Help

In example file `Info.plist`(https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler/example/ios/Runner/Info.plist), there isn't `PermissionGroupNotification` option.

Is the option forgot to be added?

**Comment by bartekpacia** [comment]
Same goes for `PermissionGroupCriticalAlerts`.

**Comment by bartekpacia** [comment]
@horo99 Is this some auto responder kinda thing? xD

**Comment by horo99** [comment]
> Same goes for `PermissionGroupCriticalAlerts`.

I didn't even notice my holiday auto-reply   (#-.-)

**Comment by bartekpacia** [comment]
@horo99 Why did you close this?

**Comment by horo99** [comment]
> PermissionGroupNotification

`	<key>PermissionGroupNotification</key>`
`	<string>Notification</string>`

This is used in my project, and it works properly.

but reopening may be a better choice, and waiting for developers' reasonable reply.

**Comment by mvanbeusekom** [comment]
There is no option to override the default message displayed by iOS when requesting notification permissions. Therefore to request notification permissions it is not necessary to register a separate key in your `Info.plist` file.

**Comment by kelvinpraises** [comment]
@mvanbeusekom I don't think that is completely correct now, as not adding  <key>PermissionGroupNotification</key> entry to the `Info.plist` causes my app to crash and lose connection just like https://github.com/Baseflow/flutter-permission-handler/issues/101 the only solution was adding that key and a dummy string or removing the permission from the pod file.
