### ISSUE TITLE
Migrate to enum classes

### ISSUE THREAD

**Issue by lukepighetti** [Baseflow/flutter-permission-handler#848]
## 🏗 Enhancement Proposal

Migrate `Permission` to enum classes

### Pitch

It will allow us to switch block on `Permission` for things like localization strings.

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by JeroenWeener** [comment]
Hi @lukepighetti, thank you for taking the time to open this enhancement proposal!

It is not entirely clear to me what benefits your proposal brings. Could you share a code example that showcases the need for this enhancement?
