### ISSUE TITLE
Status isDenied true even if permission not requested yet

### ISSUE THREAD

**Issue by andzejsw** [Baseflow/flutter-permission-handler#850]
In my opinion **isDenied** by default should be false. Cause it is logical that if permission is not requested, it isn't denied yet. Based on that I would be able to request permission only if it wasn't denied. using this package only and not using extra variables in my app.

**Comment by mvanbeusekom** [comment]
Hi @andzejsw,

Unfortunately on Android this is the default behavior and we adapted the same flow on iOS to have consistent cross-platform functionality. As on Android there is no option to determine if permissions have been requested before or not. Basically Android treats permissions as implicitly denied until indicated differently by the user of the device.

On iOS however we do strictly distinguish between `isDenied` and `isPermanentlyDenied`. Where `isDenied` basically means permissions have not been requested yet and `isPermanentlyDenied` means permissions have been requested by denied by the user.

Hope this helps. I am going to close this issue if you have any further remarks feel free to leave a comment.
