### ISSUE TITLE
PackageManager has been deprecated

### ISSUE THREAD

**Issue by pradeep14598** [Baseflow/flutter-permission-handler#851]
/Users/user/.pub-cache/hosted/pub.dartlang.org/permission_handler_android-9.0.2+1/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java:318: warning: [deprecation] getPackageInfo(String,int) in PackageManager has been deprecated
                    .getPackageInfo(context.getPackageName(), PackageManager.GET_PERMISSIONS);

**Comment by alex-sandri** [comment]
@pradeep14598 I updated this as part of the migration to support Android 13's `POST_NOTIFICATIONS` permission in #845.

**Comment by mvanbeusekom** [comment]
This should be fixed as part of version 10.0.0 of the permission_handler plugin. 

Warning this version contains a breaking change and requires you to update the `compileSdkVersion` to 33 in the `android/app/build.gradle` file. This means you should also download and install this SDK using Android Studios SDK Manager.

**Comment by tashiwangdi** [comment]
@mvanbeusekom  While this fixes the issue in android, the issue with iOS - https://github.com/Baseflow/flutter-permission-handler/issues/860
makes version ^10.0.0 of plugin unusable 😞

**Comment by tashiwangdi** [comment]
> @mvanbeusekom While this fixes the issue in android, the issue with iOS - #860 makes version ^10.0.0 of plugin unusable 😞 in the sense that camera permission is asked every time camera is needed even if the permission has already been granted.

I got around the issue with the following : https://github.com/Baseflow/flutter-permission-handler/issues/860#issuecomment-1173520284

**Comment by govindaeologic** [comment]
in my case by upgrading the permission handler to latest version resolved my problem

**Comment by nazmulislamrony** [comment]
I also get the same issue  After upgrading the compileSdkVersion 33 and targetSdkVersion 33, flutter get an error.

This is the error I got :

`/home/aman/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-8.3.0/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java:317: warning: [deprecation] getPackageInfo(String,int) in PackageManager has been deprecated
                    .getPackageInfo(context.getPackageName(), PackageManager.GET_PERMISSIONS);`

 If you use the flutter 3.0 + and the latest version of compileSdkVersion 33 and targetSdkVersion 33, you may face this error. In this case, you have to change the permission handler in pubspec.yaml to any.

`permission_handler: any`

I have got this solution from flutter service article:  [How to Solve the Flutter PackageManager has been Deprecated](https://flutterservice.com/flutter-packagemanager-has-been-deprecated/)

**Comment by Sarat-1997** [comment]
> This should be fixed as part of version 10.0.0 of the permission_handler plugin.
> 
> Warning this version contains a breaking change and requires you to update the `compileSdkVersion` to 33 in the `android/app/build.gradle` file. This means you should also download and install this SDK using Android Studios SDK Manager.

Thanks @mvanbeusekom. It works!!!!

**Comment by yogithesymbian** [comment]
> + and t

how about if my min dart sdk is `2.12` not `2.15`
