### ISSUE TITLE
Adding GPS sensor activation

### ISSUE THREAD

**Issue by nicolasvahidzein** [Baseflow/flutter-permission-handler#856]
## 🚀 Feature Requests

Allow the user to request the activation of the GPS sensor from inside the app.

### Contextualize the feature
n/a

### Describe the feature
The Location package allows the user to activate the GPS sensor which this app should be able to do as it is more feature rich but yet it is missing.

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi @nicolasvahidzein,

Thank you for taking the time to contact us. This question have been asked before and we decided not to add this feature to the permission_handler plugin as this is not part of the core functionality of the plugin (which is managing permissions). The activation of Android Location service is not related to permissions and permissions can be requested and checked even when the location services are disabled.

Adding this feature would bring a lot of additional complexity to the plugin and we feel this functionality has a better fit in plugins that focus purely on exposing the GPS capabilities of the target device's (for example [Geolocator](https://pub.dev/packages/geolocator) and [Location](https://pub.dev/packages/location)).

**Comment by nicolasvahidzein** [comment]
Thank you for your feedback. I use Geolocator so i will go that route. Thank you for an amazing package and take good care.
