### ISSUE TITLE
iOS is permenantlyDenied when trying to get camera permission, even when it is enabled in app settings

### ISSUE THREAD

**Issue by haydgately** [Baseflow/flutter-permission-handler#860]
## 🐛 Bug Report

iOS is permenantlyDenied when trying to get camera permission, even when it is enabled in app settings

### Expected behavior
If you have camera enabled, then the permission is granted
### Reproduction steps
Check perm status when you call it, when you have permission granted -> var perm = await Permission.camera.request();
### Configuration
Simulator - iPhone 12 (iOS 15.5)
**Version:** 1.x
^10.0.0

**Platform:** 
- [ X] :iphone: iOS
- [ ] :robot: Android

**Comment by novas1r1** [comment]
I have the same for camera and mediaLibrary permission. Is there any workaround?

**Comment by tashiwangdi** [comment]
And you would also need this in your ios/Podfile

```
## dart: PermissionGroup.camera
        'PERMISSION_CAMERA=1',
```

**Comment by zzdota** [comment]
> And you would also need this in your ios/Podfile
> 
> ```
> ## dart: PermissionGroup.camera
>         'PERMISSION_CAMERA=1',
> ```

more detail :https://www.jianshu.com/p/cebd00a7cc16

**Comment by maerlynflagg** [comment]
Same for camera, microphone and location.

**Comment by themmfa** [comment]
Do you check it in applifecycle of the app? Example: 

`
void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.resumed) {
      PermissionHandler()
          .checkPermissionStatus(PermissionGroup.locationWhenInUse)
          .then(_updateStatus);
    }
  }
`
