### ISSUE TITLE
`Permission.notification` `request()` method not working on Android 13 example project. 

### ISSUE THREAD

**Issue by dius00** [Baseflow/flutter-permission-handler#865]
## 🐛 Bug Report

Calling `request()` method on `Permission.notification`  does not show system dialog and always returns `PermissionStatus.denied` on Android 13 (Emulator running API: `33` with ABI: `arm64-v8a` system image).

### Expected behavior

Notification permission is requested. 

### Reproduction steps

Create Android Emulator with API 33, launch the example project, and request notification permission. 

### Configuration

**Version:** 10.0.0

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android

**Comment by dius00** [comment]
Turns out the issue is due to the mission permissions in the AndroidManifest, I opened a PR to fix the issue.

**Comment by JDDV** [comment]
Hi @dius00, thank you for bringing this to our attention, and for your PR, it looks good! 

I saw however not all the checks succeeded, is it possible that you split your PR into two different PR's? One being the permission_handler_android side, and the other one being the permission_handler? Just like I did with PR #563 and PR #564?

Thanks again for your contribution!

**Comment by dius00** [comment]
@JDDV Thanks for the reply!
I split the PR in 2 as requested. 

The only step left would be a 3rd PR after the PR involving`permission_handler_android` is merged, and the updated package is published to update the dependency in the main `permission_handler` package, as that is what was breaking the checks earlier (I had bumped both in the PR, and it couldn't find the 10.0.1 for `permission_handler_android`. 

Thanks again, let me know if I need to make any more changes.

**Comment by JeroenWeener** [comment]
Closing this issue, as it seems to be fixed in #880 and #881.
