### ISSUE TITLE
Unable to request for permissions.

### ISSUE THREAD

**Issue by AlphabetsAlphabets** [Baseflow/flutter-permission-handler#872]
## 🐛 Bug Report

I get this error when I follow the getting started section in the README
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method checkPermissionStatus on channel flutter.baseflow.com/permissions/methods)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
<asynchronous suspension>
#1      MethodChannelPermissionHandler.checkPermissionStatus (package:permission_handler_platform_interface/src/method_channel/method_channel_permission_handler.dart:16:20)
<asynchronous suspension>
#2      Perms.requestPermissions (package:passync/perms.dart:5:18)
<asynchronous suspension>
```
I'm not sure if it matters but I have only added permissions in the android manifest file located in the `main` folder. Do I need to include the permissions in all the manifest files found in different folders or just the one?

I tried requesting for other permissions just to check if it's just a thing with that specific request. But they all give the same asynchronous suspension error. I've searched for issues with that term in the body or title but didn't get much. I've searched online for "Unhandled Exception: MissingPluginException" but the solutions which involves flutter clean but that didn't work. I've tried uninstalling permission_handler and reinstalling it again but that didn't work either. Any solutions to this issue?

### Expected behavior
I am able to request for the permissions if has not been granted.

### Reproduction steps
1. Have the latest version of flutter
2. Have the latest version of this plugin
3. Have [this](https://paste.rs/ii9) code.

### Configuration
If there is any information here that is missing, I'll update it once you inform me of what you need.

Output of `flutter --version`
```
Flutter 3.0.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 85684f9300 (13 days ago) • 2022-06-30 13:22:47 -0700
Engine • revision 6ba2af10bb
Tools • Dart 2.17.5 • DevTools 2.12.2
```

Output of `flutter doctor`
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.4, on Manjaro Linux 5.15.50-1-MANJARO, locale en_US.utf8)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.2)
[✓] Connected device (1 available)
[✓] HTTP Host Availability

! Doctor found issues in 2 categories.
```

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi @AlphabetsAlphabets.

This issue might occur when you request permissions from the background or before the Flutter app has started. From the linked code sample I cannot determine when the permission is requested during the application life cycle so it is hard to judge for me.

Please make sure you don't request permission before the `runApp()` function or when running in the background.

**Comment by AlphabetsAlphabets** [comment]
Hello @mvanbeusekom , I have solved this issue. I took another look at the page and realized there's no implementation for this on Linux. So, it's working as intended. I just didn't look at it closely enough.
