### ISSUE TITLE
WRITE_EXTERNAL_STORAGE can not request base on Android 11

### ISSUE THREAD

**Issue by chensimin920511** [Baseflow/flutter-permission-handler#875]
I have a try with example project，request READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE，result of example is success。then I use “adb shell dumpsys package” to check it，WRITE_EXTERNAL_STORAGE : granted = false

**Comment by Sispheor** [comment]
You need "MANAGE_EXTERNAL_STORAGE" perm.
But if you do that Google will not let you publish your app.....
I don't know what do do either.
I try to save files into the document folder.

I'm able to write into the folder. But If I uninstall the app and install it back I get the `flutter Error: Permission denied, errno = 13`.

**Comment by Sispheor** [comment]
Linked to #877. I guess can be closed too if you consider that this lib should not handle it.
