### ISSUE TITLE
Open App permission settings

### ISSUE THREAD

**Issue by SubratDevop** [Baseflow/flutter-permission-handler#876]
Add the feature that navigate us to App permission Settings.

As an example when openAPPsettings() called it shows all the  app required settings in which location permission is one of them.
But there is no method which opens the specific option's interface(app Permission screen )..

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by JDDV** [comment]
`openAppSettings()` opens the settings for the app that calls the method on Android. A part of this screen is the permission that are allowed/denied by the app. When you click on the permissions option, In this screen you can see the permissions that are granted, and can change them to your liking (allow/deny the permission) when you click on the permissions. So this already navigates you to the permissions for the app. For iOS this is not possible I thought, (correct me if I'm wrong) and it will only open the settings screen for you.
