### ISSUE TITLE
Permission denied, errno = 13 after deleting and reinstalling the app

### ISSUE THREAD

**Issue by Sispheor** [Baseflow/flutter-permission-handler#877]
## 💬 Questions and Help

Hello guys,

I've set the following perms into my app. I get an error on Android 12. 
```xml
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
```

From that I'm able to create a folder in the "Documents" folder of my Android phone and then create files (hive local db files) into it.

But then if uninstall my app and reinstall it, I get this error when trying to read the previously created files:
```
Permission denied, errno = 13
```

I'm want to expose my files in Document so I can grab them via a cloud sync app in case of phone crash. Uninstalling and reinstalling the app simulate this and that's why I would like to get it working.

I'm actually able to "fix" it by adding this perm:
```xml
<uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" />
```

With this perm the reinstalled version of the app is able to read and write into files that have been created by the previous installation.

But...

- Google don't like this perm and rejected my app as it's not a "core feature". (I can workaround this by adding a doc that explain why I need this access as well as adding a menu in the app that explain that I'm going to ask for it.)
- It's weird hat I've been able to read and write with the two first perms and then I'm not able to do it anymore. I haven't found any group or user owner rights in Andoid.
- Asking for this MANAGE_EXTERNAL_STORAGE perm is a big scary for a end user. 

Maybe I'm missing something.
I know that it's not a "bug" here as your lib has done its job by asking the perms. I just don't know where to find help so I add an issue here. Fell free to close it.

Thank you for your time and for this lib.

**Comment by Sispheor** [comment]
Seems same as #642 which has been closed...

**Comment by JDDV** [comment]
Hi @Sispheor, is it possible for you to send me your code (or a stripped down version), so I can see how and what you do and maybe try to reproduce it myself?

Can you check out for me if the folder you made with the hive local db files in it still exists if you uninstall the app? I think that the issue might be just that, but I would like to see an example code so I can reproduce it.

**Comment by Sispheor** [comment]
Hi @JDDV . Thanks for the answer.

After looking for resources I finally found that it was a normal behavior for the SDK 30.
The MediaStore only allow to manipulate object that have been created by the app.
[See ref here](https://commonsware.com/blog/2020/01/05/scoped-storage-stories-modify-content-other-app.html).

If you still need to visualize the code you can take a look [here](https://github.com/Sispheor/sloth_day/blob/storage_issue/lib/utils/external_storage.dart#L36).

Everything is working fine if the folder does not exist in the "Documents" folder. I can read and write..
The problem occurs if I uninstall and reinstall.

Seems that a possible workaround would be to use and `Intent.ACTION_OPEN_DOCUMENT_TREE` to get the perm from the user to read and write the existing folder.
Not tested yet.

**Comment by JDDV** [comment]
Thank you @Sispheor for your reply. 

As a quick sidenote, If the usage of the Manage External Storage permission is needed for your app, you can fill out the Permission Declaration Form upon submitting your app to the Google Play Store. More details can be found here: https://support.google.com/googleplay/android-developer/answer/9214102#zippy=

I hope the workaround you have found will work for you!
