### ISSUE TITLE
可以添加打开定位服务和通知允许

### ISSUE THREAD

**Issue by LoveBabyForeve** [Baseflow/flutter-permission-handler#878]
## 🚀 Feature Requests

如标题所示，openAppSettings()只能满足开启权限相关的需求，并不能在满足开启定位服务、通知方面的需求。
### Describe the feature

比如开定位服务：
    android：
        Intent locationIntent = new Intent(Settings.ACTION_LOCATION_SOURCE_SETTINGS);
        context.startActivity(locationIntent);
    ios：
       url = URL(string: UIApplication.openSettingsURLString)
       UIApplication.shared.open(url)

### Platforms affected (mark all that apply)
- [√] :iphone: iOS
- [√ ] :robot: Android

**Comment by JDDV** [comment]
@LoveBabyForeve, please write feature requests and other issues in English

**Comment by LoveBabyForeve** [comment]
add open location service
code：
Intent locationIntent = new Intent(Settings.ACTION_LOCATION_SOURCE_SETTINGS);
context.startActivity(locationIntent);

**Comment by JDDV** [comment]
Notification and Location permission are both managable from the `openAppSettings()` method as can be seen in the screenshot hereunder. From this screen you can see all the permissions, and notification settings, so I personally don't see the need for implementing another method to open the location settings that is one click further than `openAppSettings()`. Is there a reason you would like to see this implemented?

![Screenshot_20220728_104313](https://user-images.githubusercontent.com/47666699/181463827-2b834f1f-b5dd-4278-867f-0eb981d384d9.png)

**Comment by LoveBabyForeve** [comment]
openAppSettings()  doesn't open location service setting

![image](https://user-images.githubusercontent.com/20234684/181466771-17152260-2a73-4b89-9194-16e6efd771c0.png)

so need add new ones method ，address this issue

**Comment by JDDV** [comment]
I understand that it does not open the location settings of the app. But from the screenshot I've shown you, you can go to that screen as well when you click on `Permissions` -> `Location` after asking for permission. I don't see the point of adding in the extra feature to go to that specific settings page when you have a clear overview and accessibility to the same Location Permission screen when you use 'openAppSettings()`. I would like to hear your reasoning why it would be a nice feature to have it added your way, cause I might overlook a certain situation where it could be useful.

**Comment by LoveBabyForeve** [comment]
Because when you get Permission.location.serviceStatus is ServiceStatus.disabled，users have a hard time finding open portals。

**Comment by florissmit1** [comment]
Android does not support opening specific permission setting screens, and therefor I will close this issue. The only workaround is to request the user for background location access, which will deeplink tot the location permission screen OR when the user denies the request a few times.
