### ISSUE TITLE
Flutter Permission Handler for MacOS.

### ISSUE THREAD

**Issue by DenisMrGnusa** [Baseflow/flutter-permission-handler#886]
## Flutter Permission Handler for MacOS

I hope this plugin can also support for macOS in addition to being able to desktop windows.

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [ ] :robot: Android
- [x] :MacOS

**Comment by hassan-2040** [comment]
@DenisMrGnusa hi, did you find a workaround for this? I need to ask cam/mic permission on mac os but I cant seem to find a way. Did you get it to work?

**Comment by egyleader** [comment]
I also vote for this feature , is it planned to be implemented in this plugin so people can submit a pull request ?

**Comment by bvoq** [comment]
Bump on this feature.

**Comment by LinHaoLove** [comment]
I also vote for this feature!

**Comment by JeroenWeener** [comment]
Closing as this is a duplicate of #337.
