### ISSUE TITLE
[Android] Sometimes, opening the settings' screen doesn't work

### ISSUE THREAD

**Issue by g123k** [Baseflow/flutter-permission-handler#889]
## 🐛 Bug Report
Hello, in my code, in case of a camera permission denial, I open the app settings.
It works 95% of the time, but sometimes, it won't open, just like here:

https://user-images.githubusercontent.com/246838/184590888-15edfad0-717c-457c-b971-09ae7b3c020d.mp4

According to the Logcat, it seems the Intent is not launched at all.
What could explain that?

**Comment by okbye123** [comment]
This might help https://www.youtube.com/watch?v=uMvGpBOT0ZY

**Comment by JeroenWeener** [comment]
Hi @g123k, thank you for filing a bug report!

Could you provide us with a minimal reproducible code sample that allows us to reproduce the issue you are having? The code sample allows us to quickly and effectively track down the issue.

Are you experiencing this issue only on Android?
