### ISSUE TITLE
When I was packing the release version use `flutter run --release`, there was such an error

### ISSUE THREAD

**Issue by dzenm** [Baseflow/flutter-permission-handler#890]
### Configuration

**Version:** 8.3.0

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Androi
<img width="1135" alt="WechatIMG686" src="https://user-images.githubusercontent.com/28523411/184602216-8af32786-78eb-4a1a-9036-319da90b94c8.png">

**Comment by Usama3074** [comment]
i am getting the same error even on debug mode.

https://github.com/Baseflow/flutter-permission-handler/issues/742
it says to update the kotlin version but didn't solve the problem for me.

**Comment by korenminchev** [comment]
Having the same issue here, using ```ext.kotlin_version = '1.6.10'```

**Comment by korenminchev** [comment]
> Having the same issue here, using `ext.kotlin_version = '1.6.10'`

Upgraded ```compileSdkVersion``` in ```app/build.gradle``` to ```32``` and successfully built.

**Comment by TimHoogstrate** [comment]
It seems that this issue has been resolved. I'll close this issue. Feel free to reopen the issue when you needs some additional help. Kind regards,
