### ISSUE TITLE
The plugin `permission_handler` uses a deprecated version of the Android embedding. for v2

### ISSUE THREAD

**Issue by kamranmeyo** [Baseflow/flutter-permission-handler#891]
## 🚀 Feature Requests

The plugin `permission_handler` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.
### Describe the feature

The plugin `permission_handler` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.
### Platforms affected (mark all that apply)
- [y ] :iphone: iOS
- [y ] :robot: Android

**Comment by het1409** [comment]
y

**Comment by okbye123** [comment]
This might help https://www.youtube.com/watch?v=uMvGpBOT0ZY

**Comment by mnazarety** [comment]
I have the same problem, someone help

**Comment by senyomotey** [comment]
Update the version of permission handler in your pubspec.yaml file
The current version at the time of posting this comment is show below

`dependencies:`
`  permission_handler: ^10.3.0`
