### ISSUE TITLE
disabled notification on startup, permission shows old style request pop up

### ISSUE THREAD

**Issue by Handelika** [Baseflow/flutter-permission-handler#894]
## 🐛 Bug Report

android asks for permission, if a user closed notifications permission permanently, and this notification request is old style native request. Ios has the same behaviour but the pop up of request is well designed

### Expected behavior
Android normally not controlling notification because default is granted. If a user closes notification permission permanently, permission handler asks automatic permission request every beginning of application, because of One signal. 

### Reproduction steps
User closes notifications.
Opens the application
And request shown at the beginning of application

### Configuration

**Version:** 1.x
  permission_handler: ^10.0.0

**Platform:** 
- [x ] :iphone: iOS
- [ x] :robot: Androi
![IMG_0174](https://user-images.githubusercontent.com/46781563/185624426-fceeef25-6098-44d9-9331-f37c9e46b82d.jpg)

**Comment by mot-thanhdnv** [comment]
@Handelika I also got the same error.

**Comment by Handelika** [comment]
@mot-thanhdnv I hope they consider this issue

**Comment by TimHoogstrate** [comment]
Dear @Handelika, it is unclear to me what you mean. We would be keen if you update this issue with steps to reproduce, the output of `flutter doctor -v` and maybe some minimal reproducible code. 

Kind regards,
