### ISSUE TITLE
Contacts Permission not working

### ISSUE THREAD

**Issue by deevsaini** [Baseflow/flutter-permission-handler#898]
## 🐛 Bug Report

I am using permission hanger from a long time but recently the contacts permission has stopped working. I haven't changed anything in the code, one day suddenly my contacts permission decided not to show any dialogs at all on new apps only in iOS.

### Reproduction steps
use permission contacts in iOS

### Configuration

**Version:** 10.0.0

**Platform:** 
- [15.5 ] :iphone: iOS
- [ ] :robot: Android

**Comment by dab246** [comment]
I have the same problem.

**Comment by dab246** [comment]
> ## 🐛 Bug Report
> I am using permission hanger from a long time but recently the contacts permission has stopped working. I haven't changed anything in the code, one day suddenly my contacts permission decided not to show any dialogs at all on new apps only in iOS.
> 
> ### Expected behavior
> ### Reproduction steps
> use permission contacts in iOS
> 
> ### Configuration
> **Version:** 10.0.0
> 
> **Platform:**
> 
> * [15.5 ] 📱 iOS
> * [ ]  🤖 Android

I am working around the problem by changing the `permission` value in `ios/Podfile`

```
 ## dart: PermissionGroup.contacts
 'PERMISSION_CONTACTS=1',
```

**Comment by deevsaini** [comment]
> > ## 🐛 Bug Report
> > I am using permission hanger from a long time but recently the contacts permission has stopped working. I haven't changed anything in the code, one day suddenly my contacts permission decided not to show any dialogs at all on new apps only in iOS.
> > ### Expected behavior
> > ### Reproduction steps
> > use permission contacts in iOS
> > ### Configuration
> > **Version:** 10.0.0
> > **Platform:**
> > 
> > * [15.5 ] 📱 iOS
> > * [ ]   🤖 Android
> 
> I am working around the problem by changing the `permission` value in `ios/Podfile`
> 
> ```
>  ## dart: PermissionGroup.contacts
>  'PERMISSION_CONTACTS=1',
> ```

working?

**Comment by deevsaini** [comment]
Closing this as a walk around mentioned above is working , just include required persmissions in your pod file.
