### ISSUE TITLE
Android 13 Permission.notification returns denied

### ISSUE THREAD

**Issue by otopba** [Baseflow/flutter-permission-handler#902]
## 🐛 Bug Report

If the user cancels notification permission request several times then the next time we get a `denied` value when check `permissionStatus`.

Although, we can no longer ask for permission. And we need it to be `permanentlyDenied`

Otherwise, it turns out that the interface has a button "allow access to notifications" but when you click on it nothing happens

### Expected behavior

If the user has canceled the access request several times, I want to get the status `permanentlyDenied`

### Reproduction steps

Take Android 13 and reject the notification access request several times

### Configuration

**Version:** 10.0.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mockturtl** [comment]
> Otherwise, it turns out that the interface has a button "allow access to notifications" but when you click on it nothing happens

I encountered an issue that sounds similar, unrelated to this plugin, which I think the Android 13 docs communicate poorly.

Using 

- `targetSdkVersion 33`
- **without** `<uses-permission ... POST_NOTIFICATIONS" /> ` in `AndroidManifest.xml`, 

then a

- new app install
- on an Android 13 device
 
has its system settings toggle (App Info -> Permissions -> Notifications) **disabled.**

A workaround is to roll back targetSdk to 32, and (/or?) add the manifest permission.

**Comment by Theunodb** [comment]
A temp workaround is to downgrade your targetSdkVersion to 32, while keeping compileSdkVersion on 33 to cater for firebase requirements.

**Comment by brim-borium** [comment]
> > Otherwise, it turns out that the interface has a button "allow access to notifications" but when you click on it nothing happens
> 
> I encountered an issue that sounds similar, unrelated to this plugin, which I think the Android 13 docs communicate poorly.
> 
> Using
> 
> * `targetSdkVersion 33`
> * **without** `<uses-permission ... POST_NOTIFICATIONS" /> ` in `AndroidManifest.xml`,
> 
> then a
> 
> * new app install
> * on an Android 13 device
> 
> has its system settings toggle (App Info -> Permissions -> Notifications) **disabled.**
> 
> A workaround is to roll back targetSdk to 32, and (/or?) add the manifest permission.

Android 13 has the notifications permissions switched off by default as described here https://developer.android.com/develop/ui/views/notifications/notification-permission#new-apps.

But to specify this issue a little bit more:

When using  `await Permission.notification.request()` the correct behavior can be observed for android 13. After denying the permission for a second time the request dialogue won't show up anymore and the status `permanentlyDenied` is true will be returned.

But if I try to just get the status via `Permission.notification.status.isPermanentlyDenied` or `Permission.notification.isPermanentlyDenied` right after I denied the Dialogue for a second time `isPermanentlyDenied` will be false.

**Comment by sebaslogen** [comment]
I'm also having the same problem with Permission.storage, after denying a second time I get `isDenied` true always and `isPermanentlyDenied` false

**Comment by kkoken** [comment]
I have the same behavior on iOS when I check the notification permission. Always returns `denied` even though I granted

**Comment by jlandiseigsti** [comment]
Has anyone found a fix for this? I'm experiencing the same issue. The notification request dialogue isn't showing up, but the logic to handle that is thrown off by the fact that the status  is `denied` rather than `permanentlyDenied`.

**Comment by tiendung01023** [comment]
Hope my code can help you
[https://gist.github.com/tiendung01023/b8d661b910fe2bc4279a6cb7ac0f7c02](https://gist.github.com/tiendung01023/b8d661b910fe2bc4279a6cb7ac0f7c02)

**Comment by sanekyy** [comment]
Hello! 
I think that I found bug in this approach.

If I will not click on buttons in system dialog and just close dialog via click outside of dialog, on third iteration `permission.request();` will show system dialog and then `before` and `after` will be both false, as a result, we will end up in a block with `print('No more permission pop-ups displayed');`

Do anyone have any idea what we can do with that?

**Comment by h3x4d3c1m4l** [comment]
@sanekyy When you reached that specific situation, you can just open the settings. e.g. using the function `openAppSettings` of the package `app_settings`

**Comment by sanekyy** [comment]
Problem is that in that case user see system dialog first, skip then and there we have to end flow.

But we open settings:(

**Comment by KlGleb** [comment]
Same issue

I don't want to show a message to the user if he make a decision  to disable notifications permanently. My temporary solution is:

1. Save a flag in preferences as soon as Permission.notification.request() returns isPermanentlyDenied status. 
2. Call openAppSettings() when previous status is denied and new status (after call request() ) is  isPermanentlyDenied, and when it was not a long time between calling  Permission.notification.status and  Permission.notification.request()

So, when user click the button 'Allow access', he will see notifications dialog or app settings. And then, I don't show the message and the button if Permission.notification.status is disabled and the flag from permissions is true.

Main disadvantages are: 
- If a user clicks "deny" very fast, openSettings() will be call just after dialog complete
- If  request() is slow when it is permanently denied, it returns "denied" status
- app settings will be opened instead of usual dialog on the third interaction

It looks like this:

```dart
///Temporary fix https://github.com/Baseflow/flutter-permission-handler/issues/902
extension TemporaryNotificationsStatusSolution on Permission {
  static const _permissionName = "notificationsPermanentlyDenied";
  static const _diffInMills = 500;

  Future<PermissionStatus> notificationStatus() async {
    var permissionStatus = await Permission.notification.status;
    if (!permissionStatus.isDenied || !(await _isAndroidSdk33())) {
      return permissionStatus;
    }

    final preferences = await SharedPreferences.getInstance();
    final flag = preferences.getBool(_permissionName);
    if (flag == true && permissionStatus.isDenied) {
      return PermissionStatus.permanentlyDenied;
    }

    return permissionStatus;
  }

  ///returns null when it opens App Settings
  Future<PermissionStatus?> notificationRequest() async {
    if (!(await _isAndroidSdk33())) {
      return await Permission.notification.request();
    }

    final checkStatusTime = DateTime.now();
    final status = await Permission.notification.status;
    final newStatus = await Permission.notification.request();
    final newCheckStatusTime = DateTime.now();
    Duration difference = newCheckStatusTime.difference(checkStatusTime);
    logger.d(difference.inMilliseconds);

    if (status.isDenied &&
        newStatus.isPermanentlyDenied &&
        difference.inMilliseconds < _diffInMills) {
      final preferences = await SharedPreferences.getInstance();
      preferences.setBool(_permissionName, true);
      openAppSettings();
      return null;
    }

    return newStatus;
  }

  Future<bool> _isAndroidSdk33() async {
    if (defaultTargetPlatform != TargetPlatform.android) {
      return false;
    }
    DeviceInfoPlugin deviceInfo = DeviceInfoPlugin();
    AndroidDeviceInfo androidInfo = await deviceInfo.androidInfo;
    return androidInfo.version.sdkInt == 33;
  }
}
```

And then I call Permission.notification.notificationStatus(); instead of Permission.notification.status and Permission.notification.notificationRequest(); instead of Permission.notification.request()

For example:
```dart
class _NotificationPermissionsExampleState
    extends State<NotificationPermissionsExample> with WidgetsBindingObserver {
  bool _needToShow = false;

  @override
  Widget build(BuildContext context) {
    if (!_needToShow) {
      return const Text(
          "Permissions are granted, limited or permanently denied");
    }

    return Column(
      children: [
        const Text("Please grant location permissions"),
        OutlinedButton(
            onPressed: _requestPermissions,
            child: const Text("Grant permissions"))
      ],
    );
  }

  @override
  void initState() {
    _checkForPermissions();
    WidgetsBinding.instance.addObserver(this);
    super.initState();
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.resumed) {
      _checkForPermissions();
    }
  }

  Future<void> _checkForPermissions(
      {PermissionStatus? permissionStatus}) async {
    final status =
        permissionStatus ?? await Permission.notification.notificationStatus();
    setState(() {
      _needToShow =
          !status.isGranted && !status.isLimited && !status.isPermanentlyDenied;
    });
  }

  Future<void> _requestPermissions() async {
    final permissionStatus =
        await Permission.notification.notificationRequest();
    if (permissionStatus != null) {
      _checkForPermissions(permissionStatus: permissionStatus);
    }
  }
}
```

**Comment by okbye123** [comment]
This might help https://www.youtube.com/watch?v=uMvGpBOT0ZY

**Comment by Avinash01111992** [comment]
I am having other issue with respect to getting the status of the notification permission.

 When the app installed first time, When i check for       
 final  notificationStatus = await Permission.notification.status;

 Excepted behaviour : Status should be UNKNOWN or not determined 

 Actual behaviour : Status always Denied.

 I need the status as unknown in app first lunch to show some explanations before i show the OS permission pop-up.

**Comment by sanekyy** [comment]
@Avinash01111992 Hi!

Usually this task solves via bool pref in preferences manager.

**Comment by AvinashGowda-11** [comment]
@sanekyy  Hello 

Thank you for you'er reply.

What you mean by **via bool pref in preferences manager** 

Can you eleborate more on this solution.

Do I need to store  the permission status in the front end ?? How ? Because when the app starts up , Status should be unknown , and also I should know when permission  permanently disabled.
