### ISSUE TITLE
english -> japanese(Match app language)!!!!!!!!

### ISSUE THREAD

**Issue by kirasoga** [Baseflow/flutter-permission-handler#912]
## 🚀 Feature Requests

Display in Japanese
<img width="177" alt="スクリーンショット 2022-09-15 17 09 29" src="https://user-images.githubusercontent.com/57799569/190350968-f30df220-9c59-4d1d-85eb-8b4c45528daf.png">

Would like to send you notifications -> 

this!!!!!!!!!
<img width="290" alt="スクリーンショット 2022-09-15 17 10 57" src="https://user-images.githubusercontent.com/57799569/190351136-7a79d6bd-3c0b-433c-a9d5-ecf26d98c53b.png">

### Describe the feature
look at the photo

### Platforms affected (mark all that apply)
- [✨] :iphone: iOS

**Comment by mvanbeusekom** [comment]
Have you setup localization in your Flutter application correctly? The permission_handler doesn't interfere with language or locale settings, these are all coming from the system and is something app developers should override correctly. 

Please carefully read the following documentation: https://docs.flutter.dev/development/accessibility-and-localization/internationalization#introduction-to-localizations-in-flutter
