### ISSUE TITLE
PermissionStatus is being set to permanentlyDenied not denied

### ISSUE THREAD

**Issue by FigueredoMatheus** [Baseflow/flutter-permission-handler#919]
## 🐛 Bug Report

When request permission, a pop up are displayed and is dismissed by clicking on one of the buttons as expected, but some devices when user dismiss the pop up (clicking outside pop up), the PermissionStatus are automatically set to PermanentlyDenied, however when user click again, the pop up for permission display normally.

### Expected behavior

When the pop up is dismissed the PermissionStatus is set to denied but not permanentlyDenied

### Reproduction steps

1 - await Permission.storage.request();
2 - dismiss pop up permission (clicking ouside)

### Configuration

**Version:** 10.0.0

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android

**Comment by AlexDochioiu** [comment]
Up. Came here to report the same

**Comment by baharudin-yusup** [comment]
> Up. Came here to report the same for camera permission on Android.

Me too

**Comment by deandreamatias-worldline** [comment]
Maybe related to this?
https://pub.dev/packages/permission_handler#requesting-storage-permissions-always-returns-denied-on-android-13-what-can-i-do
