### ISSUE TITLE
How to handle "back" event after openAppSettings was called

### ISSUE THREAD

**Issue by beerline** [Baseflow/flutter-permission-handler#920]
Hi!

First of all thank u for amazing library!

I am trying to find call back function to handle get back after `openAppSettings()`.

1. call `openAppSettings()`
2. App settings page was open
3. press `back` button
4. get back to app
5. *here i want to call my call back*

i was trying this callback but non of them is firing after App Settings Page is closed

```
 @override
  void didPop() {
    print('----didPop');
    _checkPermission();
  }

 @override
  Future<bool> didPopRoute() {
    print('----didPopRoute');
    _checkPermission();

    return super.didPopRoute();
  }

  @override
  void didUpdateWidget(Widget oldWidget) {
    print('----didUpdateWidget');
    _checkPermission();
    super.didUpdateWidget(widget);
  }

 @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    print('----didChangeAppLifecycleState: $state');
    if (state == AppLifecycleState.resumed) {
      _checkPermission();
    }
  }
```

**Comment by devmuaz** [comment]
I believe you can use the AppLifeCycle of your app which in this case is AppLifeCycle.resumed because your app is actually resumed after closing the settings.

Read more here: https://api.flutter.dev/flutter/dart-ui/AppLifecycleState.html

**Comment by beerline** [comment]
@devmuaz thank u for your replay.

But as u can see in code above i already used `AppLifeCycle.resumed` and it is not firing print to console.

I think it's happening because open settings through platform channels and it is counting as application itself. In other words it is mean that even while we see settings page application is still on foreground

**Comment by mvanbeusekom** [comment]
I will go ahead and close this issue for now. If there are any concerns please leave a detailed comment and we would be happy to look into the issue once more.
