### ISSUE TITLE
nearbyWifiDevices.request() does not work

### ISSUE THREAD

**Issue by guyluz11** [Baseflow/flutter-permission-handler#938]
## 🐛 Bug Report

Request nearby WiFi devices do not open any popup for me and returned denied value.

### Expected behavior
Popup to allow access opens up or function returns automatically granted state.

### Reproduction steps
1. Create empty project
2. Add a call to the function `await Permission.nearbyWifiDevices.request();`
3. Add a bunch of android permissions to `AndroidManifest.xml` just to make sure that we are not missing anything 
```
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.CHANGE_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
    <uses-permission android:name="android.permission.NEARBY_WIFI_DEVICES" />
    <uses-permission android:name="android.permission.WRITE_SETTINGS" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
```
4. Run the app on android 12 device

### Configuration

**Version:** 10.1.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by guyluz11** [comment]
Ok so no nearby wifi devices permission is needed for below 13.

I do expect the method to return true in that case and for this to be stated in the documentation of the method (not just inside code 31).
![image](https://user-images.githubusercontent.com/9304740/196750821-a9936e49-2440-4336-9566-1e9df8a5752b.png)

**Comment by JeroenWeener** [comment]
This seems to be resolved in the latest version of the plugin: https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler_platform_interface/lib/src/permissions.dart#L256C1-L257C53.

```dart
  /// Permission for connecting to nearby devices via Wi-Fi (Android T+ only).
  static const nearbyWifiDevices = Permission._(31);
```

**Comment by guyluz11** [comment]
What is Android `Android T+`? there aren't any relevant results when searching it in google.
Why not write an API-level or android version instead?

**Comment by JeroenWeener** [comment]
@guyluz11 Android T refers to Android Tiramisu, also known as Android 13 or API level 33. For a complete overview of Android versions have a look here: https://en.wikipedia.org/wiki/Android_version_history.

You have a point that we could be clearer in the documentation. I believe Android has strayed away from using names such as Tiramisu. Therefore, changing the docs to mention Android 13 would be more convenient.

I will reopen the issue as a reminder to update the documentation.
