### ISSUE TITLE
ios notification permission always denied

### ISSUE THREAD

**Issue by wolru** [Baseflow/flutter-permission-handler#940]
PermissionStatus statusNotification = await Permission.notification.status;
Log.d('notification permission status = $statusNotification');

always denied even if permission is granted
Android is working perfectly, but IOS has problem

I'm using 
permission_handler: ^10.1.0

**Comment by scotch-formitable** [comment]
I am having the same issue, always status == 'permanentlyDenied' on IOS

**Comment by scotch-formitable** [comment]
I ran into a similar Issue, and then realised I had not read the setup instructions correctly.

Have you added the post install script to the Podfile? 

Click the IOS tab in the setup for: https://pub.dev/packages/permission_handler and follow the instructions :)

**Comment by HatsuneMikuV** [comment]
I have the same problem,
If the permission obtained by calling your own iOS code with channel is enabled, but the permission obtained with Permission.notification.status is denied
Other configurations are normal

permission_handler: ^10.1.0

**Comment by hanbit-valla** [comment]
@scotch-formitable Thank you!!! There is a typo in podfile

**Comment by wolru** [comment]
@scotch-formitable Thank you!! There is a typo in my podfile
