### ISSUE TITLE
[10.2.0] Permission.photos.status always returns PermissionStatus.denied on Android 12

### ISSUE THREAD

**Issue by MinseokKang003** [Baseflow/flutter-permission-handler#944]
### Old (and correct) behavior
Permission.photos.status returns PermissionStatus.granted on Android 12

### Current behavior
Permission.photos.status always returns PermissionStatus.denied on Android 12

### Reproduction steps
Call Permission.photos.status on Android 12

### Configuration
Properly setup AndroidManifest.xml.
It worked well on 10.1.0.

**Version:** 
10.1.0 -> 10.2.0

**Comment by MinseokKang003** [comment]
Needs to be fixed, it works properly as soon as I downgrade permission_handler and permission_handler_android to 10.1.0.

**Comment by hinrikHelga** [comment]
> [2395c10#r87752291](https://github.com/Baseflow/flutter-permission-handler/commit/2395c10c0da4000dad4e2c36d4589679c927d9d7#r87752291) No permissions found in manifest for: []9 I found this maybe error.
> 
> ```
> 
>  if (names.isEmpty()) {
>   Log.d(PermissionConstants.LOG_TAG, "No permissions found in manifest for: " + permission + " no need to show request rationale");
>   successCallback.onSuccess(false);
>   return;
> }
> 
>  static List<String> getManifestNames(Context context, @PermissionConstants.PermissionGroup int permission) {
>         final ArrayList<String> permissionNames = new ArrayList<>();
> 
>         switch (permission) {
>  case PermissionConstants.PERMISSION_GROUP_PHOTOS:
>                 // The READ_MEDIA_IMAGES permission is introduced in Android T, meaning we should
>                 // not handle permissions on pre Android T devices.   
>                 if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU && hasPermissionInManifest(context, permissionNames, Manifest.permission.READ_MEDIA_IMAGES ))
>                     permissionNames.add(Manifest.permission.READ_MEDIA_IMAGES);
>                 break;
> ```

I've been experiencing exactly this issue for Android versions 12.0 and before. Works fine on Android 13.0. 

Any idea of how to solve this or a workaround?

**Comment by NaosFr** [comment]
Same problem

**Comment by TillCity** [comment]
I ran into the issue with `Permissions.photos.status `always returning `PermissionStatus.denied `today for no reason that is immediately obvious to me though I suppose the Flutter upgrades and the upgrade of the image_picker plugin may have a role to play there.  I have fixed this by checking `Permissions.storage.status` instead and ensuring that that permission has been granted.  While this works it is not clear to me what `Permissions.photos` does if `Permissions.storage` works to let me have access to the image gallery on the device

**Comment by dr953** [comment]
Same problem here

**Comment by hinrikHelga** [comment]
> I ran into the issue with `Permissions.photos.status `always returning `PermissionStatus.denied `today for no reason that is immediately obvious to me though I suppose the Flutter upgrades and the upgrade of the image_picker plugin may have a role to play there. I have fixed this by checking `Permissions.storage.status` instead and ensuring that that permission has been granted. While this works it is not clear to me what `Permissions.photos` does if `Permissions.storage` works to let me have access to the image gallery on the device

I've fixed this by checking for `Permissions.storage.status` when the device is Android 12.0 or below, else I use the `Permissions.storage.status`. I use the [device_info_plus plugin](https://pub.dev/packages/device_info_plus) to check the Android version.

I added the following to my `AndroidManifest.kt` 
```kotlin
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"
        android:maxSdkVersion="32"/>
<uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/>
```

and in flutter:
```dart
if (Platform.isAndroid) {
  final androidInfo = await DeviceInfoPlugin().androidInfo;
  if (androidInfo.version.sdkInt <= 32) {
    /// use [Permissions.storage.status]
  }  else {
    /// use [Permissions.photos.status]
  }
}
```

**Comment by ehangwork** [comment]
Same question

**Comment by oscarshaitan** [comment]
I spot that the version 10.0.0 works only if I set the android version to 10.0.0 too
  permission_handler: 10.0.0
  permission_handler_android: 10.0.0
 If I leave only the handler the pubspeck.lock will pull the android 10.2.0 that fails

**Comment by mujahid008** [comment]
Same is happening with me on Android 11

**Comment by Alpha17-2** [comment]
> > I ran into the issue with `Permissions.photos.status `always returning `PermissionStatus.denied `today for no reason that is immediately obvious to me though I suppose the Flutter upgrades and the upgrade of the image_picker plugin may have a role to play there. I have fixed this by checking `Permissions.storage.status` instead and ensuring that that permission has been granted. While this works it is not clear to me what `Permissions.photos` does if `Permissions.storage` works to let me have access to the image gallery on the device
> 
> I've fixed this by checking for `Permissions.storage.status` when the device is Android 12.0 or below, else I use the `Permissions.storage.status`. I use the [device_info_plus plugin](https://pub.dev/packages/device_info_plus) to check the Android version.
> 
> I added the following to my `AndroidManifest.kt`
> 
> ```kotlin
> <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"
>         android:maxSdkVersion="32"/>
> <uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/>
> ```
> 
> and in flutter:
> 
> ```dart
> if (Platform.isAndroid) {
>   final androidInfo = await DeviceInfoPlugin().androidInfo;
>   if (androidInfo.version.sdkInt <= 32) {
>     /// use [Permissions.storage.status]
>   }  else {
>     /// use [Permissions.photos.status]
>   }
> }
> ```

Until they fix this, i guess we should work with @hinrikHelga solution.

**Comment by lg8294** [comment]
same question

**Comment by seceba** [comment]
Android 11 and Android 13 works but android 12 ( sdk 31 ) problem still exist.

**Comment by alfietapping** [comment]
> > > I ran into the issue with `Permissions.photos.status `always returning `PermissionStatus.denied `today for no reason that is immediately obvious to me though I suppose the Flutter upgrades and the upgrade of the image_picker plugin may have a role to play there. I have fixed this by checking `Permissions.storage.status` instead and ensuring that that permission has been granted. While this works it is not clear to me what `Permissions.photos` does if `Permissions.storage` works to let me have access to the image gallery on the device
> > 
> > 
> > I've fixed this by checking for `Permissions.storage.status` when the device is Android 12.0 or below, else I use the `Permissions.storage.status`. I use the [device_info_plus plugin](https://pub.dev/packages/device_info_plus) to check the Android version.
> > I added the following to my `AndroidManifest.kt`
> > ```kotlin
> > <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"
> >         android:maxSdkVersion="32"/>
> > <uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and in flutter:
> > ```dart
> > if (Platform.isAndroid) {
> >   final androidInfo = await DeviceInfoPlugin().androidInfo;
> >   if (androidInfo.version.sdkInt <= 32) {
> >     /// use [Permissions.storage.status]
> >   }  else {
> >     /// use [Permissions.photos.status]
> >   }
> > }
> > ```
> 
> Until they fix this, i guess we have to work with @hinrikHelga solution.

Tried this on android 13 & 11, neither currently working. Using   permission_handler: ^10.2.0

**Comment by oscarshaitan** [comment]
any update or fix?

**Comment by QPAYRE** [comment]
Got the same issue .

@hinrikHelga 's solution worked for me. Thanks

**Comment by ardeshir-33033** [comment]
I hope this gets a fix since some packages like Agora use this version of the Permission handler so we cannot downgrade it.

**Comment by jdevp** [comment]
Tried @hinrikHelga solution but didn't get rid of " No permissions found in manifest for: []9". Permission.photos is always denied. Running Android 12 and target 31.

**Comment by wojciechzahradnikdeviniti** [comment]
Hi, any updates on this issue? I still have a problem with that.

**Comment by JDongKhan** [comment]
bluetoothConnect & bluetoothScan can not work too.

**Comment by carman247** [comment]
Is there any workaround for this currently?

**Comment by dehypnosis** [comment]
@carman247 as far as know, 10.1.0 is latest working version.

**Comment by dehypnosis** [comment]
No progress...? I cannot upgrade this lib since this issue happend.

**Comment by TimHoogstrate** [comment]
According to the documentation: https://developer.android.com/about/versions/14/changes/partial-photo-video-access and https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions you need to grand permissions to access photos on Android 13 and higher. 

Android 12 and lower need to grand different permissions like readExternalStorage and writeExternalStorage to access photos. 

I don't think this is a bug in the permission handler. It is also not introduced in 10.1.0. Support for Android 13 was introduced by ADDING permissions for photo's. I have to test the behaviour on Android 12 and below, but it seems to work as expected. 

I'll discuss within the team to see if this is something we would like to change in the future or if we need to add additional documentation to make things clear. Either way, it would be an enhancement. The solution of @hinrikHelga would be the way to go until further notice.

**Comment by richanshah** [comment]
so is this fixed? what to update in project?

**Comment by icodeyou** [comment]
Is it fixed ? 
I have the same issue on iOS 17, with permission_handler 11.3.1
I don't know if I should open a new ticket for that

**Comment by balasubramanian1612s** [comment]
@richanshah @icodeyou Did you guys find something? Did it work?
