### ISSUE TITLE
Only work with latest Android version

### ISSUE THREAD

**Issue by AdrKacz** [Baseflow/flutter-permission-handler#945]
## 💬 Only work with the latest Android version

I would like to know why the package only works with the latest Android version.

Because of this restriction, I cannot use version `^10.0.0`.

Indeed, only a few users have the latest version of Android.

Best,

**Comment by mvanbeusekom** [comment]
Hi @AdrKacz, 

The `permission_handler` plugin works on Android 4.1 (SDK 16) to Android 13 (SDK 33). 

The only requirement is that you compile it against SDK 33 (by setting `compileSdkVersion` to `33`. 

Setting the `compileSdkVersion` is different from being able to target lower versions of Android. It simply means we can make use of all the latest versions of Android 13.

You can read more on this here: https://proandroiddev.com/compilesdkversion-and-targetsdkversion-what-is-the-difference-b4227c663ba8
