### ISSUE TITLE
permission_handler:  10.2.0 All Ios Permission retrun Denied;

### ISSUE THREAD

**Issue by fenngzui** [Baseflow/flutter-permission-handler#948]
### Configuration

**Version:** 10.2.0

**Platform:** 
- [ 15.6.1] :iphone: iOS 
- [ ] :robot: Android

<img width="789" alt="image" src="https://user-images.githubusercontent.com/75266036/198198233-ddb27590-96a4-45b0-bb89-3c09ebb750b6.png">

**Comment by mvanbeusekom** [comment]
Have you added the permissions to the `ios/Podfile` as instructed in the `ios` section of the README.md file?

**Comment by fenngzui** [comment]
ThankYou! @mvanbeusekom  I have fix this.
