### ISSUE TITLE
on android platform if i select denied and request permission again , it return exception message "request for permissions is already running"

### ISSUE THREAD

**Issue by Etermally** [Baseflow/flutter-permission-handler#950]
## 💬 Questions and Help

SOS!!! HELP!!!  MOGUL!!!
<img width="906" alt="截屏2022-11-02 14 43 09" src="https://user-images.githubusercontent.com/13942100/199418899-fea05cbb-8e6f-422a-8013-8bb17da1043e.png">

on android platform if i select denied and request permission again , it return exception message "request for permissions is already running"

E/flutter (24097): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(PermissionHandler.PermissionManager, A request for permissions is already running, please wait for it to finish before doing another request (note that you can request multiple permissions at the same time)., null, null)
E/flutter (24097): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (24097): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter (24097): <asynchronous suspension>
E/flutter (24097): #2      MethodChannelPermissionHandler.requestPermissions (package:permission_handler_platform_interface/src/method_channel/method_channel_permission_handler.dart:71:9)
E/flutter (24097): <asynchronous suspension>
E/flutter (24097): #3      _TEstPermissionPageState._selectContact (package:digital_storage_app/mine/controller/test_test_permission_page.dart:116:50)
E/flutter (24097): <asynchronous suspension>

**Comment by Etermally** [comment]
How to solve this problem? Very worried! Thanks for your advice!

**Comment by ubitechparth** [comment]
when I am allow all the permissions than second time I am hit location function this errors comes in console  
how to solve it multiple permission allow  in one time .
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(PermissionHandler.PermissionManager, A request for permissions is already running, please wait for it to finish before doing another request (note that you can request multiple permissions at the same time)., null, null)

**Comment by E-MRE** [comment]
same problem. I try to request microphone request. I allow it but package doesn't respond to me.

**Comment by samyak039** [comment]
I am having this same issue.

what I trying to do is:
```dart
    PermissionStatus status = await Permission.locationWhenInUse.status;

    if (status.isGranted) {
      // location permission is GRANTED
      print('===> permission GRANTED');
    } else if (status.isDenied) {
      // location permission is NOT GRANTED
      await Permission.locationWhenInUse.request();
    } else if (status.isPermanentlyDenied) {
      // location permission is PERMANENTLY DENIED
      openAppSettings();
    }
```

but it always throws exception on `Permission.locationWhenInUse.request()` and doesn't request for the permission also.

I am guessing that `.request()` is having some issues.

I tested an Android 13 & Android 11. same thing on both devices.

**Comment by steph-laporte** [comment]
Same problem with android and camera permission. First time requesting permission the popup is displayed. Then if we choose denied when we try later to request again the permission the popup is not displayed and the exception occurs. The problem doesn't occurs if the first time the popup is displayed we do not choose any option but have tapped outside the popup on the overlay.
Unhandled Exception: PlatformException(PermissionHandler.PermissionManager, A request for permissions is already running, please wait for it to finish before doing another request

**Comment by sjoerdlmkns** [comment]
We are experiencing the same problem on some Android devices. Our code looks like this:

```dart
Future<void> _showCameraPermissionDialog(BuildContext context) => showDialog<void>(
      context: context,
      builder: (context) => CameraPermissionDialog(),
    );


Future<bool> handleCameraPermission(BuildContext context) async {
  final cameraPermissionStatus = await Permission.camera.request();


  if (cameraPermissionStatus.isGranted) {
    return true;
  } else if (cameraPermissionStatus.isPermanentlyDenied) {
    await _showCameraPermissionDialog(context);
  }


  return false;
}
```
