### ISSUE TITLE
deny location always crashes android

### ISSUE THREAD

**Issue by dstavy** [Baseflow/flutter-permission-handler#951]
## 🐛 Bug Report

when selecting something different then allow always app crashes while the system permission window is on the screen
### Expected behavior
return permanently denied or denied
### Reproduction steps
using the sample app ask location in use then ask location always and select something else then always
### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by SupremeDeity08** [comment]
`Android version: 11`
`permission_handler: ^10.1.0`

This issue is happening with `manageExternalStorage` aswell. Basically, if you switch the allow switch on and off, the app will crash. No exception is returned.

**Comment by TimHoogstrate** [comment]
I cannot reproduce this on Android 13. Is it still happening?

Kind regards,
