### ISSUE TITLE
IOS permission status returns denied but is granted 

### ISSUE THREAD

**Issue by fullflash** [Baseflow/flutter-permission-handler#954]
Hi.
we are getting permission.microphone as PermissionStatus.denied
but it is granted also checked on device settings it is on

```

    • Flutter version 3.3.7 on channel stable at ******
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (12 days ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0
```

permission_handler: ^10.1.0
ios 16.1
device iphone xs max

```

<key>NSMicrophoneUsageDescription</key>
	<string>need to record audi messages</string>
```

**Comment by alihuseyin** [comment]
Same here. It was working but not anymore.

**Comment by alihuseyin** [comment]
I realized that my pod file has been changed.

Just be sure that you set up your pod file correctly by adding this:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

 	target.build_configurations.each do |config|
   	config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      
      #  Preprocessor definitions can be found in: https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler/ios/Classes/PermissionHandlerEnums.h
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',


        ## dart: PermissionGroup.microphone
       'PERMISSION_MICROPHONE=1',

        ## dart: PermissionGroup.speech
        # 'PERMISSION_SPEECH_RECOGNIZER=1',


        ## dart: PermissionGroup.notification
        # 'PERMISSION_NOTIFICATIONS=1',

        ## dart: PermissionGroup.mediaLibrary
        # 'PERMISSION_MEDIA_LIBRARY=1',


        ## dart: PermissionGroup.appTrackingTransparency
        # 'PERMISSION_APP_TRACKING_TRANSPARENCY=1',

        ## dart: PermissionGroup.criticalAlerts
        # 'PERMISSION_CRITICAL_ALERTS=1'
      ]
    end
  end
end
```

**Comment by fullflash** [comment]
> I realized that my pod file has been changed.
> 
> Just be sure that you set up your pod file correctly by adding this:
> 
> ```
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     flutter_additional_ios_build_settings(target)
> 
>  	target.build_configurations.each do |config|
>    	config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
>       
>       #  Preprocessor definitions can be found in: https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler/ios/Classes/PermissionHandlerEnums.h
>       config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
>         '$(inherited)',
> 
> 
>         ## dart: PermissionGroup.microphone
>        'PERMISSION_MICROPHONE=1',
> 
>         ## dart: PermissionGroup.speech
>         # 'PERMISSION_SPEECH_RECOGNIZER=1',
> 
> 
>         ## dart: PermissionGroup.notification
>         # 'PERMISSION_NOTIFICATIONS=1',
> 
>         ## dart: PermissionGroup.mediaLibrary
>         # 'PERMISSION_MEDIA_LIBRARY=1',
> 
> 
>         ## dart: PermissionGroup.appTrackingTransparency
>         # 'PERMISSION_APP_TRACKING_TRANSPARENCY=1',
> 
>         ## dart: PermissionGroup.criticalAlerts
>         # 'PERMISSION_CRITICAL_ALERTS=1'
>       ]
>     end
>   end
> end
> ```

thanks @alihuseyin it solves the issue.
