### ISSUE TITLE
Requesting only camera permission, excluding microphone permission

### ISSUE THREAD

**Issue by navaronbracke** [Baseflow/flutter-permission-handler#957]
## 🚀 Feature Requests

Requesting only camera permission, not microphone permission.

### Contextualize the feature

I have an app where I scan barcodes using MLKit and the device camera.
If I want to request the camera permission, `Permission.camera` requests the microphone as well,
even though in my case I don't need it.

### Describe the feature
Allow excluding the microphone permission when requesting camera permissions.

### Platforms affected (mark all that apply)
- [x] :iphone: iOS (not sure if this could be fixed by **not** using the microphone macro)
- [x] :robot: Android

**Comment by okbye123** [comment]
This might help https://www.youtube.com/watch?v=uMvGpBOT0ZY

**Comment by TimHoogstrate** [comment]
Dear @navaronbracke,

I cannot reproduce this on Android 13 with the example app. Can you try to test this with the example app to see if it is happening as well? If not, maybe it is something in your code?

Kind regards,
