### ISSUE TITLE
IOS app integration Flutter, permission.microphone status returns denied

### ISSUE THREAD

**Issue by luciferyue** [Baseflow/flutter-permission-handler#958]
info.plist && Podfile config has been added～！
flutter run alone , permission.microphone status return true. 
but IOS app run width flutter, permission.microphone status returns denied.

**Comment by Ashkan-Sarlak** [comment]
Try:
`cd ios`
`pod install`
You have to run this everytime you make a change to Podfile.

**Comment by fullflash** [comment]
same here.
microphone permission returns denied all the time.
this case is only with audio permission
