### ISSUE TITLE
On Android 13 notification permission request() returns different value than status() when permanently denied

### ISSUE THREAD

**Issue by orestesgaolin** [Baseflow/flutter-permission-handler#961]
## 🐛 Bug Report

The result of `Permission.notification.status` is different than `request()`. 

- `status` - `denied`
- `request` - `permanentlyDenied`

### Expected behavior

Both calls should return the same value.

### Reproduction steps

| Before | After |
| ---- | ---- | 
| ![CleanShot 2022-12-01 at 18 24 46](https://user-images.githubusercontent.com/16854239/205120081-ca66dc07-061b-4aa8-ad50-fae9e9fc6c36.png) | ![CleanShot 2022-12-01 at 18 25 10](https://user-images.githubusercontent.com/16854239/205120087-e5204b40-ca3e-4c73-a21c-c932aa65b10b.png) |

1. Add `<uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>` to the AndroidManifest of the example app
2. Run the app on Android 13 device
3. Setup breakpoint in the `requestPermission` and add `final statusStatus = await permission.status;`
4. Tap on the notification permissions and deny them
5. In the `requestPermission` compare responses from 2 methods

![CleanShot 2022-12-01 at 18 24 56](https://user-images.githubusercontent.com/16854239/205120011-ecd846f0-75e8-43cb-9574-89d8ddad3cda.png)

### Configuration

**Version:** permission_handler: ^10.2.0

**Flutter**: stable 3.3.8

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android 13 (SDK 33)

**Comment by jonbhanson** [comment]
Related to #902.  Seems like there are quite a few Android 13 related tickets.  @mvanbeusekom can you look at these please? 🙏

**Comment by winren9** [comment]
any news on this?
