### ISSUE TITLE
An MissingPluginException occurs when you apply for permission

### ISSUE THREAD

**Issue by ydd-fk** [Baseflow/flutter-permission-handler#966]
## 🐛 Bug Report
**MissingPluginException**
An MissingPluginException occurs when you apply for permission
![image](https://user-images.githubusercontent.com/82138609/208931293-00574630-89e6-43f1-acd5-68934b260370.png)
console print
![image](https://user-images.githubusercontent.com/82138609/208931524-81f052b3-d35d-4f27-ac73-df5ee0593a38.png)
The required permissions are also configured in the Android profile
![image](https://user-images.githubusercontent.com/82138609/208931954-9aba8e17-a296-424d-89b3-d1ce93da21e5.png)

### Configuration
permission_handler_version: 10.2.0
flutter_version: 3.3.2

**Comment by ElHyperion** [comment]
This issue is still relevant and I can't seem to find a way around it either. It started happening after adding this code to MainActivity.kt, which I needed to handle BLE errors:
```kotlin
class MainActivity : FlutterActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        RxJavaPlugins.setErrorHandler { throwable: Throwable ->
            if (throwable is UndeliverableException && throwable.cause is BleException) {
                return@setErrorHandler // ignore BleExceptions since we do not have subscriber
            } else {
                throw throwable
            }
        }
    }
}
```
