### ISSUE TITLE
Location Permission Not Appearing for Aplications with Permission Handler Plugin on iOS 16.1

### ISSUE THREAD

**Issue by yamauchieduardo** [Baseflow/flutter-permission-handler#970]
I am experiencing an issue with the Permission Handler plugin in Flutter on iOS devices running version 16.1.

When a Flutter app that uses the Permission Handler plugin with the location permission is installed with the iOS "Location services" setting turned off, the location permission option does not appear in the app's configuration when the "Location services" setting is later turned on. **As a result, users are unable to grant the location permission to the app, and the permission request is always denied.**

<img src="https://user-images.githubusercontent.com/44825178/209242362-29344df6-5ff1-4af0-924c-f3344a630165.jpg" width="30%" height="30%">

<img src="https://user-images.githubusercontent.com/44825178/209242394-cb056890-300d-4f59-9a02-a901d2f8d921.jpg" width="30%" height="30%">

I have already confirmed that I have correctly configured the location permission in my Flutter app according to the instructions in the Permission Handler plugin documentation, and I have checked for any known issues or workarounds related to the plugin on its GitHub page. However, the issue persists.

Could you please provide some guidance on how to resolve this issue? Any help would be greatly appreciated.

Thank you!

**Platform:** 
- [X] :iphone: iOS
- [ ] :robot: Android

**Comment by giovannilima262** [comment]
It worked for me to change Permission.photos to Permission.storage

**Comment by abdalmonem** [comment]
same issue

**Comment by LEMUSADR000** [comment]
Same issue here

**Comment by MatyasK** [comment]
yeah same issue here as well

**Comment by okbye123** [comment]
This might help https://www.youtube.com/watch?v=uMvGpBOT0ZY

**Comment by helendeguinion1** [comment]
Hello any update fix for this one?

**Comment by shubhamkumarmaghar** [comment]
change the default post_installer to this.Basically we are adding GCC_PREPROCESSOR_DEFINITIONS.

post_install do |installer|
  installer.pods_project.targets.each do |target|
  flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',

        ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
        'PERMISSION_LOCATION=1',

        ## dart: PermissionGroup.notification
        'PERMISSION_NOTIFICATIONS=1',

        ## dart: PermissionGroup.photos
        'PERMISSION_PHOTOS=1'

        ]
    end
  end
end

if this does not work then in info.plist ,add the "location" in ui bckgrond modes.

<key>UIBackgroundModes</key>
	<array>
		<string>fetch</string>
		<string>processing</string>
		<string>location</string>
		<string>remote-notification</string>
	</array>
