### ISSUE TITLE
Support NSPhotoLibraryAddUsageDescription permission

### ISSUE THREAD

**Issue by idish** [Baseflow/flutter-permission-handler#980]
## 🚀 Feature Requests

It would be great to have the NSPhotoLibraryAddUsageDescription permission included (i.e permission for saving photos only - available on ios 11+). Currently we can only leverage the NSPhotoLibraryUsageDescription which is applicable for read & write permission, that would be too broad permission for those who like to only save to library.

### Platforms affected (mark all that apply)
- [V] :iphone: iOS

**Comment by ChristianNavolskyi** [comment]
That permission is already present in the code, it's just not mentioned in the README. 
Its in [`permission_handler_platform_interface/lib/src/permissions.dart`](https://github.com/Baseflow/flutter-permission-handler/blob/978dbebc195a3d23c18b067a6357d7cdd6e729f6/permission_handler_platform_interface/lib/src/permissions.dart#L126).

```dart
/// Permission for adding photos to the device's photo library (iOS only).
///
/// Photos can only be added. If you want to read them as well, use the
/// [photos] permission instead.
///
/// iOS: Photos (14+ read & write access level)
static const photosAddOnly = Permission._(10);
```

**Comment by TimHoogstrate** [comment]
The PR is merged. I'll close this issue for now. Feel free to reopen or file a new issue with new information.

Kind regards,
