### ISSUE TITLE
Permission.manageExternalStorage

### ISSUE THREAD

**Issue by engineer-ece** [Baseflow/flutter-permission-handler#985]
1. for Android not able add in play store.
2. It redirected to permission of Access all files, so app is crashing. please check it soon as possible.

java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=210, result=0, data=null} to activity {com.fieldlytics.framex/com.fieldlytics.frame.MainActivity}: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 2256): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:6007)
E/AndroidRuntime( 2256): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:6046)
E/AndroidRuntime( 2256): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
E/AndroidRuntime( 2256): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/AndroidRuntime( 2256): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 2256): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 2256): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2571)
E/AndroidRuntime( 2256): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 2256): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime( 2256): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime( 2256): 	at android.app.ActivityThread.main(ActivityThread.java:8741)
E/AndroidRuntime( 2256): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 2256): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/AndroidRuntime( 2256): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
E/AndroidRuntime( 2256): Caused by: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 2256): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:430)
E/AndroidRuntime( 2256): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:267)
E/AndroidRuntime( 2256): 	at com.baseflow.permissionhandler.MethodCallHandlerImpl$$ExternalSyntheticLambda6.onSuccess(Unknown Source:2)
E/AndroidRuntime( 2256): 	at com.baseflow.permissionhandler.PermissionManager.onActivityResult(PermissionManager.java:100)
E/AndroidRuntime( 2256): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:805)
E/AndroidRuntime( 2256): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:428)
E/AndroidRuntime( 2256): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:807)
E/AndroidRuntime( 2256): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:724)
E/AndroidRuntime( 2256): 	at android.app.Activity.dispatchActivityResult(Activity.java:8938)
E/AndroidRuntime( 2256): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:6000)
E/AndroidRuntime( 2256): 	... 13 more
I/Process ( 2256): Sending signal. PID: 2256 SIG: 9
Lost connection to device.

**Comment by razfazz** [comment]
please fix!

**Comment by JeroenWeener** [comment]
Hi @engineer-ece and @razfazz! Thank you for reaching out.

As this is an open source project, we cannot make any guarantees as to when we look into an issue. Generally, it helps to provide as much information as possible, by filling in all the fields in the issue report. This might also spark interest for new contributors, who could dive into the issue and open a PR.

For us to investigate this issue, we would need a reproducible code sample. You can quickly create one by running `flutter create` and tweaking `main.dart` and `AndroidManifest.xml`. You can then paste the contents of these files here directly, or via a [gist](https://gist.github.com/).

Some extra information that speeds up our process:
- Which version of the plugin are you using?
- Does this also happen on the latest version of the plugin?
- Which Android version are you running this on?
- What is the output of `flutter doctor -v`?

Hoping to hear from you, I would be happy to help.
