### ISSUE TITLE
await Permission.scheduleExactAlarm.status.isGranted didn't get Device's current granted status

### ISSUE THREAD

**Issue by hyeonjeong-roh** [Baseflow/flutter-permission-handler#987]
## 🐛 Bug Report

When i set my device(Android 12) setting 'Allow setting alarms and reminders' to false,
await Permission.scheduleExactAlarm.status.isGranted  return true.
It seems like package didn't catch device's current granted status.

### Expected behavior
My device: Android 12

So after i check device's granted status and  tried to set exact alarm, error occurs.
below is error code.
'PlatformException(100, Failed while read arguments, Caller net.fiet.fiet needs to hold android.permission.SCHEDULE_EXACT_ALARM to set exact alarms., null)' error occurs.

Is there a way to capture device's current SCHEDULE_EXACT_ALARM granted status?
please help

### Configuration

- *Version:** 10.2.0
- *Platform:**
- :iphone: iOS
- [X] :robot: Android

**Comment by vbuberen** [comment]
Also see the same issue on `10.2.0` plugin version, but in the project that targets Android 13 and on emulator with Android 13.

In case I revoke the permission in phone settings during the next app launch I would still get status `granted` when calling `Permission.scheduleExactAlarm.status`.

**Comment by TimHoogstrate** [comment]
Dear @hyeonjeong-roh,

https://developer.android.com/about/versions/14/changes/schedule-exact-alarms Regarding the documentation it seems that Android 12 is Granted by Default and Android 13 should be no longer Granted by default. On My Android 13 test device it seems that is is Granted by default. I am not sure if this is a bug on the plugin or platform but I'll label this as a bug for now.

**Comment by TimHoogstrate** [comment]
Good then I'll close the issue. Thanks all!
