### ISSUE TITLE
Add support for `ACTIVITY_RECOGNITION` permission

### ISSUE THREAD

**Issue by bartekpacia** [Baseflow/flutter-permission-handler#989]
## 🚀 Feature Requests

Add support for [ACTIVITY_RECOGNITION](https://developer.android.com/reference/android/Manifest.permission#ACTIVITY_RECOGNITION) permission. I've seen a user experience the need for it [here](https://github.com/leancodepl/patrol/issues/897).

I don't know what's the iOS equivalent (if there's any).

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS (maybe?)
- [x] :robot: Android

**Comment by Flajt** [comment]
This is already implemented I think. Try:
```dart
PermissionStatus activityRecognitionEnabled = Platform.isAndroid ? await Permission.activityRecognition.status : await Permission.sensors.status; // Check if permission is granted

Platform.isAndroid ? await Permission.activityRecognition.request() : await Permission.sensors.request(); //Request permission
```
