### ISSUE TITLE
Don't understand setup in README for iOS

### ISSUE THREAD

**Issue by AdrKacz** [Baseflow/flutter-permission-handler#997]
## 💬 Questions and Help

In the iOS setup, it is mentioned:

Delete the corresponding permission description in Info.plist e.g. when you don't need camera permission, just delete `NSCameraUsageDescription` The following lists the relationship between Permission and The key of `Info.plist`

I don't understand what I am supposed to do:
1. Add the `key` but not the `description`
2. Add both
3. Remove both if they are here

Indeed, the *setup* ask me to **delete** an element corresponding to the element I use if I don't want to use them.. Well, maybe I don't know how to read. Can someone explain this to me?

**Comment by mw66** [comment]
Same question:

https://github.com/Baseflow/flutter-permission-handler/issues/1013

I think the confusion is the word *corresponding*: I think the true meaning is NOT corresponding to point 2, but corresponding to "when you don't need camera permission", later in the sentence.

Maybe that sentence should re-write as:


When you don't need a particular (e.g. camera) permission, then delete the corresponding permission description in Info.plist
(e.g. delete NSCameraUsageDescription).

Now the meaning of *corresponding* is clear: it's corresponding to the "When you don't need a particular (e.g. camera) permission"; but not corresponding to the previous point 2.

**Comment by JeroenWeener** [comment]
Thank you @AdrKacz and @mw66 for bringing this to our attention.

@AdrKacz you are indeed required to **remove** permissions you do not use as part of the setup.

I am closing this issue in favor of #1013 for tracking progress regarding clarifying documentation, as I agree this can be a little confusing.
