### ISSUE TITLE
Request : Support default app request

### ISSUE THREAD

**Issue by QuentinSc** [Baseflow/flutter-permission-handler#998]
## 🚀 Feature Requests

Simply add the ability to request Android to change de the default app (for SMS or Browser for example)

1. Launch my SMS app
2. Check if it already the default app
3. If not, show the user the android prompt to change SMS default app

### Platforms affected
- [x] :robot: Android

**Comment by JeroenWeener** [comment]
Hi @QuentinSc, thank you for submitting this feature request!

While this is indeed a nifty feature, we do not believe it belongs to the responsibilities of the `permission_handler` plugin, and should instead be offered by a different plugin.

I found this plugin on `pub.dev`: https://pub.dev/packages/open_as_default. The behavior is a little different than you described, and it seems to support opening the application for files, but not for SMS or URLs. You could reach out to the developer with this feature request to see if they are willing to implement it (or accept a PR).
